// React-Inertia/Full/resources/js/pages/graphs/apex/bubble/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getSimpleBubbleChart, getThreeBubbleChart, getThreedBubbleChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Bubble Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Simple Bubble Charts">
                            <CustomApexChart getOptions={getSimpleBubbleChart} series={getSimpleBubbleChart().series} type="bubble" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="3D Bubble Charts">
                            <CustomApexChart getOptions={getThreedBubbleChart} series={getThreedBubbleChart().series} type="bubble" height={350} />
                        </ComponentCard>
                    </Col>

                    <Col xl={6}>
                        <ComponentCard title="Bubble Charts">
                            <CustomApexChart getOptions={getThreeBubbleChart} series={getThreeBubbleChart().series} type="bubble" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page

// Vue/Full/src/views/graphs/apex/bubble/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Bubble Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Simple Bubble Charts">
                        <CustomApexChart :get-options='getSimpleBubbleChart' :series='getSimpleBubbleChart().series'
                            type="bubble" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="3D Bubble Charts">
                        <CustomApexChart :get-options='getThreedBubbleChart' :series='getThreedBubbleChart().series'
                            type="bubble" :height='350' />
                    </UICard>
                </BCol>

                <BCol xl='6'>
                    <UICard title="Bubble Charts">
                        <CustomApexChart :get-options='getThreeBubbleChart' :series='getThreeBubbleChart().series'
                            type="bubble" :height='350' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import { getSimpleBubbleChart, getThreeBubbleChart, getThreedBubbleChart } from './data';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';


usePageMeta('Apex Bubble Charts')
</script>

<style scoped></style>
