// Vue-Inertia/Seed/resources/js/layouts/components/sidenav/components/MenuItem.vue
<template>
  <li v-if="item.url" class="side-nav-item" :class="{ active: isActive }">
    <Link
      :href="item.url"
      class="side-nav-link"
      :class="{ disabled: item.isDisabled, 'special-menu': item.isSpecial, active: isActive }"
    >
      <span v-if="item.icon" class="menu-icon"><Icon :icon="item.icon" /></span>
      <span class="menu-text">{{ item.label }}</span>
      <span v-if="item.badge" :class="`badge text-bg-${item.badge.variant} opacity-50`">{{
        item.badge.text
      }}</span>
    </Link>
  </li>
</template>

<script setup lang="ts">
import type { MenuItemType } from '@/types/layout'
import { Icon } from '@iconify/vue'
import { Link, usePage } from '@inertiajs/vue3';
import { computed } from 'vue'

type PropsType = {
  item: MenuItemType
}

const props = defineProps<PropsType>()

const page = usePage()
const pathname = computed(() => page.url)

const isActive = computed(() => {
  return props.item.url && pathname.value.endsWith(props.item.url)
})
</script>

// SvelteKit/Seed/src/lib/layouts/components/sidenav/components/MenuItem.svelte
<script lang="ts">
	import type { MenuItemType } from '$lib/types/layout';
	import Icon from '@iconify/svelte';
	import { page } from '$app/stores';
	import { hideBackdrop, toggleAttribute } from '$lib/helpers/layout';
	import { layout } from '$lib/stores/layout';

	export let item: MenuItemType;

	$: isActive = !!(item?.url && $page.url.pathname === item.url);

	$: classNames = [item.isDisabled && 'disabled', item.isSpecial && 'special-menu']
		.filter(Boolean)
		.join(' ');

	const closeOffcanvasSidebar = () => {
		if ($layout.sidenav.size === 'offcanvas') {
			toggleAttribute('class', 'sidebar-enable', true);
			hideBackdrop();
		}
	};
</script>

{#if item.url}
	<li class="side-nav-item" class:active={isActive}>
		<a
			href={item.url}
			class="side-nav-link {classNames}"
			class:active={isActive}
			on:click={closeOffcanvasSidebar}
		>
			{#if item.icon}
				<span class="menu-icon"><Icon icon={item.icon} /></span>
			{/if}
			<span class="menu-text">{item.label}</span>
			{#if item.badge}
				<span class="badge text-bg-{item.badge.variant} opacity-50">{item.badge.text}</span>
			{/if}
		</a>
	</li>
{/if}
