// Full/src/components/TextDifferentView.vue
<template>
    <div class="p-3 bg-light-subtle border border-dashed rounded lh-lg">
        <div class="diff-output diff">
            <span v-for="(part, index) in diffOutput" :key="index" :style="part.style">
                {{ part.value }}
            </span>
        </div>
    </div>
</template>

<script setup lang="ts">
import { diffWords } from 'diff'
import { computed } from 'vue'
import { getColor } from '@/helpers/chart';

interface Props {
    originalText: string
    modifiedText: string
}

const props = defineProps<Props>()

const diffOutput = computed(() => {
    const diff = diffWords(props.originalText, props.modifiedText)
    return diff.map((part: any) => {
        let style: Record<string, string> = {}

        if (part.added) {
            style = { backgroundColor: getColor('success-rgb', 0.1), color: getColor('success') }
        } else if (part.removed) {
            style = {
                backgroundColor: getColor('danger-rgb', 0.1),
                color: getColor('danger'),
                textDecoration: 'line-through',
            }
        }

        return { value: part.value, style }
    })
})
</script>

// NextJs/NextJs/Full/JS/src/components/TextDifferentView.jsx
'use client';

import { getColor } from '@/helpers/color';
import { diffWords } from 'diff';
import { useEffect, useState } from 'react';
const TextDifferentView = ({
  originalText,
  modifiedText
}) => {
  const [diffOutput, setDiffOutput] = useState([]);
  useEffect(() => {
    const diff = diffWords(originalText, modifiedText);
    const jsx = diff.map((part, index) => {
      let style = {};
      if (part.added) {
        style = {
          backgroundColor: getColor('success-rgb', 0.1),
          color: getColor('success')
        };
      } else if (part.removed) {
        style = {
          backgroundColor: getColor('danger-rgb', 0.1),
          color: getColor('danger'),
          textDecoration: 'line-through'
        };
      }
      return <span key={index} style={style}>
          {part.value}
        </span>;
    });
    setDiffOutput(jsx);
  }, [originalText, modifiedText]);
  return <div className="p-3 bg-light-subtle border border-dashed rounded lh-lg">
      <div className="diff-output diff">{diffOutput}</div>
    </div>;
};
export default TextDifferentView;
