// SvelteKit/Seed/src/lib/layouts/components/navbar/components/AppMenu.svelte
<script lang="ts">
	import MenuItemWithChildren from '$lib/layouts/components/navbar/components/MenuItemWithChildren.svelte';
	import MenuItem from '$lib/layouts/components/navbar/components/MenuItem.svelte';
	import { horizontalMenuItems } from '$lib/layouts/components/data';
</script>

<ul class="navbar-nav">
	{#each horizontalMenuItems || [] as item, idx (idx)}
		{#if item.children}
			<MenuItemWithChildren {item} wrapperClass="nav-item" togglerClass="nav-link" />
		{:else}
			<MenuItem {item} linkClass="nav-link" wrapperClass="nav-item" />
		{/if}
	{/each}
</ul>

// Vue-Inertia/Full/resources/js/layouts/components/navbar/components/AppMenu.vue
<template>
  <ul class="navbar-nav">
    <template v-for="(item, idx) in horizontalMenuItems">
      <MenuItemWithChildren
        v-if="item.children"
        :key="item.key"
        :item="item"
        wrapper-class="nav-item"
        toggler-class="nav-link"
      />
      <MenuItem v-else :key="idx" :item="item" link-class="nav-link" wrapper-class="nav-item" />
    </template>
  </ul>
</template>

<script setup lang="ts">
import MenuItemWithChildren from '@/layouts/components/navbar/components/MenuItemWithChildren.vue'
import MenuItem from '@/layouts/components/navbar/components/MenuItem.vue'
import { horizontalMenuItems } from '@/layouts/components/data'
</script>
