// React-Inertia/Full/resources/js/pages/widgets/components/Widget3.tsx
import { Link } from '@inertiajs/react'
import { Card, CardBody } from 'react-bootstrap'
import { TbExternalLink, TbPointFilled } from 'react-icons/tb'
import type { Widget3Type } from '@/pages/widgets/types'
import CountUp from 'react-countup'

const Widget3 = ({ item }: { item: Widget3Type }) => {
  const { count, totalCount, label, description, variant, title, icon: Icon } = item
  return (
    <Card>
      <CardBody>
        <Link href="#" className="text-muted float-end mt-n1 fs-xl">
          <TbExternalLink />
        </Link>
        <h5 title="Number of Tasks">{title}</h5>
        <div className="d-flex align-items-center gap-2 my-3">
          <div className="avatar-md flex-shrink-0">
            <span className={`avatar-title text-bg-${variant} rounded-circle fs-22 d-flex align-items-center justify-content-center`}>
              {Icon && <Icon className="d-flex align-items-center" />}
            </span>
          </div>
          <h3 className="mb-0">
            <CountUp prefix={count.prefix} suffix={count.suffix} end={count.value} duration={1} enableScrollSpy scrollSpyOnce />
          </h3>
          <span className={`badge badge-soft-${variant} fw-medium ms-2 fs-xs ms-auto`}>{label}</span>
        </div>
        <p className="d-flex align-items-center gap-1 mb-0">
          <TbPointFilled className={`text-${variant}`} />
          <span className="text-nowrap text-muted"> {description}</span>
          <span className="ms-auto">
            <b>{totalCount}</b>
          </span>
        </p>
      </CardBody>
    </Card>
  )
}
export default Widget3

// Vue-Inertia/Full/resources/js/pages/widgets/components/Widget3.vue
<template>
    <BCard no-body>
        <BCardBody>
            <Link href="#" class="text-muted float-end mt-n1 fs-xl">
                <Icon icon="tabler:external-link"/>
            </Link>

            <h5 :title="item.title">{{ item.title }}</h5>

            <div class="d-flex align-items-center gap-2 my-3">
                <div class="avatar-md flex-shrink-0">
                    <span
                        :class="`avatar-title text-bg-${item.variant} rounded-circle fs-22 d-flex align-items-center justify-content-center`">
                        <Icon v-if="item.icon" :icon="item.icon" class="d-flex align-items-center" />
                    </span>
                </div>

                <h3 class="mb-0">
                    
                        <CountUp :end-val="item.count.value"
                            :options="{ prefix: item.count.prefix ?? '', suffix: item.count.suffix ?? '', scrollSpyOnce: true, enableScrollSpy: true, duration: 1 }" />
                    
                </h3>

                <span :class="`badge badge-soft-${item.variant} fw-medium ms-2 fs-xs ms-auto`">
                    {{ item.label }}
                </span>
            </div>

            <p class="d-flex align-items-center gap-1 mb-0">
                <Icon icon="tabler:point-filled" :class="`text-${item.variant}`" />
                <span class="text-nowrap text-muted">{{ item.description }}</span>
                <span class="ms-auto">
                    <b>{{ item.totalCount }}</b>
                </span>
            </p>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody } from 'bootstrap-vue-next'
import type { Widget3Type } from './types';
import CountUp from 'vue-countup-v3'
import { Icon } from '@iconify/vue';
import { Link } from '@inertiajs/vue3';

defineProps<{ item: Widget3Type }>()
</script>
