// Vue-Inertia/Full/resources/js/pages/other-apps/issue-tracker/index.vue
<template>
    <MainLayout>
         
        <BContainer fluid>
            <PageBreadcrumb title="Issue List" subtitle="Apps" />

            <BRow>
                <BCol xs="12">
                    <BCard no-body>
                        <BCardHeader class="border-light justify-content-between">
                            <div class="app-search">
                                <input v-model="searchQuery" type="search" class="form-control"
                                    placeholder="Search issues...">
                                <Icon icon="lucide:search"  class="app-search-icon text-muted" />
                            </div>

                            <button type="submit" class="btn btn-success">Add New Issues</button>
                        </BCardHeader>

                        <BCardBody>
                            <div class="table-responsive">

                                <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                                    thead-class="d-none" v-model:selected-rows="selected" hover :fields="fields"
                                    :items="issuesData" :per-page="perPage" :current-page="currentPage"
                                    @filtered="onFiltered" responsive
                                    class="table table-custom table-nowrap table-centered mb-0 w-100">
                                    <template #cell(status)="{ item }">
                                        <span class="badge fs-xxs badge-label"
                                            :class="item.status === 'resolved' ? 'text-bg-success' : item.status === 'in-progress' ? 'text-bg-warning' : item.status === 'review' ? 'text-bg-info' : item.status === 'pending' ? 'text-bg-secondary' : 'text-bg-danger'">{{
                                                toPascalCase(item.status) }}</span>
                                    </template>
                                    <template #cell(issue)="{ item }">
                                        <Link href="" class="link-reset text-uppercase fw-semibold">{{ item.issueID
                                            }}
                                        </Link>
                                        <p class="mb-0 text-muted">{{ item.description }}</p>
                                    </template>
                                    <template #cell(userName)="{ item }">
                                        <div class="d-flex justify-content-start align-items-center gap-2">
                                            <div class="avatar avatar-xs">
                                                <img :src="item.image" alt="avatar-3"
                                                    class="img-fluid rounded-circle" />
                                            </div>
                                            <div>
                                                <h5 class="text-nowrap mb-0 lh-base">{{ item.name }}</h5>
                                            </div>
                                        </div>

                                    </template>
                                    <template #cell(created)="{ item }">
                                        <p class="mb-0">
                                            <Icon icon="tabler:calendar" /> <span class="fw-semibold">Created:</span>
                                            {{ item.createdAt }}
                                        </p>
                                        <p class="mb-0">
                                            <Icon icon="tabler:clock" /> <span class="fw-semibold">Due:</span>
                                            {{ item.dueDate }}
                                        </p>
                                    </template>
                                    <template #cell(role)="{ item }">
                                        <Link href="" v-for="(tag, idx) in item.tags" :key="idx"
                                            class="badge badge-label badge-default me-1">{{ tag }}</Link>
                                    </template>
                                    <template #cell(progress)="{ item }">
                                        <BProgress :value="item.progress" :bg-variant="item.variant" :max="100"
                                            style="height: 6px;" />

                                        <small class="text-muted">{{ item.progress }}% Complete</small>
                                    </template>
                                    <template #cell(comments)="{ item }">
                                        <Icon icon="tabler:message-circle" class="text-muted me-1" /> {{ item.comments
                                        }}
                                        comments
                                    </template>
                                    <template #cell(files)="{ item }">
                                        <Icon icon="tabler:paperclip" class="text-muted me-1" /> {{ item.files }} files
                                    </template>

                                    <template #cell(action)="{ item }">
                                        <div class="d-flex justify-content-center gap-1">
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:eye" class="fs-lg" />
                                            </button>
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:edit" class="fs-lg" />
                                            </button>
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:trash" class="fs-lg"
                                                    @click="handleDeleteItem(item)" />
                                            </button>
                                        </div>
                                    </template>
                                </BTable>
                                <BCardFooter class="border-0 px-0 pb-0">
                                    <TablePagination v-model:currentPage="currentPage" :per-page="perPage"
                                        :total-items="totalRows" label="categories" />
                                </BCardFooter>
                            </div>
                        </BCardBody>
                    </BCard>
                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardHeader, BCardBody, BCol, BContainer, BRow, type TableFieldRaw, BProgress } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import TablePagination from '@/components/TablePagination.vue';
import { issues, type IssueType } from './data';
import { toPascalCase } from '@/helpers/casing';
import { Icon } from '@iconify/vue';
import { ref } from 'vue';
import { useTableActions } from '@/composables/useTableActions';
import { Link } from '@inertiajs/vue3';
import MainLayout from '@/layouts/MainLayout.vue';

const fields: Exclude<TableFieldRaw<IssueType>, string>[] = [
    { key: 'status', label: 'Status', },
    { key: 'issue', label: 'Issue', },
    { key: 'userName', label: 'User Name', },
    { key: 'created', label: 'Created', },
    { key: 'role', label: 'Role', },
    { key: 'progress', label: 'Progress', },
    { key: 'comments', label: 'Comments', },
    { key: 'files', label: 'Files', },
    { key: 'action', label: 'Action', sortable: false },
]

const searchQuery = ref('')


const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(issues.length)
const issuesData = ref<IssueType[]>(issues)

function onFiltered(filteredItems: IssueType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

function adjustPage() {
    const totalPages = Math.ceil(issuesData.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: IssueType) {
    deleteItem(item)
    totalRows.value = issuesData.value.length
    adjustPage()
}


const { selected, deleteItem } = useTableActions(issuesData)



</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/other-apps/issue-tracker/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import DataTable from '@/components/table/DataTable'
import DeleteConfirmationModal from '@/components/table/DeleteConfirmationModal'
import TablePagination from '@/components/table/TablePagination'
import { toPascalCase } from '@/helpers/casing'
import {
    createColumnHelper,
    getCoreRowModel,
    getFilteredRowModel,
    getPaginationRowModel,
    getSortedRowModel,
    type Row as TableRow,
    useReactTable,
} from '@tanstack/react-table'
import { Button, Card, CardBody, CardHeader, Col, Container, ProgressBar, Row } from 'react-bootstrap'
import { Link } from '@inertiajs/react'
import { useState } from 'react'
import { LuSearch } from 'react-icons/lu'
import { TbCalendar, TbClock, TbEdit, TbEye, TbMessageCircle, TbPaperclip, TbTrash } from 'react-icons/tb'
import { issues, type IssueType } from '@/pages/other-apps/issue-tracker/data'
import MainLayout from '@/layouts/MainLayout'

const columnHelper = createColumnHelper<IssueType>()

const Page = () => {
    const columns = [
        columnHelper.accessor('status', {
            header: () => null,
            cell: ({ row }) => (
                <span
                    className={`badge ${row.original.status === 'resolved' ? 'text-bg-success' : row.original.status === 'in-progress' ? 'text-bg-warning' : row.original.status === 'review' ? 'text-bg-info' : row.original.status === 'pending' ? 'text-bg-secondary' : 'text-bg-danger'} fs-xxs badge-label`}>
                    {toPascalCase(row.original.status)}
                </span>
            ),
        }),
        columnHelper.accessor('issueID', {
            header: () => null,
            cell: ({ row }) => (
                <>
                    <Link href="#" className="link-reset text-uppercase fw-semibold">
                        {row.original.issueID}
                    </Link>
                    <p className="mb-0 text-muted">{row.original.description}</p>
                </>
            ),
        }),
        columnHelper.accessor('name', {
            header: () => null,
            cell: ({ row }) => (
                <div className="d-flex justify-content-start align-items-center gap-2">
                    <div className="avatar avatar-xs">
                        <img src={row.original.image} height={24} width={24} alt="" className="img-fluid rounded-circle" />
                    </div>
                    <div>
                        <h5 className="text-nowrap mb-0 lh-base">{row.original.name}</h5>
                    </div>
                </div>
            ),
        }),
        columnHelper.accessor('createdAt', {
            header: () => null,
            cell: ({ row }) => (
                <>
                    <p className="mb-0 d-flex align-items-center gap-1">
                        <TbCalendar /> <span className="fw-semibold">Created:</span> {row.original.createdAt}
                    </p>
                    <p className="mb-0 d-flex align-items-center gap-1">
                        <TbClock /> <span className="fw-semibold">Due:</span>
                        {row.original.dueDate}
                    </p>
                </>
            ),
        }),
        columnHelper.accessor('tags', {
            header: () => null,
            cell: ({ row }) => (
                <>
                    {row.original.tags.map((tag, idx) => (
                        <span key={idx} className="badge badge-label badge-default me-1">
                            {tag}
                        </span>
                    ))}
                </>
            ),
        }),
        columnHelper.accessor('progress', {
            header: () => null,
            cell: ({ row }) => (
                <>
                    <ProgressBar
                        now={row.original.progress}
                        variant={row.original.progress <= 25 ? 'danger' : row.original.progress <= 75 ? 'warning' : 'success'}
                        style={{ height: '6px' }}
                    />
                    <small className="text-muted">{row.original.progress}% Complete</small>
                </>
            ),
        }),
        columnHelper.accessor('comments', {
            header: () => null,
            cell: ({ row }) => (
                <span className="d-flex align-items-center gap-1">
                    <TbMessageCircle className="text-muted" />
                    <span>{row.original.comments} comments</span>
                </span>
            ),
        }),
        columnHelper.accessor('files', {
            header: () => null,
            cell: ({ row }) => (
                <span className="d-flex align-items-center gap-1">
                    <TbPaperclip className="text-muted" />
                    <span>{row.original.files} files</span>
                </span>
            ),
        }),
        columnHelper.accessor('id', {
            header: () => null,
            cell: ({ row }: { row: TableRow<IssueType> }) => (
                <div className="d-flex  gap-1">
                    <Button variant="light" size="sm" className="btn-icon rounded-circle">
                        <TbEye className="fs-lg" />
                    </Button>
                    <Button variant="light" size="sm" className="btn-icon rounded-circle">
                        <TbEdit className="fs-lg" />
                    </Button>
                    <Button
                        variant="light"
                        size="sm"
                        className="btn-icon rounded-circle"
                        onClick={() => {
                            toggleDeleteModal()
                            setSelectedRowIds({ [row.id]: true })
                        }}>
                        <TbTrash className="fs-lg" />
                    </Button>
                </div>
            ),
        }),
    ]

    const [data, setData] = useState<IssueType[]>(() => [...issues])
    const [globalFilter, setGlobalFilter] = useState('')
    const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: 8 })

    const [selectedRowIds, setSelectedRowIds] = useState<Record<string, boolean>>({})

    const table = useReactTable({
        data,
        columns,
        state: { globalFilter, pagination, rowSelection: selectedRowIds },
        onGlobalFilterChange: setGlobalFilter,
        onPaginationChange: setPagination,
        onRowSelectionChange: setSelectedRowIds,
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
        globalFilterFn: 'includesString',
        enableRowSelection: true,
    })

    const pageIndex = table.getState().pagination.pageIndex
    const pageSize = table.getState().pagination.pageSize
    const totalItems = table.getFilteredRowModel().rows.length

    const start = pageIndex * pageSize + 1
    const end = Math.min(start + pageSize - 1, totalItems)

    const [showDeleteModal, setShowDeleteModal] = useState<boolean>(false)

    const toggleDeleteModal = () => {
        setShowDeleteModal(!showDeleteModal)
    }

    const handleDelete = () => {
        const selectedIds = new Set(Object.keys(selectedRowIds))
        setData((old) => old.filter((_, idx) => !selectedIds.has(idx.toString())))
        setSelectedRowIds({})
        setPagination({ ...pagination, pageIndex: 0 })
        setShowDeleteModal(false)
    }

    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Issue Tracker" subtitle="Apps" />

                <Row>
                    <Col cols={12}>
                        <Card>
                            <CardHeader className="border-light justify-content-between">
                                <div className="app-search">
                                    <input
                                        type="search"
                                        className="form-control"
                                        placeholder="Search issues..."
                                        value={globalFilter ?? ''}
                                        onChange={(e) => setGlobalFilter(e.target.value)}
                                    />
                                    <LuSearch className="app-search-icon text-muted" />
                                </div>

                                <Button variant="success">Add New Issues</Button>
                            </CardHeader>

                            <CardBody>
                                <DataTable<IssueType> table={table} emptyMessage="No records found" showHeaders={false} className="mb-3" />
                                {table.getRowModel().rows.length > 0 && (
                                    <TablePagination
                                        totalItems={totalItems}
                                        start={start}
                                        end={end}
                                        itemsName="issues"
                                        showInfo
                                        previousPage={table.previousPage}
                                        canPreviousPage={table.getCanPreviousPage()}
                                        pageCount={table.getPageCount()}
                                        pageIndex={table.getState().pagination.pageIndex}
                                        setPageIndex={table.setPageIndex}
                                        nextPage={table.nextPage}
                                        canNextPage={table.getCanNextPage()}
                                    />
                                )}
                            </CardBody>

                            <DeleteConfirmationModal
                                show={showDeleteModal}
                                onHide={toggleDeleteModal}
                                onConfirm={handleDelete}
                                selectedCount={Object.keys(selectedRowIds).length}
                                itemName="issue"
                            />
                        </Card>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
