// React/Full/JS/src/views/forms/basic/components/ChecksRadiosSwitches.jsx
import ComponentCard from '@/components/cards/ComponentCard';
import { Col, Form, Row } from 'react-bootstrap';
const ChecksRadiosSwitches = () => {
  return <ComponentCard title="Checks, Radios and Switches">
      <Row>
        <Col lg={12}>
          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Checkboxes</label>
            </Col>
            <Col lg={5}>
              <Form.Check type="checkbox" label="Default Checkbox" className="mb-2" />

              <div className="mb-2">
                <Form.Check inline type="checkbox" label="Inline 1" />
                <Form.Check inline type="checkbox" label="Inline 2" />
              </div>

              <Form.Check type="checkbox" label="Disabled checked checkbox" checked disabled className="mb-2" onChange={() => {}} />

              <h5 className="mt-3">Sizes</h5>

              <Form.Check type="checkbox" label="I'm 16px Checkbox" className="fs-lg mb-2" />

              <Form.Check type="checkbox" label="I'm 20px Checkbox" className="fs-xxl mb-2" />
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Radios</label>
            </Col>
            <Col lg={5}>
              <Form.Check type="radio" name="group1" label="Option 1" className="mb-2" />

              <Form.Check type="radio" name="group1" label="Option 2" className="mb-2" />

              <div className="mb-2">
                <Form.Check type="radio" name="group2" inline label="Option 1" />
                <Form.Check type="radio" name="group2" inline label="Option 2" />
              </div>

              <Form.Check type="radio" checked disabled label="Disabled Checked Radio" className="mb-2" onChange={() => {}} />

              <h5 className="mt-3">Sizes</h5>

              <div className="mb-2">
                <Form.Check type="radio" label="Cash" name="group3" inline className="fs-lg" />
                <Form.Check type="radio" label="Card" name="group3" inline className="fs-lg" />
              </div>

              <div className="mb-2">
                <Form.Check type="radio" label="Pickup" name="group4" inline className="fs-xxl" />
                <Form.Check type="radio" label="Home Delivery" name="group4" inline className="fs-xxl" />
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Switches</label>
            </Col>
            <Col lg={5}>
              <Form.Check type="switch" label="Enabled Switch" className="mb-2" />

              <Form.Check type="switch" label="Disabled Switch" disabled className="mb-2" />

              <h5 className="mt-3">Sizes</h5>

              <Form.Check type="switch" label="I'm 16px Switch" className="fs-lg mb-2" />

              <Form.Check type="switch" label="I'm 20px Switch" className="fs-xxl mb-2" />
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Reverse</label>
            </Col>
            <Col lg={5}>
              <div className="w-lg-50">
                <Form.Check type="checkbox" reverse label="Reverse checkbox" className="mb-2" />
                <Form.Check type="radio" reverse label="Reverse radio" className="mb-2" />
                <Form.Check type="switch" reverse label="Reverse switch" className="mb-2" />
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Colored Checkboxes</label>
            </Col>
            <Col lg={5}>
              <div className="d-flex flex-wrap gap-4">
                <div>
                  <div className="form-check form-check-primary mb-2">
                    <Form.Check type="checkbox" id="checkPrimary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkPrimary">
                      Primary
                    </label>
                  </div>
                  <div className="form-check form-check-secondary mb-2">
                    <Form.Check type="checkbox" id="checkSecondary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkSecondary">
                      Secondary
                    </label>
                  </div>
                  <div className="form-check form-check-success mb-2">
                    <Form.Check type="checkbox" id="checkSuccess" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkSuccess">
                      Success
                    </label>
                  </div>
                  <div className="form-check form-check-info mb-2">
                    <Form.Check type="checkbox" id="checkInfo" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkInfo">
                      Info
                    </label>
                  </div>
                </div>
                <div>
                  <div className="form-check form-check-warning mb-2">
                    <Form.Check type="checkbox" id="checkWarning" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkWarning">
                      Warning
                    </label>
                  </div>
                  <div className="form-check form-check-danger mb-2">
                    <Form.Check type="checkbox" id="checkDanger" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkDanger">
                      Danger
                    </label>
                  </div>
                  <div className="form-check form-check-purple mb-2">
                    <Form.Check type="checkbox" id="checkPurple" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkPurple">
                      Purple
                    </label>
                  </div>
                  <div className="form-check form-check-dark">
                    <Form.Check type="checkbox" id="checkDark" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="checkDark">
                      Dark
                    </label>
                  </div>
                </div>
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Colored Radios</label>
            </Col>
            <Col lg={5}>
              <div className="d-flex flex-wrap gap-4">
                <div>
                  <div className="form-check form-check-primary mb-2">
                    <Form.Check type="radio" name="radioPrimary" id="radioPrimary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioPrimary">
                      Primary
                    </label>
                  </div>
                  <div className="form-check form-check-secondary mb-2">
                    <Form.Check type="radio" name="radioSecondary" id="radioSecondary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioSecondary">
                      Secondary
                    </label>
                  </div>
                  <div className="form-check form-check-success mb-2">
                    <Form.Check type="radio" name="radioSuccess" id="radioSuccess" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioSuccess">
                      Success
                    </label>
                  </div>
                  <div className="form-check form-check-info mb-2">
                    <Form.Check type="radio" name="radioInfo" id="radioInfo" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioInfo">
                      Info
                    </label>
                  </div>
                </div>
                <div>
                  <div className="form-check form-check-warning mb-2">
                    <Form.Check type="radio" name="radioWarning" id="radioWarning" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioWarning">
                      Warning
                    </label>
                  </div>
                  <div className="form-check form-check-danger mb-2">
                    <Form.Check type="radio" name="radioDanger" id="radioDanger" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioDanger">
                      Danger
                    </label>
                  </div>
                  <div className="form-check form-check-purple mb-2">
                    <Form.Check type="radio" name="radioPurple" id="radioPurple" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioPurple">
                      Purple
                    </label>
                  </div>
                  <div className="form-check form-check-dark">
                    <Form.Check type="radio" name="radioDark" id="radioDark" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="radioDark">
                      Dark
                    </label>
                  </div>
                </div>
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Colored Switches</label>
            </Col>
            <Col lg={5}>
              <div className="d-flex flex-wrap gap-4">
                <div>
                  <div className="form-check form-check-primary form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchPrimary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchPrimary">
                      Primary
                    </label>
                  </div>
                  <div className="form-check form-check-secondary form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchSecondary" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchSecondary">
                      Secondary
                    </label>
                  </div>
                  <div className="form-check form-check-success form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchSuccess" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchSuccess">
                      Success
                    </label>
                  </div>
                  <div className="form-check form-check-info form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchInfo" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchInfo">
                      Info
                    </label>
                  </div>
                </div>
                <div>
                  <div className="form-check form-check-warning form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchWarning" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchWarning">
                      Warning
                    </label>
                  </div>
                  <div className="form-check form-check-danger form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchDanger" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchDanger">
                      Danger
                    </label>
                  </div>
                  <div className="form-check form-check-purple form-switch mb-2">
                    <input type="checkbox" className="form-check-input" id="switchPurple" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchPurple">
                      Purple
                    </label>
                  </div>
                  <div className="form-check form-check-dark form-switch">
                    <input type="checkbox" className="form-check-input" id="switchDark" checked onChange={() => {}} />
                    <label className="form-check-label" htmlFor="switchDark">
                      Dark
                    </label>
                  </div>
                </div>
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Checkbox Toggle</label>
            </Col>

            <Col lg={5}>
              <div className="mb-2">
                <input type="checkbox" className="btn-check" id="btncheck1" />
                <label className="btn btn-outline-primary" htmlFor="btncheck1">
                  Single Toggle
                </label>
              </div>

              <div className="btn-group" role="group" aria-label="Checkbox toggle group">
                <input type="checkbox" className="btn-check" id="btncheck2" />
                <label className="btn btn-outline-primary" htmlFor="btncheck2">
                  One
                </label>

                <input type="checkbox" className="btn-check" id="btncheck3" />
                <label className="btn btn-outline-primary" htmlFor="btncheck3">
                  Two
                </label>

                <input type="checkbox" className="btn-check" id="btncheck4" />
                <label className="btn btn-outline-primary" htmlFor="btncheck4">
                  Three
                </label>
              </div>
            </Col>
          </Row>

          <div className="border-top border-dashed my-3"></div>

          <Row className="g-lg-4 g-2">
            <Col lg={2}>
              <label className="col-form-label">Radio Toggle</label>
            </Col>

            <Col lg={5}>
              <div className="btn-group" role="group" aria-label="Radio toggle group">
                <input type="radio" className="btn-check" name="btnradio" id="btnradio1" />
                <label className="btn btn-outline-secondary" htmlFor="btnradio1">
                  Left
                </label>

                <input type="radio" className="btn-check" name="btnradio" id="btnradio2" />
                <label className="btn btn-outline-secondary" htmlFor="btnradio2">
                  Middle
                </label>

                <input type="radio" className="btn-check" name="btnradio" id="btnradio3" />
                <label className="btn btn-outline-secondary" htmlFor="btnradio3">
                  Right
                </label>
              </div>
            </Col>
          </Row>
        </Col>
      </Row>
    </ComponentCard>;
};
export default ChecksRadiosSwitches;

// Nuxt/Full/pages/forms/basic/components/ChecksRadiosSwitches.vue
<template>
  <UICard title="Checks, Radios and Switches">
    <BRow>
      <BCol lg="12">
        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Checkboxes</label>
          </BCol>
          <BCol lg="5">
            <BFormCheckbox class="mb-2">Default Checkbox</BFormCheckbox>

            <div class="mb-2">
              <BFormCheckbox inline>Inline 1</BFormCheckbox>
              <BFormCheckbox inline>Inline 2</BFormCheckbox>
            </div>

            <BFormCheckbox checked disabled class="mb-2">Disabled checked checkbox</BFormCheckbox>

            <h5 class="mt-3">Sizes</h5>
            <BFormCheckbox class="fs-lg mb-2">I'm 16px Checkbox</BFormCheckbox>
            <BFormCheckbox class="fs-xxl mb-2">I'm 20px Checkbox</BFormCheckbox>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Radios</label>
          </BCol>
          <BCol lg="5">
            <BFormRadio name="group1" class="mb-2">Option 1</BFormRadio>
            <BFormRadio name="group1" class="mb-2">Option 2</BFormRadio>

            <div class="mb-2">
              <BFormRadio name="group2" inline>Option 1</BFormRadio>
              <BFormRadio name="group2" inline>Option 2</BFormRadio>
            </div>

            <BFormRadio checked disabled class="mb-2">Disabled Checked Radio</BFormRadio>

            <h5 class="mt-3">Sizes</h5>
            <div class="mb-2">
              <BFormRadio name="group3" inline class="fs-lg">Cash</BFormRadio>
              <BFormRadio name="group3" inline class="fs-lg">Card</BFormRadio>
            </div>
            <div class="mb-2">
              <BFormRadio name="group4" inline class="fs-xxl">Pickup</BFormRadio>
              <BFormRadio name="group4" inline class="fs-xxl">Home Delivery</BFormRadio>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Switches</label>
          </BCol>
          <BCol lg="5">
            <BFormCheckbox switch class="mb-2">Enabled Switch</BFormCheckbox>
            <BFormCheckbox switch disabled class="mb-2">Disabled Switch</BFormCheckbox>

            <h5 class="mt-3">Sizes</h5>
            <BFormCheckbox switch class="fs-lg mb-2">I'm 16px Switch</BFormCheckbox>
            <BFormCheckbox switch class="fs-xxl mb-2">I'm 20px Switch</BFormCheckbox>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Reverse</label>
          </BCol>
          <BCol lg="5">
            <div class="w-lg-50">
              <BFormCheckbox reverse class="mb-2">Reverse checkbox</BFormCheckbox>
              <BFormRadio reverse class="mb-2">Reverse radio</BFormRadio>
              <BFormCheckbox switch reverse class="mb-2">Reverse switch</BFormCheckbox>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Colored Checkboxes</label>
          </BCol>
          <BCol lg="5">
            <div class="d-flex flex-wrap gap-4">
              <div>
                <BFormCheckbox id="checkPrimary" checked class="form-check-primary mb-2">Primary</BFormCheckbox>
                <BFormCheckbox id="checkSecondary" checked class="form-check-secondary mb-2">Secondary</BFormCheckbox>
                <BFormCheckbox id="checkSuccess" checked class="form-check-success mb-2">Success</BFormCheckbox>
                <BFormCheckbox id="checkInfo" checked class="form-check-info mb-2">Info</BFormCheckbox>
              </div>
              <div>
                <BFormCheckbox id="checkWarning" checked class="form-check-warning mb-2">Warning</BFormCheckbox>
                <BFormCheckbox id="checkDanger" checked class="form-check-danger mb-2">Danger</BFormCheckbox>
                <BFormCheckbox id="checkPurple" checked class="form-check-purple mb-2">Purple</BFormCheckbox>
                <BFormCheckbox id="checkDark" checked class="form-check-dark">Dark</BFormCheckbox>
              </div>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Colored Radios</label>
          </BCol>
          <BCol lg="5">
            <div class="d-flex flex-wrap gap-4">
              <div>
                <BFormRadio name="radioPrimary" id="radioPrimary" checked class="form-check-primary mb-2">Primary</BFormRadio>
                <BFormRadio name="radioSecondary" id="radioSecondary" checked class="form-check-secondary mb-2">Secondary</BFormRadio>
                <BFormRadio name="radioSuccess" id="radioSuccess" checked class="form-check-success mb-2">Success</BFormRadio>
                <BFormRadio name="radioInfo" id="radioInfo" checked class="form-check-info mb-2">Info</BFormRadio>
              </div>
              <div>
                <BFormRadio name="radioWarning" id="radioWarning" checked class="form-check-warning mb-2">Warning</BFormRadio>
                <BFormRadio name="radioDanger" id="radioDanger" checked class="form-check-danger mb-2">Danger</BFormRadio>
                <BFormRadio name="radioPurple" id="radioPurple" checked class="form-check-purple mb-2">Purple</BFormRadio>
                <BFormRadio name="radioDark" id="radioDark" checked class="form-check-dark">Dark</BFormRadio>
              </div>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Colored Switches</label>
          </BCol>
          <BCol lg="5">
            <div class="d-flex flex-wrap gap-4">
              <div>
                <BFormCheckbox switch id="switchPrimary" checked class="form-check-primary mb-2">Primary</BFormCheckbox>
                <BFormCheckbox switch id="switchSecondary" checked class="form-check-secondary mb-2">Secondary</BFormCheckbox>
                <BFormCheckbox switch id="switchSuccess" checked class="form-check-success mb-2">Success</BFormCheckbox>
                <BFormCheckbox switch id="switchInfo" checked class="form-check-info mb-2">Info</BFormCheckbox>
              </div>
              <div>
                <BFormCheckbox switch id="switchWarning" checked class="form-check-warning mb-2">Warning</BFormCheckbox>
                <BFormCheckbox switch id="switchDanger" checked class="form-check-danger mb-2">Danger</BFormCheckbox>
                <BFormCheckbox switch id="switchPurple" checked class="form-check-purple mb-2">Purple</BFormCheckbox>
                <BFormCheckbox switch id="switchDark" checked class="form-check-dark">Dark</BFormCheckbox>
              </div>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Checkbox Toggle</label>
          </BCol>
          <BCol lg="5">
            <div class="mb-2">
              <input type="checkbox" class="btn-check" id="btncheck1" />
              <label class="btn btn-outline-primary" for="btncheck1">Single Toggle</label>
            </div>
            <div class="btn-group" role="group" aria-label="Checkbox toggle group">
              <input type="checkbox" class="btn-check" id="btncheck2" />
              <label class="btn btn-outline-primary" for="btncheck2">One</label>
              <input type="checkbox" class="btn-check" id="btncheck3" />
              <label class="btn btn-outline-primary" for="btncheck3">Two</label>
              <input type="checkbox" class="btn-check" id="btncheck4" />
              <label class="btn btn-outline-primary" for="btncheck4">Three</label>
            </div>
          </BCol>
        </BRow>

        <div class="border-top border-dashed my-3"></div>

        <BRow class="g-lg-4 g-2">
          <BCol lg="2">
            <label class="col-form-label">Radio Toggle</label>
          </BCol>
          <BCol lg="5">
            <div class="btn-group" role="group" aria-label="Radio toggle group">
              <input type="radio" class="btn-check" name="btnradio" id="btnradio1" />
              <label class="btn btn-outline-secondary" for="btnradio1">Left</label>
              <input type="radio" class="btn-check" name="btnradio" id="btnradio2" />
              <label class="btn btn-outline-secondary" for="btnradio2">Middle</label>
              <input type="radio" class="btn-check" name="btnradio" id="btnradio3" />
              <label class="btn btn-outline-secondary" for="btnradio3">Right</label>
            </div>
          </BCol>
        </BRow>
      </BCol>
    </BRow>
  </UICard>
</template>

<script setup lang="ts">
import { BFormCheckbox, BFormRadio, BRow } from 'bootstrap-vue-next';
import UICard from '~/components/UICard.vue';

</script>
