// Angular/Full/src/app/views/ecommerce/categories/categories.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {LucideAngularModule, LucideCircle, LucidePlus, LucideSearch} from 'lucide-angular';
import {RouterLink} from '@angular/router';
import {currency} from '@/app/constants';
import {toTitleCase} from '@/app/utils/string-utils';
import {NgIcon} from '@ng-icons/core';
import {Observable} from 'rxjs';
import {TableService} from '@core/services/table.service';
import {FormsModule} from '@angular/forms';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';
import {NgbPagination, NgbPaginationNext, NgbPaginationPrevious} from '@ng-bootstrap/ng-bootstrap';
import {AsyncPipe} from '@angular/common';

type categoryType = {
    id: number,
    name: string,
    image: string,
    slug: string,
    products: number,
    orders: number,
    earnings: number,
    date: string,
    time: string,
    status: 'active' | 'inactive',
    selected?: boolean
}

@Component({
    selector: 'app-categories',
    imports: [
        PageTitleComponent,
        LucideAngularModule,
        RouterLink,
        NgIcon,
        FormsModule,
        NgbdSortableHeader,
        NgbPagination,
        NgbPaginationNext,
        NgbPaginationPrevious,
        AsyncPipe
    ],
    providers: [TableService],
    templateUrl: './categories.component.html',
    styles: ``
})
export class CategoriesComponent implements OnInit {
    filterStatus='All'
    selectAll = false;

    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideCircle = LucideCircle;
    protected readonly LucidePlus = LucidePlus;

    categories$: Observable<categoryType[]>
    total$: Observable<number>;

    constructor(public tableService: TableService<categoryType>) {
        this.categories$ = this.tableService.items$
        this.total$ = this.tableService.total$
    }

    ngOnInit(): void {
        this.tableService.setItems(this.productCategories, 8)
    }

    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    deleteSelected() {
        this.tableService.deleteSelectedItems();
        this.selectAll = false;
    }

    get hasSelection(): boolean {
        return this.tableService.hasSelectedItems();
    }

    productCategories: categoryType[] = [
        {
            id: 1,
            name: 'Furnitures',
            image: 'assets/images/products/1.png',
            products: 5248,
            slug: 'furnitures',
            orders: 95.6,
            earnings: 40.5,
            date: '18 Apr, 2025',
            time: '12:24 PM',
            status: 'active'
        },
        {
            id: 2,
            name: 'Electronics',
            image: 'assets/images/products/2.png',
            slug: 'electronics',
            products: 9854,
            orders: 112.3,
            earnings: 30.4,
            date: '20 Apr, 2025',
            time: '09:10 AM',
            status: 'active'
        },
        {
            id: 3,
            name: 'Smartphones',
            slug: 'electronics-smartphones',
            image: 'assets/images/products/3.png',
            products: 1324,
            orders: 50.1,
            earnings: 22.3,
            date: '22 Apr, 2025',
            time: '11:45 AM',
            status: 'inactive'
        },
        {
            id: 4,
            name: 'Headphones',
            image: 'assets/images/products/4.png',
            slug: 'headphones',
            products: 5123,
            orders: 70.8,
            earnings: 5.7,
            date: '25 Apr, 2025',
            time: '08:20 AM',
            status: 'active',

        },
        {
            id: 5,
            name: 'Table Lamps',
            image: 'assets/images/products/5.png',
            slug: 'furniture-tables',
            products: 7589,
            orders: 88.7,
            earnings: 13.2,
            date: '27 Apr, 2025',
            time: '03:15 PM',
            status: 'inactive'
        },
        {
            id: 6,
            name: 'Kitchen Appliances',
            image: 'assets/images/products/6.png',
            slug: 'appliances',
            products: 3021,
            orders: 110.4,
            earnings: 12.1,
            date: '30 Apr, 2025',
            time: '06:00 PM',
            status: 'active'
        },
        {
            id: 7,
            name: 'Smart Watches',
            image: 'assets/images/products/7.png',
            slug: 'wearables',
            products: 6245,
            orders: 95.3,
            earnings: 8.9,
            date: '28 Apr, 2025',
            time: '10:45 AM',
            status: 'active'
        },
        {
            id: 8,
            name: 'Laptops',
            image: 'assets/images/products/8.png',
            slug: 'electronics',
            products: 4890,
            orders: 67.2,
            earnings: 15.4,
            date: '29 Apr, 2025',
            time: '02:30 PM',
            status: 'inactive'
        },
        {
            id: 9,
            name: 'Gaming Consoles',
            image: 'assets/images/products/9.png',
            slug: 'gaming',
            products: 3756,
            orders: 82.1,
            earnings: 10.7,
            date: '27 Apr, 2025',
            time: '09:10 AM',
            status: 'active'
        },
        {
            id: 10,
            name: 'Bluetooth Speakers',
            image: 'assets/images/products/10.png',
            products: 5432,
            slug: 'audio',
            orders: 78.9,
            earnings: 6.3,
            date: '26 Apr, 2025',
            time: '04:20 PM',
            status: 'active'
        }
    ];

    protected readonly currency = currency;
    protected readonly toTitleCase = toTitleCase;
}

<div class="container-fluid">
    <app-page-title title="Categories" subTitle="Ecommerce"/>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-light justify-content-between">

                    <div class="d-flex gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" data-table-search type="search"
                                   class="form-control"
                                   placeholder="Search category...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>
                        @if (hasSelection) {
                            <button class="btn btn-danger" (click)="deleteSelected()">Delete</button>
                        }
                    </div>

                    <div class="d-flex align-items-center gap-1">
                        <div>
                            <select [(ngModel)]="tableService.pageSize" class="form-select form-control my-1 my-md-0">
                                <option [ngValue]="5">5</option>
                                <option [ngValue]="8">8</option>
                                <option [ngValue]="10">10</option>
                                <option [ngValue]="15">15</option>
                                <option [ngValue]="20">20</option>
                            </select>
                        </div>

                        <div class="app-search">
                            <select [(ngModel)]="filterStatus"
                                    (ngModelChange)="tableService.setFilter('status', filterStatus)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">All</option>
                                <option value="Active">Active</option>
                                <option value="Inactive">Inactive</option>
                            </select>
                            <lucide-angular [img]="LucideCircle" class="app-search-icon text-muted"/>
                        </div>

                        <button class="btn btn-primary ms-1">
                            <lucide-angular [img]="LucidePlus" class="fs-sm me-2"/>
                            Add Category
                        </button>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th class="ps-3" style="width: 1%;">
                                <input [(ngModel)]="selectAll" (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" value="option">
                            </th>
                            <th sortable="name" (sort)="tableService.setSort($event.column, $event.direction)">Category
                                Name
                            </th>
                            <th sortable="slug" (sort)="tableService.setSort($event.column, $event.direction)">Slug</th>
                            <th sortable="products" (sort)="tableService.setSort($event.column, $event.direction)">
                                Products
                            </th>
                            <th sortable="orders" (sort)="tableService.setSort($event.column, $event.direction)">
                                Orders
                            </th>
                            <th sortable="earnings" (sort)="tableService.setSort($event.column, $event.direction)">
                                Earnings
                            </th>
                            <th sortable="date" (sort)="tableService.setSort($event.column, $event.direction)">Last
                                Modify
                            </th>
                            <th sortable="status" (sort)="tableService.setSort($event.column, $event.direction)">
                                Status
                            </th>
                            <th class="text-center" style="width: 1%;">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for ( category of categories$ | async; track $index) {
                                <tr>
                                    <td class="ps-3">
                                        <input
                                            class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                            type="checkbox" value="option" [(ngModel)]="category.selected"
                                            (change)="toggleSingleSelection()">
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <div class="avatar-md me-3">
                                                <img [src]="category.image" alt="Product" class="img-fluid rounded">
                                            </div>
                                            <div>
                                                <h5 class="mb-0">
                                                    <a data-sort="product" routerLink="/ecommerce/products/WB-10245"
                                                       class="link-reset">{{ category.name }}</a>
                                                </h5>
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{ category.slug }}</td>
                                    <td>
                                        <h5 class="fs-base mb-0 fw-medium">{{ category.products }}</h5>
                                    </td>
                                    <td>{{ category.orders }}k</td>
                                    <td>{{ currency }}{{ category.earnings }}M</td>
                                    <td>18 Apr, 2025 <small class="text-muted">{{ category.time }}</small></td>
                                    <td><span
                                        class="badge  fs-xxs {{category.status==='inactive' ? 'badge-soft-danger' : 'badge-soft-success'}}">{{ toTitleCase(category.status) }}</span>
                                    </td>
                                    <td>
                                        <div class="d-flex justify-content-center gap-1">
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <ng-icon
                                                    name="tablerEye" class="fs-lg"/>
                                            </button>
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <ng-icon
                                                    name="tablerEdit" class="fs-lg"/>
                                            </button>
                                            <button (click)="tableService.deleteItem(category)"
                                                    class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <ng-icon
                                                    name="tablerTrash" class="fs-lg"/>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="9" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                        <div
                            class="d-flex justify-content-between pagination-boxed align-items-center">
                            {{ tableService.showingRange }} categories
                            <ngb-pagination
                                [collectionSize]="(total$ | async)!"
                                [(page)]="tableService.page"
                                [pageSize]="tableService.pageSize"
                            >
                                <ng-template ngbPaginationPrevious>
                                    <ng-icon name="tablerChevronLeft"/>
                                </ng-template>
                                <ng-template ngbPaginationNext>
                                    <ng-icon name="tablerChevronRight"/>
                                </ng-template>
                            </ngb-pagination>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>

</div>

// Vue-Inertia/Full/resources/js/pages/apps/ecommerce/categories/index.vue
<template>
    <MainLayout>
        
        <BContainer fluid>
            <PageBreadcrumb title="Categories" subtitle="Ecommerce" />

            <BRow>
                <BCol xs="12">
                    <BCard no-body>
                        <BCardHeader class="border-light justify-content-between">
                            <div class="d-flex gap-2">
                                <div class="app-search">
                                    <input type="search" class="form-control" placeholder="Search category..."
                                        v-model="searchQuery">
                                    <Icon  icon="lucide:search" class="app-search-icon text-muted" />
                                </div>

                                <BButton v-if="selected.length" variant="danger" @click="handleDeleteSelected">
                                    Delete
                                </BButton>
                            </div>

                            <div class="d-flex align-items-center gap-1">
                                <div>
                                    <BFormSelect v-model="perPage" :options="perPageOptions"
                                        class="form-control my-1 my-md-0" />
                                </div>

                                <div class="app-search">
                                    <select data-table-filter="status" class="form-select form-control my-1 my-md-0">
                                        <option value="">All</option>
                                        <option value="Active">Active</option>
                                        <option value="Inactive">Inactive</option>
                                    </select>
                                    <Icon icon="lucide:circle" class="app-search-icon text-muted" />
                                </div>

                                <Link href="" class="btn btn-primary ms-1">
                                    <Icon icon="lucide:plus" class="fs-sm me-2" /> Add Category
                                </Link>
                            </div>
                        </BCardHeader>

                        <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                            v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                            hover :fields="fields" :items="categories" :per-page="perPage" :current-page="currentPage"
                            @filtered="onFiltered" responsive
                            class="table table-custom table-nowrap table-centered mb-0 w-100">
                            <template #head()="data">
                                <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                            </template>
                            <template #head(id)>
                                <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                                    id="select-all-products" value="option" :checked="allSelected"
                                    :indeterminate="isIndeterminate" @change="toggleSelectAll" />
                            </template>
                            <template #head(action)>
                                <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                            </template>
                            <template #cell(id)="data">
                                <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                    type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                    @change="onToggleRow(data.item, $event)" />
                            </template>
                            <template #cell(name)="{ item }">
                                <div class="d-flex align-items-center">
                                    <div class="avatar-md me-3">
                                        <img :src="item.image" alt="Product" class="img-fluid rounded" />
                                    </div>
                                    <div>
                                        <h5 class="mb-0">
                                            <Link href="/product-details/1" class="link-reset">{{ item.name }}
                                            </Link>
                                        </h5>
                                    </div>
                                </div>
                            </template>
                            <template #cell(products)="{ item }">
                                <h5 class="fs-base mb-0 fw-medium">{{ item.products }}</h5>
                            </template>
                            <template #cell(lastModified)="{ item }">
                                {{ item.lastModified }} <small class="text-muted">{{ item.lastModifiedTime }}</small>
                            </template>
                            <template #cell(status)="{ item }">
                                <span class="badge fs-xxs"
                                    :class="item.status == 'Active' ? 'badge-soft-success' : 'badge-soft-danger'">{{
                                        item.status }}</span>
                            </template>
                            <template #cell(action)="{ item }">
                                <div class="d-flex justify-content-center gap-1">
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:eye" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:edit" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:trash" class="fs-lg" @click="handleDeleteItem(item)" />
                                    </button>
                                </div>
                            </template>

                        </BTable>
                        <BCardFooter class="border-0">
                            <TablePagination v-model:currentPage="currentPage" :per-page="perPage"
                                :total-items="totalRows" label="categories" />
                        </BCardFooter>
                    </BCard>

                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardFooter, BCardHeader, BCol, BContainer, BFormSelect, BRow, type TableFieldRaw } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { categoriesData, type CategoryType } from './data';
import TablePagination from '@/components/TablePagination.vue';
import { ref } from 'vue';
import { Head ,Link} from '@inertiajs/vue3';
import { useTableActions } from '@/composables/useTableActions';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';

const fields: Exclude<TableFieldRaw<CategoryType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Category Name', sortable: true },
    { key: 'slug', label: 'Slug', sortable: true },
    { key: 'products', label: 'Products', sortable: true },
    { key: 'orders', label: 'Orders', sortable: true },
    { key: 'earnings', label: 'Earnings', sortable: true },
    { key: 'lastModified', label: 'Last Modified', sortable: true },
    { key: 'status', label: 'Status', sortable: true },
    { key: 'action', label: 'Action', sortable: false },
]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(categoriesData.length)
const categories = ref<CategoryType[]>(categoriesData)

function onFiltered(filteredItems: CategoryType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

function adjustPage() {
    const totalPages = Math.ceil(categories.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: CategoryType) {
    deleteItem(item)
    totalRows.value = categories.value.length
    adjustPage()
}

function handleDeleteSelected() {
    deleteSelected()
    totalRows.value = categories.value.length
    adjustPage()
}

const { selected, toggleSelectAll, onToggleRow, deleteSelected, deleteItem, allSelected, isIndeterminate } = useTableActions(categories)



</script>

<style scoped></style>
