// Vue-Inertia/Seed/resources/js/pages/auth/auth-1/login-pin/index.vue
<template>
    <Head title="Login With PIN" />
  <div class="auth-box overflow-hidden align-items-center d-flex">
    <BContainer>
      <BRow class="justify-content-center">
        <BCol cols="12" sm="8" md="6" xxl="4">
          <div class="auth-brand text-center mb-4">
            <AuthLogo />
            <h4 class="fw-bold mt-3">Login with PIN! | IN+</h4>
            <p class="text-muted w-lg-75 mx-auto">
              This screen is locked. Enter your PIN to continue.
            </p>
          </div>

          <BCard no-body class="p-4 rounded-4">
            <div class="text-center mb-4">
              <img
                :src="user1"
                class="rounded-circle img-thumbnail avatar-xxl mb-2"
                alt="thumbnail"
              />
              <h5 class="fs-md">Damian D.</h5>
            </div>

            <form>
              <label class="form-label"
                >Enter your 6-digit code <span class="text-danger">*</span></label
              >
              <VOtpInput
                v-model:value="otp"
                :num-inputs="6"
                input-classes="form-control text-center"
                input-type="tel"
                :is-input-num="true"
                :should-auto-focus="true"
                separator=" "
              />

              <div class="d-grid mt-3">
                <BButton type="submit" variant="primary" class="fw-semibold py-2 w-100">
                  Confirm
                </BButton>
              </div>
            </form>

            <p class="text-muted text-center mt-4 mb-0">
              Not you? Return to
              <Link
                href="/auth-1/sign-in"
                class="text-decoration-underline link-offset-3 fw-semibold"
              >
                Sign in
              </Link>
            </p>
          </BCard>

          <p class="text-center text-muted mt-4 mb-0">
            © 2014 - {{ currentYear }} INSPINIA — by <span class="fw-semibold">{{ author }}</span>
          </p>
        </BCol>
      </BRow>
    </BContainer>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import VOtpInput from 'vue3-otp-input'
import { BButton, BCard, BCol, BContainer, BRow } from 'bootstrap-vue-next'
import { author, currentYear } from '@/helpers'
import AuthLogo from '@/components/AuthLogo.vue'


import user1 from '@/images/users/user-1.jpg'
import { Head, Link } from '@inertiajs/vue3'

const otp = ref('')

</script>

// React-Inertia/Seed/resources/js/pages/auth/auth-1/login-pin/index.tsx
import { Head, Link } from '@inertiajs/react';
import { useState } from 'react'
import { Button, Card, Col, Container, Form, Row } from 'react-bootstrap'
import AppLogo from '@/components/AppLogo'
import OTPInput from '@/components/OTPInput'
import { author, currentYear } from '@/helpers'

import user1 from '@/images/users/user-1.jpg'

const Page = () => {
  const [code, setCode] = useState<string[]>(Array(6).fill(''))
  return (
    <div className="auth-box overflow-hidden align-items-center d-flex">
      <Head title="Login Pin" />
      <Container>
        <Row className="justify-content-center">
          <Col xxl={4} md={6} sm={8}>
            <div className="auth-brand text-center mb-4">
              <AppLogo />
              <h4 className="fw-bold mt-3">Login with PIN! | IN+</h4>
              <p className="text-muted w-lg-75 mx-auto">This screen is locked. Enter your PIN to continue.</p>
            </div>

            <Card className="p-4 rounded-4">
              <div className="text-center mb-4">
                <img src={user1} alt="User thumbnail" className="rounded-circle img-thumbnail avatar-xxl mb-2" height={96} />
                <h5 className="fs-md">Damian D.</h5>
              </div>

              <Form>
                <div className="form-group mb-3">
                  <OTPInput code={code} setCode={setCode} label="Enter your 6-digit code" />
                </div>

                <div className="d-grid">
                  <Button type="submit" variant="primary" className="fw-semibold py-2">
                    Confirm
                  </Button>
                </div>
              </Form>

              <p className="text-muted text-center mt-4 mb-0">
                Not you? Return to{' '}
                <Link href={route('login')} className="text-decoration-underline link-offset-3 fw-semibold">
                  Sign in
                </Link>
              </p>
            </Card>

            <p className="text-center text-muted mt-4 mb-0">
              © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
            </p>
          </Col>
        </Row>
      </Container>
    </div>
  )
}

export default Page
