// Vue-Inertia/Full/resources/js/pages/ui/accordions/index.vue
<template>
    <MainLayout>
         
        <BContainer fluid>
            <PageBreadcrumb title="Accordions" subtitle="UI" />
        </BContainer>
        <div class="container-xl">
            <BRow>
                <BCol xl="12">
                    <BCard no-body>
                        <BCardHeader>
                            <h4 class="card-title">Examples</h4>
                        </BCardHeader>

                        <BCardBody>
                            <p class="text-muted mb-2">
                                Build vertically collapsing accordions in combination with our Collapse JavaScript
                                plugin.
                            </p>

                            <a class="btn btn-link p-0 fw-semibold"
                                href="https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/accordion.html"
                                target="_blank">
                                Accordions on Bootstrap
                                <Icon icon="tabler:chevron-right" class="ms-1" />
                            </a>
                        </BCardBody>
                    </BCard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Default Accordions" isCollapsable>
                        <BAccordion>
                            <BAccordionItem v-for="(item, idx) in accordionData" :key="idx"
                                :title="item.question + '#' + (idx + 1)" :visible="idx == 0">
                                <div v-html="item.answer"></div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Flush Accordions" isCollapsable>
                        <BAccordion flush>
                            <BAccordionItem v-for="(item, idx) in accordionData" :key="idx"
                                :title="item.question + '#' + (idx + 1)" :visible="idx == 0">
                                <div v-html="item.answer"></div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Always Open Accordions" isCollapsable>
                        <BAccordion free>
                            <BAccordionItem v-for="(item, idx) in accordionData" :key="idx"
                                :title="item.question + '#' + (idx + 1)" :visible="idx == 0">
                                <div v-html="item.answer"></div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Accordion Without Arrow" isCollapsable>
                        <BAccordion class="accordion-arrow-none">
                            <BAccordionItem v-for="(item, idx) in accordionData" :key="idx"
                                :title="item.question + '#' + (idx + 1)" :visible="idx == 0">
                                <div v-html="item.answer"></div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Bordered Accordions" isCollapsable>
                        <BAccordion class="accordion-bordered">
                            <BAccordionItem v-for="(item, idx) in accordionData" :key="idx"
                                :title="item.question + '#' + (idx + 1)" :visible="idx == 0">
                                <div v-html="item.answer"></div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>

                <BCol xl="12">
                    <UICard title="Custom Icon Accordion" isCollapsable>
                        <BAccordion v-model="activeItem" class="accordion-custom-icon accordion-arrow-none">
                            <BAccordionItem id="0">
                                <template #title>
                                    Accordion item with tabler icons
                                    <Icon icon="tabler:plus" class="accordion-icon accordion-icon-on" />
                                    <Icon icon="tabler:minus" class="accordion-icon accordion-icon-off" />
                                </template>

                                <div>
                                    <strong>This is the first item's accordion body.</strong> It is shown by default,
                                    until
                                    the collapse
                                    plugin adds the appropriate classes that we use to style each element. These classes
                                    control the overall
                                    appearance, as well as the showing and hiding via CSS transitions. You can modify
                                    any of
                                    this with
                                    custom CSS or overriding our default variables. It's also worth noting that just
                                    about
                                    any HTML can go
                                    within the <code>.accordion-body</code>, though the transition does limit overflow.
                                </div>
                            </BAccordionItem>

                            <BAccordionItem id="1">
                                <template #title>
                                    Accordion item with lucid icons
                                    <Icon icon="lucide:plus-circle"
                                        class="accordion-icon accordion-icon-on avatar-xxs" />
                                    <Icon icon="lucide:minus-circle"
                                        class="accordion-icon accordion-icon-off avatar-xxs" />
                                </template>

                                <div>
                                    <strong>This is the second item's accordion body.</strong> It is hidden by default,
                                    until the collapse
                                    plugin adds the appropriate classes that we use to style each element. These classes
                                    control the overall
                                    appearance, as well as the showing and hiding via CSS transitions. You can modify
                                    any of
                                    this with
                                    custom CSS or overriding our default variables. It's also worth noting that just
                                    about
                                    any HTML can go
                                    within the <code>.accordion-body</code>, though the transition does limit overflow.
                                </div>
                            </BAccordionItem>

                            <BAccordionItem id="2">
                                <template #title>
                                    Accordion item with tabler icons
                                    <Icon icon="tabler:arrow-down" class="accordion-icon accordion-icon-on" />
                                    <Icon icon="tabler:arrow-up" class="accordion-icon accordion-icon-off" />
                                </template>

                                <div>
                                    <strong>This is the third item's accordion body.</strong> It is hidden by default,
                                    until
                                    the collapse
                                    plugin adds the appropriate classes that we use to style each element. These classes
                                    control the overall
                                    appearance, as well as the showing and hiding via CSS transitions. You can modify
                                    any of
                                    this with
                                    custom CSS or overriding our default variables. It's also worth noting that just
                                    about
                                    any HTML can go
                                    within the <code>.accordion-body</code>, though the transition does limit overflow.
                                </div>
                            </BAccordionItem>
                        </BAccordion>
                    </UICard>
                </BCol>
            </BRow>

        </div>
    </MainLayout>
</template>

<script setup lang="ts">

import { BAccordion, BAccordionItem, BCard, BCardBody, BCardHeader, BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import { ref } from 'vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';

const activeItem = ref('0')

interface AccordionType {
    question: string
    answer: string
}

const accordionData: AccordionType[] = [
    {
        question: 'Accordion Item ',
        answer:
            "<strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
    },
    {
        question: 'Accordion Item ',
        answer:
            "<strong>This is the second item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
    },
    {
        question: 'Accordion Item ',
        answer:
            "<strong>This is the third item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
    },
]


</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/ui/accordions/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Accordion, AccordionBody, AccordionHeader, AccordionItem, Card, CardBody, CardHeader, CardTitle, Col, Container, Row } from 'react-bootstrap'
import { LuCircleMinus, LuCirclePlus } from 'react-icons/lu'
import { TbArrowDown, TbArrowUp, TbChevronRight, TbMinus, TbPlus } from 'react-icons/tb'
import { Link } from '@inertiajs/react'
import MainLayout from '@/layouts/MainLayout'

export type AccordionType = {
  question: string
  answer: string
}

const accordionData: AccordionType[] = [
  {
    question: 'Accordion Item ',
    answer:
      "<strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
  },
  {
    question: 'Accordion Item ',
    answer:
      "<strong>This is the second item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
  },
  {
    question: 'Accordion Item ',
    answer:
      "<strong>This is the third item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.",
  },
]

const DefaultAccordions = () => {
  return (
    <ComponentCard title="Default Accordions">
      <Accordion defaultActiveKey={'1'} id="accordionExample">
        {accordionData.map((item, idx) => (
          <AccordionItem eventKey={`${idx + 1}`} key={idx}>
            <AccordionHeader as={'h2'} id="headingOne">
              {item.question}
            </AccordionHeader>
            <AccordionBody dangerouslySetInnerHTML={{ __html: item.answer }}></AccordionBody>
          </AccordionItem>
        ))}
      </Accordion>
    </ComponentCard>
  )
}

const FlushAccordions = () => {
  return (
    <ComponentCard title="Flush Accordions">
      <Accordion defaultActiveKey={'1'} className="accordion-flush " id="accordionFlushExample">
        {accordionData.map((item, idx) => (
          <AccordionItem eventKey={`${idx + 1}`} key={idx}>
            <AccordionHeader as={'h2'} id="headingOne">
              {item.question}
            </AccordionHeader>
            <AccordionBody dangerouslySetInnerHTML={{ __html: item.answer }}></AccordionBody>
          </AccordionItem>
        ))}
      </Accordion>
    </ComponentCard>
  )
}

const AlwaysOpenAccordions = () => {
  return (
    <ComponentCard title="Always Open Accordions">
      <Accordion alwaysOpen defaultActiveKey={['1']} className="" id="accordionPanelsStayOpenExample">
        {accordionData.map((item, idx) => (
          <AccordionItem eventKey={`${idx + 1}`} key={idx}>
            <AccordionHeader as={'h2'} id="headingOne">
              {item.question}
            </AccordionHeader>
            <AccordionBody dangerouslySetInnerHTML={{ __html: item.answer }}></AccordionBody>
          </AccordionItem>
        ))}
      </Accordion>
    </ComponentCard>
  )
}

const WithoutArrowAccordion = () => {
  return (
    <ComponentCard title="Accordion Without Arrow">
      <Accordion defaultActiveKey={'1'} className="accordion-arrow-none " id="withoutarrowaccordionExample">
        {accordionData.map((item, idx) => (
          <AccordionItem eventKey={`${idx}`} key={idx}>
            <AccordionHeader as={'h2'} id="headingOne">
              {item.question}
            </AccordionHeader>
            <AccordionBody dangerouslySetInnerHTML={{ __html: item.answer }}></AccordionBody>
          </AccordionItem>
        ))}
      </Accordion>
    </ComponentCard>
  )
}

const BorderedAccordions = () => {
  return (
    <ComponentCard title="Bordered Accordions">
      <Accordion defaultActiveKey={'1'} className="accordion-bordered " id="BorderedaccordionExample">
        {accordionData.map((item, idx) => (
          <AccordionItem eventKey={`${idx}`} key={idx}>
            <AccordionHeader as={'h2'} id="headingOne">
              {item.question}
            </AccordionHeader>
            <AccordionBody dangerouslySetInnerHTML={{ __html: item.answer }}></AccordionBody>
          </AccordionItem>
        ))}
      </Accordion>
    </ComponentCard>
  )
}

const CustomIconAccordion = () => {
  return (
    <ComponentCard title="Custom Icon Accordion">
      <Accordion defaultActiveKey={'0'} className="accordion-bordered accordion-custom-icon accordion-arrow-none" id="CustomIconaccordionExample">
        <AccordionItem eventKey="0">
          <AccordionHeader as={'h2'} id="CustomIconheadingOne">
            Accordion item with tabler icons
            <TbPlus className="accordion-icon accordion-icon-on" />
            <TbMinus className="accordion-icon accordion-icon-off" />
          </AccordionHeader>
          <AccordionBody>
            <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes
            that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions.
            You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go
            within the <code>.accordion-body</code>, though the transition does limit overflow.
          </AccordionBody>
        </AccordionItem>
        <AccordionItem eventKey="1">
          <AccordionHeader as={'h2'} id="CustomIconheadingTwo">
            Accordion item with lucid icons
            <LuCirclePlus className="accordion-icon accordion-icon-on avatar-xxs me-n1" />
            <LuCircleMinus className="accordion-icon accordion-icon-off avatar-xxs me-n1" />
          </AccordionHeader>
          <AccordionBody>
            <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes
            that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions.
            You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go
            within the <code>.accordion-body</code>, though the transition does limit overflow.
          </AccordionBody>
        </AccordionItem>
        <AccordionItem eventKey="2">
          <AccordionHeader as={'h2'} id="CustomIconheadingThree">
            Accordion item with solar duotone icons
            <TbArrowDown className="accordion-icon accordion-icon-on" />
            <TbArrowUp className="accordion-icon accordion-icon-off" />
          </AccordionHeader>
          <AccordionBody>
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes
            that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions.
            You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go
            within the <code>.accordion-body</code>, though the transition does limit overflow.
          </AccordionBody>
        </AccordionItem>
      </Accordion>
    </ComponentCard>
  )
}

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="Accordions" subtitle="UI" />
        <Container fluid="xl">
          <Row>
            <Col xl={12}>
              <Card>
                <CardHeader>
                  <CardTitle as={'h4'}>Examples</CardTitle>
                </CardHeader>
                <CardBody>
                  <p className="text-muted mb-2">Build vertically collapsing accordions in combination with our Collapse JavaScript plugin.</p>
                  <Link className="btn btn-link p-0 fw-semibold" href="https://react-bootstrap.netlify.app/docs/components/accordion/" target="_blank">
                    Accordions on React Bootstrap
                    <TbChevronRight className="ms-1" />
                  </Link>
                </CardBody>
              </Card>
            </Col>
            <Col xl={12}>
              <DefaultAccordions />
            </Col>
            <Col xl={12}>
              <FlushAccordions />
            </Col>
            <Col xl={12}>
              <AlwaysOpenAccordions />
            </Col>
            <Col xl={12}>
              <WithoutArrowAccordion />
            </Col>
            <Col xl={12}>
              <BorderedAccordions />
            </Col>
            <Col xl={12}>
              <CustomIconAccordion />
            </Col>
          </Row>
        </Container>
      </Container>
    </MainLayout>
  )
}

export default Page
