// SvelteKit/Seed/src/routes/(auth)/auth-2/sign-in/+page.svelte
<script lang="ts">
	import { author, currentYear } from '$lib/helpers';
	import Icon from '@iconify/svelte';
	import AuthLogo from '$lib/components/AuthLogo.svelte';
	import PageMeta from '$lib/components/PageMeta.svelte';
	import { Button, Card, Col, Container, Form, Input, Row } from '@sveltestrap/sveltestrap';
</script>

<PageMeta title="Sign In" />

<div class="auth-box d-flex align-items-center">
	<Container xxl>
		<Row class="align-items-center justify-content-center">
			<Col xl="10">
				<Card class="rounded-4">
					<Row class="justify-content-between g-0">
						<Col lg="6">
							<div class="card-body">
								<div class="auth-brand text-center mb-4">
									<AuthLogo />
									<h4 class="fw-bold mt-4">Welcome to IN+</h4>
									<p class="text-muted w-lg-75 mx-auto">
										Let’s get you signed in. Enter your email and password to continue.
									</p>
								</div>

								<Form>
									<div class="mb-3">
										<label for="userEmail" class="form-label">
											Email address <span class="text-danger">*</span>
										</label>
										<div class="input-group">
											<span class="input-group-text bg-light">
												<Icon icon="tabler:mail" class="text-muted fs-xl" />
											</span>
											<Input type="email" id="userEmail" placeholder="you@example.com" required />
										</div>
									</div>

									<div class="mb-3">
										<label for="userPassword" class="form-label">
											Password <span class="text-danger">*</span>
										</label>
										<div class="input-group">
											<span class="input-group-text bg-light">
												<Icon icon="tabler:lock-password" class="text-muted fs-xl" />
											</span>
											<Input type="password" id="userPassword" placeholder="••••••••" required />
										</div>
									</div>

									<div class="d-flex justify-content-between align-items-center mb-3">
										<Input type="checkbox" name="termAndPolicy" label="Keep me signed in" />
										<a
											href="/auth-2/reset-password"
											class="text-decoration-underline link-offset-3 text-muted"
										>
											Forgot Password?
										</a>
									</div>

									<div class="d-grid">
										<Button type="submit" color="primary" class="fw-semibold py-2">Sign In</Button>
									</div>
								</Form>

								<p class="text-muted text-center mt-4 mb-0">
									New here?
									<a
										href="/auth-2/sign-up"
										class="text-decoration-underline link-offset-3 fw-semibold"
									>
										Create an account
									</a>
								</p>

								<p class="text-center text-muted mt-4 mb-0">
									© 2014 - {currentYear} INSPINIA — by
									<span class="fw-semibold">{author}</span>
								</p>
							</div>
						</Col>

						<Col lg="6" class="d-none d-lg-block">
							<div class="h-100 position-relative card-side-img rounded-end-4 overflow-hidden">
								<div
									class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"
								></div>
							</div>
						</Col>
					</Row>
				</Card>
			</Col>
		</Row>
	</Container>
</div>

// React-Inertia/Full/resources/js/pages/auth/auth-2/sign-in/index.tsx
import AppLogo from '@/components/AppLogo'
import { author, currentYear } from '@/helpers'
import { Head, Link } from '@inertiajs/react';
import { Button, Card, Col, Form, FormControl, FormLabel, Row } from 'react-bootstrap'
import { TbLockPassword, TbMail } from 'react-icons/tb'

const Page = () => {
  return (
    <div className="auth-box d-flex align-items-center">
      <Head title="Sign In" />
      <div className="container-xxl">
        <Row className="align-items-center justify-content-center">
          <Col xl={10}>
            <Card className="rounded-4">
              <Row className="justify-content-between g-0">
                <Col lg={6}>
                  <div className="card-body">
                    <div className="auth-brand text-center mb-4">
                      <AppLogo />
                      <h4 className="fw-bold mt-4">Welcome to IN+</h4>
                      <p className="text-muted w-lg-75 mx-auto">Let’s get you signed in. Enter your email and password to continue.</p>
                    </div>

                    <Form>
                      <div className="mb-3">
                        <FormLabel htmlFor="userEmail" className="form-label">
                          Email address <span className="text-danger">*</span>
                        </FormLabel>
                        <div className="input-group">
                          <span className="input-group-text bg-light">
                            <TbMail className="text-muted fs-xl" />
                          </span>
                          <FormControl type="email" id="userEmail" placeholder="you@example.com" required />
                        </div>
                      </div>

                      <div className="mb-3">
                        <FormLabel htmlFor="userPassword" className="form-label">
                          Password <span className="text-danger">*</span>
                        </FormLabel>
                        <div className="input-group">
                          <span className="input-group-text bg-light">
                            <TbLockPassword className="text-muted fs-xl" />
                          </span>
                          <FormControl type="password" id="userPassword" placeholder="••••••••" required />
                        </div>
                      </div>

                      <div className="d-flex justify-content-between align-items-center mb-3">
                        <div className="form-check">
                          <input className="form-check-input form-check-input-light fs-14" type="checkbox" id="rememberMe" />
                          <label className="form-check-label" htmlFor="rememberMe">
                            Keep me signed in
                          </label>
                        </div>

                        <Link href="/auth-2/reset-password" className="text-decoration-underline link-offset-3 text-muted">
                          Forgot Password?
                        </Link>
                      </div>

                      <div className="d-grid">
                        <Button type="submit" className="btn btn-primary fw-semibold py-2">
                          Sign In
                        </Button>
                      </div>
                    </Form>

                    <p className="text-muted text-center mt-4 mb-0">
                      New here?{' '}
                      <Link href="/auth-2/sign-up" className="text-decoration-underline link-offset-3 fw-semibold">
                        Create an account
                      </Link>
                    </p>

                    <p className="text-center text-muted mt-4 mb-0">
                      © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
                    </p>
                  </div>
                </Col>
                <Col lg={6} className="d-none d-lg-block">
                  <div className="h-100 position-relative card-side-img rounded-end-4 rounded-end rounded-0 overflow-hidden">
                    <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                  </div>
                </Col>
              </Row>
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  )
}

export default Page
