// Nuxt/Full/pages/(dashboards)/dashboard/components/ProjectUpdates.vue
<template>
    <BCard no-body>
        <BCardHeader class="d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0">Latest Project Updates</h5>
            <BBadge variant="warning" class="fs-xxs p-1">
                8 Notifications
            </BBadge>
        </BCardHeader>

        <BCardBody>
            <div class="timeline timeline-icon-bordered">
                <div v-for="event in timelineEvents" :key="event.id" class="timeline-item d-flex align-items-stretch">
                    <div class="timeline-dot">
                        <Icon :name="event.icon" :class="`text-${event.iconColor}`" size="18" />
                    </div>
                    <div class="timeline-content ps-3">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1 fs-base">
                                {{ event.title }}
                                <span :class="`badge badge-label badge-soft-${event.tagVariant} ms-2`">
                                    {{ event.tag }}
                                </span>
                            </h5>
                            <span class="text-muted fs-xxs">{{ event.time }}</span>
                        </div>
                        <p class="mb-1 text-muted">{{ event.description }}</p>
                        <div class="d-flex align-items-center gap-2">
                            <NuxtImg :src="event.userImage" :alt="event.userName" class="rounded-circle avatar-xxs" />
                            <NuxtLink :to="event.userLink" class="fw-medium link-reset text-muted">
                                {{ event.userName }}
                            </NuxtLink>
                        </div>
                        <hr v-if="event.hasDivider" class="border-dashed" />
                    </div>
                </div>
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BBadge, BCard, BCardBody, BCardHeader } from 'bootstrap-vue-next';
import { timelineEvents } from './data';


</script>

<style scoped></style>

// NextJs/NextJs/Full/TS/src/app/(admin)/(apps)/(dashboards)/dashboard/components/ProjectUpdates.tsx
import Image from 'next/image'
import { Badge, Card, CardBody, CardHeader } from 'react-bootstrap'

import { timelineEvents } from '../data'

const ProjectUpdates = () => {
  return (
    <Card>
      <CardHeader className="d-flex justify-content-between align-items-center">
        <h5 className="card-title mb-0">Latest Project Updates</h5>
        <Badge bg="warning" className="fs-xxs p-1">
          8 Notifications
        </Badge>
      </CardHeader>
      <CardBody>
        <div className="timeline timeline-icon-bordered">
          {timelineEvents.map((event) => {
            const IconComponent = event.icon
            return (
              <div key={event.id} className="timeline-item d-flex align-items-stretch">
                <div className="timeline-dot">
                  <IconComponent className={`text-${event.iconColor}`} size={18} />
                </div>
                <div className="timeline-content ps-3">
                  <div className="d-flex justify-content-between">
                    <h5 className="mb-1 fs-base">
                      {event.title}
                      <span className={`badge badge-label badge-soft-${event.tagVariant} ms-2`}>{event.tag}</span>
                    </h5>
                    <span className="text-muted fs-xxs">{event.time}</span>
                  </div>
                  <p className="mb-1 text-muted">{event.description}</p>
                  <div className="d-flex align-items-center gap-2">
                    <Image src={event.userImage} alt={event.userName} className="rounded-circle avatar-xxs" />
                    <a href={event.userLink} className="fw-medium link-reset text-muted">
                      {event.userName}
                    </a>
                  </div>
                  {event.hasDivider && <hr className="border-dashed" />}
                </div>
              </div>
            )
          })}
        </div>
      </CardBody>
    </Card>
  )
}

export default ProjectUpdates
