// Full/src/views/apps/projects/projects/[id]/components/ProjectTabs.vue
<template>
    <BTabs nav-class="nav nav-tabs nav-bordered mb-3">
        <BTab>
            <template #title>
                <Icon icon="tabler:message-circle" class="fs-lg me-md-1 align-middle" />
                <span class="d-none d-md-inline-block align-middle">Comments</span>
            </template>
            <Comments />
        </BTab>
        <BTab>
            <template #title>
                <Icon icon="tabler:list-check" class="fs-lg me-md-1 align-middle" />
                <span class="d-none d-md-inline-block align-middle">Task List</span>
            </template>
            <TaskList />
        </BTab>
        <BTab>
            <template #title>
                <Icon icon="tabler:activity" class="fs-lg me-md-1 align-middle" />
                <span class="d-none d-md-inline-block align-middle">Activity</span>
            </template>
            <Activity />
        </BTab>
    </BTabs>

</template>

<script setup lang="ts">
import { BTabs } from 'bootstrap-vue-next';
import Comments from './Comments.vue';
import TaskList from './TaskList.vue';
import Activity from './Activity.vue';
import { Icon } from '@iconify/vue';


</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/apps/projects/projects/[projectId]/components/ProjectTabs.tsx
import { Nav, NavItem, NavLink, TabContainer, TabContent, TabPane } from 'react-bootstrap'
import { TbActivity, TbListCheck, TbMessageCircle } from 'react-icons/tb'
import Comments from '@/pages/apps/projects/projects/[projectId]/components/Comments'
import TaskList from '@/pages/apps/projects/projects/[projectId]/components/TaskList'
import Activity from '@/pages/apps/projects/projects/[projectId]/components/Activity'

const ProjectTabs = () => {
  return (
    <TabContainer defaultActiveKey="0">
      <Nav as="ul" className="nav nav-tabs nav-bordered mb-3" role="tablist">
        <NavItem>
          <NavLink eventKey="0" role="tab">
            <TbMessageCircle className="fs-lg me-md-1 align-middle" />
            <span className="d-none d-md-inline-block align-middle">Comments</span>
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink eventKey={'1'} role="tab">
            <TbListCheck className="fs-lg me-md-1 align-middle" />
            <span className="d-none d-md-inline-block align-middle">Task List</span>
          </NavLink>
        </NavItem>
        <NavItem>
          <NavLink eventKey={'2'} role="tab">
            <TbActivity className="fs-lg me-md-1 align-middle" />
            <span className="d-none d-md-inline-block align-middle">Activity</span>
          </NavLink>
        </NavItem>
      </Nav>
      <TabContent>
        <TabPane eventKey="0" className="fade" id="comments" role="tabpanel">
          <Comments />
        </TabPane>

        <TabPane eventKey="1" className="fade" id="tasks" role="tabpanel">
          <TaskList />
        </TabPane>

        <TabPane eventKey="2" className="fade" id="activity" role="tabpanel">
          <Activity />
        </TabPane>
      </TabContent>
    </TabContainer>
  )
}

export default ProjectTabs
