// React/Full/JS/src/views/tables/tanstack/components/TableWithCheckboxSelect.jsx
import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import { Button, CardHeader, Col, Row } from 'react-bootstrap';
import { Link } from 'react-router';
import { useState } from 'react';
import { LuSearch } from 'react-icons/lu';
import { TbEdit, TbEye, TbTrash } from 'react-icons/tb';
import ComponentCard from '@/components/cards/ComponentCard';
import Rating from '@/components/Rating';
import DataTable from '@/components/table/DataTable';
import DeleteConfirmationModal from '@/components/table/DeleteConfirmationModal';
import { currency } from '@/helpers';
import { toPascalCase } from '@/helpers/casing';
import { products } from '@/views/tables/tanstack/data';
const priceRangeFilterFn = (row, columnId, value) => {
  const price = row.getValue(columnId);
  if (!value) return true;
  if (value === '500+') return price > 500;
  const [min, max] = value.split('-').map(Number);
  return price >= min && price <= max;
};
const columnHelper = createColumnHelper();
const TableWithCheckboxSelect = () => {
  const columns = [{
    id: 'select',
    header: ({
      table
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()} />,
    cell: ({
      row
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} />,
    enableSorting: false,
    enableColumnFilter: false
  }, columnHelper.accessor('name', {
    header: 'Product',
    cell: ({
      row
    }) => <div className="d-flex">
          <div className="avatar-md me-3">
            <img src={row.original.image} alt="Product" height={36} width={36} className="img-fluid rounded" />
          </div>
          <div>
            <h5 className="mb-1">
              <Link to={row.original.url} className="link-reset">
                {row.original.name}
              </Link>
            </h5>
            <p className="text-muted mb-0 fs-xxs">by: {row.original.brand}</p>
          </div>
        </div>
  }), columnHelper.accessor('code', {
    header: 'Code'
  }), columnHelper.accessor('category', {
    header: 'Category',
    filterFn: 'equalsString',
    enableColumnFilter: true
  }), columnHelper.accessor('stock', {
    header: 'Stock'
  }), columnHelper.accessor('price', {
    header: 'Price',
    filterFn: priceRangeFilterFn,
    enableColumnFilter: true,
    cell: ({
      row
    }) => <>
          {currency}
          {row.original.price}
        </>
  }), columnHelper.accessor('sold', {
    header: 'Sold'
  }), columnHelper.accessor('rating', {
    header: 'Rating',
    cell: ({
      row
    }) => <>
          <Rating rating={row.original.rating} />
          <span className="ms-1">
            <Link to="" className="link-reset fw-semibold">
              ({row.original.reviews})
            </Link>
          </span>
        </>
  }), columnHelper.accessor('status', {
    header: 'Status',
    filterFn: 'equalsString',
    enableColumnFilter: true,
    cell: ({
      row
    }) => <span className={`badge ${row.original.status === 'published' ? 'badge-soft-success' : row.original.status === 'pending' ? 'badge-soft-warning' : 'badge-soft-danger'} fs-xxs`}>
          {toPascalCase(row.original.status)}
        </span>
  }), columnHelper.accessor('date', {
    header: 'Date',
    cell: ({
      row
    }) => <>
          {row.original.date} <small className="text-muted">{row.original.time}</small>
        </>
  }), {
    header: 'Actions',
    cell: () => <div className="d-flex  gap-1">
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbEye className="fs-lg" />
          </Button>
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbEdit className="fs-lg" />
          </Button>
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbTrash className="fs-lg" />
          </Button>
        </div>
  }];
  const [data, setData] = useState(() => [...products]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [sorting, setSorting] = useState([]);
  const [columnFilters, setColumnFilters] = useState([]);
  const [pagination, setPagination] = useState({
    pageIndex: 0,
    pageSize: 5
  });
  const [selectedRowIds, setSelectedRowIds] = useState({});
  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
      globalFilter,
      columnFilters,
      pagination,
      rowSelection: selectedRowIds
    },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    onColumnFiltersChange: setColumnFilters,
    onPaginationChange: setPagination,
    onRowSelectionChange: setSelectedRowIds,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    globalFilterFn: 'includesString',
    enableColumnFilters: true,
    enableRowSelection: true,
    filterFns: {
      priceRange: priceRangeFilterFn
    }
  });
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const toggleDeleteModal = () => {
    setShowDeleteModal(!showDeleteModal);
  };
  const handleDelete = () => {
    const selectedIds = new Set(Object.keys(selectedRowIds));
    setData(old => old.filter((_, idx) => !selectedIds.has(idx.toString())));
    setSelectedRowIds({});
    setPagination({
      ...pagination,
      pageIndex: 0
    });
    setShowDeleteModal(false);
  };
  return <Row>
      <Col sm={12}>
        <ComponentCard title="Custom table with checkbox select" bodyClassName="p-0">
          <CardHeader className="border-light justify-content-between">
            <div className="d-flex gap-2">
              <div className="app-search">
                <input type="search" className="form-control" placeholder="Search product name..." value={globalFilter ?? ''} onChange={e => setGlobalFilter(e.target.value)} />
                <LuSearch className="app-search-icon text-muted" />
              </div>

              {Object.keys(selectedRowIds).length > 0 && <Button variant="danger" size="sm" onClick={toggleDeleteModal}>
                  Delete
                </Button>}
            </div>
          </CardHeader>

          <DataTable table={table} emptyMessage="No records found" />

          <DeleteConfirmationModal show={showDeleteModal} onHide={toggleDeleteModal} onConfirm={handleDelete} selectedCount={Object.keys(selectedRowIds).length} itemName="product" />
        </ComponentCard>
      </Col>
    </Row>;
};
export default TableWithCheckboxSelect;

// Nuxt/Full/pages/tables/custom/components/TableWithCheckBoxSelect.vue
<template>
    <UICard title="Custom table with checkbox select" body-class="p-0">

        <BCardHeader class="border-light justify-content-between">
            <div class="d-flex gap-2">
                <div class="app-search">
                    <input v-model="searchQuery" type="search" class="form-control"
                        placeholder="Search product name...">
                    <Icon name="lucide:search" class="app-search-icon text-muted" />
                </div>
            </div>

            <div class="d-flex align-items-center gap-2">
                <div>
                    <BFormSelect v-model="perPage" :options="perPageOptions" class="form-control my-1 my-md-0" />
                </div>

            </div>
        </BCardHeader>

        <BTable show-empty :filter="searchQuery" empty-text="Nothing found." v-model:selected-rows="selected"
            thead-class="bg-light align-middle bg-opacity-25 thead-sm" hover :fields="fields" :items="productsData"
            :per-page="perPage" :current-page="currentPage" @filtered="onFiltered" responsive
            class="table table-custom table-nowrap table-centered mb-0 w-100">
            <template #head()="data">
                <span class="text-uppercase fs-xxs">{{ data.label }}</span>
            </template>
            <template #head(id)>
                <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                    id="select-all-products" value="option" :checked="allSelected" :indeterminate="isIndeterminate"
                    @change="toggleSelectAll" />
            </template>
            <template #head(action)>
                <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
            </template>
            <template #cell(id)="data">
                <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0" type="checkbox"
                    :value="data.item" :checked="selected.includes(data.item)"
                    @change="onToggleRow(data.item, $event)" />
            </template>
            <template #cell(name)="{ item }">
                <div class="d-flex">
                    <div class="avatar-md me-3">
                        <NuxtImg :src="item.image" alt="Product" class="img-fluid rounded" />
                    </div>
                    <div>
                        <h5 class="mb-1">
                            <NuxtLink :to="`/products/${item.id}`" class="link-reset">{{ item.name }}</NuxtLink>
                        </h5>
                        <p class="text-muted mb-0 fs-xxs">by: {{ item.manufacturer }}</p>
                    </div>
                </div>
            </template>
            <template #cell(stock)="{ item }">
                <h5 class="fs-base mb-0 fw-medium">{{ item.stock }}</h5>
            </template>
            <template #cell(price)="{ item }">
                {{ currency }}{{ item.price }}
            </template>
            <template #cell(rating)="{ item }">
                <Rating :rating="item.rating" class="d-inline-flex align-items-center gap-1"/>
                <span class="ms-1">
                    <NuxtLink to="/reviews" class="link-reset fw-semibold">({{ item.reviews }})</NuxtLink>
                </span>
            </template>
            <template #cell(status)="{ item }">
                <span class="badge  fs-xxs"
                    :class="item.status === 'out-of-stock' ? 'badge-soft-danger' : item.status === 'pending' ? 'badge-soft-warning' : 'badge-soft-success'">{{
                        toPascalCase(item.status) }}</span>
            </template>
            <template #cell(publish)="{ item }">
                {{ item.date }} <small class="text-muted">{{ item.time }}</small>
            </template>
            <template #cell(action)>
                <div class="d-flex justify-content-center gap-1">
                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                        <Icon name="tabler:eye" class="fs-lg" />
                    </button>
                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                        <Icon name="tabler:edit" class="fs-lg" />
                    </button>
                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                        <Icon name="tabler:trash" class="fs-lg"/>
                    </button>
                </div>
            </template>
        </BTable>
            
        <BCardFooter class="border-0">
            <TablePagination v-model:currentPage="currentPage" :per-page="perPage" :total-items="totalRows"
                label="products" />
        </BCardFooter>

    </UICard>
</template>

<script setup lang="ts">
import { BCard, BCardHeader, BFormSelect, BTable, type TableFieldRaw } from 'bootstrap-vue-next';
import UICard from '~/components/UICard.vue';
import { products, type ProductType } from '../data';
import { currency } from '~/helpers';
import Rating from '~/components/Rating.vue';
import { toPascalCase } from '~/helpers/casing';
import TablePagination from '~/components/TablePagination.vue';

const fields: Exclude<TableFieldRaw<ProductType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Product' },
    { key: 'sku', label: 'Sku' },
    { key: 'category', label: 'Category', },
    { key: 'stock', label: 'Stock', },
    { key: 'price', label: 'Price', },
    { key: 'orders', label: 'Orders', },
    { key: 'rating', label: 'Rating'},
    { key: 'status', label: 'Status', },
    { key: 'publish', label: 'Publish', },
    { key: 'action', label: 'Action', },
]

const searchQuery = ref('')

const perPageOptions = [5, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(5)
const totalRows = ref(products.length)
const productsData = ref<ProductType[]>(products)

function onFiltered(filteredItems: ProductType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}



const { selected, toggleSelectAll, onToggleRow, allSelected, isIndeterminate } = useTableActions(productsData)

</script>

<style scoped></style>
