// React-Inertia/Seed/resources/js/pages/auth/auth-1/verify-email/index.tsx
import checkmark from '@/images/checkmark.png'
import AppLogo from '@/components/AppLogo'
import { author, currentYear } from '@/helpers'
import { Head, Link, useForm } from '@inertiajs/react'

import { Button, Card, Col, Container, Form, Row } from 'react-bootstrap'
import type { FormEventHandler } from 'react'

const VerifyEmail = () => {
        const { post, processing } = useForm({});

    const submit: FormEventHandler = (e) => {
        e.preventDefault();

        post(route('verification.send'));
    };
  return (
    <div className="auth-box overflow-hidden align-items-center d-flex">
      <Head title="Verify Email" />
      <Container>
        <Row className="justify-content-center">
          <Col xxl={4} md={6} sm={8}>
            <div className="auth-brand text-center mb-4">
              <AppLogo />
              <h4 className="fw-bold mt-3">Welcome to IN+</h4>
              <p className="text-muted w-lg-75 mx-auto">Awesome! You&apos;ve read the important message like a pro.</p>
            </div>

            <Card className="p-4 rounded-4">
              <Form onSubmit={submit}>
                <div className="mb-4">
                  <div className="avatar-xxl mx-auto mt-2">
                    <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                      <img src={checkmark} alt="checkmark" height="64" />
                    </div>
                  </div>
                </div>


                <div className="d-grid">
                  <Button type="submit" className="btn btn-primary fw-semibold py-2" disabled={processing}>
                    Resend verification email
                  </Button>
                  <Link method='post' type="submit" href={route('logout')} className="btn btn-danger mt-2 fw-semibold py-2" disabled={processing}>
                 Logout
                  </Link>
                </div>
              </Form>
            </Card>

            <p className="text-center text-muted mt-4 mb-0">
              © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
            </p>
          </Col>
        </Row>
      </Container>
    </div>
  )
}

export default VerifyEmail

// Vue-Inertia/Seed/resources/js/pages/auth/auth-1/verify-email/index.vue
<template>

    <Head title="Verify Email" />
    <div class="auth-box overflow-hidden d-flex align-items-center">
        <BContainer>
            <BRow class="justify-content-center">
                <BCol cols="12" sm="8" md="6" xxl="4">
                    <div class="auth-brand text-center mb-4">
                        <AuthLogo />
                        <h4 class="fw-bold mt-3">Verify Email | IN+</h4>
                        <p class="text-muted w-lg-75 mx-auto">
                            Verify your email address
                        </p>
                    </div>

                    <BCard no-body class="p-4 rounded-4">
                        <p v-if="status === 'verification-link-sent'" class="text-success mb-3">
                            A new verification link has been sent to the email address you provided during registration.
                        </p>
                        <form @submit.prevent="submit">

                            <div class="d-grid">
                                <BButton :disabled="form.processing" variant="primary" type="submit"
                                    class="fw-semibold py-2">
                                    Resend verification email
                                </BButton>
                                <Link :href="route('logout')" method="post"  class="fw-semibold py-2 mt-2 btn btn-danger" type="submit"
                                    >
                                  Logout
                                </Link>
                            </div>
                        </form>
                    </BCard>

                    <p class="text-center text-muted mt-4 mb-0">
                        © 2014 - {{ currentYear }} INSPINIA — by <span class="fw-semibold">{{ author }}</span>
                    </p>
                </BCol>
            </BRow>
        </BContainer>
    </div>
</template>

<script setup lang="ts">

import AuthLogo from '@/components/AuthLogo.vue';
import { author, currentYear } from '@/helpers';
import { Link, useForm } from '@inertiajs/vue3';


defineProps<{
    status?: string;
}>();

const form = useForm({});

const submit = () => {
    form.post(route('verification.send'));
};

</script>
