// SvelteKit/Seed/src/routes/(admin)/dashboard/+page.svelte
<script lang="ts">
	import { Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageBreadcrumb from '$lib/components/PageBreadcrumb.svelte';
	import StatisticWidget from './components/StatisticWidget.svelte';
	import OrderStatistics from './components/OrderStatistics.svelte';
	import ProductInventory from './components/ProductInventory.svelte';
	import RecentOrders from './components/RecentOrders.svelte';
	import Transactions from './components/Transactions.svelte';
	import { statistics } from './data';
</script>

<Container fluid>
	<PageBreadcrumb title="Dashboard" />

	<Row class="row-cols-xxl-4 row-cols-md-2 row-cols-1">
		{#each statistics as item, idx (idx)}
			<Col>
				<StatisticWidget {item} />
			</Col>
		{/each}
	</Row>

	<Row>
		<Col sm="12">
			<OrderStatistics />
		</Col>
	</Row>

	<Row>
		<Col xxl="6">
			<ProductInventory />
		</Col>
		<Col xxl="6">
			<RecentOrders />
		</Col>
	</Row>

	<Row>
		<Col sm="12">
			<Transactions />
		</Col>
	</Row>
</Container>

// Vue-Inertia/Seed/resources/js/pages/dashboard/index.vue
<template>
  <MainLayout>
       <Head title="Dashboard" />
    <BContainer fluid>
      <PageBreadcrumb title="Dashboard" />

      <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1">
        <BCol v-for="(item, idx) in statistics" :key="idx">
          <StatisticWidget :item="item" />
        </BCol>
      </BRow>

      <BRow>
        <BCol cols="12">
          <OrderStatistics />
        </BCol>
      </BRow>

      <BRow>
        <BCol xxl="6">
          <ProductInventory />
        </BCol>
        <BCol xxl="6">
          <RecentOrders />
        </BCol>
      </BRow>

      <BRow>
        <BCol cols="12">
          <Transactions />
        </BCol>
      </BRow>
    </BContainer>
  </MainLayout>
</template>

<script setup lang="ts">
import MainLayout from '@/layouts/MainLayout.vue'
import PageBreadcrumb from '@/components/PageBreadcrumb.vue'
import StatisticWidget from '@/pages/dashboard/components/StatisticWidget.vue'
import OrderStatistics from '@/pages/dashboard/components/OrderStatistics.vue'
import ProductInventory from '@/pages/dashboard/components/ProductInventory.vue'
import RecentOrders from '@/pages/dashboard/components/RecentOrders.vue'
import Transactions from '@/pages/dashboard/components/Transactions.vue'
import { statistics } from '@/pages/dashboard/components/data'
import { Head } from '@inertiajs/vue3'

</script>
