// Angular/Full/src/app/views/forms/layouts/layouts.component.ts
import {Component, inject, TemplateRef} from '@angular/core';
import { PageTitleComponent } from "@app/components/page-title.component";
import {LucideAngularModule, LucideShieldUser, ShieldUser} from 'lucide-angular';
import {UiCardComponent} from '@app/components/ui-card.component';
import {NgbModal} from '@ng-bootstrap/ng-bootstrap';
import {RouterLink} from '@angular/router';

@Component({
    selector: 'app-layouts',
    imports: [PageTitleComponent, LucideAngularModule, UiCardComponent, RouterLink],
    templateUrl: './layouts.component.html',
    styles: ``
})
export class LayoutsComponent {
    ShieldUser = ShieldUser
    private modalService = inject(NgbModal)

    open(content: TemplateRef<any>) {
        this.modalService.open(content, { size: 'lg' })
    }

    protected readonly LucideShieldUser = LucideShieldUser;
}

<div class="container-fluid">
    <app-page-title title="Layouts" subTitle="Forms"/>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <app-ui-card title="Basic Form">
                <div class="row g-4 align-items-center p-3" card-body>
                    <div class="col-sm-6 border-end border-dashed">
                        <div class="p-4">
                            <h4 class="mb-1 fw-bold text-uppercase">Sign in</h4>
                            <p class="text-muted mb-4">Let’s get you signed in. Enter your email and password to
                                continue.</p>

                            <form>
                                <div class="mb-3">
                                    <label for="userEmail" class="form-label">Email address <span
                                        class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <input type="email" class="form-control" id="userEmail"
                                               placeholder="you@example.com" required>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label for="userPassword" class="form-label">Password <span
                                        class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <input type="password" class="form-control" id="userPassword"
                                               placeholder="••••••••" required>
                                    </div>
                                </div>

                                <div class="d-flex flex-wrap justify-content-between">
                                    <div class="form-check fs-sm">
                                        <input class="form-check-input form-check-input-light" type="checkbox"
                                               id="rememberMe1">
                                        <label class="form-check-label fw-semibold fst-italic text-muted fs-base"
                                               for="rememberMe1">Keep me signed in</label>
                                    </div>

                                    <button class="btn btn-primary rounded-pill" type="submit"><strong>Log
                                        in</strong></button>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="col-sm-6 text-center">
                        <div class="avatar avatar-xl mx-auto">
                                <span class="avatar-title bg-purple-subtle text-purple rounded-circle fw-bold">
                                    <lucide-angular [img]="ShieldUser" class="text-purple fs-28 fill-purple"/>
                                </span>
                        </div>
                        <h4 class="mt-3">Don't Have an Account Yet?</h4>
                        <p class="text-muted mb-3">Join us today and unlock access to personalized features,
                            updates, and more!</p>
                        <a href="auth-sign-up.html"
                           class="link-primary text-decoration-underline fw-semibold link-offset-3">Create Your
                            Account</a>
                    </div>
                </div>
            </app-ui-card>

            <app-ui-card title="Modal Form">
                <div card-body>
                    <div class="text-center">
                        <button class="btn btn-primary" (click)="open(content)">Form in simple modal
                            box
                        </button>
                    </div>
                    <ng-template #content let-modal>

                        <div class="modal-body">
                            <div class="row g-4 align-items-center">
                                <div class="col-sm-6 border-end border-dashed">
                                    <div class="p-4">
                                        <h4 class="mb-1 fw-bold text-uppercase">Sign in</h4>
                                        <p class="text-muted mb-4">Let’s get you signed in. Enter your email and
                                            password to continue.</p>

                                        <form>
                                            <div class="mb-3">
                                                <label for="userEmail1" class="form-label">Email address <span
                                                    class="text-danger">*</span></label>
                                                <div class="input-group">
                                                    <input type="email" class="form-control" id="userEmail1"
                                                           placeholder="you@example.com" required>
                                                </div>
                                            </div>

                                            <div class="mb-3">
                                                <label for="userPassword1" class="form-label">Password <span
                                                    class="text-danger">*</span></label>
                                                <div class="input-group">
                                                    <input type="password" class="form-control"
                                                           id="userPassword1" placeholder="••••••••" required>
                                                </div>
                                            </div>

                                            <div class="d-flex flex-wrap justify-content-between">
                                                <div class="form-check fs-sm">
                                                    <input class="form-check-input form-check-input-light"
                                                           type="checkbox" id="rememberMe">
                                                    <label
                                                        class="form-check-label fw-semibold fst-italic text-muted fs-base"
                                                        for="rememberMe">Keep me signed in</label>
                                                </div>

                                                <button class="btn btn-primary rounded-pill"
                                                        type="submit"><strong>Log in</strong></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                                <div class="col-sm-6 text-center">
                                    <div class="avatar avatar-xl mx-auto">
                                                <span
                                                    class="avatar-title bg-purple-subtle text-purple rounded-circle fw-bold">
                                                    <lucide-angular [img]="LucideShieldUser"
                                                       class="text-purple fs-28 fill-purple"/>
                                                </span>
                                    </div>
                                    <h4 class="mt-3">Don't Have an Account Yet?</h4>
                                    <p class="text-muted mb-3">Join us today and unlock access to personalized
                                        features, updates, and more!</p>
                                    <a routerLink="/auth/sign-up"
                                       class="link-primary text-decoration-underline fw-semibold link-offset-3">Create
                                        Your Account</a>
                                </div>
                            </div>
                        </div>

                    </ng-template>
                </div>
            </app-ui-card>

            <app-ui-card title="Basic Example">
                <form card-body>
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1"
                               aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                            else.</small>
                    </div>
                    <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1"
                               placeholder="Password">
                    </div>
                    <div class=" mb-3">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="checkmeout0">
                            <label class="form-check-label" for="checkmeout0">Check me out !</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </app-ui-card>

            <app-ui-card title="Horizontal Form">
                <form class="form-horizontal p-3" card-body>
                    <div class="row mb-3">
                        <label for="inputEmail3" class="col-3 col-form-label">Email</label>
                        <div class="col-9">
                            <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="inputPassword3" class="col-3 col-form-label">Password</label>
                        <div class="col-9">
                            <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label for="inputPassword5" class="col-3 col-form-label">Re Password</label>
                        <div class="col-9">
                            <input type="password" class="form-control" id="inputPassword5"
                                   placeholder="Retype Password">
                        </div>
                    </div>
                    <div class="row mb-3 justify-content-end">
                        <div class="col-9">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="checkmeout">
                                <label class="form-check-label" for="checkmeout">Check me out !</label>
                            </div>
                        </div>
                    </div>
                    <div class="justify-content-end row">
                        <div class="col-9">
                            <button type="submit" class="btn btn-info">Sign in</button>
                        </div>
                    </div>
                </form>
            </app-ui-card>

            <app-ui-card title="Horizontal Form Label Sizing">
                <form  card-body>
                    <div class="mb-2 row">
                        <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control form-control-sm" id="colFormLabelSm"
                                   placeholder="col-form-label-sm">
                        </div>
                    </div>
                    <div class="mb-2 row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="colFormLabel" placeholder="col-form-label">
                        </div>
                    </div>
                    <div class="row">
                        <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg">Email</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control form-control-lg" id="colFormLabelLg"
                                   placeholder="col-form-label-lg">
                        </div>
                    </div>
                </form>
            </app-ui-card>

            <app-ui-card title="Inline Form">
                <div card-body>
                    <form class="row row-cols-lg-auto g-3 align-items-center">
                        <div class="col-12">
                            <label for="staticEmail2" class="visually-hidden">Email</label>
                            <input type="text" readonly class="form-control-plaintext" id="staticEmail2"
                                   value="email@example.com">
                        </div>
                        <div class="col-12">
                            <label for="inputPassword2" class="visually-hidden">Password</label>
                            <input type="password" class="form-control" id="inputPassword2" placeholder="Password">
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Confirm identity</button>
                        </div>
                    </form>

                    <h6 class="fs-base mt-3">Auto-sizing</h6>
                    <form>
                        <div class="row gy-2 gx-2 align-items-center">
                            <div class="col-auto">
                                <label class="visually-hidden" for="inlineFormInput">Name</label>
                                <input type="text" class="form-control mb-2" id="inlineFormInput"
                                       placeholder="Jane Doe">
                            </div>
                            <div class="col-auto">
                                <label class="visually-hidden" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2">
                                    <div class="input-group-text">&#64;</div>
                                    <input type="text" class="form-control" id="inlineFormInputGroup"
                                           placeholder="Username">
                                </div>
                            </div>
                            <div class="col-auto">
                                <div class="form-check mb-2">
                                    <input type="checkbox" class="form-check-input" id="autoSizingCheck">
                                    <label class="form-check-label" for="autoSizingCheck">Remember me</label>
                                </div>
                            </div>
                            <div class="col-auto">
                                <button type="submit" class="btn btn-primary mb-2">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </app-ui-card>

            <app-ui-card title="Form Row">
                <form  card-body>
                    <div class="row g-2">
                        <div class="mb-3 col-md-6">
                            <label for="inputEmail4" class="form-label">Email</label>
                            <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
                        </div>
                        <div class="mb-3 col-md-6">
                            <label for="inputPassword4" class="form-label">Password</label>
                            <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress" class="form-label">Address</label>
                        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
                    </div>

                    <div class="mb-3">
                        <label for="inputAddress2" class="form-label">Address 2</label>
                        <input type="text" class="form-control" id="inputAddress2"
                               placeholder="Apartment, studio, or floor">
                    </div>

                    <div class="row g-2">
                        <div class="mb-3 col-md-6">
                            <label for="inputCity" class="form-label">City</label>
                            <input type="text" class="form-control" id="inputCity">
                        </div>
                        <div class="mb-3 col-md-4">
                            <label for="inputState" class="form-label">State</label>
                            <select id="inputState" class="form-select">
                                <option>Choose</option>
                                <option>Option 1</option>
                                <option>Option 2</option>
                                <option>Option 3</option>
                            </select>
                        </div>
                        <div class="mb-3 col-md-2">
                            <label for="inputZip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="inputZip">
                        </div>
                    </div>

                    <div class="mb-2">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="customCheck11">
                            <label class="form-check-label" for="customCheck11">Check this custom checkbox</label>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Sign in</button>
                </form>
            </app-ui-card>

            <app-ui-card title="Floating Labels">
                <form action="#" card-body>
                    <div class="row g-3">
                        <!-- Username -->
                        <div class="col-lg-6">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="usernameInput"
                                       placeholder="Enter username">
                                <label for="usernameInput">Username</label>
                            </div>
                        </div>

                        <!-- Full Name -->
                        <div class="col-lg-6">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="fullnameInput"
                                       placeholder="Enter full name">
                                <label for="fullnameInput">Full Name</label>
                            </div>
                        </div>

                        <!-- Phone Number -->
                        <div class="col-lg-4">
                            <div class="form-floating">
                                <input type="tel" class="form-control" id="phoneInput"
                                       placeholder="Enter phone number">
                                <label for="phoneInput">Phone Number</label>
                            </div>
                        </div>

                        <!-- Date of Birth -->
                        <div class="col-lg-4">
                            <div class="form-floating">
                                <input type="date" class="form-control" id="dobInput">
                                <label for="dobInput">Date of Birth</label>
                            </div>
                        </div>

                        <!-- Gender -->
                        <div class="col-lg-4">
                            <div class="form-floating">
                                <select class="form-select" id="genderSelect" aria-label="Select gender">
                                    <option selected>Choose...</option>
                                    <option value="1">Male</option>
                                    <option value="2">Female</option>
                                    <option value="3">Other</option>
                                </select>
                                <label for="genderSelect">Gender</label>
                            </div>
                        </div>

                        <!-- Address -->
                        <div class="col-lg-8">
                            <div class="form-floating">
                                <input type="text" class="form-control" id="addressInput"
                                       placeholder="Enter your address">
                                <label for="addressInput">Street Address</label>
                            </div>
                        </div>

                        <!-- State -->
                        <div class="col-lg-4">
                            <div class="form-floating">
                                <select class="form-select" id="stateSelect" aria-label="Select state">
                                    <option selected>Choose...</option>
                                    <option value="1">California</option>
                                    <option value="2">Texas</option>
                                    <option value="3">Florida</option>
                                </select>
                                <label for="stateSelect">State</label>
                            </div>
                        </div>

                        <!-- Website -->
                        <div class="col-lg-6">
                            <div class="form-floating">
                                <input type="url" class="form-control" id="websiteInput"
                                       placeholder="Enter website URL">
                                <label for="websiteInput">Website (optional)</label>
                            </div>
                        </div>

                        <!-- Bio -->
                        <div class="col-lg-6">
                            <div class="form-floating">
                                    <textarea class="form-control" placeholder="Tell us about yourself" id="bioTextarea"
                                              style="height: 100px"></textarea>
                                <label for="bioTextarea">Short Bio</label>
                            </div>
                        </div>

                        <!-- Submit -->
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-success">Create Account</button>
                        </div>
                    </div>

                </form>
            </app-ui-card>
        </div>
    </div>

</div>

// React-Inertia/Full/resources/js/pages/forms/layouts/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import ComponentCard from '@/components/cards/ComponentCard'
import MainLayout from '@/layouts/MainLayout'
import { Link } from '@inertiajs/react'
import { useState } from 'react'
import {
  Button,
  Col,
  Container,
  FloatingLabel,
  Form,
  FormCheck,
  FormControl,
  FormGroup,
  FormLabel,
  FormSelect,
  FormText,
  InputGroup,
  Modal,
  ModalBody,
  Row,
} from 'react-bootstrap'
import InputGroupText from 'react-bootstrap/InputGroupText'
import { TbUserShield } from 'react-icons/tb'

const BasicForm = () => {
  return (
    <ComponentCard title="Basic Form">
      <Row className="g-4 align-items-center">
        <Col sm={6} className="border-end border-dashed">
          <div className="p-4">
            <h4 className="mb-1 fw-bold text-uppercase">Sign in</h4>
            <p className="text-muted mb-4">Let’s get you signed in. Enter your email and password to continue.</p>

            <Form>
              <div className="mb-3">
                <FormLabel htmlFor="userEmail">
                  Email address <span className="text-danger">*</span>
                </FormLabel>
                <div className="input-group">
                  <FormControl type="email" id="userEmail" placeholder="you@example.com" required />
                </div>
              </div>

              <div className="mb-3">
                <FormLabel htmlFor="userPassword">
                  Password <span className="text-danger">*</span>
                </FormLabel>
                <div className="input-group">
                  <FormControl type="password" id="userPassword" placeholder="••••••••" required />
                </div>
              </div>

              <div className="d-flex flex-wrap justify-content-between">
                <FormCheck type="checkbox" label="Keep me signed in" className="fw-semibold fst-italic text-muted fs-base" />

                <Button variant="primary" className="rounded-pill" type="submit">
                  <strong>Log in</strong>
                </Button>
              </div>
            </Form>
          </div>
        </Col>

        <Col sm={6} className="text-center">
          <div className="avatar avatar-xl mx-auto">
            <span className="avatar-title bg-purple-subtle text-purple rounded-circle fw-bold">
              <TbUserShield className="text-purple fs-28 fill-purple" />
            </span>
          </div>
          <h4 className="mt-3">Don't Have an Account Yet?</h4>
          <p className="text-muted mb-3">Join us today and unlock access to personalized features, updates, and more!</p>
          <Link href="/auth-1/sign-up" className="link-primary text-decoration-underline fw-semibold link-offset-3">
            Create Your Account
          </Link>
        </Col>
      </Row>
    </ComponentCard>
  )
}

const ModalForm = () => {
  const [show, setShow] = useState(false)

  const toggle = () => setShow(!show)

  return (
    <ComponentCard title="Modal Form">
      <div className="text-center">
        <Button variant="primary" onClick={toggle}>
          Form in simple modal box
        </Button>
      </div>
      <Modal show={show} onHide={toggle} size="lg">
        <ModalBody>
          <Row className="g-4 align-items-center">
            <Col sm={6} className="border-end border-dashed">
              <div className="p-4">
                <h4 className="mb-1 fw-bold text-uppercase">Sign in</h4>
                <p className="text-muted mb-4">Let’s get you signed in. Enter your email and password to continue.</p>
                <Form>
                  <div className="mb-3">
                    <FormLabel htmlFor="userEmail1">
                      Email address <span className="text-danger">*</span>
                    </FormLabel>
                    <div className="input-group">
                      <FormControl type="email" id="userEmail1" placeholder="you@example.com" required />
                    </div>
                  </div>

                  <div className="mb-3">
                    <FormLabel htmlFor="userPassword1">
                      Password <span className="text-danger">*</span>
                    </FormLabel>
                    <div className="input-group">
                      <FormControl type="password" id="userPassword1" placeholder="••••••••" required />
                    </div>
                  </div>

                  <div className="d-flex flex-wrap justify-content-between">
                    <FormCheck type="checkbox" label="Keep me signed in" className="fw-semibold fst-italic text-muted fs-base" />

                    <Button variant="primary" className="rounded-pill" type="submit">
                      <strong>Log in</strong>
                    </Button>
                  </div>
                </Form>
              </div>
            </Col>

            <Col sm={6} className="text-center">
              <div className="avatar avatar-xl mx-auto">
                <span className="avatar-title bg-purple-subtle text-purple rounded-circle fw-bold">
                  <TbUserShield className="text-purple fs-28 fill-purple" />
                </span>
              </div>
              <h4 className="mt-3">Don't Have an Account Yet?</h4>
              <p className="text-muted mb-3">Join us today and unlock access to personalized features, updates, and more!</p>
              <Link href="/auth-1/sign-up" className="link-primary text-decoration-underline fw-semibold link-offset-3">
                Create Your Account
              </Link>
            </Col>
          </Row>
        </ModalBody>
      </Modal>
    </ComponentCard>
  )
}

const BasicExample = () => {
  return (
    <ComponentCard title="Basic Example">
      <Form>
        <FormGroup className="mb-3">
          <FormLabel htmlFor="exampleInputEmail1">Email address</FormLabel>
          <FormControl type="email" placeholder="Enter email" id="exampleInputEmail1" />
          <FormText className=" text-muted">We'll never share your email with anyone else.</FormText>
        </FormGroup>
        <FormGroup className="mb-3">
          <FormLabel htmlFor="exampleInputPassword1">Password</FormLabel>
          <FormControl type="password" placeholder="Enter Password" id="exampleInputPassword1" />
        </FormGroup>
        <FormCheck type="checkbox" label="Check me out !" className="mb-3" />
        <Button variant="primary" type="submit">
          Submit
        </Button>
      </Form>
    </ComponentCard>
  )
}

const HorizontalForm = () => {
  return (
    <ComponentCard title="Horizontal Form">
      <Form className="form-horizontal">
        <FormGroup as={Row} className="mb-3">
          <FormLabel column sm={3}>
            Email
          </FormLabel>
          <Col sm={9}>
            <FormControl type="email" placeholder="Email" />
          </Col>
        </FormGroup>

        <FormGroup as={Row} className="mb-3">
          <FormLabel column sm={3}>
            Password
          </FormLabel>
          <Col sm={9}>
            <FormControl type="password" placeholder="Password" />
          </Col>
        </FormGroup>

        <FormGroup as={Row} className="mb-3">
          <FormLabel column sm={3}>
            Confirm Password
          </FormLabel>
          <Col sm={9}>
            <FormControl type="password" placeholder="Confirm Password" />
          </Col>
        </FormGroup>

        <FormGroup as={Row} className="mb-3">
          <Col sm={{ span: 9, offset: 3 }}>
            <FormCheck label="Check me out !" />
          </Col>
        </FormGroup>

        <FormGroup as={Row}>
          <Col sm={{ span: 9, offset: 3 }}>
            <Button variant="info" type="submit">
              Sign in
            </Button>
          </Col>
        </FormGroup>
      </Form>
    </ComponentCard>
  )
}

const HorizontalFormLabelSize = () => {
  return (
    <ComponentCard title="Horizontal Form Label Sizing">
      <Form>
        <Row className="mb-2">
          <FormLabel sm={2} column="sm">
            Email
          </FormLabel>
          <Col sm={10}>
            <FormControl size="sm" type="email" placeholder="col-form-label-sm" />
          </Col>
        </Row>
        <Row className="mb-2">
          <FormLabel sm={2} column>
            Email
          </FormLabel>
          <Col sm={10}>
            <FormControl type="email" placeholder="col-form-label" />
          </Col>
        </Row>
        <Row>
          <FormLabel sm={2} column="lg">
            Email
          </FormLabel>
          <Col sm={10}>
            <FormControl size="lg" type="email" placeholder="col-form-label-lg" />
          </Col>
        </Row>
      </Form>
    </ComponentCard>
  )
}

const InlineForm = () => {
  return (
    <ComponentCard title="Inline Form">
      <div>
        <Form>
          <Row className="row-cols-lg-auto g-3 align-items-center">
            <Col sm={12}>
              <FormLabel className="visually-hidden">Email</FormLabel>
              <FormControl plaintext type="text" readOnly value="email@example.com" />
            </Col>
            <Col sm={12}>
              <FormLabel htmlFor="inputPassword2" className="visually-hidden">
                Password
              </FormLabel>
              <FormControl type="password" id="inputPassword2" placeholder="Password" />
            </Col>
            <Col sm={12}>
              <Button variant="primary" type="submit">
                Confirm identity
              </Button>
            </Col>
          </Row>
        </Form>

        <h6 className="fs-base mt-3">Auto-sizing</h6>
        <Form>
          <Row className="gy-2 gx-2 align-items-center">
            <Col xs="auto">
              <FormLabel className="visually-hidden" htmlFor="inlineFormInput">
                Name
              </FormLabel>
              <FormControl type="text" className="mb-2" id="inlineFormInput" placeholder="Jane Doe" />
            </Col>
            <Col xs="auto">
              <FormLabel className="visually-hidden" htmlFor="inlineFormInputGroup">
                Username
              </FormLabel>
              <InputGroup className="mb-2">
                <InputGroupText>@</InputGroupText>
                <FormControl type="text" id="inlineFormInputGroup" placeholder="Username" />
              </InputGroup>
            </Col>
            <Col xs="auto">
              <FormCheck type="checkbox" className="mb-2" label="Remember me" />
            </Col>
            <Col xs="auto">
              <Button variant="primary" type="submit" className="mb-2">
                Submit
              </Button>
            </Col>
          </Row>
        </Form>
      </div>
    </ComponentCard>
  )
}

const FormRow = () => {
  return (
    <ComponentCard title="Form Row">
      <Form>
        <Row className="g-2">
          <FormGroup as={Col} md={6} className="mb-3">
            <FormLabel>Email address</FormLabel>
            <FormControl type="email" placeholder="Email" />
          </FormGroup>

          <FormGroup as={Col} md={6} className="mb-3">
            <FormLabel>Password</FormLabel>
            <FormControl type="password" placeholder="Password" />
          </FormGroup>
        </Row>

        <FormGroup className="mb-3">
          <FormLabel>Address</FormLabel>
          <FormControl type="text" placeholder="1234 Main St" />
        </FormGroup>

        <FormGroup className="mb-3">
          <FormLabel>Address 2</FormLabel>
          <FormControl type="text" placeholder="Apartment, studio, or floor" />
        </FormGroup>

        <Row className="g-2">
          <FormGroup as={Col} md={6} className="mb-3">
            <FormLabel>City</FormLabel>
            <FormControl type="text" placeholder="Password" />
          </FormGroup>

          <FormGroup as={Col} md={4} className="mb-3">
            <FormLabel>State</FormLabel>
            <FormSelect>
              <option>Choose</option>
              <option>Option 1</option>
              <option>Option 2</option>
              <option>Option 3</option>
            </FormSelect>
          </FormGroup>

          <FormGroup as={Col} md={2} className="mb-3">
            <FormLabel>Zip</FormLabel>
            <FormControl type="text" placeholder="Password" />
          </FormGroup>
        </Row>

        <FormGroup className="mb-2">
          <FormCheck type="checkbox" label="Check this custom checkbox" />
        </FormGroup>

        <Button variant="primary" type="submit">
          Sign in
        </Button>
      </Form>
    </ComponentCard>
  )
}

const FloatingLabelForm = () => {
  return (
    <ComponentCard title="Floating Labels">
      <Form>
        <Row className="g-3">
          <Col lg={6}>
            <FloatingLabel label="Username">
              <FormControl type="text" placeholder="Enter username" />
            </FloatingLabel>
          </Col>

          <Col lg={6}>
            <FloatingLabel label="Full Name">
              <FormControl type="text" placeholder="Enter full name" />
            </FloatingLabel>
          </Col>

          <Col lg={4}>
            <FloatingLabel label="Phone Number">
              <FormControl type="tel" placeholder="Enter phone number" />
            </FloatingLabel>
          </Col>

          <Col lg={4}>
            <FloatingLabel label="Date of Birth">
              <FormControl type="date" />
            </FloatingLabel>
          </Col>

          <Col lg={4}>
            <FloatingLabel label="Gender">
              <FormSelect>
                <option>Choose...</option>
                <option value="1">Male</option>
                <option value="2">Female</option>
                <option value="3">Other</option>
              </FormSelect>
            </FloatingLabel>
          </Col>

          <Col lg={8}>
            <FloatingLabel label="Street Address">
              <FormControl type="text" placeholder="Enter your address" />
            </FloatingLabel>
          </Col>

          <Col lg={4}>
            <FloatingLabel label="State">
              <FormSelect>
                <option>Choose...</option>
                <option value="1">California</option>
                <option value="2">Texas</option>
                <option value="3">Florida</option>
              </FormSelect>
            </FloatingLabel>
          </Col>

          <Col lg={6}>
            <FloatingLabel label="Website (optional)">
              <FormControl type="url" placeholder="Enter website URL" />
            </FloatingLabel>
          </Col>

          <Col lg={6}>
            <FloatingLabel label="Short Bio">
              <FormControl as="textarea" placeholder="Tell us about yourself" style={{ height: '100px' }} />
            </FloatingLabel>
          </Col>

          <Col lg={12}>
            <Button variant="success" type="submit">
              Create Account
            </Button>
          </Col>
        </Row>
      </Form>
    </ComponentCard>
  )
}

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="Layouts" subtitle="Forms" />
      </Container>

      <Container>
        <Row>
          <Col lg={12}>
            <BasicForm />

            <ModalForm />

            <BasicExample />

            <HorizontalForm />

            <HorizontalFormLabelSize />

            <InlineForm />

            <FormRow />

            <FloatingLabelForm />
          </Col>
        </Row>
      </Container>
    </MainLayout>
  )
}

export default Page
