// React-Inertia/Full/resources/js/pages/pages/empty-page/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import MainLayout from '@/layouts/MainLayout'
import { Container } from 'react-bootstrap'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Starter" subtitle="Pages" />
            </Container>
        </MainLayout>
    )
}

export default Page

// Full/src/views/pages/empty-page/index.vue
<template>
    <MainLayout>
        <PageBreadcrumb title="Empty Page" />
    </MainLayout>
</template>

<script setup lang="ts">
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { usePageMeta } from '@/composables/usePageMeta';
import MainLayout from '@/layouts/MainLayout.vue';

usePageMeta('Starter Page')
</script>

<style scoped></style>
