// Nuxt/Full/pages/widgets/components/Widget2.vue
<template>
    <BCard no-body class="rounded-0 border shadow-none border-dashed mb-0"
        :class="item.variant ? `bg-opacity-10 bg-${item.variant} border-${item.variant}` : ''">
        <BCardBody>
            <div class="mb-3 d-flex justify-content-between align-items-center">
                <h5 class="fs-xl mb-0">
                    <span v-if="item.count.prefix">{{ item.count.prefix }}</span>
                    {{ item.count.value }}
                    <small v-if="item.count.suffix" class="fs-6">{{ item.count.suffix }}</small>
                </h5>

                <span>
                    {{ item.percentage }}%
                    <Icon v-if="item.percentageIcon" :name="item.percentageIcon"
                        :class="item.isPositive ? 'text-success' : 'text-danger'" />
                </span>
            </div>

            <p class="text-muted mb-2">
                <span>{{ item.title }}</span>
            </p>

            <BProgress :value="item.percentage" class="progress-sm mb-0" :bg-variant="item.variant || 'primary'" />
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard } from 'bootstrap-vue-next';
import type { Widget2Type } from './types';


defineProps<{
    item: Widget2Type
}>()
</script>

// React-Inertia/Full/resources/js/pages/widgets/components/Widget2.tsx
import clsx from 'clsx'
import { ProgressBar } from 'react-bootstrap'
import type { Widget2Type } from '@/pages/widgets/types'

const Widget2 = ({ item }: { item: Widget2Type }) => {
  const { count, variant, isPositive, percentage, percentageIcon: Icon, title } = item
  return (
    <div
      className={clsx(
        'card rounded-0 border shadow-none border-dashed mb-0',
        item.variant ? `bg-opacity-10 bg-${item.variant} border-${item.variant}` : '',
      )}>
      <div className="card-body">
        <div className="mb-3 d-flex justify-content-between align-items-center">
          <h5 className="fs-xl mb-0">
            {count.prefix || ''}
            {count.value}
            {count.suffix && <small className="fs-6">{count.suffix}</small>}
          </h5>
          <span>
            {percentage}%{Icon && <Icon className={isPositive ? 'text-success' : 'text-danger'} />}
          </span>
        </div>
        <p className="text-muted mb-2">
          <span>{title}</span>
        </p>
        <ProgressBar now={percentage} className="progress-sm mb-0" variant={variant ? variant : 'primary'} />
      </div>
    </div>
  )
}

export default Widget2
