// src/views/widgets/components/Widget5.vue
<template>
    <BCard no-body>
        <BCardBody>
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <h3 class="mb-1">
                        <CountUp :end-val="item.count.value"
                            :options="{ prefix: item.count.prefix, suffix: item.count.suffix, scrollSpyOnce: true, enableScrollSpy: true, duration: 1 }" />
                    </h3>
                    <p class="mb-0 text-muted">{{ item.title }}</p>
                </div>

                <div class="avatar fs-60 avatar-img-size flex-shrink-0">
                    <span
                        :class="`avatar-title bg-${item.variant}-subtle text-${item.variant} rounded-circle fs-32 d-flex`">
                        <Icon v-if="item.icon" :icon="item.icon" class="d-flex" />
                    </span>
                </div>
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody } from 'bootstrap-vue-next'
import CountUp from 'vue-countup-v3'
import type { Widget5Type } from './types';
import { Icon } from '@iconify/vue';


defineProps<{ item: Widget5Type }>()
</script>

// React-Inertia/Full/resources/js/pages/widgets/components/Widget5.tsx
import type { Widget5Type } from '@/pages/widgets/types'
import CountUp from 'react-countup'

const Widget5 = ({ item }: { item: Widget5Type }) => {
  const { count, variant, title, icon: Icon } = item
  return (
    <div className="card">
      <div className="card-body">
        <div className="d-flex justify-content-between align-items-center">
          <div>
            <h3 className="mb-1">
              <CountUp prefix={count.prefix} suffix={count.suffix} end={count.value} duration={1} enableScrollSpy scrollSpyOnce />
            </h3>
            <p className="mb-0 text-muted">{title}</p>
          </div>
          <div className="avatar fs-60 avatar-img-size flex-shrink-0">
            <span className={`avatar-title bg-${variant}-subtle text-${variant} rounded-circle fs-32 d-flex`}>
              <Icon className="d-flex" />
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Widget5
