// Nuxt/Full/pages/widgets/components/Widget4.vue
<template>
    <BCard no-body>
        <BCardHeader class="d-flex border-dashed justify-content-between align-items-center">
            <BCardTitle tag="h5" >{{ item.title }}</BCardTitle>
            <span :class="`badge badge-soft-${item.variant}`">{{ item.label }}</span>
        </BCardHeader>

        <BCardBody>
            <div class="d-flex justify-content-between align-items-center">
                <div class="avatar fs-60 avatar-img-size flex-shrink-0">
                    <span class="avatar-title text-bg-dark rounded-circle fs-32 d-flex">
                        <Icon  v-if="item.icon" :name="item.icon" class="d-flex" />
                    </span>
                </div>

                <div class="text-end">
                    <h3 class="mb-2 fw-normal">
                        <CountUp :end-val="item.count.value"
                            :options="{ prefix: item.count.prefix ?? '', suffix: item.count.suffix ?? '', scrollSpyOnce: true, enableScrollSpy: true, duration: 1 }" />
                    </h3>
                    <p class="mb-0 text-muted">{{ item.description }}</p>
                </div>
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import CountUp from 'vue-countup-v3'
import type { Widget4Type } from './types';
import { BCard, BCardBody, BCardHeader } from 'bootstrap-vue-next';


defineProps<{ item: Widget4Type }>()
</script>

// React-Inertia/Full/resources/js/pages/widgets/components/Widget4.tsx
import type { Widget4Type } from '@/pages/widgets/types'
import CountUp from 'react-countup'

const Widget4 = ({ item }: { item: Widget4Type }) => {
  const { count, label, description, variant, title, icon: Icon } = item
  return (
    <div className="card">
      <div className="card-header d-flex border-dashed justify-content-between align-items-center">
        <h5 className="card-title">{title}</h5>
        <span className={`badge badge-soft-${variant}`}>{label}</span>
      </div>
      <div className="card-body">
        <div className="d-flex justify-content-between align-items-center">
          <div className="avatar fs-60 avatar-img-size flex-shrink-0">
            <span className="avatar-title text-bg-dark rounded-circle fs-32 d-flex">
              <Icon className="d-flex" />
            </span>
          </div>
          <div className="text-end">
            <h3 className="mb-2 fw-normal">
              <CountUp end={count.value} prefix={count.prefix} suffix={count.suffix} duration={1} enableScrollSpy scrollSpyOnce />
            </h3>
            <p className="mb-0 text-muted">{description}</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Widget4
