// Angular/Full/src/app/views/landing/components/blogs/blogs.component.ts
import {Component} from '@angular/core';
import type {BlogType} from '../types';
import {BlogCardComponent} from "../blog-card/blog-card.component";

@Component({
    selector: 'app-blogs',
    imports: [BlogCardComponent],
    templateUrl: './blogs.component.html',
    styles: ``
})
export class BlogsComponent {
    blogs: BlogType[] = [
        {
            category: 'Technology',
            image: 'assets/images/blog/blog-4.jpg',
            title: 'The Future of Artificial Intelligence',
            description: 'Discover how AI is transforming industries and what the future holds for this cutting-edge technology.',
            date: 'Jan 12, 2025',
            comments: 89,
            views: 1284,
            author: {
                name: 'Michael Turner',
                image: 'assets/images/users/user-4.jpg',
            },
            url: '/article',
        },
        {
            category: 'Data Science',
            image: 'assets/images/blog/blog-5.jpg',
            title: 'Top Data Science Trends in 2025',
            description: 'Get ahead in the data science field with the latest trends, technologies, and tools that are reshaping the industry.',
            date: 'Jan 12, 2025',
            comments: 89,
            views: 1284,
            author: {
                name: 'Olivia Brown',
                image: 'assets/images/users/user-1.jpg',
            },
            url: '/article',

        },
        {
            category: 'Business',
            image: 'assets/images/blog/blog-3.jpg',
            title: '5 Key Tips for New Entrepreneurs',
            description: 'Start your entrepreneurial journey with these 5 essential tips that will guide you through the first year of business.',
            date: 'Jan 12, 2025',
            comments: 89,
            views: 1284,
            author: {
                name: 'David Clark',
                image: 'assets/images/users/user-7.jpg',
            },
            url: '/article',
        },
    ];
}

<section class="section-custom bg-light bg-opacity-30 border-top border-bottom border-light" id="blog">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <span class="text-muted rounded-3 d-inline-block">📝 Insights & Resources</span>
                <h2 class="mt-3 fw-bold mb-5">Explore Our
                    <mark class="fst-italic">Latest</mark>
                    Articles and Updates
                </h2>
            </div>
        </div>

        <div class="row g-4">
            @for (blog of blogs; track $index) {
                <div class="col-lg-4">
                    <app-blog-card [blog]="blog"/>
                </div>
            }
        </div>
    </div>
</section>

// React-Inertia/Full/resources/js/pages/landing/components/Blogs.tsx
import type { BlogType } from './types'
import { Col, Container, Row } from 'react-bootstrap'
import BlogCard from './BlogCard'

import blog4 from '@/images/blog/blog-4.jpg'
import blog5 from '@/images/blog/blog-5.jpg'
import blog3 from '@/images/blog/blog-3.jpg'

import user4 from '@/images/users/user-4.jpg'
import user1 from '@/images/users/user-1.jpg'
import user7 from '@/images/users/user-7.jpg'

const Blogs = () => {
  const blogs: BlogType[] = [
    {
      category: 'Technology',
      image: blog4,
      title: 'The Future of Artificial Intelligence',
      description: 'Discover how AI is transforming industries and what the future holds for this cutting-edge technology.',
      date: 'Jan 12, 2025',
      comments: 89,
      views: 1284,
      author: {
        name: 'Michael Turner',
        image: user4,
      },
      url: '/article',
    },
    {
      category: 'Data Science',
      image: blog5,
      title: 'Top Data Science Trends in 2025',
      description: 'Get ahead in the data science field with the latest trends, technologies, and tools that are reshaping the industry.',
      date: 'Jan 12, 2025',
      comments: 89,
      views: 1284,
      author: {
        name: 'Olivia Brown',
        image: user1,
      },
      url: '/article',
    },
    {
      category: 'Business',
      image: blog3,
      title: '5 Key Tips for New Entrepreneurs',
      description: 'Start your entrepreneurial journey with these 5 essential tips that will guide you through the first year of business.',
      date: 'Jan 12, 2025',
      comments: 89,
      views: 1284,
      author: {
        name: 'David Clark',
        image: user7,
      },
      url: '/article',
    },
  ]
  return (
    <section className="section-custom bg-light bg-opacity-30 border-top border-bottom border-light" id="blog">
      <Container>
        <Row>
          <Col xs={12} className="text-center">
            <span className="text-muted rounded-3 d-inline-block">📝 Insights & Resources</span>
            <h2 className="mt-3 fw-bold mb-5">
              Explore Our <mark className="fst-italic">Latest</mark> Articles and Updates
            </h2>
          </Col>
        </Row>

        <Row className="g-4">
          {blogs.map((blog, index) => (
            <Col lg={4} key={index}>
              <BlogCard blog={blog} />
            </Col>
          ))}
        </Row>
      </Container>
    </section>
  )
}

export default Blogs
