// Vue/Seed/src/views/layouts/sidebars/gradient/index.vue
<template>
  <MainLayout>
    <BContainer fluid>
      <PageBreadcrumb title="Gradient Sidebar" />

      <BRow>
        <BCol cols="12">
          <BAlert
            show
            variant="info"
            class="alert-bordered border-start border-info"
            body-class="d-flex align-items-center gap-2"
          >
            <Icon icon="tabler:info-circle" class="fs-xxl" />
            <div>
              To switch to a gradient sidebar, add
              <code>data-menu-color="gradient"</code> to the <code>&lt;html&gt;</code> tag. To apply
              this dynamically, use <code>setSideNavColor('gradient')</code> from the
              <code>useLayout</code>.
            </div>
          </BAlert>
        </BCol>
      </BRow>
    </BContainer>
  </MainLayout>
</template>

<script setup lang="ts">
import MainLayout from '@/layouts/MainLayout.vue'
import PageBreadcrumb from '@/components/PageBreadcrumb.vue'
import { Icon } from '@iconify/vue'
import { onBeforeUnmount, onMounted } from 'vue'
import { useLayout } from '@/stores/layout'
import { usePageMeta } from '@/composables/usePageMeta.ts'

const { setSideNavColor, reset } = useLayout()

usePageMeta('Gradient Sidebar')

onMounted(() => {
  setSideNavColor('gradient')
})

onBeforeUnmount(() => {
  reset()
})
</script>

// SvelteKit/Seed/src/routes/layouts/sidebars/gradient/+page.svelte
<script lang="ts">
	import { Alert, Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageBreadcrumb from '$lib/components/PageBreadcrumb.svelte';
	import Icon from '@iconify/svelte';
	import { onMount } from 'svelte';
	import { reset, setSideNavColor } from '$lib/stores/layout';

	onMount(() => {
		setSideNavColor('gradient');

		return () => reset();
	});
</script>

<Container fluid>
	<PageBreadcrumb title="Gradient Sidebar" />

	<Row>
		<Col sm="12">
			<Alert color="info" class="alert-bordered border-start border-info">
				<div class="d-flex align-items-center gap-2">
					<Icon icon="tabler:info-circle" class="fs-xxl" />
					<div>
						To switch to a gradient sidebar, add
						<code>data-menu-color="gradient"</code> to the
						<code>&lt;html&gt;</code> tag. To apply this dynamically, use
						<code>setSideNavColor('gradient')</code> from the <code>layout</code> store.
					</div>
				</div>
			</Alert>
		</Col>
	</Row>
</Container>
