// React-Inertia/Full/resources/js/pages/error/404/index.tsx
import AppLogo from '@/components/AppLogo'
import { author, currentYear } from '@/helpers'

import { Head, Link } from '@inertiajs/react';
import { Col, Container, Row } from 'react-bootstrap'

import error404 from '@/images/svg/404.svg'

const Page = () => {
  return (
    <div className="auth-box overflow-hidden align-items-center d-flex">
      <Head title="Error 404" />
      <Container>
        <Row className="justify-content-center">
          <Col xxl={4} md={6} sm={8}>
            <div className="auth-brand text-center mb-3">
              <AppLogo />
            </div>

            <div className="p-2 text-center">
              <img src={error404} alt="404" className="img-fluid" />
              <h3 className="fw-bold text-uppercase">Page Not Found</h3>
              <p className="text-muted">The page you’re looking for doesn’t exist or has been moved.</p>

              <Link href="/" className="btn btn-primary mt-3 rounded-pill">
                Go Home
              </Link>
            </div>

            <p className="text-center text-muted mt-5 mb-0">
              © 2014 - {currentYear} INSPINIA — by <span className="fw-bold">{author}</span>
            </p>
          </Col>
        </Row>
      </Container>
    </div>
  )
}

export default Page

// Vue-Inertia/Full/resources/js/pages/error/404/index.vue
<template>

    <Head title="404 Error" />
    <div class="auth-box overflow-hidden align-items-center d-flex">
        <BContainer>
            <BRow class="justify-content-center">
                <BCol cols="12" sm="8" md="6" xxl="4">
                    <div class="auth-brand text-center mb-3">
                        <AuthLogo />
                    </div>

                    <div class="p-2 text-center">
                        <img :src="img404" alt="404" class="img-fluid" />
                        <h3 class="fw-bold text-uppercase">Page Not Found</h3>
                        <p class="text-muted">The page you’re looking for doesn’t exist or has been moved.</p>

                        <Link href="/" class="btn btn-primary mt-3 rounded-pill"> Go Home</Link>
                    </div>

                    <p class="text-center text-muted mt-5 mb-0">
                        © 2014 - {{ currentYear }} INSPINIA — by <span class="fw-bold">{{ author }}</span>
                    </p>
                </BCol>
            </BRow>
        </BContainer>
    </div>
</template>

<script setup lang="ts">
import { author, currentYear } from '@/helpers'
import AuthLogo from '@/components/AuthLogo.vue'


import img404 from '@/images/svg/404.svg'
import { Head, Link } from '@inertiajs/vue3'

</script>
