// Vue-Inertia/Full/resources/js/pages/miscellaneous/idle-timer/index.vue
<template>
    <MainLayout>
         
        <BContainer fluid>
            <PageBreadcrumb title="Idle Timer" subtitle="Miscellaneous" />

            <BRow class="justify-content-center">
                <BCol xxl="10">
                    <BCard no-body>
                        <BCardHeader>
                            <h5 class="mb-0">Idle Timer</h5>
                        </BCardHeader>
                        <BCardBody>

                            <Vidle :duration="inactiveDuration" @idle="handleIdle" @refresh="handleActive" />


                            <div v-if="state === 'Inactive'" class="alert alert-danger">
                                Your session has expired. Please move your mouse to resume your activity.
                            </div>

                            <p class="text-muted">
                                The Idle Timer plugin allows you to monitor user activity on the page. Idle is defined
                                as a
                                lack of mouse movement, scrolling, or keyboard input.
                            </p>

                            <div class="text-center p-3 h-200">
                                <Icon icon="tabler:hand-finger" class="fs-36 mb-3 d-block mx-auto" />
                                <h3 class="fst-italic">Please stay idle for {{ inactiveDuration }} seconds</h3>
                            </div>

                            <p class="mb-0">
                                You can instantiate the timer either statically or on a specific element. Element-bound
                                timers will only track activity within that element,
                                whereas global timers will monitor activity on the entire page.
                            </p>
                        </BCardBody>
                    </BCard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">

import MainLayout from '@/layouts/MainLayout.vue'
import { Icon } from '@iconify/vue'
import { ref } from 'vue'
import { toast } from 'vue3-toastify'
import Vidle from 'v-idle'
import 'vue3-toastify/dist/index.css'
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';

const inactiveDuration = 5

const state = ref<'Active' | 'Inactive'>('Active')

const handleIdle = () => {
    state.value = 'Inactive'
    toast.warning("You've been inactive for too long. Please interact with the page to continue.", {
        position: 'top-right',
        autoClose: 2000,
    })
}

const handleActive = () => {
    if (state.value === 'Inactive') {
        toast.success('We missed you! Welcome back!', {
            position: 'top-right',
            autoClose: 2000,
        })
        state.value = 'Active'
    }
}


</script>

// Angular/Full/src/app/views/miscellaneous/idle-timer/idle-timer.component.ts
import {Component, inject, type OnInit} from '@angular/core';
import {IdleDetectorService} from '@core/services/idle-detector.service';
import {PageTitleComponent} from "@app/components/page-title.component";
import {NgIcon} from '@ng-icons/core';
import {NgbAlertModule, NgbToastModule} from '@ng-bootstrap/ng-bootstrap';

@Component({
    selector: 'app-idle-timer',
    imports: [PageTitleComponent, NgIcon, NgbToastModule,NgbAlertModule],
    templateUrl: './idle-timer.component.html',
    styles: ``
})
export class IdleTimerComponent implements OnInit{
    toasts: any[] = [];
    showAlert = false;
    private idleService = inject(IdleDetectorService);

    ngOnInit(): void {
        this.idleService.startMonitoring();

        this.idleService.onIdle.subscribe(() => {
            this.showAlert = true;
            this.showToast('You\'ve been inactive for too long. Please interact with the page to continue.', 'Idle Alert', 'text-bg-warning border-warning', 3000);
        });

        this.idleService.onResume.subscribe(() => {
            this.showAlert = false;
            this.showToast('We missed you! Welcome back!', ' Welcome back!', 'text-bg-success border-success', 3000);
        });
    }

    showToast(text: string, header: string, classname: string, delay: number) {
        this.toasts.push({ text, header, classname, delay });
    }

    remove(toast: any) {
        this.toasts = this.toasts.filter(t => t !== toast);
    }
}

<div class="container-fluid">
    <app-page-title subTitle="Idle Timer" title="Miscellaneous"/>

    <div class="row justify-content-center">
        <div class="col-xxl-10">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Idle Timer Plugin</h4>
                </div>
                <div class="card-body">
                    @if (showAlert) {
                        <ngb-alert type="danger" [dismissible]="false" class="alert alert-danger"
                                   role="alert">
                            Your session has expired. Please move your mouse to resume your activity.
                        </ngb-alert>
                    }

                    <p class="text-muted">
                        The Idle Timer plugin allows you to monitor user activity on the page. Idle is defined as a lack of mouse movement, scrolling, or keyboard input.
                    </p>

                    <div class="text-center p-3 h-200">
                        <ng-icon name="tablerHandFinger" class="fs-36 mb-3 d-block mx-auto"></ng-icon>
                        <h3 class="fst-italic">Please stay idle for 5 seconds</h3>
                    </div>

                    <p class="mb-0">
                        You can instantiate the timer either statically or on a specific element. Element-bound timers
                        will only track activity within that element, whereas global timers will monitor activity on the
                        entire page.
                    </p>

                    <div class="toast-container position-fixed top-0 end-0 m-3 z-5" >
                        @for (toast of toasts; track $index) {
                            <ngb-toast [class]="toast.classname"
                                       [autohide]="true" [delay]="toast.delay" (hidden)="remove(toast)"
                                     >

                                <div ngbToastHeader>
                                    <strong class="me-auto">{{ toast.header }}</strong>
                                    <div class="d-flex align-items-center gap-2 float-end">
                                        <small>Now</small>
                                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="toast"
                                                (click)="remove(toast)"></button>
                                    </div>
                                </div>

                                <div class="toast-body fst-italic">
                                    {{ toast.text }}
                                </div>
                            </ngb-toast>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
