// React/Full/TS/src/views/graphs/apex/treemap/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart.tsx'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicTreemapChart, getColorRangeTreemapChart, getDistributedTreemapChart, getTreemapMultipleChart } from './data'

const Page = () => {
  return (
    <Container fluid>
      <PageBreadcrumb title="Treemap Apexchart" subtitle="Charts" />
      <Row>
        <Col xl={6}>
          <ComponentCard title="Basic Treemap">
            <CustomApexChart getOptions={getBasicTreemapChart} series={getBasicTreemapChart().series} type="treemap" height={350} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Treemap Multiple Series">
            <CustomApexChart getOptions={getTreemapMultipleChart} series={getTreemapMultipleChart().series} type="treemap" height={350} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Distributed Treemap">
            <CustomApexChart getOptions={getDistributedTreemapChart} series={getDistributedTreemapChart().series} type="treemap" height={350} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Color Range Treemaps">
            <CustomApexChart getOptions={getColorRangeTreemapChart} series={getColorRangeTreemapChart().series} type="treemap" height={350} />
          </ComponentCard>
        </Col>
      </Row>
    </Container>
  )
}

export default Page

// Nuxt/Full/pages/graphs/apex/treemap/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Treemap Apexchart" subtitle="Charts" />
        <BRow>
            <BCol xl='6'>
                <UICard title="Basic Treemap">
                        <CustomApexChart :get-options='getBasicTreemapChart' :series='getBasicTreemapChart().series'
                        type="treemap" :height='350' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Treemap Multiple Series">
                    <CustomApexChart :get-options='getTreemapMultipleChart' :series='getTreemapMultipleChart().series'
                        type="treemap" :height='350' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Distributed Treemap">
                    <CustomApexChart :get-options='getDistributedTreemapChart'
                        :series='getDistributedTreemapChart().series' type="treemap" :height='350' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Color Range Treemaps">
                    <CustomApexChart :get-options='getColorRangeTreemapChart' :series='getColorRangeTreemapChart().series'
                        type="treemap" :height='350' />
                </UICard>
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '~/components/CustomApexChart.vue';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import UICard from '~/components/UICard.vue';
import { getBasicTreemapChart, getColorRangeTreemapChart, getDistributedTreemapChart, getTreemapMultipleChart } from './data';

usePageTitle('Treemap ApexCharts')
</script>

<style scoped></style>
