// SvelteKit/Seed/src/routes/(admin)/dashboard/components/Transactions.svelte
<script lang="ts">
	import { derived, writable } from 'svelte/store';
	import { Col, Row } from '@sveltestrap/sveltestrap';
	import CustomJsVectorMap from '$lib/components/CustomJsVectorMap.svelte';
	import UICard from '$lib/components/UICard.svelte';
	import Icon from '@iconify/svelte';
	import { currency } from '$lib/helpers';
	import { toTitleCase } from '$lib/helpers/casing';
	import type { TransactionsType } from '../types';
	import { transactions as transactionsData, worldTransactionMapOptions } from '../data';

	const transactions = writable<TransactionsType[]>(transactionsData);
	const currentPage = writable(1);
	const perPage = writable(5);

	const paginatedTransactions = derived(
		[transactions, currentPage, perPage],
		([$transactions, $currentPage, $perPage]) => {
			const start = ($currentPage - 1) * $perPage;
			return $transactions.slice(start, start + $perPage);
		}
	);
</script>

<UICard title="Transactions Worldwide" bodyClass="pt-2" isCollapsable isReloadable isCloseable>
	<Row class="align-items-center">
		<Col xl="6">
			<table class="table table-custom table-nowrap table-hover table-centered mb-0">
				<thead class="bg-light align-middle bg-opacity-25 thead-sm">
					<tr class="text-uppercase fs-xxs">
						<th class="text-muted">Tran. No.</th>
						<th class="text-muted">Order</th>
						<th class="text-muted">Date</th>
						<th class="text-muted">Amount</th>
						<th class="text-muted">Status</th>
						<th class="text-muted">Payment Method</th>
					</tr>
				</thead>
				<tbody>
					{#each $paginatedTransactions as item (item.id)}
						<tr>
							<td><a href={null} class="link-reset fw-semibold">{item.id}</a></td>
							<td>{item.order}</td>
							<td>{item.date} <small class="text-muted">{item.time}</small></td>
							<td class="fw-semibold">{currency}{item.amount}</td>
							<td>
								<span class="badge badge-soft-{item.variant} fs-xxs">
									<Icon icon="tabler:circle-filled" />
									{toTitleCase(item.status)}
								</span>
							</td>
							<td>
								<img src={item.cardImage} alt="card" class="me-2" height="28" /> xxxx {item.lastFour}
							</td>
						</tr>
					{/each}
				</tbody>
			</table>

			<div class="text-center mt-3">
				<a href={null} class="link-reset text-decoration-underline fw-semibold link-offset-3">
					View All Transactions
					<Icon icon="tabler:send-2" />
				</a>
			</div>
		</Col>
		<Col xl="6">
			<CustomJsVectorMap
				id="world-map"
				options={worldTransactionMapOptions}
				className="w-100 mt-4 mt-xl-0"
				style="height: 297px"
			/>
		</Col>
	</Row>
</UICard>

// Seed/src/views/dashboard/components/Transactions.vue
<template>
  <UICard
    title="Transactions Worldwide"
    body-class="pt-2"
    is-collapsable
    is-reloadable
    is-closeable
  >
    <BRow class="align-items-center">
      <BCol xl="6">
        <BTable
          small
          hover
          :fields="fields"
          :items="transactions"
          :per-page="perPage"
          :current-page="currentPage"
          responsive
          thead-class="bg-light align-middle bg-opacity-25 thead-sm text-uppercase fs-xxs"
          class="table table-centered table-custom table-nowrap mb-0"
        >
          <template #cell(id)="data">
            <RouterLink to="#" class="link-reset fw-semibold">{{ data.item.id }}</RouterLink>
          </template>

          <template #cell(datetime)="data">
            {{ data.item.date }} <small class="text-muted">{{ data.item.time }}</small>
          </template>

          <template #cell(amount)="data">
            <span class="fw-semibold">{{ currency }}{{ data.item.amount }}</span>
          </template>

          <template #cell(statusvariant)="data">
            <span :class="`badge badge-soft-${data.item.variant} fs-xxs`">
              <Icon icon="tabler:circle-filled" /> {{ toTitleCase(data.item.status) }}
            </span>
          </template>

          <template #cell(cardImagepaymentMethodlastFour)="data">
            <img :src="data.item.cardImage" class="me-2" height="28" />
            xxxx {{ data.item.lastFour }}
          </template>
        </BTable>

        <div class="text-center mt-3">
          <RouterLink to="#" class="link-reset text-decoration-underline fw-semibold link-offset-3">
            View All Transactions
            <Icon icon="tabler:send-2" />
          </RouterLink>
        </div>
      </BCol>
      <BCol xl="6">
        <JsVectorMap
          id="world-map"
          :options="worldTransactionMapOptions"
          class="w-100 mt-4 mt-xl-0"
          :style="{ height: '297px' }"
        />
      </BCol>
    </BRow>
  </UICard>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { currency } from '@/helpers'
import { toTitleCase } from '@/helpers/casing'
import type { TransactionsType } from '@/views/dashboard/components/types'
import {
  transactions as transactionsData,
  worldTransactionMapOptions,
} from '@/views/dashboard/components/data'
import JsVectorMap from '@/components/JsVectorMap.vue'
import { ref } from 'vue'

const fields = [
  { key: 'id', label: 'Tran. No.', thClass: 'text-muted' },
  { key: 'order', label: 'Order', thClass: 'text-muted' },
  { key: 'datetime', label: 'Date', thClass: 'text-muted' },
  { key: 'amount', label: 'Amount', thClass: 'text-muted' },
  { key: 'statusvariant', label: 'Status', thClass: 'text-muted' },
  { key: 'cardImagepaymentMethodlastFour', label: 'Payment Method', thClass: 'text-muted' },
]

const currentPage = ref(1)
const perPage = ref(5)

const transactions = ref<TransactionsType[]>(transactionsData)
</script>
