// Angular/Full/src/app/views/ui/tooltips/tooltips.component.ts
import {Component} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {UiCardComponent} from '@app/components/ui-card.component';
import {NgIcon} from '@ng-icons/core';
import {NgbTooltipModule} from '@ng-bootstrap/ng-bootstrap';
import {toTitleCase} from '@/app/utils/string-utils';

@Component({
    selector: 'app-tooltips',
    imports: [
        PageTitleComponent,
        UiCardComponent,
        NgIcon,
        NgbTooltipModule,
    ],
    templateUrl: './tooltips.component.html',
    styles: ``
})
export class TooltipsComponent {
    tooltipVariants = ['primary', 'danger', 'info', 'success', 'secondary', 'warning', 'dark', 'purple']
    protected readonly toTitleCase = toTitleCase;
}

<div class="container-fluid">
    <app-page-title title="Tooltips" subTitle="UI"/>
</div>

<div class="container-xl">
    <div class="row">
        <div class="col-12">
            <app-ui-card title="Examples">
                <div card-body>
                    <p class="text-muted mb-2">
                        Documentation and examples for adding custom Bootstrap tooltips with CSS and JavaScript using
                        CSS3 for animations and data-bs-attributes for local title storage.
                    </p>

                    <a class="btn btn-link p-0 fw-semibold"
                       href="https://getbootstrap.com/docs/5.3/components/tooltips/" target="_blank">
                        Tooltips on Bootstrap
                        <ng-icon name="tablerChevronRight"/>
                    </a>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Basic">
                <div card-body>
                    <p class="text-muted">Hover over the links below to see tooltips.</p>

                    <p class="mb-0">
                        Powerful admin features like <a href="#" class="fw-medium"
                                                        ngbTooltip="Manage your dashboard easily">custom dashboards</a>
                        and UI components help you build scalable web applications efficiently.
                        This template includes pre-built pages, clean layouts, and reusable code blocks to boost your
                        development workflow.
                        From user management to analytics and settings, everything is modular and developer-friendly.
                        Create modern admin panels with <a href="#" class="fw-medium"
                                                           ngbTooltip="Built with Bootstrap 5">responsive design</a> and
                        seamless UX.
                        Get started quickly with a professional-grade <a href="#" class="fw-medium"
                                                                         ngbTooltip="Tailored for developers">UI
                        toolkit</a> and supercharge your app with <a href="#" class="fw-medium"
                                                                     ngbTooltip="Includes charts, tables, forms and more">powerful
                        components</a> and flexible layouts.
                    </p>

                </div>
            </app-ui-card>

            <app-ui-card title="Disabled Elements">
                <div card-body>
                    <p class="text-muted">Elements with the <code>disabled</code> attribute
                        aren’t interactive, meaning users cannot focus, hover, or click them to trigger
                        a tooltip (or popover). As a workaround, you’ll want to trigger the tooltip from
                        a wrapper <code>&lt;div&gt;</code> or <code>&lt;span&gt;</code>, ideally made
                        keyboard-focusable using <code>tabindex="0"</code>, and override the
                        <code>pointer-events</code> on the disabled element.
                    </p>

                    <span class="d-inline-block" tabindex="0" ngbTooltip="Disabled tooltip">
                                    <button class="btn btn-primary pe-none" type="button"
                                            disabled>Disabled Button</button>
                     </span>
                </div>
            </app-ui-card>

            <app-ui-card title="Hover Elements">
                <div card-body>
                    <p class="text-muted">Elements with the <code>disabled</code> attribute
                        aren’t interactive, meaning users cannot focus, hover, or click them to trigger
                        a tooltip (or popover). As a workaround, you’ll want to trigger the tooltip from
                        a wrapper <code>&lt;div&gt;</code> or <code>&lt;span&gt;</code>, ideally made
                        keyboard-focusable using <code>tabindex="0"</code>, and override the
                        <code>pointer-events</code> on the disabled element.
                    </p>

                    <button class="btn btn-primary" type="button" triggers="hover"
                            ngbTooltip="Tooltip appears on hover only">Hover to See Info
                    </button>
                </div>
            </app-ui-card>

        </div>

        <div class="col-xl-6">
            <app-ui-card title="Four Directions">
                <div card-body>
                    <p class="text-muted">Hover over the buttons below to see the four tooltips
                        directions: top, right, bottom, and left.</p>

                    <div class="d-flex flex-wrap gap-2">
                        <button type="button" class="btn btn-info" placement="top"
                                ngbTooltip="Tooltip on top">Tooltip on top
                        </button>
                        <button type="button" class="btn btn-info" placement="bottom"
                                ngbTooltip="Tooltip on bottom">Tooltip on bottom
                        </button>
                        <button type="button" class="btn btn-info" placement="left"
                                ngbTooltip="Tooltip on left">Tooltip on left
                        </button>
                        <button type="button" class="btn btn-info" placement="right"
                                ngbTooltip="Tooltip on right">Tooltip on right
                        </button>
                    </div>
                </div>
            </app-ui-card>

            <app-ui-card title="HTML Tags">
                <div card-body>
                    <p class="text-muted">And with custom HTML added:</p>

                    <button type="button" class="btn btn-secondary"
                            [ngbTooltip]="htmlTooltip">
                        Tooltip with HTML
                    </button>
                    <ng-template #htmlTooltip>
                        <em>New</em> <u>Tooltip</u> <b>with</b> <i>HTML</i><br>Custom message here!
                    </ng-template>
                </div>
            </app-ui-card>

            <app-ui-card title="Color Tooltips">
                <div card-body>
                    <p class="text-muted">We set a custom class with ex.
                        <code>data-bs-custom-class="primary-tooltip"</code> to scope our background-color
                        primary appearance and use
                        it to override a local CSS
                        variable.
                    </p>

                    <div class="d-flex flex-wrap gap-2">
                        @for (variant of tooltipVariants; track $index) {
                            <button type="button" class="btn btn-{{variant}}" placement="top"
                                    tooltipClass="tooltip-{{variant}}"
                                    ngbTooltip="This is a {{variant}} tooltip with a custom style.">
                                {{ toTitleCase(variant) }} tooltip
                            </button>
                        }
                    </div>
                </div>
            </app-ui-card>
        </div>
    </div>

</div>

// NextJs/NextJs/Full/JS/src/app/(admin)/ui/tooltips/page.jsx
import ComponentCard from '@/components/cards/ComponentCard';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Link from 'next/link';
import { Button, Card, CardBody, CardHeader, CardTitle, Col, Container, OverlayTrigger, Row, Tooltip } from 'react-bootstrap';
import { TbChevronRight } from 'react-icons/tb';
const colorVariants = ['primary', 'danger', 'info', 'success', 'secondary', 'warning', 'dark', 'purple'];
const BasicTooltips = () => {
  return <ComponentCard title="Basic">
      <p className="text-muted">Hover over the links below to see tooltips.</p>
      <p className="mb-0">
        Powerful admin features like
        <OverlayTrigger placement="top" overlay={<Tooltip className="danger-tooltip">Manage your dashboard easily</Tooltip>}>
          <a href="#" className="fw-medium" data-bs-title="Manage your dashboard easily">
            custom dashboards
          </a>
        </OverlayTrigger>
        &nbsp; and UI components help you build scalable web applications efficiently. This template includes pre-built pages, clean layouts, and
        reusable code blocks to boost your development workflow. From user management to analytics and settings, everything is modular and
        developer-friendly. Create modern admin panels with&nbsp;
        <OverlayTrigger placement="top" overlay={<Tooltip className="danger-tooltip">Built with Bootstrap 5</Tooltip>}>
          <a href="#" className="fw-medium" data-bs-title="Built with Bootstrap 5">
            responsive design
          </a>
        </OverlayTrigger>
        &nbsp; and seamless UX. Get started quickly with a professional-grade&nbsp;
        <OverlayTrigger placement="top" overlay={<Tooltip className="danger-tooltip">Tailored for developers</Tooltip>}>
          <a href="#" className="fw-medium" data-bs-title="Tailored for developers">
            UI toolkit
          </a>
        </OverlayTrigger>
        &nbsp; and supercharge your app with&nbsp;
        <OverlayTrigger placement="top" overlay={<Tooltip className="danger-tooltip">Includes charts, tables, forms and more</Tooltip>}>
          <a href="#" className="fw-medium" data-bs-title="Includes charts, tables, forms and more">
            powerful components
          </a>
        </OverlayTrigger>
        &nbsp; and flexible layouts.
      </p>
    </ComponentCard>;
};
const DisabledElements = () => {
  return <ComponentCard title="Disabled Elements">
      <p className="text-muted">
        Elements with the <code>disabled</code> attribute aren’t interactive, meaning users cannot focus, hover, or click them to trigger a tooltip
        (or popover). As a workaround, you’ll want to trigger the tooltip from a wrapper <code>&lt;div&gt;</code> or <code>&lt;span&gt;</code>,
        ideally made keyboard-focusable using <code>tabindex="0"</code>, and override the
        <code>pointer-events</code> on the disabled element.
      </p>
      <OverlayTrigger placement="top" overlay={<Tooltip>Disabled tooltip</Tooltip>}>
        <span className="d-inline-block" tabIndex={0} data-bs-title="Disabled tooltip">
          <Button variant="primary" className="pe-none" disabled>
            Disabled button
          </Button>
        </span>
      </OverlayTrigger>
    </ComponentCard>;
};
const HoverElements = () => {
  return <ComponentCard title="Hover Elements">
      <p className="text-muted">
        Elements with the <code>disabled</code> attribute aren’t interactive, meaning users cannot focus, hover, or click them to trigger a tooltip
        (or popover). As a workaround, you’ll want to trigger the tooltip from a wrapper <code>&lt;div&gt;</code> or <code>&lt;span&gt;</code>,
        ideally made keyboard-focusable using <code>tabindex="0"</code>, and override the
        <code>pointer-events</code> on the disabled element.
      </p>
      <OverlayTrigger placement="top" overlay={<Tooltip>Tooltip appears on hover only</Tooltip>}>
        <Button variant="primary" data-bs-trigger="hover">
          Hover to See Info
        </Button>
      </OverlayTrigger>
    </ComponentCard>;
};
const FourDirections = () => {
  return <ComponentCard title="Four Directions">
      <p className="text-muted">Hover over the buttons below to see the four tooltips directions: top, right, bottom, and left.</p>
      <div className="d-flex flex-wrap gap-2">
        <OverlayTrigger overlay={<Tooltip className="primary-tooltip">Tooltip on top</Tooltip>}>
          <Button variant="info" data-bs-placement="top">
            Tooltip ontop
          </Button>
        </OverlayTrigger>
        <OverlayTrigger placement="bottom" overlay={<Tooltip className="danger-tooltip">Tooltip on bottom</Tooltip>}>
          <Button variant="info" data-bs-placement="bottom">
            Tooltip on bottom
          </Button>
        </OverlayTrigger>
        <OverlayTrigger placement="left" overlay={<Tooltip className="danger-tooltip">Tooltip on left</Tooltip>}>
          <Button variant="info" data-bs-placement="left">
            Tooltip on left
          </Button>
        </OverlayTrigger>
        <OverlayTrigger placement="right" overlay={<Tooltip className="danger-tooltip">Tooltip on right</Tooltip>}>
          <Button variant="info" data-bs-placement="right" data-bs-title="Tooltip on right">
            Tooltip on right
          </Button>
        </OverlayTrigger>
      </div>
    </ComponentCard>;
};
const HTMLTags = () => {
  return <ComponentCard title="HTML Tags">
      <p className="text-muted">And with custom HTML added:</p>
      <OverlayTrigger placement="top" overlay={<Tooltip className="danger-tooltip">
            <em>New</em> <u>Tooltip</u> <b>with</b> <i>HTML</i> <br />
            Custom message here!
          </Tooltip>}>
        <Button variant="secondary" data-bs-toggle="tooltip" data-bs-html="true" data-bs-title="<em>New</em> <u>Tooltip</u> <b>with</b> <i>HTML</i> <br/>Custom message here!">
          Tooltip with HTML
        </Button>
      </OverlayTrigger>
    </ComponentCard>;
};
const ColorTooltips = () => {
  return <ComponentCard title="Color Tooltips">
      <p className="text-muted">
        We set a custom class with ex.
        <code>data-bs-custom-class="primary-tooltip"</code> to scope our background-color primary appearance and use it to override a local CSS
        variable.
      </p>
      <div className="d-flex flex-wrap gap-2">
        {colorVariants.map((color, idx) => {
        return <OverlayTrigger placement="top" key={idx} overlay={<Tooltip className={`tooltip-${color}`}>This top tooltip {color} is themed via CSS variables.</Tooltip>}>
              <Button variant={color}>{color} tooltip</Button>
            </OverlayTrigger>;
      })}
      </div>
    </ComponentCard>;
};
const page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="Tooltips" subtitle="UI" />
        <Container fluid="xl">
          <Row>
            <Col xs={12}>
              <Card>
                <CardHeader>
                  <CardTitle as={'h4'}>Examples</CardTitle>
                </CardHeader>
                <CardBody>
                  <p className="text-muted mb-2">
                    Documentation and examples for adding custom Bootstrap tooltips with CSS and JavaScript using CSS3 for animations and
                    data-bs-attributes for local title storage.
                  </p>
                  <Link className="btn btn-link p-0 fw-semibold" href="https://getbootstrap.com/docs/5.3/components/tooltips/" target="_blank">
                    Tooltips on Bootstrap
                    <TbChevronRight className="ms-1" />
                  </Link>
                </CardBody>
              </Card>
            </Col>
            <Col xl={6}>
              <BasicTooltips />
              <DisabledElements />
              <HoverElements />
            </Col>
            <Col xl={6}>
              <FourDirections />
              <HTMLTags />
              <ColorTooltips />
            </Col>
          </Row>
        </Container>
      </Container>
    </>;
};
export default page;
