// Vue-Inertia/Full/resources/js/pages/graphs/apex/radar/index.vue
<template>
    <MainLayout>
        
        <BContainer fluid>
            <PageBreadcrumb title="Radar Apexchart" subtitle="Charts" />

            <BRow>
                <BCol xl="6">
                    <UICard title="Basic Radar Chart">
                        <CustomApexChart :getOptions="getBasicRadarChart" :series="getBasicRadarChart().series"
                            type="radar" height="350" />
                    </UICard>
                </BCol>

                <BCol xl="6">
                    <UICard title="Radar with Polygon-fill">
                        <CustomApexChart :getOptions="getRadarPolygonChart" :series="getRadarPolygonChart().series"
                            type="radar" height="350" />
                    </UICard>
                </BCol>
            </BRow>

            <BRow>
                <BCol xl="6">
                    <UICard title="Radar – Multiple Series">
                        <CustomApexChart :getOptions="() => ({ ...getRadarMultiPleSeriesChart(), series: series })"
                            :series="series" type="radar" height="350" />
                        <div class="text-center mt-2">
                            <BButton size="sm" variant="primary" @click="handleUpdate">
                                Update
                            </BButton>
                        </div>
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { ref } from 'vue'

import {
    generateRandomSeries,
    getBasicRadarChart,
    getRadarMultiPleSeriesChart,
    getRadarPolygonChart,
} from './data'
import { BCol, BContainer, BRow } from 'bootstrap-vue-next'
import PageBreadcrumb from '@/components/PageBreadcrumb.vue'
import UICard from '@/components/UICard.vue'
import CustomApexChart from '@/components/CustomApexChart.vue'
import MainLayout from '@/layouts/MainLayout.vue'


const series = ref(generateRandomSeries())

const handleUpdate = () => {
    series.value = generateRandomSeries()
}


</script>

// React-Inertia/Full/resources/js/pages/graphs/apex/radar/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { useState } from 'react'
import { Button, Col, Container, Row } from 'react-bootstrap'
import { generateRandomSeries, getBasicRadarChart, getRadarMultiPleSeriesChart, getRadarPolygonChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    const [series, setSeries] = useState(generateRandomSeries)

    const handleUpdate = () => {
        setSeries(generateRandomSeries())
    }

    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Radar Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Basic Radar Chart">
                            <CustomApexChart getOptions={getBasicRadarChart} series={getBasicRadarChart().series} type="radar" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Radar with Polygon-fill">
                            <CustomApexChart getOptions={getRadarPolygonChart} series={getRadarPolygonChart().series} type="radar" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
                <Row>
                    <Col xl={12} md={6}>
                        <ComponentCard title="Radar – Multiple Series">
                            <CustomApexChart getOptions={() => ({ ...getRadarMultiPleSeriesChart(), series })} series={series} type="radar" height={350} />
                            <div className="text-center mt-2">
                                <Button size="sm" variant="primary" onClick={handleUpdate}>
                                    Update
                                </Button>
                            </div>
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
