// Nuxt/Full/pages/graphs/echart/heatmap/index.vue
<template>
  <BContainer fluid>
    <PageBreadcrumb title="Heatmap Echart" subtitle="Charts" />

    <BRow>
      <BCol xl="6">
        <UICard title="Basic Heatmap Chart">
          <CustomEChart
            :extensions="[HeatmapChart, CanvasRenderer]"
            :getOptions="getBasicBasicHeatmapChart"
            :style="{ height: '300px' }"
          />
        </UICard>
      </BCol>

      <BCol xl="6">
        <UICard title="Heatmap Chart">
          <CustomEChart
            :extensions="[HeatmapChart, CanvasRenderer]"
            :getOptions="getHeatmapChart"
            :style="{ height: '300px' }"
          />
        </UICard>
      </BCol>

      <BCol xl="6">
        <UICard title="Heatmap - 20K Data Chart">
          <CustomEChart
            :extensions="[HeatmapChart, CanvasRenderer]"
            :getOptions="getHeatmapDataChart"
            :style="{ height: '300px' }"
          />
        </UICard>
      </BCol>
    </BRow>
  </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next'
import UICard from '~/components/UICard.vue'
import PageBreadcrumb from '~/components/PageBreadcrumb.vue'
import CustomEChart from '~/components/CustomEChart.vue'

import { CanvasRenderer } from 'echarts/renderers'
import { HeatmapChart } from 'echarts/charts'

import {
  getBasicBasicHeatmapChart,
  getHeatmapChart,
  getHeatmapDataChart,
} from './data'

usePageTitle('Echart Heatmap Chart')
</script>

// React/Full/TS/src/views/graphs/echart/heatmap/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomEChart from '@/components/CustomEChart.tsx'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { RadarChart } from 'echarts/charts'
import { CanvasRenderer } from 'echarts/renderers'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicBasicHeatmapChart, getHeatmapChart, getHeatmapDataChart } from './data'

const Page = () => {
  return (
    <Container fluid>
      <PageBreadcrumb title="Heatmap Echart" subtitle="Charts" />
      <Row>
        <Col xl={6}>
          <ComponentCard title="Basic Heatmap Chart">
            <CustomEChart extensions={[RadarChart, CanvasRenderer]} getOptions={getBasicBasicHeatmapChart} style={{ height: '300px' }} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Heatmap Chart">
            <CustomEChart extensions={[RadarChart, CanvasRenderer]} getOptions={getHeatmapChart} style={{ height: '300px' }} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Heatmap - 20K Data Chart">
            <CustomEChart extensions={[RadarChart, CanvasRenderer]} getOptions={getHeatmapDataChart} style={{ height: '300px' }} />
          </ComponentCard>
        </Col>
      </Row>
    </Container>
  )
}

export default Page
