// NextJs/NextJs/Full/JS/src/app/(admin)/layouts/sidebars/with-lines/page.jsx
'use client';

import PageBreadcrumb from '@/components/PageBreadcrumb';
import { toggleAttribute } from '@/helpers/layout';
import { useEffect } from 'react';
import { Alert, Col, Container, Row } from 'react-bootstrap';
import { TbInfoCircle } from 'react-icons/tb';
const Page = () => {
  useEffect(() => {
    toggleAttribute('class', 'sidebar-with-line');
    return () => toggleAttribute('class', '');
  }, []);
  return <Container fluid>
      <PageBreadcrumb title="With Lines Menu" />

      <Row>
        <Col sm={12}>
          <Alert variant="info" className="alert-bordered border-start border-info d-flex align-items-start gap-2">
            <TbInfoCircle className="fs-xxl" />
            <div>
              If you want to display a line with each menu item, add the class <code>"sidebar-with-line"</code> to the <code>&lt;html&gt;</code> tag.
            </div>
          </Alert>
        </Col>
      </Row>
    </Container>;
};
export default Page;

// SvelteKit/Seed/src/routes/layouts/sidebars/with-lines/+page.svelte
<script lang="ts">
	import { Alert, Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageBreadcrumb from '$lib/components/PageBreadcrumb.svelte';
	import Icon from '@iconify/svelte';
	import { onMount } from 'svelte';
	import { toggleAttribute } from '$lib/helpers/layout';

	onMount(() => {
		toggleAttribute('class', 'sidebar-with-line');

		return () => toggleAttribute('class', 'sidebar-with-line', true);
	});
</script>

<Container fluid>
	<PageBreadcrumb title="Sidebar with Lines" />

	<Row>
		<Col sm="12">
			<Alert color="info" class="alert-bordered border-start border-info">
				<div class="d-flex align-items-center gap-2">
					<Icon icon="tabler:info-circle" class="fs-xxl" />
					<div>
						If you want to display a line with each menu item, add the class
						<code>"sidebar-with-line"</code> to the
						<code>&lt;html&gt;</code> tag. To apply this dynamically, use
						<code>toggleAttribute('class', 'sidebar-with-line')</code>.
					</div>
				</div>
			</Alert>
		</Col>
	</Row>
</Container>
