// React/Full/JS/src/views/graphs/apex/mixed/index.jsx
import ComponentCard from '@/components/cards/ComponentCard';
import CustomApexChart from '@/components/CustomApexChart';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { Col, Container, Row } from 'react-bootstrap';
import { getAllMixedChart, getLineAreaChart, getLineColumnChart, getMultipleYaxisMixedChart } from './data';
const Page = () => {
  return <Container fluid>
      <PageBreadcrumb title="Mixed Apexchart" subtitle="Charts" />
      <Row>
        <Col xl={6}>
          <ComponentCard title="Line & Column Chart">
            <CustomApexChart getOptions={getLineColumnChart} series={getLineColumnChart().series} type="line" height={380} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Multiple Y-Axis Chart">
            <CustomApexChart getOptions={getMultipleYaxisMixedChart} series={getMultipleYaxisMixedChart().series} type="line" height={380} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Line & Area Chart">
            <CustomApexChart getOptions={getLineAreaChart} series={getLineAreaChart().series} type="line" height={380} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Line, Column & Area Chart">
            <CustomApexChart getOptions={getAllMixedChart} series={getAllMixedChart().series} type="line" height={380} />
          </ComponentCard>
        </Col>
      </Row>
    </Container>;
};
export default Page;

// Nuxt/Full/pages/graphs/apex/mixed/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Mixed Apexchart" subtitle="Charts" />
        <BRow>
            <BCol xl='6'>
                <UICard title="Line & Column Chart">
                    <CustomApexChart :get-options='getLineColumnChart' :series='getLineColumnChart().series' type="line"
                        :height='380' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Multiple Y-Axis Chart">
                    <CustomApexChart :get-options='getMultipleYaxisMixedChart'
                        :series='getMultipleYaxisMixedChart().series' type="line" :height='380' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Line & Area Chart">
                    <CustomApexChart :get-options='getLineAreaChart' :series='getLineAreaChart().series' type="line"
                        :height='380' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Line, Column & Area Chart">
                    <CustomApexChart :get-options='getAllMixedChart' :series='getAllMixedChart().series' type="line"
                        :height='380' />
                </UICard>
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '~/components/CustomApexChart.vue';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import UICard from '~/components/UICard.vue';
import { getAllMixedChart, getLineAreaChart, getLineColumnChart, getMultipleYaxisMixedChart } from './data';

usePageTitle('Apex Mixed Charts')
</script>

<style scoped></style>
