// React-Inertia/Full/resources/js/pages/widgets/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Card, CardBody, Col, Container, Row } from 'react-bootstrap'
import { TbMail, TbPhone } from 'react-icons/tb'
import Widget1 from '@/pages/widgets/components/Widget1'
import SalesPerformanceOverview from '@/pages/widgets/components/SalesPerformanceOverview'
import TrafficSources from '@/pages/widgets/components/TrafficSources'
import TopCountries from '@/pages/widgets/components/TopCountries'
import ProfileCard from '@/pages/widgets/components/ProfileCard'
import CommentCard from '@/pages/widgets/components/CommentCard'
import ChatCard from '@/pages/widgets/components/ChatCard'
import FileManageCard from '@/pages/widgets/components/FileMangeCard'
import Widget3 from '@/pages/widgets/components/Widget3'
import Widget6 from '@/pages/widgets/components/Widget6'
import Widget7 from '@/pages/widgets/components/Widget7'
import Widget5 from '@/pages/widgets/components/Widget5'
import Widget4 from '@/pages/widgets/components/Widget4'
import TodaySchedule from '@/pages/widgets/components/TodaySchedule'
import { widget1Data, widget3Data, widget4Data, widget5Data, widget6Data, widget7Data } from '@/pages/widgets/data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Widgets" />
                <Row>
                    <Col xs={12}>
                        <Card>
                            <CardBody>
                                <Row className="row-cols-xxl-4 row-cols-md-2 row-cols-1 g-3 align-items-center">
                                    {widget1Data.map((widget, idx) => (
                                        <Col key={idx}>
                                            <Widget1 widget={widget} />
                                        </Col>
                                    ))}
                                </Row>
                            </CardBody>
                        </Card>
                    </Col>
                </Row>

                <Row>
                    <Col xl={4}>
                        <SalesPerformanceOverview />
                    </Col>
                    <Col xxl={4} lg={6}>
                        <TrafficSources />
                    </Col>

                    <Col xxl={4} lg={6}>
                        <TopCountries />
                    </Col>
                </Row>

                <Row>
                    <Col xl={4}>
                        <ProfileCard />

                        <CommentCard />
                    </Col>

                    <Col xl={4}>
                        <ChatCard />

                        <Row>
                            <Col xl={6}>
                                <Card className="text-bg-purple">
                                    <CardBody>
                                        <div className="d-flex align-items-center mb-3 gap-2">
                                            <div className="avatar-md">
                                                <span className="avatar-title bg-light bg-opacity-20 text-white rounded-circle fs-xl">
                                                    <TbPhone />
                                                </span>
                                            </div>
                                            <p className="mb-0 fw-semibold">PHONE</p>
                                        </div>
                                        <h5 className="mb-1 text-white text-opacity-75">+1 800 123 4567</h5>
                                        <h5 className="mb-0 text-white text-opacity-75">+1 800 765 4321</h5>
                                    </CardBody>
                                </Card>
                            </Col>
                            <Col xl={6}>
                                <Card className="text-bg-success">
                                    <CardBody>
                                        <div className="d-flex align-items-center mb-3 gap-2">
                                            <div className="avatar-md">
                                                <span className="avatar-title bg-light bg-opacity-20 text-white rounded-circle fs-xl">
                                                    <TbMail />
                                                </span>
                                            </div>
                                            <p className="mb-0 fw-semibold">EMAIL</p>
                                        </div>
                                        <h5 className="mb-1 text-white text-opacity-75">support@example.com</h5>
                                        <h5 className="mb-0 text-white text-opacity-75">sales@example.com</h5>
                                    </CardBody>
                                </Card>
                            </Col>
                        </Row>
                    </Col>

                    <Col xl={4}>
                        <FileManageCard />

                        <TodaySchedule />
                    </Col>
                </Row>

                <Row className="row-cols-xxl-5 row-cols-md-3 row-cols-1 align-items-center">
                    {widget3Data.map((item, idx) => (
                        <Col key={idx} className={idx != widget3Data.length - 1 ? 'col-lg col-md-auto' : ''}>
                            <Widget3 item={item} />
                        </Col>
                    ))}
                </Row>

                <Row className="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                    {widget4Data.map((item, idx) => (
                        <Col key={idx}>
                            <Widget4 item={item} />
                        </Col>
                    ))}
                </Row>

                <Row className="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                    {widget5Data.map((item, idx) => (
                        <Col key={idx}>
                            <Widget5 item={item} />
                        </Col>
                    ))}
                </Row>

                <Row className="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                    {widget6Data.map((item, idx) => (
                        <Col key={idx}>
                            <Widget6 item={item} />
                        </Col>
                    ))}
                </Row>

                <Row className="row-cols-xxl-6 row-cols-md-3 row-cols-2">
                    {widget7Data.map((item, idx) => (
                        <Col key={idx}>
                            <Widget7 item={item} />
                        </Col>
                    ))}
                </Row>
            </Container>
        </MainLayout>
    )
}
export default Page

// Vue/Full/src/views/widgets/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Widgets" />

            <BRow>
                <BCol cols="12">
                    <BCard no-body>
                        <BCardBody>
                            <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1 g-3 align-items-center">
                                <BCol v-for="(widget, idx) in widget1Data" :key="idx">
                                    <Widget1 :widget="widget" />
                                </BCol>
                            </BRow>
                        </BCardBody>
                    </BCard>
                </BCol>
            </BRow>

            <BRow>
                <BCol xl="4">
                    <SalesPerformanceOverview />
                </BCol>
                <BCol xxl="4" lg="6">
                    <TrafficSources />
                </BCol>
                <BCol xxl="4" lg="6">
                    <TopCountries />
                </BCol>
            </BRow>

            <BRow>
                <BCol xl="4">
                    <ProfileCard />
                    <CommentCard />
                </BCol>

                <BCol xl="4">
                    <ChatCard />
                    <BRow>
                        <BCol xl="6">
                            <BCard no-body class="text-bg-purple">
                                <BCardBody>
                                    <div class="d-flex align-items-center mb-3 gap-2">
                                        <div class="avatar-md">
                                            <span
                                                class="avatar-title bg-light bg-opacity-20 text-white rounded-circle fs-xl">
                                                <Icon icon="tabler:phone" />
                                            </span>
                                        </div>
                                        <p class="mb-0 fw-semibold">PHONE</p>
                                    </div>
                                    <h5 class="mb-1 text-white text-opacity-75">+1 800 123 4567</h5>
                                    <h5 class="mb-0 text-white text-opacity-75">+1 800 765 4321</h5>
                                </BCardBody>
                            </BCard>
                        </BCol>

                        <BCol xl="6">
                            <BCard no-body class="text-bg-success">
                                <BCardBody>
                                    <div class="d-flex align-items-center mb-3 gap-2">
                                        <div class="avatar-md">
                                            <span
                                                class="avatar-title bg-light bg-opacity-20 text-white rounded-circle fs-xl">
                                                <Icon icon="tabler:mail" />
                                            </span>
                                        </div>
                                        <p class="mb-0 fw-semibold">EMAIL</p>
                                    </div>
                                    <h5 class="mb-1 text-white text-opacity-75">support@example.com</h5>
                                    <h5 class="mb-0 text-white text-opacity-75">sales@example.com</h5>
                                </BCardBody>
                            </BCard>
                        </BCol>
                    </BRow>
                </BCol>

                <BCol xl="4">
                    <FileManageCard />
                    <TodaySchedule />
                </BCol>
            </BRow>

            <BRow class="row-cols-xxl-5 row-cols-md-3 row-cols-1 align-items-center">
                <BCol v-for="(item, idx) in widget3Data" :key="idx"
                    :class="idx !== widget3Data.length - 1 ? 'col-lg col-md-auto' : ''">
                    <Widget3 :item="item" />
                </BCol>
            </BRow>

            <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                <BCol v-for="(item, idx) in widget4Data" :key="idx">
                    <Widget4 :item="item" />
                </BCol>
            </BRow>

            <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                <BCol v-for="(item, idx) in widget5Data" :key="idx">
                    <Widget5 :item="item" />
                </BCol>
            </BRow>

            <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1">
                <BCol v-for="(item, idx) in widget6Data" :key="idx">
                    <Widget6 :item="item" />
                </BCol>
            </BRow>

            <BRow class="row-cols-xxl-6 row-cols-md-3 row-cols-2">
                <BCol v-for="(item, idx) in widget7Data" :key="idx">
                    <Widget7 :item="item" />
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { widget1Data, widget3Data, widget4Data, widget5Data, widget6Data, widget7Data } from './components/data';
import { BCard, BCardBody, BCol, BContainer, BRow } from 'bootstrap-vue-next';

import Widget1 from './components/Widget1.vue';
import Widget3 from './components/Widget3.vue';
import Widget4 from './components/Widget4.vue';
import Widget5 from './components/Widget5.vue';
import Widget6 from './components/Widget6.vue';
import Widget7 from './components/Widget7.vue';
import SalesPerformanceOverview from './components/SalesPerformanceOverview.vue';
import TrafficSources from './components/TrafficSources.vue';
import TopCountries from './components/TopCountries.vue';
import ProfileCard from './components/ProfileCard.vue';
import CommentCard from './components/CommentCard.vue';
import ChatCard from './components/ChatCard.vue';
import FileManageCard from './components/FileManageCard.vue';
import TodaySchedule from './components/TodaySchedule.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';
import { Icon } from '@iconify/vue';


usePageMeta('Widgets')
</script>
