// React-Inertia/Full/resources/js/pages/graphs/apex/polar-area/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicPolarAreaChart, getMonochromePolarAreaChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Ploar Area Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Basic Polar Area Chart">
                            <CustomApexChart getOptions={getBasicPolarAreaChart} series={getBasicPolarAreaChart().series} type="polarArea" height={380} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Monochrome Polar Area">
                            <CustomApexChart getOptions={getMonochromePolarAreaChart} series={getMonochromePolarAreaChart().series} type="polarArea" height={380} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page

// Vue-Inertia/Full/resources/js/pages/graphs/apex/polar-area/index.vue
<template>
    <MainLayout>
        
        <BContainer fluid>
            <PageBreadcrumb title="Ploar Area Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Basic Polar Area Chart">
                        <CustomApexChart :get-options='getBasicPolarAreaChart' :series='getBasicPolarAreaChart().series'
                            type="polarArea" :height='380' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Monochrome Polar Area">
                        <CustomApexChart :get-options='getMonochromePolarAreaChart'
                            :series='getMonochromePolarAreaChart().series' type="polarArea" :height='380' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import UICard from '@/components/UICard.vue';
import { getBasicPolarAreaChart, getMonochromePolarAreaChart } from './data';
import MainLayout from '@/layouts/MainLayout.vue';

import PageBreadcrumb from '@/components/PageBreadcrumb.vue';


</script>

<style scoped></style>
