// Vue/Full/src/views/forms/basic/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Basic Elements" subtitle="Forms" />

            <BContainer>
                <BRow>
                    <BCol xl='12'>
                        <InputTextFieldType />

                        <InputType />

                        <InputGroups />

                        <FloatingLabels />

                        <InputSizes />

                        <ChecksRadiosSwitches />
                    </BCol>
                </BRow>
            </BContainer>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import InputTextFieldType from './components/InputTextFieldType.vue';
import InputType from './components/InputType.vue';
import InputGroups from './components/InputGroups.vue';
import FloatingLabels from './components/FloatingLabels.vue';
import InputSizes from './components/InputSizes.vue';
import ChecksRadiosSwitches from './components/ChecksRadiosSwitches.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';

usePageMeta('Basic Elements')
</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/forms/basic/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import InputTextFieldType from '@/pages/forms/basic/components/InputTextFieldType'
import InputType from '@/pages/forms/basic/components/InputType'
import InputGroups from '@/pages/forms/basic/components/InputGroups'
import FloatingLabels from '@/pages/forms/basic/components/FloatingLabels'
import InputSizes from '@/pages/forms/basic/components/InputSizes'
import ChecksRadiosSwitches from '@/pages/forms/basic/components/ChecksRadiosSwitches'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="Basic Elements" subtitle="Forms" />

        <Container>
          <Row>
            <Col xl={12}>
              <InputTextFieldType />

              <InputType />

              <InputGroups />

              <FloatingLabels />

              <InputSizes />

              <ChecksRadiosSwitches />
            </Col>
          </Row>
        </Container>
      </Container>
    </MainLayout>
  )
}

export default Page
