// React/Full/JS/src/views/miscellaneous/pdf-viewer/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { useState } from 'react';
import { Button, Card, CardBody, Col, Container, FormControl, Row } from 'react-bootstrap';
import { TbArrowLeft, TbArrowRight, TbZoomIn, TbZoomOut } from 'react-icons/tb';
import { Document, Page as PDFPage, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = '/pdfjs/pdf.worker.min.mjs';
const Page = () => {
  const [numPages, setNumPages] = useState(0);
  const [pageNumber, setPageNumber] = useState(1);
  const [scale, setScale] = useState(1.5);
  function onDocumentLoadSuccess({
    numPages
  }) {
    setNumPages(numPages);
  }
  const nextPage = () => {
    if (pageNumber < numPages) {
      setPageNumber(pageNumber + 1);
    }
  };
  const prevPage = () => {
    if (pageNumber > 1) {
      setPageNumber(pageNumber - 1);
    }
  };
  const onZoomIn = () => {
    if (scale >= 3) {
      return;
    }
    setScale(scale + 0.2);
  };
  const onZoomOut = () => {
    if (scale <= 0.5) {
      return;
    }
    setScale(scale - 0.2);
  };
  const onZoomReset = () => {
    setScale(1);
  };
  const handleChange = event => {
    const value = parseInt(event.target.value);
    if (!isNaN(value) && value > 0 && value <= numPages) {
      setPageNumber(value);
    }
  };
  return <Container fluid>
      <PageBreadcrumb title="PDF Viewer" subtitle="Miscellaneous" />

      <Row>
        <Col xs={12}>
          <Card>
            <CardBody>
              <div className="text-center">
                <div className="btn-group text-nowrap">
                  <Button variant="dark" onClick={prevPage}>
                    <TbArrowLeft />
                    <span className="d-none d-sm-inline ms-2">Previous</span>
                  </Button>

                  <Button variant="dark" onClick={nextPage}>
                    <TbArrowRight />
                    <span className="d-none d-sm-inline ms-2">Next</span>
                  </Button>

                  <Button variant="dark" onClick={onZoomIn}>
                    <TbZoomIn />
                    <span className="d-none d-sm-inline ms-2">Zoom In</span>
                  </Button>

                  <Button variant="dark" onClick={onZoomOut}>
                    <TbZoomOut />
                    <span className="d-none d-sm-inline ms-2">Zoom Out</span>
                  </Button>

                  <Button variant="dark" className="rounded-end-3" onClick={onZoomReset}>
                    100%
                  </Button>

                  <FormControl type="text" className="rounded-end-0 ms-1" value={pageNumber} onChange={handleChange} />
                  <span className="input-group-text rounded-start-0 border-start-0">/ {numPages}</span>
                </div>
              </div>

              <div className="text-center  d-flex justify-content-center mt-3">
                <Document file="https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf" onLoadSuccess={onDocumentLoadSuccess}>
                  <PDFPage pageNumber={pageNumber} scale={scale} className="pdfcanvas border rounded-3 overflow-hidden" />
                </Document>
              </div>
            </CardBody>
          </Card>
        </Col>
      </Row>
    </Container>;
};
export default Page;

// Angular/Full/src/app/views/miscellaneous/pdf-viewer/pdf-viewer.component.ts
import { Component } from '@angular/core';
import { PageTitleComponent } from "@app/components/page-title.component";
import { FormsModule } from '@angular/forms';
import { PdfViewerModule } from 'ng2-pdf-viewer';
import { NgIcon } from '@ng-icons/core';
@Component({
    selector: 'app-pdf-viewer',
    imports: [PageTitleComponent, FormsModule, PdfViewerModule,NgIcon],
    templateUrl: './pdf-viewer.component.html',
    styles: ``
})
export class PdfViewerComponent {
    pdfSrc = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf';
    currentPage = 1;
    totalPages = 0;
    zoom = 1.0;

    afterLoadComplete(pdf: any) {
        this.totalPages = pdf.numPages;
    }

    goToPrevPage(): void {
        if (this.currentPage > 1) {
            this.currentPage--;
        }
    }

    goToNextPage(): void {
        if (this.currentPage < this.totalPages) {
            this.currentPage++;
        }
    }

    zoomIn(): void {
        this.zoom += 0.1;
    }

    zoomOut(): void {
        this.zoom = Math.max(0.1, this.zoom - 0.1);
    }

    zoomFit(): void {
        this.zoom = 1.0;
    }
}

<div class="container-fluid">
    <app-page-title subTitle="Miscellaneous" title="PDF Viewer" />

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text-center">
                        <div class="btn-group text-nowrap align-items-center">
                            <button (click)="goToPrevPage()" class="btn btn-dark">
                                <ng-icon name="tablerArrowLeft" />
                                <span class="d-none d-sm-inline ms-2">Previous</span>
                            </button>

                            <button (click)="goToNextPage()" class="btn btn-dark">
                                <ng-icon name="tablerArrowRight" />
                                <span class="d-none d-sm-inline ms-2">Next</span>
                            </button>

                            <button (click)="zoomIn()" class="btn btn-dark">
                                <ng-icon name="tablerZoomIn" />
                                <span class="d-none d-sm-inline ms-2">Zoom In</span>
                            </button>

                            <button (click)="zoomOut()" class="btn btn-dark">
                                <ng-icon name="tablerZoomOut" />
                                <span class="d-none d-sm-inline ms-2">Zoom Out</span>
                            </button>

                            <button (click)="zoomFit()" class="btn btn-dark rounded-end-3">100%</button>

                            <input type="number" class="form-control ms-2" [(ngModel)]="currentPage" [min]="1"
                                [max]="totalPages" style="width: 60px" />
                            <span class="ms-1">/ {{ totalPages }}</span>
                        </div>
                    </div>

                    <div class="text-center overflow-auto mt-3">
                        <pdf-viewer [src]="pdfSrc" [show-borders]="true" [zoom-scale]="'page-height'"
                            [page]="currentPage" [zoom]="zoom" (after-load-complete)="afterLoadComplete($event)"
                            [show-all]="false" [original-size]="false" [render-text]="true"
                            style="height: 100vh;"></pdf-viewer>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
