// React/Full/JS/src/views/dashboards/dashboard/components/ProjectPerformance.jsx
import { CardBody, ProgressBar } from 'react-bootstrap';
import { TbCircleFilled } from 'react-icons/tb';
import ComponentCard from '@/components/cards/ComponentCard';
import { projectStats } from '../data';
const ProjectPerformance = () => {
  return <ComponentCard title="Project Performance" bodyClassName="p-0" isCollapsible isRefreshable isCloseable>
      <CardBody>
        <div>
          {projectStats.map((stat, index) => <div key={stat.id}>
              <div className="d-flex justify-content-between mb-2">
                <h5 className="fs-base mb-0">{stat.title}</h5>
                <div>
                  <span>{stat.count}</span>
                  {stat.showPercentage && <span>
                      <TbCircleFilled className="text-light mx-3 fs-10" /> {stat.percentage}%
                    </span>}
                </div>
              </div>
              <ProgressBar variant={stat.variant} now={stat.percentage} className={index < projectStats.length - 1 ? 'mb-4' : ''} style={{
            height: '4px'
          }} />
            </div>)}
        </div>
      </CardBody>
    </ComponentCard>;
};
export default ProjectPerformance;

// src/views/dashboards/dashboard/components/ProjectPerformance.vue
<template>
    <UICard title="Project Performance" body-class="p-0" is-collapsable is-reloadable is-closeable>
        <BCardBody>
            <div>
                <div v-for="(stat, index) in projectStats" :key="index">
                    <div class="d-flex justify-content-between mb-2">
                        <h5 class="fs-base mb-0">{{ stat.title }}</h5>
                        <div>
                            <span>{{ stat.count }}</span>
                            <span v-if="stat.showPercentage">
                                <Icon icon="tabler:circle-filled" class="text-light mx-3 fs-10" /> {{ stat.percentage
                                }}%
                            </span>
                        </div>
                    </div>
                    <BProgress :variant="stat.variant" :value="stat.percentage" :max="100"
                        :class="{ 'mb-4': index < projectStats.length - 1 }" :style="{ height: '4px' }" />
                </div>
            </div>
        </BCardBody>
    </UICard>
</template>

<script setup lang="ts">
import { BProgress } from 'bootstrap-vue-next';
import { projectStats } from './data';
import UICard from '@/components/UICard.vue';
import { Icon } from '@iconify/vue';

</script>

<style lang="scss" scoped></style>
