// Vue-Inertia/Full/resources/js/pages/apps/ecommerce/sellers/[id]/components/SellerOverview.vue
<template>
    <BCard no-body>
        <BCardHeader>
            <h4 class="card-title">Seller Overview</h4>
        </BCardHeader>

        <BCardBody>
            <BRow class="row-cols-xxl-4 row-cols-md-2 row-cols-1 align-items-center">
                <BCol v-for="(item, idx) in sellerStatistics" :key="idx">
                    <SellerStatisticWidget :item="item" />
                </BCol>
            </BRow>

            <CustomApexChart :get-options="getSellerChartOptions" :series="getSellerChartOptions().series" />

        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BCol, BRow } from 'bootstrap-vue-next';
import SellerStatisticWidget from './SellerStatisticWidget.vue';
import { getSellerChartOptions, sellerStatistics } from './data';
import CustomApexChart from '@/components/CustomApexChart.vue';


</script>

<style scoped></style>

// React/Full/TS/src/views/ecommerce/sellers/[sellerId]/components/SellerOverview.tsx
import { Card, CardBody, CardHeader, CardTitle, Col, Row } from 'react-bootstrap'
import { getSellerChartOptions, sellerStatistics } from '../data'
import SellerStatisticWidget from '@/views/ecommerce/sellers/[sellerId]/components/SellerStatisticWidget.tsx'
import CustomApexChart from '@/components/CustomApexChart.tsx'

const SellerOverview = () => {
  return (
    <Card>
      <CardHeader>
        <CardTitle as={'h4'}>Seller Overview</CardTitle>
      </CardHeader>
      <CardBody>
        <Row className="row-cols-xxl-4 row-cols-md-2 row-cols-1 align-items-center">
          {sellerStatistics.map((item, idx) => (
            <Col key={idx}>
              <SellerStatisticWidget item={item} />
            </Col>
          ))}
        </Row>
        <div className="mb-1">
          <CustomApexChart getOptions={getSellerChartOptions} series={getSellerChartOptions().series} type="bar" height={370} />
        </div>
      </CardBody>
    </Card>
  )
}

export default SellerOverview
