// NextJs/NextJs/Seed/JS/src/layouts/components/topbar/components/UserProfile.jsx
import { userDropdownItems } from '@/layouts/components/data';
import Image from 'next/image';
import Link from 'next/link';
import { Fragment } from 'react';
import { Dropdown, DropdownDivider, DropdownItem, DropdownMenu, DropdownToggle } from 'react-bootstrap';
import { TbChevronDown } from 'react-icons/tb';
import user2 from '@/assets/images/users/user-2.jpg';
const UserProfile = () => {
  return <div className="topbar-item nav-user">
      <Dropdown align="end">
        <DropdownToggle as={'a'} className="topbar-link dropdown-toggle drop-arrow-none px-2">
          <Image src={user2.src} width="32" height="32" className="rounded-circle me-lg-2 d-flex" alt="user-image" />
          <div className="d-lg-flex align-items-center gap-1 d-none">
            <h5 className="my-0">Damian D.</h5>
            <TbChevronDown className="align-middle" />
          </div>
        </DropdownToggle>
        <DropdownMenu className="dropdown-menu-end">
          {userDropdownItems.map((item, idx) => <Fragment key={idx}>
              {item.isHeader ? <div className="dropdown-header noti-title">
                  <h6 className="text-overflow m-0">{item.label}</h6>
                </div> : item.isDivider ? <DropdownDivider /> : <DropdownItem as={Link} href={item.url} className={item.class}>
                  {item.icon && <item.icon className="me-2 fs-17 align-middle" />}
                  <span className="align-middle">{item.label}</span>
                </DropdownItem>}
            </Fragment>)}
        </DropdownMenu>
      </Dropdown>
    </div>;
};
export default UserProfile;

// SvelteKit/Seed/src/lib/layouts/components/topbar/components/UserProfile.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { userDropdownItems } from '$lib/layouts/components/data';
	import { Dropdown, DropdownItem, DropdownMenu, DropdownToggle } from '@sveltestrap/sveltestrap';

	import user2 from '$lib/assets/images/users/user-2.jpg';
</script>

<div class="topbar-item nav-user">
	<Dropdown>
		<DropdownToggle nav class="topbar-link px-2">
			<img src={user2} width={32} class="rounded-circle me-lg-2 d-flex" alt="User Profile" />
			<div class="d-lg-flex align-items-center gap-1 d-none">
				<h5 class="my-0">Damian D.</h5>
				<Icon icon="tabler:chevron-down" class="align-middle" />
			</div>
		</DropdownToggle>

		<DropdownMenu end>
			{#each userDropdownItems || [] as item, idx (idx)}
				{#if item.isHeader}
					<DropdownItem header class="noti-title">
						<p class="text-overflow m-0">{item.label}</p>
					</DropdownItem>
				{:else if item.isDivider}
					<DropdownItem divider />
				{:else}
					<DropdownItem href={item.url ?? '#'} class="d-flex align-items-center {item.class}">
						{#if item.icon}
							<Icon icon={item.icon} class="me-2 fs-17 align-middle" />
						{/if}
						<span class="align-middle">{item.label}</span>
					</DropdownItem>
				{/if}
			{/each}
		</DropdownMenu>
	</Dropdown>
</div>
