// SvelteKit/Seed/src/routes/layouts/sidebars/light/+page.svelte
<script lang="ts">
	import { Alert, Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageBreadcrumb from '$lib/components/PageBreadcrumb.svelte';
	import Icon from '@iconify/svelte';
	import { onMount } from 'svelte';
	import { reset, setSideNavColor } from '$lib/stores/layout';

	onMount(() => {
		setSideNavColor('light');

		return () => reset();
	});
</script>

<Container fluid>
	<PageBreadcrumb title="Light Sidebar" />

	<Row>
		<Col sm="12">
			<Alert color="info" class="alert-bordered border-start border-info">
				<div class="d-flex align-items-center gap-2">
					<Icon icon="tabler:info-circle" class="fs-xxl" />
					<div>
						To switch to a light sidebar, add
						<code>data-menu-color="light"</code> to the
						<code>&lt;html&gt;</code> tag. To apply this dynamically, use
						<code>setSideNavColor('light')</code> from the <code>layout</code> store.
					</div>
				</div>
			</Alert>
		</Col>
	</Row>
</Container>

// NextJs/NextJs/Seed/JS/src/app/(admin)/layouts/sidebars/light/page.jsx
'use client';

import PageBreadcrumb from '@/components/PageBreadcrumb';
import { useLayoutContext } from '@/context/useLayoutContext';
import { useEffect } from 'react';
import { Alert, Col, Container, Row } from 'react-bootstrap';
import { TbInfoCircle } from 'react-icons/tb';
const Page = () => {
  const {
    changeSideNavColor,
    reset
  } = useLayoutContext();
  useEffect(() => {
    changeSideNavColor('light');
    return () => reset();
  }, []);
  return <Container fluid>
      <PageBreadcrumb title="Light Menu" />

      <Row>
        <Col sm={12}>
          <Alert variant="info" className="alert-bordered border-start border-info d-flex align-items-start gap-2">
            <TbInfoCircle className="fs-xxl" />
            <div>
              To switch to a light sidebar, add <code>data-menu-color="light"</code> to the <code>&lt;html&gt;</code> tag. To apply this dynamically,
              use <code>changeSideNavColor('light')</code> from the <code>LayoutContext</code>.
            </div>
          </Alert>
        </Col>
      </Row>
    </Container>;
};
export default Page;
