// React/Full/TS/src/views/widgets/components/Widget6.tsx
import { toPascalCase } from '@/helpers/casing'
import { Link } from 'react-router'
import { Card, CardBody, ProgressBar } from 'react-bootstrap'
import type { Widget6Type } from '@/views/widgets/types.ts'

const Widget6 = ({ item }: { item: Widget6Type }) => {
  const { title, progress, status, description } = item
  return (
    <Card>
      <CardBody>
        <div>
          <Link to="#" className="link-reset text-uppercase fw-semibold">
            {title}
          </Link>
          <div className="py-2">
            <span className="fs-xl fw-bold me-2">{progress}%</span>
            <span className="fw-semibold text-muted fs-7">{toPascalCase(status)}</span>
          </div>
        </div>
        <ProgressBar now={progress} variant="success" className="progress-md bg-opacity-25" />
        <div className="mt-2 text-muted">{description}</div>
      </CardBody>
    </Card>
  )
}

export default Widget6

// Nuxt/Full/pages/widgets/components/Widget6.vue
<template>
    <BCard no-body>
        <BCardBody>
            <div>
                <NuxtLink to="" class="link-reset text-uppercase fw-semibold">
                    {{ item.title }}
                </NuxtLink>

                <div class="py-2">
                    <span class="fs-xl fw-bold me-2">{{ item.progress }}%</span>
                    <span class="fw-semibold text-muted fs-7">{{ toPascalCase(item.status) }}</span>
                </div>
            </div>

            <BProgress :value="item.progress" bg-variant="success" class="progress-md bg-opacity-25" />

            <div class="mt-2 text-muted">
                {{ item.description }}
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BProgress } from 'bootstrap-vue-next'
import type { Widget6Type } from './types';
import { toPascalCase } from '~/helpers/casing';

defineProps<{ item: Widget6Type }>()
</script>
