// NextJs/NextJs/Full/TS/src/app/(admin)/widgets/components/Widget1.tsx
import { Widget1Type } from '@/app/(admin)/widgets/types'
import { Card, CardBody } from 'react-bootstrap'
import { TbPointFilled } from 'react-icons/tb'

const Widget1 = ({ widget }: { widget: Widget1Type }) => {
  const { title, icon: Icon, totalCount, count, variant, description } = widget
  return (
    <Card className={`border-0 bg-${variant} bg-opacity-10 shadow-none mb-0`}>
      <CardBody>
        <h5 title="Number of Orders">{title}</h5>
        <div className="d-flex align-items-center gap-2 my-3">
          <div className="avatar-md flex-shrink-0">
            <span className={`avatar-title text-bg-${variant} bg-opacity-90 rounded-circle fs-22`}>
              <Icon />
            </span>
          </div>
          <h3 className="mb-0">
            {count.prefix && count.prefix}
            {count.value} {count.suffix && count.suffix}
          </h3>
        </div>
        <p className="mb-0">
          <span className={`text-${variant}`}>
            <TbPointFilled className="me-1" />
          </span>
          <span className="text-nowrap text-muted">{description}</span>
          <span className="float-end">
            <b>{totalCount}</b>
          </span>
        </p>
      </CardBody>
    </Card>
  )
}

export default Widget1

// Nuxt/Full/pages/widgets/components/Widget1.vue
<template>
    <BCard no-body :class="`border-0 bg-${widget.variant} bg-opacity-10 shadow-none mb-0`">
        <BCardBody>
            <h5 :title="`Number of ${widget.title}`">{{ widget.title }}</h5>

            <div class="d-flex align-items-center gap-2 my-3">
                <div class="avatar-md flex-shrink-0">
                    <span :class="`avatar-title text-bg-${widget.variant} bg-opacity-90 rounded-circle fs-22`">
                        <Icon :name="widget.icon" />
                    </span>
                </div>

                <h3 class="mb-0">
                    <span v-if="widget.count.prefix">{{ widget.count.prefix }}</span>
                    {{ widget.count.value }}
                    <span v-if="widget.count.suffix">{{ widget.count.suffix }}</span>
                </h3>
            </div>

            <p class="mb-0">
                <span :class="`text-${widget.variant}`">
                    <Icon name="tabler:point-filled" class="me-1" />
                </span>
                <span class="text-nowrap text-muted">{{ widget.description }}</span>
                <span class="float-end">
                    <b>{{ widget.totalCount }}</b>
                </span>
            </p>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import type { Widget1Type } from './types';


defineProps<{
    widget: Widget1Type
}>()
</script>
