// Nuxt/Full/pages/forms/other-plugins/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Other Plugins" subTitle="Forms" />
    </BContainer>

    <BContainer>
        <BRow>
            <BCol xs="12">
                <FormInputMasks />

                <Typeaheads />

                <InputTouchspin />
            </BCol>
        </BRow>

    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import FormInputMasks from './components/FormInputMasks.vue';
import Typeaheads from './components/Typeaheads.vue';
import InputTouchspin from './components/InputTouchspin.vue';

usePageTitle('Other Plugins')
</script>

<style scoped></style>

// NextJs/NextJs/Full/JS/src/app/(admin)/forms/other-plugins/page.jsx
import ReactInputMask from '@/app/(admin)/forms/other-plugins/components/ReactInputMask';
import ReactTypeahead from '@/app/(admin)/forms/other-plugins/components/ReactTypeahead';
import TouchSpin from '@/app/(admin)/forms/other-plugins/components/Touchspin';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { Col, Container, Row } from 'react-bootstrap';
const Page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="Other Plugins" subtitle="Forms" />
      </Container>

      <Container>
        <Row>
          <Col cols={12}>
            <ReactInputMask />
            <ReactTypeahead />
            <TouchSpin />
          </Col>
        </Row>
      </Container>
    </>;
};
export default Page;
