// SvelteKit/Seed/src/routes/layouts/compact/+page.svelte
<script lang="ts">
	import { Alert, Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageBreadcrumb from '$lib/components/PageBreadcrumb.svelte';
	import VerticalLayout from '$lib/layouts/VerticalLayout.svelte';
	import Icon from '@iconify/svelte';
</script>

<VerticalLayout>
	<Container fluid>
		<PageBreadcrumb title="Compact" />
	</Container>

	<Container xl>
		<Row>
			<Col sm="12">
				<Alert color="info" class="alert-bordered border-start border-info">
					<div class="d-flex align-items-center gap-2">
						<Icon icon="tabler:info-circle" class="fs-xxl" />
						<div>
							To use the compact layout, follow this structure: wrap your page title in
							<code>&lt;Container fluid&gt;</code> and place your main content inside
							<code>&lt;Container xl&gt;</code>. This ensures proper spacing and alignment.
						</div>
					</div>
				</Alert>
			</Col>
		</Row>
	</Container>
</VerticalLayout>

// React-Inertia/Full/resources/js/pages/layouts/compact/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import MainLayout from '@/layouts/MainLayout'
import { Alert, Col, Container, Row } from 'react-bootstrap'
import { TbInfoCircle } from 'react-icons/tb'

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="Compact" />
      </Container>

      <Container fluid="xl">
        <Row>
          <Col sm={12}>
            <Alert variant="info" className="alert-bordered border-start border-info d-flex align-items-start gap-2">
              <TbInfoCircle className="fs-xxl" />
              <div>
                To use the compact layout, follow this structure: wrap your page title in <code>&lt;div class="container-fluid"&gt;</code> and place
                your main content inside
                <code>&lt;div class="container-xl"&gt;</code>. This ensures proper spacing and alignment.
              </div>
            </Alert>
          </Col>
        </Row>
      </Container>
    </MainLayout>
  )
}

export default Page
