// Nuxt/Full/pages/(apps)/users/roles/components/MemberRoleCard.vue
<template>
    <BCard no-body>
        <BCardBody class="d-flex flex-column justify-content-between">
            <div class="d-flex align-items-center mb-4">
                <div class="flex-shrink-0">
                    <div
                        class="avatar-xl rounded-circle bg-primary-subtle d-flex align-items-center justify-content-center">
                        <Icon :name="member.icon" class="fs-24 text-primary" />
                    </div>
                </div>

                <div class="ms-3">  
                    <h5 class="mb-2">{{ member.title }}</h5>
                    <p class="text-muted mb-0 fs-base">{{ member.description }}</p>
                </div>

                <div class="ms-auto">
                    <BDropdown placement="bottom-end" variant="link" toggle-class="text-muted px-0 fs-xl drop-arrow-none">
                        <template #button-content>
                            <Icon name="tabler:dots-vertical" />
                        </template>
                        <BDropdownItem>
                            <Icon name="tabler:eye" class="me-2" /> View
                        </BDropdownItem>
                        <BDropdownItem>
                            <Icon name="tabler:edit" class="me-2" /> Edit
                        </BDropdownItem>
                        <BDropdownItem class="text-danger">
                            <Icon name="tabler:trash" class="me-2" /> Remove
                        </BDropdownItem>
                    </BDropdown>
                </div>
            </div>

            <ul class="list-unstyled mb-3">
                <li v-for="(feature, idx) in member.features" :key="idx" class="d-flex align-items-center"
                    :class="{ 'mb-2': idx !== member.features.length - 1 }">
                    <Icon name="tabler:check" class="fs-lg text-success me-2" /> {{ feature }}
                </li>
            </ul>

            <p class="mb-2 text-muted">Total {{ member.users.length }} users</p>
            <div class="avatar-group avatar-group-sm mb-3">
                <div v-for="(user, idx) in member.users.slice(0, 4)" :key="idx" class="avatar">
                    <NuxtImg :src="user" class="rounded-circle avatar-sm" :alt="`user-${idx + 1}`" />
                </div>

                <BTooltip v-if="member.users.length > 4" :title="`${member.users.length - 4} More`" placement="top">
                    <template #target>
                        <div class="avatar avatar-sm">
                            <span class="avatar-title text-bg-primary rounded-circle fw-bold">
                                +{{ member.users.length - 4 }}
                            </span>
                        </div>
                    </template>
                </BTooltip>
            </div>

            <div class="d-flex justify-content-between align-items-center">
                <span class="text-muted fs-xs">
                    <Icon name="tabler:clock" class="me-1" />
                    Updated {{ member.updatedTime }}
                </span>
                <NuxtLink to="" class="btn btn-sm btn-outline-primary rounded-pill">
                    Details
                </NuxtLink>
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BDropdown, BDropdownItem, BTooltip } from 'bootstrap-vue-next';
import type { MemberRoleType } from './types';

defineProps<{ member: MemberRoleType }>()
</script>

<style scoped></style>

// NextJs/NextJs/Full/JS/src/app/(admin)/(apps)/users/roles/components/MemberRoleCard.jsx
import Image from 'next/image';
import { Fragment } from 'react';
import { Card, CardBody, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, OverlayTrigger, Tooltip } from 'react-bootstrap';
import { TbCheck, TbClock, TbDotsVertical, TbEdit, TbEye, TbTrash } from 'react-icons/tb';
const MemberRoleCard = ({
  member
}) => {
  const {
    icon: Icon,
    title,
    users,
    features,
    description,
    updatedTime
  } = member;
  return <Card>
      <CardBody className="d-flex flex-column justify-content-between">
        <div className="d-flex align-items-center mb-4">
          <div className="flex-shrink-0">
            <div className="avatar-xl rounded-circle bg-primary-subtle d-flex align-items-center justify-content-center">
              <Icon className="fs-24 text-primary" />
            </div>
          </div>
          <div className="ms-3">
            <h5 className="mb-2">{title}</h5>
            <p className="text-muted mb-0 fs-base">{description}</p>
          </div>
          <div className="ms-auto">
            <Dropdown align="end">
              <DropdownToggle as="a" href="#" className="text-muted fs-xl drop-arrow-none">
                <TbDotsVertical />
              </DropdownToggle>

              <DropdownMenu>
                <DropdownItem href="#">
                  <TbEye className="me-2" />
                  View
                </DropdownItem>
                <DropdownItem href="#">
                  <TbEdit className="me-2" />
                  Edit
                </DropdownItem>
                <DropdownItem href="#" className="text-danger">
                  <TbTrash className="me-2" />
                  Remove
                </DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </div>
        </div>
        <ul className="list-unstyled mb-3">
          {features.map((feature, idx) => <li className={`d-flex align-items-center ${idx !== features.length - 1 ? 'mb-2' : ''}`} key={idx}>
              <TbCheck className="fs-lg text-success me-2" /> {feature}
            </li>)}
        </ul>
        <p className="mb-2 text-muted">Total {users.length} users</p>
        <div className="avatar-group avatar-group-sm mb-3">
          {users.map((user, idx) => <Fragment key={idx}>
              {idx < 4 && <div className="avatar">
                  <Image src={user} className="rounded-circle avatar-sm" alt={`user-${idx + 1}`} />
                </div>}
            </Fragment>)}
          {users.length > 4 && <OverlayTrigger overlay={<Tooltip>{users.length - 4} More</Tooltip>}>
              <div className="avatar avatar-sm">
                <span className="avatar-title text-bg-primary rounded-circle fw-bold"> +{users.length - 4}</span>
              </div>
            </OverlayTrigger>}
        </div>
        <div className="d-flex justify-content-between align-items-center">
          <span className="text-muted fs-xs">
            <TbClock className="me-1" />
            Updated {updatedTime}
          </span>
          <a href="#" className="btn btn-sm btn-outline-primary rounded-pill">
            Details
          </a>
        </div>
      </CardBody>
    </Card>;
};
export default MemberRoleCard;
