// Vue-Inertia/Full/resources/js/pages/forms/file-uploads/index.vue
<template>
    <MainLayout>
        
        <BContainer fluid>
            <PageBreadcrumb title="File Uploader" subtitle="Forms" />
        </BContainer>
        <BContainer>
            <BRow class="mt-3">
                <BCol xs="12">
                    <Dropzone />

                    <FilePond />
                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import Dropzone from './components/Dropzone.vue';
import FilePond from './components/FilePond.vue';

import MainLayout from '@/layouts/MainLayout.vue';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';


</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/forms/file-uploads/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import ReactDropzone from '@/pages/forms/file-uploads/components/ReactDropzone'
import ReactFilePond from '@/pages/forms/file-uploads/components/ReactFilePond'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="File Uploads" subtitle="Forms" />
      </Container>

      <Container>
        <Row>
          <Col cols={12}>
            <ReactDropzone />
            <ReactFilePond />
          </Col>
        </Row>
      </Container>
    </MainLayout>
  )
}

export default Page
