// Vue-Inertia/Full/resources/js/pages/miscellaneous/gallery/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Gallery" subtitle="Miscellaneous" />
            <BRow>
                <BCol xs="12">
                    <BCard no-body>
                        <BCardHeader class="flex-wrap justify-content-between w-100 gap-3">

                            <div class="flex-grow-1">
                                <div class="app-search">
                                    <input type="search" class="form-control topbar-search" name="search"
                                        placeholder="Search ...">
                                    <Icon icon="lucide:search" class="app-search-icon text-muted" />
                                </div>
                            </div>

                            <div class="d-flex flex-wrap gap-1 filter-buttons">
                                <button v-for="(category, idx) in categories" :key="idx"
                                    class="btn btn-sm btn-ghost-primary"
                                    :class="{ active: selectedCategory === category }"
                                    @click="selectedCategory = category">{{ category }}</button>
                            </div>
                        </BCardHeader>

                        <BCardBody>
                            <BRow>
                                <MasonryWall :items="filteredItems" :ssr-columns="1" :column-width="310" :gap="10">
                                    <template #default="{ item, index }">
                                        <BCol>
                                            <BCard no-body class="border-0 mb-0">
                                                <div
                                                    class="badge text-bg-dark badge-label position-absolute top-0 start-0 m-3 z-1">
                                                    beautiful</div>

                                                <img class="card-img rounded-2" :src="item.image"
                                                    :alt="`Image ${index + 1}`" @click="showLightbox(index)" />


                                            </BCard>
                                        </BCol>
                                    </template>
                                </MasonryWall>

                                <VueEasyLightbox :visible="visible" :imgs="filteredItems.map(i => i.image)"
                                    :index="index" @hide="visible = false" />

                            </BRow>
                        </BCardBody>
                    </BCard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BCardHeader, BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { Icon } from '@iconify/vue';
import { computed, ref } from 'vue';

import VueEasyLightbox from 'vue-easy-lightbox'

import img1 from '@/images/gallery/1.jpg'
import img10 from '@/images/gallery/10.jpg'
import img11 from '@/images/gallery/11.jpg'
import img12 from '@/images/gallery/12.jpg'
import img14 from '@/images/gallery/14.jpg'
import img2 from '@/images/gallery/2.jpg'
import img3 from '@/images/gallery/3.jpg'
import img4 from '@/images/gallery/4.jpg'
import img5 from '@/images/gallery/5.jpg'
import img6 from '@/images/gallery/6.jpg'
import img7 from '@/images/gallery/7.jpg'
import img8 from '@/images/gallery/8.jpg'
import img9 from '@/images/gallery/9.jpg'
import MainLayout from '@/layouts/MainLayout.vue';
import MasonryWall from '@yeger/vue-masonry-wall';

const slides = [
    { image: img1, category: 'beautiful' },
    { image: img2, category: 'nature' },
    { image: img3, category: 'beautiful' },
    { image: img4, category: 'nature' },
    { image: img5, category: 'travel' },
    { image: img6, category: 'nature' },
    { image: img7, category: 'city' },
    { image: img8, category: 'city' },
    { image: img9, category: 'travel' },
    { image: img10, category: 'beautiful' },
    { image: img11, category: 'nature' },
    { image: img12, category: 'city' },
    { image: img14, category: 'travel' },
]

const selectedCategory = ref('All')

const filteredItems = computed(() =>
    selectedCategory.value === 'All'
        ? slides
        : slides.filter(item => item.category === selectedCategory.value)
)

const categories = ['All', 'beautiful', 'nature', 'travel', 'city']


const visible = ref(false)
const index = ref(0)

const showLightbox = (i: number) => {
    index.value = i
    visible.value = true
}


</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/miscellaneous/gallery/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { useMemo, useState } from 'react'
import { Button, Card, CardBody, CardHeader, Col, Container, FormControl, Row } from 'react-bootstrap'
import { LuSearch } from 'react-icons/lu'
import { RowsPhotoAlbum } from 'react-photo-album'
import Lightbox from 'yet-another-react-lightbox'

import img1 from '@/images/gallery/1.jpg'
import img10 from '@/images/gallery/10.jpg'
import img11 from '@/images/gallery/11.jpg'
import img12 from '@/images/gallery/12.jpg'
import img14 from '@/images/gallery/14.jpg'
import img2 from '@/images/gallery/2.jpg'
import img3 from '@/images/gallery/3.jpg'
import img4 from '@/images/gallery/4.jpg'
import img5 from '@/images/gallery/5.jpg'
import img6 from '@/images/gallery/6.jpg'
import img7 from '@/images/gallery/7.jpg'
import img8 from '@/images/gallery/8.jpg'
import img9 from '@/images/gallery/9.jpg'
import MainLayout from '@/layouts/MainLayout'

const slides = [
    { asset: img1, width: 640, height: 427, category: 'beautiful' },
    { asset: img2, width: 640, height: 360, category: 'nature' },
    { asset: img3, width: 640, height: 854, category: 'beautiful' },
    { asset: img4, width: 640, height: 640, category: 'nature' },
    { asset: img5, width: 640, height: 960, category: 'travel' },
    { asset: img6, width: 640, height: 800, category: 'nature' },
    { asset: img7, width: 640, height: 425, category: 'city' },
    { asset: img8, width: 640, height: 480, category: 'city' },
    { asset: img9, width: 640, height: 960, category: 'travel' },
    { asset: img10, width: 640, height: 962, category: 'beautiful' },
    { asset: img11, width: 640, height: 427, category: 'nature' },
    { asset: img12, width: 640, height: 359, category: 'city' },
    { asset: img14, width: 640, height: 960, category: 'travel' },
].map(({ asset, width, height, category }) => ({
    src: asset,
    width,
    height,
    category,
}))

const Page = () => {
    const [selectedCategory, setSelectedCategory] = useState('All')

    const filteredItems = useMemo(() => {
        return selectedCategory === 'All' ? slides : slides.filter((item) => item.category === selectedCategory)
    }, [selectedCategory])

    const [index, setIndex] = useState(-1)

    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Gallery" subtitle="Miscellaneous" />

                <Row>
                    <Col cols={12}>
                        <Card>
                            <CardHeader className="flex-wrap justify-content-between w-100 gap-3">
                                <div className="flex-grow-1">
                                    <div className="app-search">
                                        <FormControl type="search" className="topbar-search" name="search" placeholder="Search ..." />
                                        <LuSearch className="app-search-icon text-muted" />
                                    </div>
                                </div>

                                <div className="d-flex flex-wrap gap-1 filter-buttons">
                                    <Button
                                        size="sm"
                                        className={`btn-ghost-primary ${selectedCategory === 'All' ? 'active' : ''}`}
                                        onClick={() => setSelectedCategory('All')}>
                                        All
                                    </Button>
                                    <Button
                                        size="sm"
                                        className={`btn-ghost-primary ${selectedCategory === 'beautiful' ? 'active' : ''}`}
                                        onClick={() => setSelectedCategory('beautiful')}>
                                        Beautiful
                                    </Button>
                                    <Button
                                        size="sm"
                                        className={`btn-ghost-primary ${selectedCategory === 'nature' ? 'active' : ''}`}
                                        onClick={() => setSelectedCategory('nature')}>
                                        Nature
                                    </Button>
                                    <Button
                                        size="sm"
                                        className={`btn-ghost-primary ${selectedCategory === 'travel' ? 'active' : ''}`}
                                        onClick={() => setSelectedCategory('travel')}>
                                        Travel
                                    </Button>
                                    <Button
                                        size="sm"
                                        className={`btn-ghost-primary ${selectedCategory === 'city' ? 'active' : ''}`}
                                        onClick={() => setSelectedCategory('city')}>
                                        City
                                    </Button>
                                </div>
                            </CardHeader>

                            <CardBody>
                                <div style={{ width: '100%' }}>
                                    <RowsPhotoAlbum photos={filteredItems} onClick={({ index: current }) => setIndex(current)} />

                                    <Lightbox
                                        index={index}
                                        slides={filteredItems}
                                        controller={{ closeOnBackdropClick: true }}
                                        open={index >= 0}
                                        close={() => setIndex(-1)}
                                    />
                                </div>
                            </CardBody>
                        </Card>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
