// Vue-Inertia/Full/resources/js/pages/graphs/apex/heatmap/index.vue
<template>
    <MainLayout>
        
        <BContainer fluid>
            <PageBreadcrumb title="Heatmap Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Heatmap - Single Series">
                        <CustomApexChart :get-options='getHeatmapSingleSeriesChart'
                            :series='getHeatmapSingleSeriesChart().series' type="heatmap" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Multiple Series">
                        <CustomApexChart :get-options='getMultipleSeries' :series='getMultipleSeries().series'
                            type="heatmap" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Heatmap - Color Range">
                        <CustomApexChart :get-options='getHeatmapColorRange' :series='getHeatmapColorRange().series'
                            type="heatmap" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Heatmap - Range without Shades">
                        <CustomApexChart :get-options='getRangeWithoutShades' :series='getRangeWithoutShades().series'
                            type="heatmap" :height='350' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import UICard from '@/components/UICard.vue';
import { getHeatmapColorRange, getHeatmapSingleSeriesChart, getMultipleSeries, getRangeWithoutShades } from './data';
import MainLayout from '@/layouts/MainLayout.vue';

import PageBreadcrumb from '@/components/PageBreadcrumb.vue';


</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/graphs/apex/heatmap/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getHeatmapColorRange, getHeatmapSingleSeriesChart, getMultipleSeries, getRangeWithoutShades } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Heatmap Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Heatmap - Single Series">
                            <CustomApexChart getOptions={getHeatmapSingleSeriesChart} series={getHeatmapSingleSeriesChart().series} type="heatmap" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Multiple Series">
                            <CustomApexChart getOptions={getMultipleSeries} series={getMultipleSeries().series} type="heatmap" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Heatmap - Color Range">
                            <CustomApexChart getOptions={getHeatmapColorRange} series={getHeatmapColorRange().series} type="heatmap" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Heatmap - Range without Shades">
                            <CustomApexChart getOptions={getRangeWithoutShades} series={getRangeWithoutShades().series} type="heatmap" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
