// src/views/ui/carousel/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Carousel" subTitle="UI" />
        </BContainer>

        <div class="container-xl">
            <BRow>
                <BCol xl="12">
                    <BCard no-body>
                        <BCardHeader>
                            <BCardTitle tag="h4">Examples</BCardTitle>
                        </BCardHeader>

                        <BCardBody>
                            <p class="text-muted mb-2">
                                A slideshow component for cycling through elements—images or slides of text—like a
                                carousel.
                            </p>

                            <a class="btn btn-link p-0 fw-semibold"
                                href="https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/carousel.html"
                                target="_blank">
                                Carousel on Bootstrap
                                <Icon icon="tabler:chevron-right" class="ms-1" />
                            </a>
                        </BCardBody>
                    </BCard>
                </BCol>

                <BCol lg="6">
                    <UICard title="Slides Only" isCollapsable>
                        <BCarousel ride="carousel">
                            <BCarouselSlide :img-src="small1" class="img-fluid" />
                            <BCarouselSlide :img-src="small2" class="img-fluid" />
                            <BCarouselSlide :img-src="small3" class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="With Controls" isCollapsable>
                        <BCarousel controls ride="carousel">
                            <BCarouselSlide :img-src="small4" class="img-fluid" />
                            <BCarouselSlide :img-src="small1" class="img-fluid" />
                            <BCarouselSlide :img-src="small2" class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="With Indicators" isCollapsable>
                        <BCarousel controls indicators ride="carousel">
                            <BCarouselSlide :img-src="small3" class="img-fluid" />
                            <BCarouselSlide :img-src="small2" class="img-fluid" />
                            <BCarouselSlide :img-src="small1" class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="With Captions" isCollapsable>
                        <BCarousel id="carouselCaptions" controls ride="carousel">
                            <BCarouselSlide :img-src="small1" caption="First slide label"
                                text="Some representative placeholder content for the first slide." class="img-fluid" />
                            <BCarouselSlide :img-src="small3" caption="Second slide label"
                                text="Some representative placeholder content for the second slide."
                                class="img-fluid" />
                            <BCarouselSlide :img-src="small2" caption="Third slide label"
                                text="Some representative placeholder content for the third slide." class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="Crossfade" isCollapsable>
                        <BCarousel id="carouselCrossfade" controls indicators fade ride="carousel">
                            <BCarouselSlide :img-src="small1" class="img-fluid" />
                            <BCarouselSlide :img-src="small2" class="img-fluid" />
                            <BCarouselSlide :img-src="small3" class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="Interval (Custom speed)" isCollapsable>
                        <BCarousel id="carouselInterval" controls indicators :interval="2000" ride="carousel">
                            <BCarouselSlide :img-src="small4" class="img-fluid" />
                            <BCarouselSlide :img-src="small3" class="img-fluid" />
                            <BCarouselSlide :img-src="small2" class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>

                <BCol lg="6">
                    <UICard title="Dark Variant" isCollapsable>
                        <BCarousel controls indicators ride="carousel" class="carousel-dark">
                            <BCarouselSlide :img-src="small8" caption="First slide label"
                                text="Dark variant text example." class="img-fluid" />
                            <BCarouselSlide :img-src="small9" caption="Second slide label"
                                text="Dark variant text example." class="img-fluid" />
                            <BCarouselSlide :img-src="small10" caption="Third slide label"
                                text="Dark variant text example." class="img-fluid" />
                        </BCarousel>
                    </UICard>
                </BCol>
            </BRow>

        </div>
    </MainLayout>
</template>

<script setup lang="ts">
import { usePageMeta } from '@/composables/usePageMeta';
import { BCard, BCardBody, BCardHeader, BCardTitle, BCarousel, BCarouselSlide, BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';

import small1 from '@/assets/images/stock/small-1.jpg'
import small2 from '@/assets/images/stock/small-2.jpg'
import small3 from '@/assets/images/stock/small-3.jpg'
import small4 from '@/assets/images/stock/small-4.jpg'
import small8 from '@/assets/images/stock/small-8.jpg'
import small9 from '@/assets/images/stock/small-9.jpg'
import small10 from '@/assets/images/stock/small-10.jpg'
usePageMeta('Carousel')
</script>

<style scoped></style>

// NextJs/NextJs/Full/JS/src/app/(admin)/ui/carousel/page.jsx
import small1 from '@/assets/images/stock/small-1.jpg';
import small10 from '@/assets/images/stock/small-10.jpg';
import small2 from '@/assets/images/stock/small-2.jpg';
import small3 from '@/assets/images/stock/small-3.jpg';
import small8 from '@/assets/images/stock/small-8.jpg';
import small9 from '@/assets/images/stock/small-9.jpg';
import ComponentCard from '@/components/cards/ComponentCard';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Image from 'next/image';
import Link from 'next/link';
import { Card, CardBody, CardHeader, CardTitle, Carousel, CarouselItem, Col, Container, Row } from 'react-bootstrap';
import { TbChevronRight } from 'react-icons/tb';
const SlidesOnly = () => {
  return <ComponentCard title="Slides Only">
      <Carousel controls={false} indicators={false} id="carouselExampleSlidesOnly" className="carousel slide" data-bs-ride="carousel">
        <CarouselItem className="active">
          <Image className="d-block img-fluid" src={small1} alt="First slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small2} alt="Second slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small3} alt="Third slide" />
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const SlidesWithControls = () => {
  return <ComponentCard title="With Controls">
      <Carousel indicators={false} id="carouselExampleControls" className="slide " data-bs-ride="carousel">
        <CarouselItem className="active">
          <Image className="d-block img-fluid" src={small1} alt="First slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small2} alt="Second slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small3} alt="Third slide" />
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const SlidesWithIndicators = () => {
  return <ComponentCard title="With Indicators">
      <Carousel controls={true} indicators={true} id="carouselExampleControls">
        <CarouselItem className="active">
          <Image className="d-block img-fluid" src={small1} alt="First slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small2} alt="Second slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small3} alt="Third slide" />
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const SlidesWithCaptions = () => {
  return <ComponentCard title="With Indicators">
      <Carousel indicators={true} id="carouselExampleControls" className="slide ">
        <CarouselItem className="active">
          <Image className="d-block img-fluid" src={small1} alt="First slide" />
          <div className="carousel-caption d-none d-md-block">
            <h3 className="text-white">First slide label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small2} alt="Second slide" />
          <div className="carousel-caption d-none d-md-block">
            <h3 className="text-white">Second slide label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small3} alt="Third slide" />
          <div className="carousel-caption d-none d-md-block">
            <h3 className="text-white">Third slide label</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </div>
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const CrossFade = () => {
  return <ComponentCard title="Crossfade">
      <Carousel indicators={false} id="carouselExampleFade" className="slide carousel-fade">
        <CarouselItem className="active">
          <Image className="d-block img-fluid" src={small1} alt="First slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small2} alt="Second slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="d-block img-fluid" src={small3} alt="Third slide" />
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const IndividualInterval = () => {
  return <ComponentCard title="Individual Interval">
      <Carousel indicators={false} id="carouselExampleInterval" className="slide ">
        <CarouselItem className="active" data-bs-interval={1000}>
          <Image className="img-fluid d-block w-100" src={small1} alt="First slide" />
        </CarouselItem>
        <CarouselItem data-bs-interval={2000}>
          <Image className="img-fluid d-block w-100" src={small2} alt="Second slide" />
        </CarouselItem>
        <CarouselItem>
          <Image className="img-fluid d-block w-100" src={small3} alt="Third slide" />
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const DarkVariant = () => {
  return <ComponentCard title="Dark Variant">
      <Carousel id="carouselExampleDark" data-bs-theme="dark" className="carousel-dark slide">
        <CarouselItem className="active" data-bs-interval={1000}>
          <Image className="img-fluid" src={small8} alt="Images" />
          <div className="carousel-caption d-none d-md-block">
            <h5>First slide label</h5>
            <p>Some representative placeholder content for the first slide.</p>
          </div>
        </CarouselItem>
        <CarouselItem data-bs-interval={2000}>
          <Image className="img-fluid" src={small9} alt="Images" />
          <div className="carousel-caption d-none d-md-block">
            <h5>Second slide label</h5>
            <p>Some representative placeholder content for the second slide.</p>
          </div>
        </CarouselItem>
        <CarouselItem>
          <Image className="img-fluid" src={small10} alt="Images" />
          <div className="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Some representative placeholder content for the third slide.</p>
          </div>
        </CarouselItem>
      </Carousel>
    </ComponentCard>;
};
const page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="Carousel" subtitle="UI" />
        <Container fluid="xl">
          <Row>
            <Col xl={12}>
              <Card>
                <CardHeader>
                  <CardTitle as={'h4'}>Examples</CardTitle>
                </CardHeader>
                <CardBody>
                  <p className="text-muted mb-2">A slideshow component for cycling through elements—images or slides of text—like a carousel.</p>
                  <Link className="btn btn-link p-0 fw-semibold" href="https://react-bootstrap.netlify.app/docs/components/carousel/" target="_blank">
                    Carousel on React Bootstrap
                    <TbChevronRight className="ms-1" />
                  </Link>
                </CardBody>
              </Card>
            </Col>
            <Col lg={6}>
              <SlidesOnly />
            </Col>
            <Col lg={6}>
              <SlidesWithControls />
            </Col>
            <Col lg={6}>
              <SlidesWithIndicators />
            </Col>
            <Col lg={6}>
              <SlidesWithCaptions />
            </Col>
            <Col lg={6}>
              <CrossFade />
            </Col>
            <Col lg={6}>
              <IndividualInterval />
            </Col>
            <Col lg={6}>
              <DarkVariant />
            </Col>
          </Row>
        </Container>
      </Container>
    </>;
};
export default page;
