// Angular/Full/src/app/views/ecommerce/products/products/products.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {StatisticWidget1Type} from '@/app/types';
import {StatisticWidget1Component} from '@app/components/widgets/statistic-widget1.component';
import {
    LucideAngularModule,
    LucideBox,
    LucideLayoutGrid,
    LucideList,
    LucidePlus,
    LucideSearch,
    LucideStar,
    LucideTag
} from 'lucide-angular';
import {RouterLink} from '@angular/router';
import {Observable} from 'rxjs';
import {TableService} from '@core/services/table.service';

import {currency} from '@/app/constants';
import {NgIcon} from '@ng-icons/core';
import {toTitleCase} from '@/app/utils/string-utils';
import {RatingComponent} from '@app/components/rating.component';
import {FormsModule} from '@angular/forms';
import {NgbPagination, NgbPaginationNext, NgbPaginationPrevious} from '@ng-bootstrap/ng-bootstrap';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';
import {ProductType} from '@/app/views/ecommerce/products/types';
import {products} from '@/app/views/ecommerce/products/data';
import {AsyncPipe} from '@angular/common';

@Component({
    selector: 'app-products',
    imports: [
        PageTitleComponent,
        StatisticWidget1Component,
        LucideAngularModule,
        RouterLink,
        NgIcon,
        RatingComponent,
        FormsModule,
        NgbPagination,
        NgbdSortableHeader,
        NgbPaginationNext,
        NgbPaginationPrevious,
        AsyncPipe,
    ],
    templateUrl: './products.component.html',
    styles: ``,
    providers:[TableService],
})
export class ProductsComponent implements OnInit {
    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideLayoutGrid = LucideLayoutGrid;
    protected readonly LucideList = LucideList;
    protected readonly LucidePlus = LucidePlus;

    protected readonly currency = currency;
    protected readonly toTitleCase = toTitleCase;

    categoryFilter = "All"
    statusFilter = "All"
    ratingFilter = "All"
    selectAll = false;

    products$: Observable<ProductType[]>
    total$: Observable<number>;

    constructor(public tableService: TableService<ProductType>) {
        this.products$ = this.tableService.items$
        this.total$ = this.tableService.total$
    }

    ngOnInit(): void {
        this.tableService.setItems(products, 8)
    }

    protected readonly LucideTag = LucideTag;
    protected readonly LucideBox = LucideBox;
    protected readonly LucideStar = LucideStar;

    truncateText(text: string, limit: number = 21): string {
        return text.length > limit ? text.substring(0, limit) + '...' : text;
    }


    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    deleteSelected() {
        this.tableService.deleteSelectedItems();
        this.selectAll = false;
    }

    get hasSelection(): boolean {
        return this.tableService.hasSelectedItems();
    }

    widgets: StatisticWidget1Type[] = [
        {
            title: 'Products',
            description: 'Active Listings',
            label: '+24 New',
            icon: 'tablerPackage',
            count: {value: 1240},
            variant: 'primary',
            totalCount: {value: 980}
        },
        {
            title: 'Orders',
            description: 'Total Orders',
            label: '+120 New',
            icon: 'tablerShoppingCart',
            count: {value: 8540},
            variant: 'secondary',
            totalCount: {suffix: 'K', value: 105}
        },
        {
            title: 'Sales',
            description: "Today's Sales",
            label: '+8.2%',
            icon: 'tablerCurrencyDollar',
            count: {prefix: '$', value: 9860},
            variant: 'success',
            totalCount: {prefix: '$', suffix: 'K', value: 156}
        },
        {
            title: 'Customers',
            description: 'Total Customers',
            label: '+36 New',
            icon: 'tablerUsers',
            count: {value: 2945},
            variant: 'info',
            totalCount: {value: 58320}
        },
        {
            title: 'Revenue',
            description: 'Total Customers',
            label: '+4.5 %',
            icon: 'tablerChartBar',
            count: {value: 1.2, prefix: '$', suffix: 'M'},
            variant: 'warning',
            totalCount: {value: 12.8, prefix: '$', suffix: 'M'},
        },
    ];


}

<div class="container-fluid">
    <app-page-title title="Products" subTitle="Ecommerce"/>

    <div class="row row-cols-xxl-5 row-cols-md-3 row-cols-1 align-items-center g-1">
        @for (item of widgets; track $index) {
            <div class="col">
                <app-statistic-widget1 [item]="item" cardClass="mb-1"/>
            </div>
        }
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header border-light justify-content-between">
                    <div class="d-flex gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" data-table-search type="search"
                                   class="form-control"
                                   placeholder="Search product name...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>
                        @if (hasSelection) {
                            <button class="btn btn-danger" (click)="deleteSelected()">Delete</button>
                        }
                    </div>

                    <div class="d-flex align-items-center gap-2">
                        <span class="me-2 fw-semibold">Filter By:</span>

                        <div class="app-search">
                            <select [(ngModel)]="categoryFilter"
                                    (ngModelChange)="tableService.setFilter('category', categoryFilter)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">Category</option>
                                <option value="Electronics">Electronics</option>
                                <option value="Fashion">Fashion</option>
                                <option value="Home">Home</option>
                                <option value="Sports">Sports</option>
                                <option value="Beauty">Beauty</option>
                            </select>
                            <lucide-angular [img]="LucideTag" class="app-search-icon text-muted"/>
                        </div>

                        <div class="app-search">
                            <select [(ngModel)]="statusFilter"
                                    (ngModelChange)="tableService.setFilter('status', statusFilter)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">Status</option>
                                <option value="Published">Published</option>
                                <option value="Pending">Pending</option>
                                <option value="Out of Stock">Out of Stock</option>
                            </select>
                            <lucide-angular [img]="LucideBox" class="app-search-icon text-muted"/>
                        </div>

                        <div class="app-search">
                            <select [(ngModel)]="ratingFilter"
                                    (ngModelChange)="tableService.setFilter('rating', ratingFilter)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">Rating</option>
                                <option value="5">5</option>
                                <option value="4">4</option>
                                <option value="3">3</option>
                                <option value="2">2</option>
                                <option value="1">1</option>
                            </select>
                            <lucide-angular [img]="LucideStar" class="app-search-icon text-muted"/>
                        </div>

                        <div>
                            <select [(ngModel)]="tableService.pageSize" class="form-select form-control my-1 my-md-0">
                                <option [ngValue]="5">5</option>
                                <option [ngValue]="8">8</option>
                                <option [ngValue]="10">10</option>
                                <option [ngValue]="15">15</option>
                                <option [ngValue]="20">20</option>
                            </select>
                        </div>

                    </div>

                    <div class="d-flex gap-1">
                        <a routerLink="/ecommerce/products/grid" class="btn btn-soft-primary btn-icon">
                            <lucide-angular [img]="LucideLayoutGrid" class="fs-lg"/>
                        </a>
                        <a routerLink="/ecommerce/products" class="btn btn-primary btn-icon">
                            <lucide-angular [img]="LucideList" class="fs-lg"/>
                        </a>
                        <a routerLink="/ecommerce/products/add" class="btn btn-danger ms-1">
                            <lucide-angular [img]="LucidePlus" class="fs-sm me-2"/>
                            Add Product
                        </a>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th class="ps-3" style="width: 1%;">
                                <input [(ngModel)]="selectAll"
                                       (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" id="select-all-products" value="option">
                            </th>
                            <th sortable="name" (sort)="tableService.setSort($event.column, $event.direction)">Product
                            </th>
                            <th>SKU</th>
                            <th sortable="category" (sort)="tableService.setSort($event.column, $event.direction)">
                                Category
                            </th>
                            <th sortable="stock" (sort)="tableService.setSort($event.column, $event.direction)">Stock
                            </th>
                            <th sortable="price" (sort)="tableService.setSort($event.column, $event.direction)">Price
                            </th>
                            <th sortable="orders" (sort)="tableService.setSort($event.column, $event.direction)">
                                Orders
                            </th>
                            <th sortable="rating" (sort)="tableService.setSort($event.column, $event.direction)">
                                Rating
                            </th>
                            <th sortable="status" (sort)="tableService.setSort($event.column, $event.direction)">
                                Status
                            </th>
                            <th sortable="date" (sort)="tableService.setSort($event.column, $event.direction)">
                                Published
                            </th>
                            <th class="text-center" style="width: 1%;">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for (product of products$ | async; track $index) {
                                    <tr>
                                        <td class="ps-3">
                                            <input [(ngModel)]="product.selected"
                                                   (change)="toggleSingleSelection()"
                                                   class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                                   type="checkbox" value="option">
                                        </td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="avatar-md me-3">
                                                    <img [src]="product.image" alt="Product" class="img-fluid rounded">
                                                </div>
                                                <div>
                                                    <h5 class="mb-1">
                                                        <a routerLink="/ecommerce/products/{{product.sku}}"
                                                           class="link-reset">{{ truncateText(product.name) }}</a>
                                                    </h5>
                                                    <p class="text-muted mb-0 fs-xxs">by: {{ product.manufacturer }}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{{ product.sku }}</td>
                                        <td>{{ product.category }}</td>
                                        <td>
                                            <h5 class="fs-base mb-0 fw-medium">{{ product.stock }}</h5>
                                        </td>
                                        <td>{{ currency }}{{ product.price }}</td>
                                        <td>{{ product.orders }}</td>
                                        <td>
                                            <app-rating [rate]="product.rating"/>
                                            <span class="ms-1"><a routerLink="/ecommerce/reviews"
                                                                  class="link-reset fw-semibold">({{ product.reviews }}
                                                )</a></span>
                                        </td>
                                        <td>
                                            <span class="badge fs-xxs" [class]="
                                              product.status === 'pending' ? 'badge-soft-warning' :
                                              product.status === 'out-of-stock' ? 'badge-soft-danger' :
                                              'badge-soft-success'
                                            ">{{ toTitleCase(product.status) }}</span></td>
                                        <td>{{ product.date }} <small class="text-muted">{{ product.time }}</small></td>
                                        <td>
                                            <div class="d-flex justify-content-center gap-1">
                                                <a [routerLink]="[]"
                                                   class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon
                                                        name="tablerEye" class="fs-lg"/>
                                                </a>
                                                <a [routerLink]="[]"
                                                   class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon
                                                        name="tablerEdit" class="fs-lg"/>
                                                </a>
                                                <button
                                                    class="btn btn-light btn-icon btn-sm rounded-circle"
                                                    (click)="tableService.deleteItem(product)">
                                                    <ng-icon
                                                        name="tablerTrash" class="fs-lg"/>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="11" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                        <div
                            class="d-flex justify-content-between align-items-center pagination-boxed">
                            <div class="text-muted">
                                {{ tableService.showingRange }} products
                            </div>
                            <ngb-pagination
                                [collectionSize]="(total$ | async)!"
                                [(page)]="tableService.page"
                                [pageSize]="tableService.pageSize"
                            >
                                <ng-template ngbPaginationPrevious>
                                    <ng-icon name="tablerChevronLeft"/>
                                </ng-template>
                                <ng-template ngbPaginationNext>
                                    <ng-icon name="tablerChevronRight"/>
                                </ng-template>
                            </ngb-pagination>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</div>

// Vue/Full/src/views/apps/ecommerce/products/products/index.vue
        <template>
            <MainLayout>
                <BContainer fluid>
                    <PageBreadcrumb title="Products" />
                    <BRow class="row-cols-xxl-5 row-cols-md-3 row-cols-1 align-items-center g-1">

                        <BCol v-for="(stat, index) in statsData" :key="index">
                            <ProductStatisticCard :stat="stat" />
                        </BCol>
                    </BRow>

                    <BRow>
                        <BCol xs="12">
                            <BCard no-body>
                                <BCardHeader class="border-light justify-content-between">

                                    <div class="d-flex gap-2">
                                        <div class="app-search">
                                            <input type="search" class="form-control"
                                                placeholder="Search product name..." v-model="searchQuery">
                                            <Icon  icon="lucide:search" class="app-search-icon text-muted" />
                                        </div>

                                        <BButton v-if="selected.length" variant="danger" @click="handleDeleteSelected">
                                            Delete
                                        </BButton>

                                    </div>

                                    <div class="d-flex align-items-center gap-2">

                                        <span class="me-2 fw-semibold">Filter By:</span>

                                        <div class="app-search">
                                            <select class="form-select form-control my-1 my-md-0">
                                                <option value="All">Category</option>
                                                <option value="Electronics">Electronics</option>
                                                <option value="Fashion">Fashion</option>
                                                <option value="Home">Home</option>
                                                <option value="Sports">Sports</option>
                                                <option value="Beauty">Beauty</option>
                                            </select>
                                            <Icon icon="lucide:tag"  class="app-search-icon text-muted" />
                                        </div>

                                        <div class="app-search">
                                            <select class="form-select form-control my-1 my-md-0">
                                                <option value="">Status</option>
                                                <option value="Published">Published</option>
                                                <option value="Pending">Pending</option>
                                                <option value="Out of Stock">Out of Stock</option>
                                            </select>
                                            <Icon icon="lucide:box"  class="app-search-icon text-muted" />
                                        </div>

                                        <div class="app-search">
                                            <select class="form-select form-control my-1 my-md-0">
                                                <option value="">Price Range</option>
                                                <option value="0-50">$0 - $50</option>
                                                <option value="51-150">$51 - $150</option>
                                                <option value="151-500">$151 - $500</option>
                                                <option value="500+">$500+</option>
                                            </select>
                                            <Icon icon="lucide:dollar-sign" 
                                                class="app-search-icon text-muted" />
                                        </div>

                                        <div>
                                            <BFormSelect v-model="perPage" :options="perPageOptions"
                                                class="form-control my-1 my-md-0" />

                                        </div>

                                    </div>

                                    <div class="d-flex gap-1">
                                        <RouterLink to="/products-grid" class="btn btn-soft-primary btn-icon">
                                            <Icon icon="lucide:layout-grid" class="fs-lg" />
                                        </RouterLink>
                                        <RouterLink to="/products" class="btn btn-primary btn-icon">
                                            <Icon icon="lucide:list" class="fs-lg" />
                                        </RouterLink>
                                        <RouterLink to="/add-product" class="btn btn-danger ms-1">
                                            <Icon icon="lucide:plus" class="fs-sm me-2" /> Add Product
                                        </RouterLink>
                                    </div>
                                </BCardHeader>

                                <BTable show-empty :filter="searchQuery" empty-text="No products found."
                                    v-model:selected-rows="selected"
                                    thead-class="bg-light align-middle bg-opacity-25 thead-sm" hover :fields="fields"
                                    :items="products" :per-page="perPage" :current-page="currentPage"
                                    @filtered="onFiltered" responsive
                                    class="table table-custom table-nowrap table-centered mb-0 w-100">
                                    <template #head()="data">
                                        <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                                    </template>
                                    <template #head(id)>
                                        <input class="form-check-input form-check-input-light fs-14 mt-0"
                                            type="checkbox" id="select-all-products" value="option"
                                            :checked="allSelected" :indeterminate="isIndeterminate"
                                            @change="toggleSelectAll" />
                                    </template>
                                    <template #head(action)>
                                        <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                                    </template>
                                    <template #cell(id)="data">
                                        <input
                                            class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                            type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                            @change="onToggleRow(data.item, $event)" />
                                    </template>
                                    <template #cell(name)="data">
                                        <div class="d-flex">
                                            <div class="avatar-md me-3">
                                                <img :src="data.item.image" alt="Product" class="img-fluid rounded" />
                                            </div>
                                            <div>
                                                <h5 class="mb-1">
                                                    <RouterLink to="/ecommerce/product-details" class="link-reset">{{
                                                        data.item.name
                                                        }}
                                                    </RouterLink>
                                                </h5>
                                                <p class="text-muted mb-0 fs-xxs">by: {{ data.item.brand }}</p>
                                            </div>
                                        </div>
                                    </template>

                                    <template #cell(stock)="data">
                                        <h5 class="fs-base mb-0 fw-medium">{{ data.item.stock }}</h5>
                                    </template>

                                    <template #cell(price)="data">
                                        {{ currency }}{{ data.item.price }}
                                    </template>

                                    <template #cell(rating)="data">
                                        <Rating :rating="data.item.rating"
                                            class="d-inline-flex justify-content-start gap-1" />
                                        <RouterLink to="/ecommerce/reviews" class="link-reset ms-1 fw-semibold">
                                            ({{ data.item.reviews }})</RouterLink>

                                    </template>

                                    <template #cell(status)="data">
                                        <span class="badge fs-xxs"
                                            :class="data.item.status == 'Published' ? 'badge-soft-success' : data.item.status == 'Pending' ? 'badge-soft-warning' : 'badge-soft-danger'">{{
                                                data.item.status }}</span>
                                    </template>

                                    <template #cell(publishDate)="data">
                                        {{ data.item.publishedDate }} <small class="text-muted">{{
                                            data.item.publishedTime
                                            }}</small>
                                    </template>

                                    <template #cell(action)="{ item }">
                                        <div class="d-flex justify-content-center gap-1">
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:eye" class="fs-lg" />
                                            </button>
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:edit" class="fs-lg" />
                                            </button>
                                            <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                <Icon icon="tabler:trash" class="fs-lg"
                                                    @click="handleDeleteItem(item)" />
                                            </button>
                                        </div>
                                    </template>
                                </BTable>

                                <BCardFooter class="border-0">
                                    <div v-if="products.length > 0"
                                        class="d-flex justify-content-between align-items-center">
                                        <span class="text-muted">Showing <span class="fw-semibold">{{ start }}</span> to
                                            <span class="fw-semibold">{{
                                                end }}</span> of <span class="fw-semibold">{{ totalItems
                                                }}</span>
                                            products</span>
                                        <BPagination v-model="currentPage" :total-rows="totalRows" :per-page="perPage"
                                            align="end" first-number last-number class="mb-0 pagination-boxed">
                                            <template #prev-text>
                                                <Icon icon="tabler:chevron-left" />
                                            </template>
                                            <template #next-text>
                                                <Icon icon="tabler:chevron-right" />
                                            </template>
                                        </BPagination>
                                    </div>

                                </BCardFooter>

                            </BCard>

                        </BCol>
                    </BRow>

                </BContainer>
            </MainLayout>
        </template>

<script setup lang="ts">
import { BButton, BCard, BCardHeader, BCol, BContainer, BFormSelect, BPagination, BRow, BTable } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { productData, statsData } from './components/data';
import ProductStatisticCard from './components/ProductStatisticCard.vue';
import type { ProductType } from './components/types';
import { currency } from '@/helpers';
import { computed, ref } from 'vue';
import { useTableActions } from '@/composables/useTableActions';
import { usePageMeta } from '@/composables/usePageMeta';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';


const fields = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Product', sortable: true },
    { key: 'sku', label: 'SKU' },
    { key: 'category', label: 'Category' },
    { key: 'stock', label: 'Stock', sortable: true },
    { key: 'price', label: 'Price', sortable: true },
    { key: 'orders', label: 'Orders', sortable: true },
    { key: 'rating', label: 'Rating', sortable: true },
    { key: 'status', label: 'Status', sortable: true },
    { key: 'publishDate', label: 'Published', sortable: true },
    { key: 'action', label: 'Action', sortable: false },

]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(productData.length)
const products = ref<ProductType[]>(productData)

function onFiltered(filteredItems: ProductType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}


const totalItems = computed(() => products.value.length)

const start = computed(() =>
    totalItems.value === 0 ? 0 : (currentPage.value - 1) * perPage.value + 1
)

const end = computed(() =>
    Math.min(currentPage.value * perPage.value, totalItems.value)
)

function adjustPage() {
    const totalPages = Math.ceil(products.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: ProductType) {
    deleteItem(item)
    totalRows.value = products.value.length
    adjustPage()
}

function handleDeleteSelected() {
    deleteSelected()
    totalRows.value = products.value.length
    adjustPage()
}


const { selected, toggleSelectAll, onToggleRow, deleteSelected, deleteItem, allSelected, isIndeterminate } =
    useTableActions(products)

usePageMeta('Products')
</script>

<style scoped></style>
