// Full/src/views/graphs/apex/slope/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Slope Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Basic Slope">
                        <CustomApexChart :get-options='getBasicSlopeChart' :series='getBasicSlopeChart().series'
                            type="line" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Multi Slope">
                        <CustomApexChart :get-options='getMultiSlopeChart' :series='getMultiSlopeChart().series'
                            type="line" :height='350' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import { getBasicSlopeChart, getMultiSlopeChart } from './data';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';

usePageMeta('Slope ApexCharts')
</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/graphs/apex/slope/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicSlopeChart, getMultiSlopeChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Slope Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Basic Slope">
                            <CustomApexChart getOptions={getBasicSlopeChart} series={getBasicSlopeChart().series} type="line" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Multi Slope">
                            <CustomApexChart getOptions={getMultiSlopeChart} series={getMultiSlopeChart().series} type="line" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
