// Angular/Full/src/app/views/ecommerce/product-reviews/product-reviews.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {NgIcon} from '@ng-icons/core';
import {AsyncPipe} from '@angular/common';
import {
    NgbDropdownModule,
    NgbPagination,
    NgbPaginationNext,
    NgbPaginationPrevious,
    NgbProgressbarModule
} from '@ng-bootstrap/ng-bootstrap';
import {LucideAngularModule, LucideDownload, LucideSearch} from 'lucide-angular';
import {RatingComponent} from '@app/components/rating.component';
import {Observable} from 'rxjs';
import {TableService} from '@core/services/table.service';
import {toTitleCase} from '@/app/utils/string-utils';
import {FormsModule} from '@angular/forms';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';
import {ApexOptions} from 'ng-apexcharts';
import {ApexchartComponent} from '@app/components/apexchart.component';

type ProductReviewType = {
    id: number;
    productName: string;
    image: string
    name: string;
    avatar: string;
    email: string;
    rating: number;
    message: string;
    description: string
    date: string;
    time: string;
    status: 'published' | 'pending'
    selected?: boolean
}

@Component({
    selector: 'app-product-reviews',
    imports: [
        PageTitleComponent,
        NgIcon,
        NgbProgressbarModule,
        NgbDropdownModule,
        LucideAngularModule,
        RatingComponent,
        FormsModule,
        NgbPagination,
        NgbPaginationNext,
        NgbPaginationPrevious,
        NgbdSortableHeader,
        ApexchartComponent,
        AsyncPipe
    ],
    providers: [TableService],
    templateUrl: './product-reviews.component.html',
    styles: ``
})
export class ProductReviewsComponent implements OnInit {
    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideDownload = LucideDownload;

    productReviews$: Observable<ProductReviewType[]>
    total$: Observable<number>;

    constructor(public tableService: TableService<ProductReviewType>) {
        this.productReviews$ = this.tableService.items$
        this.total$ = this.tableService.total$
    }

    ngOnInit(): void {
        this.tableService.setItems(this.productReviews, 5)
    }

    selectAll = false;

    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    deleteSelected() {
        this.tableService.deleteSelectedItems();
        this.selectAll = false;
    }

    get hasSelection(): boolean {
        return this.tableService.hasSelectedItems();
    }


    productReviews: ProductReviewType[] = [
        {
            id: 1,
            productName: 'Wireless Earbuds',
            image: 'assets/images/products/2.png',
            name: 'Sophia Lee',
            avatar: 'assets/images/users/user-8.jpg',
            email: 'sophia.lee@digitalshop.com',
            rating: 5,
            message: 'Great product, would buy again!',
            description: 'These earbuds are amazing, the sound quality is top-notch. Totally worth the price!',
            date: '22 Apr, 2025',
            time: '04:10 PM',
            status: 'published'
        },
        {
            id: 2,
            productName: 'Smart Watch',
            image: 'assets/images/products/3.png',
            name: 'David Smith',
            avatar: 'assets/images/users/user-6.jpg',
            email: 'david.smith@healthstore.com',
            rating: 4.5,
            message: 'Decent, but overpriced',
            description: "It does the job, but I feel like it's a little expensive for what it offers.",
            date: '23 Apr, 2025',
            time: '02:20 PM',
            status: 'pending'
        },
        {
            id: 3,
            productName: '4K Ultra HD TV',
            image: 'assets/images/products/4.png',
            name: 'Alice Johnson',
            avatar: 'assets/images/users/user-3.jpg',
            email: 'alice.johnson@homesupplies.com',
            rating: 5,
            message: 'Amazing quality!',
            description: 'The TV has incredible picture quality. Totally worth the investment!',
            date: '24 Apr, 2025',
            time: '09:15 AM',
            status: 'published'
        },
        {
            id: 4,
            productName: 'Smartphone X',
            image: 'assets/images/products/5.png',
            name: 'Michael Green',
            avatar: 'assets/images/users/user-2.jpg',
            email: 'michael.green@mobileshop.com',
            rating: 5,
            message: 'Perfect phone, highly recommended!',
            description: 'The camera is amazing and the performance is smooth. Definitely the best smartphone I have used!',
            date: '25 Apr, 2025',
            time: '11:30 AM',
            status: 'published'
        },
        {
            id: 5,
            productName: 'Gaming Laptop',
            image: 'assets/images/products/6.png',
            name: 'Chris Evans',
            avatar: 'assets/images/users/user-4.jpg',
            email: 'chris.evans@gamestore.com',
            rating: 4.5,
            message: 'Great for gaming but heavy',
            description: "The performance is amazing, but it's a bit too heavy to carry around all day.",
            date: '26 Apr, 2025',
            time: '10:00 AM',
            status: 'pending'
        }
    ];


    reviews: { progress: number, count: number }[] = [
        {
            progress: 85,
            count: 128,
        },
        {
            progress: 15,
            count: 37,
        },
        {
            progress: 10,
            count: 15,
        },
        {
            progress: 7,
            count: 7,
        },
        {
            progress: 2,
            count: 2,
        },
    ]
    protected readonly toTitleCase = toTitleCase;


 reviewChartOptions: () => ApexOptions = () => ({
     chart: {
         type: 'area',
         height: 185,
         toolbar: {show: false}
     },
     grid: {
         padding: {
             top: 0,
             right: 0,
             bottom: 0,
             left: 0
         }
     },
     series: [{
         name: 'Reviews',
         data: [5, 8, 6, 7, 10, 12, 9, 14, 11, 15, 17, 19, 14, 13, 16, 18, 22, 20, 19, 17, 15, 18, 20, 23, 21, 22, 24, 26, 25, 28]
     }],
     xaxis: {
         categories: Array.from({length: 30}, (_, i) => `${i + 1}`),
         labels: {
             rotate: -45,
             style: {
                 fontSize: '10px'
             }
         }
     },
     colors: ['#1ab394'],
     fill: {
         opacity: 0.3,
     },
     stroke: {
         curve: 'smooth',
         width: 2
     },
     dataLabels: {
         enabled: false
     },
     tooltip: {
         y: {
             formatter: function (val) {
                 return `${val} Reviews`;
             }
         }
     }
 })
}

<div class="container-fluid">
    <app-page-title title="Reviews" subTitle="Ecommerce"/>

    <div class="row justify-content-center">
        <div class="col-xxl-10">
            <div class="card">
                <div class="card-header p-0 d-block">
                    <div class="row g-0 align-items-center">
                        <div class="col-xl-6 border-end border-dashed">
                            <div class="row align-items-center g-0">
                                <div class="col-xl-7">
                                    <div class="d-flex align-items-center gap-4 p-4">
                                        <img src="assets/images/ratings.svg" alt="Product" height="80">
                                        <div>
                                            <h3 class="text-primary d-flex align-items-center gap-2 mb-2 fw-bold">
                                                4.92
                                                <ng-icon name="tablerStarFill"/>
                                            </h3>
                                            <p class="mb-2">Based on 245 verified reviews</p>
                                            <p class="pe-2 h6 text-muted mb-2 lh-base">Feedback collected from real
                                                customers who purchased our templates</p>
                                            <span class="badge badge-label text-bg-success">+12 new this week</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-5">
                                    <div class="p-3">
                                        @for (review of reviews; track $index; let index = $index; let last = $last) {
                                            <div class="d-flex align-items-center gap-2 {{!last ? 'mb-2' : ''}}">
                                                <div class="flex-shrink-0"
                                                     style="width: 50px;">{{ reviews.length - index }}
                                                    Star
                                                </div>
                                                <ngb-progressbar class="w-100" [value]="review.progress" type="primary"
                                                                 style="height: 8px"/>

                                                <div class="flex-shrink-0 text-end"
                                                     style="width: 30px;"><span
                                                    class="badge text-bg-light">{{ review.count }}</span></div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="pe-3 ps-1">
                                <app-apexchart [getOptions]="reviewChartOptions"/>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card-header border-light d-flex align-items-center justify-content-between flex-wrap gap-2">

                    <div class="d-flex gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" class="form-control"
                                   placeholder="Search reviews...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>
                        @if (hasSelection) {
                            <button class="btn btn-danger" (click)="deleteSelected()">Delete</button>
                        }

                    </div>

                    <div class="d-flex align-items-center gap-2">

                        <div>
                            <select [(ngModel)]="tableService.pageSize" class="form-select form-control my-1 my-md-0">
                                <option [ngValue]="5">5</option>
                                <option [ngValue]="10">10</option>
                                <option [ngValue]="15">15</option>
                                <option [ngValue]="20">20</option>
                            </select>
                        </div>

                        <div ngbDropdown>
                            <button class="btn btn-default dropdown-toggle drop-arrow-none" type="button"
                                    ngbDropdownToggle>
                                <lucide-angular [img]="LucideDownload" class="me-1"/>
                                Export
                                <ng-icon
                                    name="tablerChevronDown" class="ms-1"/>
                            </button>
                            <ul class="dropdown-menu-end" ngbDropdownMenu>
                                <li><a ngbDropdownItem>Export as PDF</a></li>
                                <li><a ngbDropdownItem>Export as CSV</a></li>
                                <li><a ngbDropdownItem>Export as Excel</a></li>
                            </ul>
                        </div>

                        <div ngbDropdown>
                            <button class="btn btn-default dropdown-toggle drop-arrow-none" type="button"
                                    ngbDropdownToggle>
                                View All
                                <ng-icon name="tablerChevronDown" class="ms-1"/>
                            </button>
                            <ul class="dropdown-menu-end" ngbDropdownMenu>
                                <li><a ngbDropdownItem>All</a></li>
                                <li><a ngbDropdownItem>Pending</a></li>
                                <li><a ngbDropdownItem>Approved</a></li>
                                <li><a ngbDropdownItem>Disabled</a></li>
                            </ul>
                        </div>

                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light align-middle bg-opacity-25">
                        <tr class="text-uppercase fs-xxs">
                            <th class="ps-3" style="width: 1%;">
                                <input [(ngModel)]="selectAll" (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" id="select-all-products" value="option">
                            </th>
                            <th sortable="productName" (sort)="tableService.setSort($event.column, $event.direction)">
                                Product
                            </th>
                            <th sortable="name" (sort)="tableService.setSort($event.column, $event.direction)">
                                Reviewer
                            </th>
                            <th style="width: 18rem;">Review</th>
                            <th sortable="date" (sort)="tableService.setSort($event.column, $event.direction)">Date</th>
                            <th sortable="status" (sort)="tableService.setSort($event.column, $event.direction)">
                                Status
                            </th>
                            <th class="text-center" style="width: 1%;">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for (review of productReviews$ | async; track $index) {
                                    <tr>
                                        <td class="ps-3">
                                            <input [(ngModel)]="review.selected" (change)="toggleSingleSelection()"
                                                   type="checkbox"
                                                   class="form-check-input form-check-input-light fs-14 mt-0"/>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="avatar-lg me-3">
                                                    <img [src]="review.image" [alt]="review.productName"
                                                         class="img-fluid rounded"/>
                                                </div>
                                                <div>
                                                    <h5 class="mb-0">{{ review.productName }}</h5>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <img [src]="review.avatar" [alt]="review.name"
                                                     class="avatar-sm rounded-circle"/>
                                                <div>
                                                    <h5 class="fs-sm mb-0">{{ review.name }}</h5>
                                                    <p class="text-muted fs-xs mb-0">{{ review.email }}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-warning fs-lg">
                                                <app-rating [rate]="review.rating" size="16"/>
                                            </div>
                                            <h5 class="mt-2 mb-1">{{ review.message }}</h5>
                                            <p class="text-muted fst-italic mb-0">"{{ review.description }}"</p>
                                        </td>
                                        <td>{{ review.date }} <small class="text-muted">{{ review.time }}</small></td>
                                        <td>
                                <span
                                    class="badge fs-xxs"
                                    [class]="review.status === 'pending' ? 'badge-soft-warning' : 'badge-soft-success'">
                                  {{ toTitleCase(review.status) }}
                                </span>
                                        </td>
                                        <td class="text-center">
                                            <div class="d-flex justify-content-center gap-1">
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon
                                                        name="tablerEye" class="fs-lg"/>
                                                </button>
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon
                                                        name="tablerEdit" class="fs-lg"/>
                                                </button>
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle"
                                                        (click)="tableService.deleteItem(review)">
                                                    <ng-icon
                                                        name="tablerTrash" class="fs-lg"/>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="11" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                        <div
                            class="d-flex justify-content-between pagination-boxed align-items-center">
                            {{ tableService.showingRange }} reviews
                            <ngb-pagination
                                [collectionSize]="(total$ | async)!"
                                [(page)]="tableService.page"
                                [pageSize]="tableService.pageSize"
                            >
                                <ng-template ngbPaginationPrevious>
                                    <ng-icon name="tablerChevronLeft"/>
                                </ng-template>
                                <ng-template ngbPaginationNext>
                                    <ng-icon name="tablerChevronRight"/>
                                </ng-template>
                            </ngb-pagination>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>

</div>

// React/Full/JS/src/views/ecommerce/reviews/components/ProductReviews.jsx
import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import clsx from 'clsx';
import { Button, Card, CardFooter, CardHeader, Col, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, ProgressBar, Row } from 'react-bootstrap';
import { Link } from 'react-router';
import { useState } from 'react';
import { LuChevronDown, LuDownload, LuSearch } from 'react-icons/lu';
import { TbChevronDown, TbEdit, TbEye, TbStarFilled, TbTrash } from 'react-icons/tb';
import Rating from '@/components/Rating';
import DataTable from '@/components/table/DataTable';
import DeleteConfirmationModal from '@/components/table/DeleteConfirmationModal';
import TablePagination from '@/components/table/TablePagination';
import { toPascalCase } from '@/helpers/casing';
import ratingsImg from '@/assets/images/ratings.svg';
import { getReviewChartOptions, productReviews, reviews } from '../data';
import CustomApexChart from '@/components/CustomApexChart';
const columnHelper = createColumnHelper();
const ProductReviews = () => {
  const columns = [{
    id: 'select',
    maxSize: 45,
    size: 45,
    header: ({
      table
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()} />,
    cell: ({
      row
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} />,
    enableSorting: false,
    enableColumnFilter: false
  }, columnHelper.accessor('productName', {
    header: 'Product',
    cell: ({
      row
    }) => <div className="d-flex align-items-center">
          <div className="avatar-lg me-3">
            <img src={row.original.image} alt="Product" className="img-fluid rounded" />
          </div>
          <div>
            <h5 className="mb-0">
              <Link to="/ecommerce/products/1" className="link-reset">
                {row.original.productName}
              </Link>
            </h5>
          </div>
        </div>
  }), columnHelper.accessor('name', {
    header: 'Reviewer',
    cell: ({
      row
    }) => <div className="d-flex justify-content-start align-items-center gap-2">
          <div className="avatar avatar-sm">
            <img src={row.original.avatar} alt="avatar-8" className="img-fluid rounded-circle" />
          </div>
          <div>
            <h5 className="text-nowrap fs-sm mb-0 lh-base">{row.original.name}</h5>
            <p className="text-muted fs-xs mb-0">{row.original.email}</p>
          </div>
        </div>
  }), columnHelper.accessor('rating', {
    header: 'Review',
    cell: ({
      row
    }) => <>
          <Rating rating={row.original.rating} className="fs-lg" />

          <h5 className="mt-2">{row.original.message}</h5>
          <p className="text-muted fst-italic mb-0">"{row.original.description}"</p>
        </>,
    enableSorting: false
  }), columnHelper.accessor('date', {
    header: 'Last Updated',
    cell: ({
      row
    }) => <>
          {row.original.date} <small className="text-muted">{row.original.time}</small>
        </>
  }), columnHelper.accessor('status', {
    header: 'Status',
    filterFn: 'equalsString',
    enableColumnFilter: true,
    cell: ({
      row
    }) => <span className={`badge ${row.original.status === 'pending' ? 'badge-soft-warning' : 'badge-soft-success'} fs-xxs`}>
          {toPascalCase(row.original.status)}
        </span>
  }), {
    header: 'Actions',
    cell: ({
      row
    }) => <div className="d-flex justify-content-center gap-1">
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbEye className="fs-lg" />
          </Button>
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbEdit className="fs-lg" />
          </Button>
          <Button variant="light" size="sm" className="btn-icon rounded-circle" onClick={() => {
        toggleDeleteModal();
        setSelectedRowIds({
          [row.id]: true
        });
      }}>
            <TbTrash className="fs-lg" />
          </Button>
        </div>
  }];
  const [data, setData] = useState(() => [...productReviews]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [sorting, setSorting] = useState([]);
  const [columnFilters, setColumnFilters] = useState([]);
  const [pagination, setPagination] = useState({
    pageIndex: 0,
    pageSize: 5
  });
  const [selectedRowIds, setSelectedRowIds] = useState({});
  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
      globalFilter,
      columnFilters,
      pagination,
      rowSelection: selectedRowIds
    },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    onColumnFiltersChange: setColumnFilters,
    onPaginationChange: setPagination,
    onRowSelectionChange: setSelectedRowIds,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    globalFilterFn: 'includesString',
    enableColumnFilters: true,
    enableRowSelection: true
  });
  const pageIndex = table.getState().pagination.pageIndex;
  const pageSize = table.getState().pagination.pageSize;
  const totalItems = table.getFilteredRowModel().rows.length;
  const start = pageIndex * pageSize + 1;
  const end = Math.min(start + pageSize - 1, totalItems);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const toggleDeleteModal = () => {
    setShowDeleteModal(!showDeleteModal);
  };
  const handleDelete = () => {
    const selectedIds = new Set(Object.keys(selectedRowIds));
    setData(old => old.filter((_, idx) => !selectedIds.has(idx.toString())));
    setSelectedRowIds({});
    setPagination({
      ...pagination,
      pageIndex: 0
    });
    setShowDeleteModal(false);
  };
  const statusFilterValue = table.getColumn('status')?.getFilterValue() ?? 'All';
  const handleStatusChange = value => {
    table.getColumn('status')?.setFilterValue(value === 'All' ? undefined : value);
  };
  return <Card>
      <CardHeader className="p-0 d-block">
        <Row className="g-0 align-items-center">
          <Col xl={6} className="border-end border-dashed">
            <Row className="align-items-center g-0">
              <Col xl={7}>
                <div className="d-flex align-items-center gap-4 p-4">
                  <img src={ratingsImg} alt="Product" height={80} />
                  <div>
                    <h3 className="text-primary d-flex align-items-center gap-2 mb-2 fw-bold">
                      4.92 <TbStarFilled />
                    </h3>
                    <p className="mb-2">Based on 245 verified reviews</p>
                    <p className="pe-2 h6 text-muted mb-2 lh-base">Feedback collected from real customers who purchased our templates</p>
                    <span className="badge badge-label text-bg-success">+12 new this week</span>
                  </div>
                </div>
              </Col>
              <Col xl={5}>
                <div className="p-3">
                  {reviews.map((review, idx) => {
                  return <div key={idx} className={clsx('d-flex align-items-center gap-2', {
                    'mb-2': idx != reviews.length - 1
                  })}>
                        <div className="flex-shrink-0" style={{
                      width: 50
                    }}>
                          {reviews.length - idx} Star
                        </div>
                        <ProgressBar now={review.progress} variant="primary" className="w-100" style={{
                      height: 8
                    }} />
                        <div className="flex-shrink-0 text-end" style={{
                      width: 30
                    }}>
                          <span className="badge text-bg-light">{review.count}</span>
                        </div>
                      </div>;
                })}
                </div>
              </Col>
            </Row>
          </Col>
          <Col xl={6}>
            <div className="pe-3 ps-1">
              <CustomApexChart getOptions={getReviewChartOptions} series={getReviewChartOptions().series} type="area" height={185} />
            </div>
          </Col>
        </Row>
      </CardHeader>
      <CardHeader className="border-light d-flex align-items-center justify-content-between flex-wrap gap-2">
        <div className="d-flex gap-2">
          <div className="app-search">
            <input type="search" value={globalFilter ?? ''} onChange={e => setGlobalFilter(e.target.value)} className="form-control" placeholder="Search reviews..." />
            <LuSearch className="app-search-icon text-muted" />
          </div>
          {Object.keys(selectedRowIds).length > 0 && <Button variant="danger" onClick={toggleDeleteModal}>
              Delete
            </Button>}
        </div>
        <div className="d-flex align-items-center gap-2">
          <div>
            <select value={table.getState().pagination.pageSize} onChange={e => table.setPageSize(Number(e.target.value))} className="form-select form-control my-1 my-md-0">
              {[5, 10, 15, 20].map(size => <option key={size} value={size}>
                  {size}
                </option>)}
            </select>
          </div>

          <Dropdown>
            <DropdownToggle className="btn btn-default dropdown-toggle drop-arrow-none" type="button">
              <LuDownload className="me-1" /> Export <LuChevronDown className="align-middle ms-1" />
            </DropdownToggle>
            <DropdownMenu className="dropdown-menu-end">
              <DropdownItem>Export as PDF</DropdownItem>
              <DropdownItem>Export as CSV</DropdownItem>
              <DropdownItem>Export as Excel</DropdownItem>
            </DropdownMenu>
          </Dropdown>

          <Dropdown>
            <DropdownToggle className="btn btn-default  drop-arrow-none" type="button">
              {statusFilterValue === 'All' ? 'View All' : statusFilterValue} <TbChevronDown className="align-middle ms-1" />
            </DropdownToggle>
            <DropdownMenu className="dropdown-menu-end">
              {['All', 'Pending', 'Published', 'disabled'].map(option => <Dropdown.Item as="button" key={option} active={statusFilterValue === option} onClick={() => handleStatusChange(option)}>
                  {option}
                </Dropdown.Item>)}
            </DropdownMenu>
          </Dropdown>
        </div>
      </CardHeader>
      <DataTable table={table} emptyMessage="No records found" />
      {table.getRowModel().rows.length > 0 && <CardFooter className="border-0">
          <TablePagination totalItems={totalItems} start={start} end={end} itemsName="reviews" showInfo previousPage={table.previousPage} canPreviousPage={table.getCanPreviousPage()} pageCount={table.getPageCount()} pageIndex={table.getState().pagination.pageIndex} setPageIndex={table.setPageIndex} nextPage={table.nextPage} canNextPage={table.getCanNextPage()} />
        </CardFooter>}
      <DeleteConfirmationModal show={showDeleteModal} onHide={toggleDeleteModal} onConfirm={handleDelete} selectedCount={Object.keys(selectedRowIds).length} itemName="row" />
    </Card>;
};
export default ProductReviews;
