// src/layouts/components/navbar/index.vue
<template>
  <header class="topnav">
    <nav class="navbar navbar-expand-lg">
      <BContainer fluid>
        <div class="navbar-collapse">
          <AppMenu />
        </div>
      </BContainer>
    </nav>
  </header>
</template>

<script setup lang="ts">
import AppMenu from '@/layouts/components/navbar/components/AppMenu.vue'
</script>

// SvelteKit/Seed/src/lib/layouts/components/navbar/index.svelte
<script lang="ts">
	import { Container } from '@sveltestrap/sveltestrap';
	import AppMenu from '$lib/layouts/components/navbar/components/AppMenu.svelte';
</script>

<header class="topnav">
	<nav class="navbar navbar-expand-lg">
		<Container fluid>
			<div class="navbar-collapse">
				<AppMenu />
			</div>
		</Container>
	</nav>
</header>
