// Nuxt/Full/pages/(apps)/(ecommerce)/sellers/[id]/components/SellerStatisticWidget.vue
<template>
    <BCard no-body :class="`border-0 bg-${item.variant} bg-opacity-10`">
        <BCardBody>
            <h5 :title="`Number of Orders`">{{ item.title }}</h5>

            <div class="d-flex align-items-center gap-2 my-3">
                <div class="avatar-md flex-shrink-0">
                    <span :class="`avatar-title text-bg-${item.variant} bg-opacity-90 rounded-circle fs-22`">
                        <Icon :name="item.icon" />
                    </span>
                </div>
                <h3 class="mb-0">
                    {{ item.count.prefix || '' }}{{ item.count.value }}{{ item.count.suffix || '' }}
                </h3>
            </div>

            <p class="mb-0">
                <span :class="`text-${item.variant}`">
                    <Icon name="tabler:point-filled" class="me-1" />
                </span>
                <span class="text-nowrap text-muted">{{ item.description }}</span>
                <span class="float-end">
                    <b>{{ item.totalCount }}</b>
                </span>
            </p>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody } from 'bootstrap-vue-next'
import type { Widget1Type } from './types';

defineProps<{ item: Widget1Type }>()
</script>

// NextJs/NextJs/Full/TS/src/app/(admin)/(apps)/(ecommerce)/sellers/[sellerId]/components/SellerStatisticWidget.tsx
import { Widget1Type } from '@/app/(admin)/widgets/types'
import { Card, CardBody } from 'react-bootstrap'
import { TbPointFilled } from 'react-icons/tb'

const SellerStatisticWidget = ({ item }: { item: Widget1Type }) => {
  const { title, icon: Icon, totalCount, count, variant, description } = item
  return (
    <Card className={`border-0 bg-${variant} bg-opacity-10`}>
      <CardBody>
        <h5 title="Number of Orders">{title}</h5>
        <div className="d-flex align-items-center gap-2 my-3">
          <div className="avatar-md flex-shrink-0">
            <span className={`avatar-title text-bg-${variant} bg-opacity-90 rounded-circle fs-22`}>
              <Icon />
            </span>
          </div>
          <h3 className="mb-0">
            {count.prefix && count.prefix}
            {count.value}
            {count.suffix && count.suffix}
          </h3>
        </div>
        <p className="mb-0">
          <span className={`text-${variant}`}>
            <TbPointFilled className="me-1" />
          </span>
          <span className="text-nowrap text-muted">{description}</span>
          <span className="float-end">
            <b>{totalCount}</b>
          </span>
        </p>
      </CardBody>
    </Card>
  )
}

export default SellerStatisticWidget
