// SvelteKit/Seed/src/lib/components/Rating.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';

	export let rating: number;
	export let height: number | string = 16;
	export let width: number | string = 16;
	export let className: string = '';
	export let style: string = '';

	const fullStars = Math.floor(rating);
	const halfStar = rating % 1 !== 0;
	const emptyStars = 5 - fullStars - (halfStar ? 1 : 0);
</script>

<span class="text-warning d-flex justify-content-center align-items-center {className}" {style}>
	{#each [...Array(fullStars)] as _, i ('filled' + i)}
		<Icon icon="tabler:star-filled" {height} {width} />
	{/each}

	{#if halfStar}
		<Icon icon="tabler:star-half-filled" {height} {width} />
	{/if}

	{#each [...Array(emptyStars)] as _, i ('empty' + i)}
		<Icon icon="tabler:star" {height} {width} />
	{/each}
</span>

// Seed/src/components/Rating.vue
<template>
  <span class="text-warning d-flex justify-content-center align-items-center" v-bind="$attrs">
    <Icon
      v-for="(_, i) in [...Array(fullStars)]"
      :key="`full-${i}`"
      icon="tabler:star-filled"
      :size="size"
    />

    <Icon v-if="halfStar" icon="tabler:star-half-filled" :size="size" />

    <Icon
      v-for="(_, i) in [...Array(emptyStars)]"
      :key="`empty-${i}`"
      icon="tabler:star"
      :size="size"
    />
  </span>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'

type PropsType = {
  rating: number
  size?: number | string
}

const props = defineProps<PropsType>()

const fullStars = Math.floor(props.rating)
const halfStar = props.rating % 1 !== 0
const emptyStars = 5 - fullStars - (halfStar ? 1 : 0)
</script>
