// Nuxt/Full/pages/(apps)/(projects)/activity-stream/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Activity Stream" subtitle="Projects" />

        <BRow>
            <BCol xxl="6">
                <BasicActivity />
            </BCol>

            <BCol xxl="6">
                <ExpandedActivity />
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import BasicActivity from './components/BasicActivity.vue';
import ExpandedActivity from './components/ExpandedActivity.vue';

usePageTitle('Activity Stream')
</script>

<style scoped></style>

// React/Full/JS/src/views/apps/projects/activity-stream/index.jsx
import { Col, Container, Row } from 'react-bootstrap';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import BasicActivity from '@/views/apps/projects/activity-stream/components/BasicActivity';
import ExpandedActivity from '@/views/apps/projects/activity-stream/components/ExpandedActivity';
const Page = () => {
  return <Container fluid>
      <PageBreadcrumb title="Activity Stream" subtitle="Projects" />

      <Row>
        <Col xxl={6}>
          <BasicActivity />
        </Col>

        <Col xxl={6}>
          <ExpandedActivity />
        </Col>
      </Row>
    </Container>;
};
export default Page;
