// React-Inertia/Full/resources/js/pages/graphs/apex/funnel/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicFunnelChart, getPyramidFunnelChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Funnel Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Basic Funnel">
                            <CustomApexChart getOptions={getBasicFunnelChart} series={getBasicFunnelChart().series} type="bar" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Pyramid Funnel">
                            <CustomApexChart getOptions={getPyramidFunnelChart} series={getPyramidFunnelChart().series} type="bar" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page

// Full/src/views/graphs/apex/funnel/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Funnel Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Basic Funnel">
                        <CustomApexChart :get-options='getBasicFunnelChart' :series='getBasicFunnelChart().series'
                            type="bar" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Pyramid Funnel">
                        <CustomApexChart :get-options='getPyramidFunnelChart' :series='getPyramidFunnelChart().series'
                            type="bar" :height='350' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import { getBasicFunnelChart, getPyramidFunnelChart } from './data';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';

usePageMeta('Apex Funnel Charts')
</script>

<style scoped></style>
