// Full/src/views/graphs/apex/boxplot/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Boxplot Apexchart" subtitle="Charts" />
            <BRow>
                <BCol xl='6'>
                    <UICard title="Basic Boxplot">
                        <CustomApexChart :get-options='getBasicBoxplotChart' :series='getBasicBoxplotChart().series'
                            type="boxPlot" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Scatter Boxplot">
                        <CustomApexChart :get-options='getScatterBoxplotChart' :series='getScatterBoxplotChart().series'
                            type="boxPlot" :height='350' />
                    </UICard>
                </BCol>
                <BCol xl='6'>
                    <UICard title="Horizontal BoxPlot">
                        <CustomApexChart :get-options='getHorizontalBoxplotChart'
                            :series='getHorizontalBoxplotChart().series' type="boxPlot" :height='350' />
                    </UICard>
                </BCol>
            </BRow>
        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '@/components/CustomApexChart.vue';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import { getBasicBoxplotChart, getHorizontalBoxplotChart, getScatterBoxplotChart } from './data';
import MainLayout from '@/layouts/MainLayout.vue';
import { usePageMeta } from '@/composables/usePageMeta';

usePageMeta('Boxplot Apex Charts')
</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/graphs/apex/boxplot/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicBoxplotChart, getHorizontalBoxplotChart, getScatterBoxplotChart } from './data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Boxplot Apexchart" subtitle="Charts" />
                <Row>
                    <Col xl={6}>
                        <ComponentCard title="Basic Boxplot">
                            <CustomApexChart getOptions={getBasicBoxplotChart} series={getBasicBoxplotChart().series} type="boxPlot" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Scatter Boxplot">
                            <CustomApexChart getOptions={getScatterBoxplotChart} series={getScatterBoxplotChart().series} type="boxPlot" height={350} />
                        </ComponentCard>
                    </Col>
                    <Col xl={6}>
                        <ComponentCard title="Horizontal BoxPlot">
                            <CustomApexChart getOptions={getHorizontalBoxplotChart} series={getHorizontalBoxplotChart().series} type="boxPlot" height={350} />
                        </ComponentCard>
                    </Col>
                </Row>
            </Container>
        </MainLayout>
    )
}

export default Page
