// React/Full/TS/src/views/graphs/apex/scatter/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import CustomApexChart from '@/components/CustomApexChart.tsx'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'
import { getBasicScatter, getDateTimeScatterChart, getImageScatterChart } from './data'

const Page = () => {
  return (
    <Container fluid>
      <PageBreadcrumb title="Scatter Apexchart" subtitle="Charts" />
      <Row>
        <Col xl={6}>
          <ComponentCard title="Scatter (XY) Chart">
            <CustomApexChart getOptions={getBasicScatter} series={getBasicScatter().series} type="scatter" height={380} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Scatter Chart - Datetime">
            <CustomApexChart getOptions={getDateTimeScatterChart} series={getDateTimeScatterChart().series} type="scatter" height={380} />
          </ComponentCard>
        </Col>
      </Row>
      <Row>
        <Col xl={6}>
          <ComponentCard title="Scatter - Images">
            <CustomApexChart getOptions={getImageScatterChart} series={getImageScatterChart().series} type="scatter" height={380} />
          </ComponentCard>
        </Col>
      </Row>
    </Container>
  )
}

export default Page

// Nuxt/Full/pages/graphs/apex/scatter/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Scatter Apexchart" subtitle="Charts" />
        <BRow>
            <BCol xl='6'>
                <UICard title="Scatter (XY) Chart">
                    <CustomApexChart :get-options='getBasicScatter' :series='getBasicScatter().series' type="scatter"
                        :height='380' />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Scatter Chart - Datetime">
                    <CustomApexChart :get-options='getDateTimeScatterChart' :series='getDateTimeScatterChart().series'
                        type="scatter" :height='380' />
                </UICard>
            </BCol>
        </BRow>
        <BRow>
            <BCol xl='6'>
                <UICard title="Scatter - Images">
                    <CustomApexChart :get-options='getImageScatterChart' :series='getImageScatterChart().series'
                        type="scatter" :height='380' />
                </UICard>
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomApexChart from '~/components/CustomApexChart.vue';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import UICard from '~/components/UICard.vue';
import { getBasicScatter, getDateTimeScatterChart, getImageScatterChart } from './data';

usePageTitle('Scatter ApexCharts')
</script>

<style scoped></style>
