// NextJs/NextJs/Full/JS/src/app/(admin)/(apps)/(projects)/activity-stream/components/ExpandedActivity.jsx
import { expandedActivities } from '@/app/(admin)/(apps)/(projects)/activity-stream/data';
import Image from 'next/image';
import Link from 'next/link';
import { Card, CardBody, CardHeader } from 'react-bootstrap';
export const ExpandedActivity = () => {
  return <Card className="card-h-100">
      <CardHeader>
        <h4 className="card-title">Expanded Activity Stream</h4>
      </CardHeader>
      <CardBody>
        <div className="timeline timeline-icon-bordered">
          {expandedActivities.map((event, idx) => {
          const Icon = event.icon;
          return <div className="timeline-item d-flex align-items-stretch" key={idx}>
                <div className="timeline-dot">
                  <Icon className={`fs-xl text-${event.variant}`} />
                </div>
                <div className="timeline-content ps-3 pb-3">
                  <div className="d-flex justify-content-between">
                    <h5 className="mb-1">
                      {event.title}
                      <span className={`badge badge-label badge-soft-${event.variant} ms-2`}>{event.label}</span>
                    </h5>
                    <span className="text-muted fs-xs">{event.time}</span>
                  </div>
                  <p className="mb-1 text-muted">{event.description}</p>
                  <div className="d-flex align-items-center gap-2">
                    <Image src={event.avatar} alt={event.name} className="rounded-circle avatar-xxs" />
                    <Link href={event.profileUrl} className="fw-semibold link-reset">
                      {event.name}
                    </Link>
                  </div>
                </div>
              </div>;
        })}
        </div>
      </CardBody>
    </Card>;
};
export default ExpandedActivity;

// Nuxt/Full/pages/(apps)/(projects)/activity-stream/components/ExpandedActivity.vue
<template>
    <BCard no-body class="card-h-100">
        <BCardHeader>
            <h4 class="card-title">Expanded Activity Stream</h4>
        </BCardHeader>
        <BCardBody>
            <div class="timeline timeline-icon-bordered">
                <div v-for="(event, idx) in expandedActivities" :key="idx"
                    class="timeline-item d-flex align-items-stretch">
                    <div class="timeline-dot">
                        <Icon :name="event.icon" :class="`fs-xl text-${event.variant}`" />
                    </div>

                    <div class="timeline-content ps-3 pb-3">
                        <div class="d-flex justify-content-between">
                            <h5 class="mb-1">
                                {{ event.title }}
                                <span :class="`badge badge-label badge-soft-${event.variant} ms-2`">
                                    {{ event.label }}
                                </span>
                            </h5>
                            <span class="text-muted fs-xs">{{ event.time }}</span>
                        </div>

                        <p class="mb-1 text-muted">{{ event.description }}</p>

                        <div class="d-flex align-items-center gap-2">
                            <NuxtImg :src="event.avatar" :alt="event.name" class="rounded-circle avatar-xxs" />
                            <NuxtLink :to="event.profileUrl" class="fw-semibold link-reset">
                                {{ event.name }}
                            </NuxtLink>
                        </div>
                    </div>
                </div>
            </div>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BCardHeader } from 'bootstrap-vue-next'
import { expandedActivities } from './data';
</script>
