// Nuxt/Full/pages/(apps)/file-manager/index.vue
    <template>
        <BContainer fluid>
            <PageBreadcrumb title="File Manager" subtitle="Apps" />

            <div class="outlook-box outlook-box-full">
                <ClientOnly>
                    <BOffcanvas body-class="p-0 h-100 " no-header v-model="show" responsive="lg" size="lg"
                        placement="start" class="outlook-left-menu outlook-left-menu-md" tabindex="-1"
                        id="fileSidebaroffcanvas">
                        <Sidebar />
                    </BOffcanvas>
                </ClientOnly>

                <BCard no-body class="h-100 mb-0 rounded-0 flex-grow-1 border-0">
                    <BCardHeader class="border-light justify-content-between">

                        <div class="d-flex gap-2">
                            <div class="d-lg-none d-inline-flex gap-2">
                                <button class="btn btn-default btn-icon" type="button" @click="show = !show"
                                    aria-controls="fileSidebaroffcanvas">
                                    <Icon name="tabler:menu-2" class="fs-lg" />
                                </button>
                            </div>

                            <div class="app-search">
                                <input v-model="searchQuery" type="search" class="form-control"
                                    placeholder="Search files...">
                                <Icon name="lucide:search" size="18" class="app-search-icon text-muted" />
                            </div>
                            <BButton v-if="selected.length" variant="danger" @click="handleDeleteSelected">
                                Delete
                            </BButton>
                        </div>

                        <div class="d-flex align-items-center gap-2">
                            <span class="me-2 fw-semibold">Filter By:</span>


                            <div class="app-search">
                                <select data-table-filter="type" class="form-select form-control my-1 my-md-0">
                                    <option selected>File Type</option>
                                    <option value="Folder">Folder</option>
                                    <option value="MySQL">MySQL</option>
                                    <option value="MP4">MP4</option>
                                    <option value="Audio">Audio</option>
                                    <option value="Figma">Figma</option>
                                </select>
                                <Icon size="18" name="lucide:file" class="app-search-icon text-muted" />
                            </div>


                            <div>
                                <BFormSelect v-model="perPage" :options="perPageOptions"
                                    class="form-control my-1 my-md-0" />
                            </div>
                        </div>
                    </BCardHeader>

                    <simplebar class="card-body" style="height: calc(100% - 100px);">
                        <BRow>
                            <BCol v-for="(item, idx) in folders" :key="idx" md="6" lg="4" xxl="3">
                                <FolderCard :folder="item" />
                            </BCol>

                        </BRow>


                        <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                            v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                            hover :fields="fields" :items="files" :per-page="perPage" :current-page="currentPage"
                            @filtered="onFiltered" responsive
                            class="table table-custom table-nowrap table-centered mb-0 w-100">
                            <template #head()="data">
                                <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                            </template>
                            <template #head(id)>
                                <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                                    id="select-all-products" value="option" :checked="allSelected"
                                    :indeterminate="isIndeterminate" @change="toggleSelectAll" />
                            </template>
                            <template #head(action)>
                                <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                            </template>
                            <template #cell(id)="data">
                                <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                    type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                    @change="onToggleRow(data.item, $event)" />
                            </template>
                            <template #cell(name)="{ item }">
                                <div class="d-flex align-items-center gap-2">
                                    <div
                                        class="d-flex align-items-center justify-content-center flex-shrink-0 avatar-md bg-light bg-opacity-50 text-muted rounded-2">
                                        <Icon :name="item.icon" class="fs-xl" />
                                    </div>
                                    <div class="flex-grow-1">
                                        <h5 class="mb-1 fs-base">
                                            <NuxtLink to="" class="link-reset">{{
                                                item.name }}</NuxtLink>
                                        </h5>
                                        <p class="text-muted mb-0 fs-xs">{{ formatBytes(item.size) }}</p>
                                    </div>
                                </div>
                            </template>
                            <template #cell(owner)="{ item }">
                                <div class="d-flex align-items-center gap-2">
                                    <div
                                        class="flex-shrink-0 bg-light bg-opacity-50 text-muted d-inline-flex align-items-center justify-content-center rounded-2">
                                        <NuxtImg :src="item.avatar" alt="" class="avatar-xs rounded-circle" />
                                    </div>
                                    <h5 class="mb-0 fs-base">
                                        <NuxtLink to="" data-sort="owner" class="link-reset">{{ item.email }}</NuxtLink>
                                    </h5>
                                </div>
                            </template>
                            <template #cell(shared)="{ item }">
                                <div class="avatar-group avatar-group-xs">
                                    <div v-for="(user, idx) in item.sharedWith" class="avatar" :key="idx">
                                        <NuxtImg :src="user.avatar" alt="" class="rounded-circle avatar-xs" />
                                    </div>

                                </div>
                            </template>
                            <template #cell(action)="{ item }">
                                <div class="d-flex align-items-center justify-content-end gap-2">
                                    <span @click="item.starred = !item.starred">
                                        <a href="#" v-if="item.starred">
                                            <Icon name="tabler:star-filled" class="text-warning fs-lg" />
                                        </a>
                                        <a href="#" v-else>
                                            <Icon name="tabler:star-filled" class="text-muted fs-lg" />
                                        </a>
                                    </span>
                                    <BDropdown variant="link" toggle-class="drop-arrow-none fs-xxl link-reset p-0"
                                        class="flex-shrink-0 text-muted">
                                        <template #button-content>
                                            <Icon name="tabler:dots-vertical" />
                                        </template>
                                        <BDropdownItem>
                                            <Icon name="tabler:share" class="me-1" />
                                            Share
                                        </BDropdownItem>
                                        <BDropdownItem>
                                            <Icon name="tabler:link" class="me-1" />
                                            Get Sharable Link
                                        </BDropdownItem>
                                        <BDropdownItem>
                                            <Icon name="tabler:download" class="me-1" />
                                            Download
                                        </BDropdownItem>
                                        <BDropdownItem>
                                            <Icon name="tabler:pin" class="me-1" />
                                            Pin
                                        </BDropdownItem>
                                        <BDropdownItem>
                                            <Icon name="tabler:edit" class="me-1" />
                                            Edit
                                        </BDropdownItem>
                                        <BDropdownItem @click="handleDeleteItem(item)">
                                            <Icon name="tabler:trash" class="me-1" />
                                            Delete
                                        </BDropdownItem>
                                    </BDropdown>
                                </div>
                            </template>


                        </BTable>

                        <div class="d-flex align-items-center justify-content-center gap-2 p-3">
                            <strong>Loading...</strong>
                            <div class="spinner-border spinner-border-sm text-danger" role="status" aria-hidden="true">
                            </div>
                        </div>

                    </simplebar>

                </BCard>
            </div>

        </BContainer>
    </template>

<script setup lang="ts">
import { BCard, BCardBody, BCardHeader, BCol, BContainer, BDropdown, BOffcanvas, type TableFieldRaw } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import { fileRecords, type FileRecordType, type FolderType } from './data';
import FolderCard from './components/FolderCard.vue';
import Sidebar from './components/Sidebar.vue';
import { ref } from 'vue'
import simplebar from 'simplebar-vue';
import { formatBytes } from '~/helpers/file';

const folders: FolderType[] = [{ name: 'INSPINIA Multi', size: 2300000000 }, { name: 'Material Design', size: 105300000 }, { name: 'DashPro UI Kit', size: 512000000 }, { name: 'VueStudio Pack', size: 880000000 }, { name: 'Nextify Pro', size: 1100000000 }, { name: 'Blazor Studio', size: 780000000 }, { name: 'Angular Prime', size: 940000000 }, { name: 'React Kit Pro', size: 1600000000 },]

const show = ref(false)

const fields: Exclude<TableFieldRaw<FileRecordType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'type', label: 'Type', sortable: true },
    { key: 'modified', label: '	Modified', sortable: true },
    { key: 'owner', label: 'Owner', sortable: true },
    { key: 'shared', label: 'Shared With', sortable: true },
    { key: 'action', label: 'Action', sortable: false },
]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(fileRecords.length)
const files = ref<FileRecordType[]>(fileRecords)

function onFiltered(filteredItems: FileRecordType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

function adjustPage() {
    const totalPages = Math.ceil(files.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: FileRecordType) {
    deleteItem(item)
    totalRows.value = files.value.length
    adjustPage()
}

function handleDeleteSelected() {
    deleteSelected()
    totalRows.value = files.value.length
    adjustPage()
}

const { selected, toggleSelectAll, onToggleRow, deleteSelected, deleteItem, allSelected, isIndeterminate } =
    useTableActions(files)

usePageTitle('File Manager')

</script>

<style scoped></style>

// NextJs/NextJs/Full/JS/src/app/(admin)/(apps)/file-manager/page.jsx
'use client';

import FolderCards from '@/app/(admin)/(apps)/file-manager/components/FolderCards';
import SideBar from '@/app/(admin)/(apps)/file-manager/components/SideBar';
import { fileRecords } from '@/app/(admin)/(apps)/file-manager/data';
import SimplebarClient from '@/components/client-wrapper/SimplebarClient';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import DataTable from '@/components/table/DataTable';
import DeleteConfirmationModal from '@/components/table/DeleteConfirmationModal';
import { formatBytes } from '@/helpers/file';
import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Button, Card, CardHeader, Container, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, Offcanvas } from 'react-bootstrap';
import { LuFile, LuSearch } from 'react-icons/lu';
import { TbDotsVertical, TbDownload, TbEdit, TbLink, TbMenu2, TbPin, TbShare, TbStarFilled, TbTrash } from 'react-icons/tb';
const columnHelper = createColumnHelper();
const Page = () => {
  const [show, setShow] = useState(false);
  const [favorites, setFavorites] = useState({});
  const columns = [{
    id: 'select',
    header: ({
      table
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14 file-item-check" checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()} />,
    cell: ({
      row
    }) => <input type="checkbox" className="form-check-input form-check-input-light fs-14 file-item-check" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} />,
    enableSorting: false,
    enableColumnFilter: false
  }, columnHelper.accessor('name', {
    header: 'Name',
    cell: ({
      row
    }) => <div className="d-flex align-items-center gap-2">
          <div className="flex-shrink-0 avatar-md bg-light bg-opacity-50 text-muted rounded-2">
            <span className="avatar-title">
              <row.original.icon className="fs-xl" />
            </span>
          </div>
          <div className="flex-grow-1">
            <h5 className="mb-1 fs-base">
              <Link href="" className="link-reset">
                {row.original.name}
              </Link>
            </h5>
            <p className="text-muted mb-0 fs-xs">{formatBytes(row.original.size)}</p>
          </div>
        </div>
  }), columnHelper.accessor('type', {
    header: 'Type',
    filterFn: 'equalsString'
  }), columnHelper.accessor('modified', {
    header: 'Modified'
  }), columnHelper.accessor('email', {
    header: 'Owner',
    cell: ({
      row
    }) => <div className="d-flex align-items-center gap-2">
          <div className="flex-shrink-0 bg-light bg-opacity-50 text-muted d-inline-flex align-items-center justify-content-center rounded-2">
            <Image src={row.original.avatar.src} height={24} width={24} alt="" className="avatar-xs rounded-circle" />
          </div>
          <h5 className="mb-0 fs-base">
            <Link href="" className="link-reset">
              {row.original.email}
            </Link>
          </h5>
        </div>
  }), columnHelper.accessor('sharedWith', {
    header: 'Shared With',
    cell: ({
      row
    }) => <div className="avatar-group avatar-group-xs">
          {row.original.sharedWith.map((item, index) => <div className="avatar" key={index}>
              <Image src={item.avatar.src} height={24} width={24} alt="" className="rounded-circle avatar-xs" />
            </div>)}
        </div>
  }), {
    header: 'Actions',
    cell: ({
      row
    }) => {
      const fileId = row.original.id;
      const isFavorite = favorites[fileId] ?? row.original.isFavorite;
      return <div className="d-flex align-items-center gap-2">
            <button type="button" className="btn btn-icon btn-sm btn-link" onClick={() => {
          setFavorites(prev => ({
            ...prev,
            [fileId]: !isFavorite
          }));
        }}>
              {isFavorite ? <TbStarFilled className="text-warning fs-lg" /> : <TbStarFilled className="text-muted fs-lg" />}
            </button>
            <Dropdown align="end" className="flex-shrink-0 text-muted">
              <DropdownToggle as="a" role="button" className="dropdown-toggle drop-arrow-none fs-xxl link-reset p-0">
                <TbDotsVertical />
              </DropdownToggle>
              <DropdownMenu>
                <DropdownItem>
                  <TbShare className="me-1" />
                  Share
                </DropdownItem>
                <DropdownItem>
                  <TbLink className="me-1" />
                  Get Sharable Link
                </DropdownItem>
                <DropdownItem>
                  <TbDownload className="me-1" /> Download
                </DropdownItem>
                <DropdownItem>
                  <TbPin className="me-1" /> Pin
                </DropdownItem>
                <DropdownItem>
                  <TbEdit className="me-1" />
                  Edit
                </DropdownItem>
                <DropdownItem onClick={() => {
              toggleDeleteModal();
              setSelectedRowIds({
                [row.id]: true
              });
            }}>
                  <TbTrash className="me-1" />
                  Delete
                </DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </div>;
    }
  }];
  const [data, setData] = useState(() => [...fileRecords]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [sorting, setSorting] = useState([]);
  const [columnFilters, setColumnFilters] = useState([]);
  const [selectedRowIds, setSelectedRowIds] = useState({});
  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
      globalFilter,
      columnFilters,
      rowSelection: selectedRowIds
    },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    onColumnFiltersChange: setColumnFilters,
    onRowSelectionChange: setSelectedRowIds,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    globalFilterFn: 'includesString',
    enableColumnFilters: true,
    enableRowSelection: true
  });
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const toggleDeleteModal = () => {
    setShowDeleteModal(!showDeleteModal);
  };
  const handleDelete = () => {
    const selectedIds = new Set(Object.keys(selectedRowIds));
    setData(old => old.filter((_, idx) => !selectedIds.has(idx.toString())));
    setSelectedRowIds({});
    setShowDeleteModal(false);
  };
  return <Container fluid>
      <PageBreadcrumb title="File Manager" subtitle="Apps" />

      <div className="outlook-box outlook-box-full">
        <Offcanvas responsive="lg" show={show} onHide={() => setShow(!show)} className="outlook-left-menu outlook-left-menu-md">
          <SideBar />
        </Offcanvas>

        <Card className="h-100 mb-0 rounded-0 flex-grow-1 border-0">
          <CardHeader className="border-light justify-content-between">
            <div className="d-flex gap-2">
              <div className="d-lg-none d-inline-flex gap-2">
                <button className="btn btn-default btn-icon" type="button" onClick={() => setShow(!show)}>
                  <TbMenu2 className="fs-lg" />
                </button>
              </div>

              <div className="app-search">
                <input type="search" className="form-control" placeholder="Search files..." value={globalFilter ?? ''} onChange={e => setGlobalFilter(e.target.value)} />
                <LuSearch className="app-search-icon text-muted" />
              </div>
              {Object.keys(selectedRowIds).length > 0 && <Button variant="danger" size="sm" onClick={toggleDeleteModal}>
                  Delete
                </Button>}
            </div>

            <div className="d-flex align-items-center gap-2">
              <span className="me-2 fw-semibold">Filter By:</span>

              <div className="app-search">
                <select className="form-select form-control my-1 my-md-0" value={table.getColumn('type')?.getFilterValue() ?? 'All'} onChange={e => table.getColumn('type')?.setFilterValue(e.target.value === 'All' ? undefined : e.target.value)}>
                  <option value="All">File Type</option>
                  <option value="Folder">Folder</option>
                  <option value="MySQL">MySQL</option>
                  <option value="MP4">MP4</option>
                  <option value="Audio">Audio</option>
                  <option value="Figma">Figma</option>
                </select>
                <LuFile className="app-search-icon text-muted" />
              </div>

              <div>
                <select className="form-select form-control my-1 my-md-0" value={table.getState().pagination.pageSize} onChange={e => table.setPageSize(Number(e.target.value))}>
                  {[5, 8, 10, 15, 20].map(size => <option key={size} value={size}>
                      {size}
                    </option>)}
                </select>
              </div>
            </div>
          </CardHeader>

          <SimplebarClient className="card-body" style={{
          height: 'calc(100% - 100px)'
        }} data-simplebar-md>
            <FolderCards />

            <DataTable table={table} emptyMessage="No records found" />

            <DeleteConfirmationModal show={showDeleteModal} onHide={toggleDeleteModal} onConfirm={handleDelete} selectedCount={Object.keys(selectedRowIds).length} itemName="clients" />

            <div className="d-flex align-items-center justify-content-center gap-2 p-3">
              <strong>Loading...</strong>
              <div className="spinner-border spinner-border-sm text-danger" role="status" aria-hidden="true"></div>
            </div>
          </SimplebarClient>
        </Card>
      </div>
    </Container>;
};
export default Page;
