// Vue-Inertia/Seed/resources/js/pages/auth/auth-2/delete-account/index.vue
<template>
    <Head title="Delete Account" />
  <div class="auth-box d-flex align-items-center">
    <BContainer fluid="xxl">
      <BRow class="align-items-center justify-content-center">
        <BCol xl="10">
          <BCard no-body class="rounded-4">
            <BRow class="justify-content-between g-0">
              <BCol lg="6">
                <div class="card-body">
                  <div class="auth-brand text-center mb-4">
                    <AuthLogo />
                  </div>

                  <div class="mb-4">
                    <div class="avatar-xxl mx-auto mt-2">
                      <div
                        class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle"
                      >
                        <img :src="deleteImg" alt="inactive" height="64" />
                      </div>
                    </div>
                  </div>

                  <h4 class="fw-bold text-center mb-3">Account Deactivated</h4>
                  <p class="text-muted text-center mb-4">
                    Your account is currently inactive. Reactivate now to regain access to all
                    features and opportunities.
                  </p>

                  <div class="d-grid">
                    <BButton type="button" variant="primary" class="fw-semibold py-2">
                      Reactivate Now
                    </BButton>
                  </div>

                  <p class="text-center text-muted mt-4 mb-0">
                    © 2014 - {{ currentYear }} INSPINIA — by
                    <span class="fw-semibold">{{ author }}</span>
                  </p>
                </div>
              </BCol>

              <BCol lg="6" class="d-none d-lg-block">
                <div
                  class="h-100 position-relative card-side-img rounded-end-4 rounded-0 overflow-hidden"
                >
                  <div
                    class="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"
                  ></div>
                </div>
              </BCol>
            </BRow>
          </BCard>
        </BCol>
      </BRow>
    </BContainer>
  </div>
</template>

<script setup lang="ts">
import { BButton, BCard, BCol, BContainer, BRow } from 'bootstrap-vue-next'
import { author, currentYear } from '@/helpers'
import AuthLogo from '@/components/AuthLogo.vue'


import deleteImg from '@/images/delete.png'
import { Head } from '@inertiajs/vue3'

</script>

// React-Inertia/Seed/resources/js/pages/auth/auth-2/delete-account/index.tsx
import AppLogo from '@/components/AppLogo'
import { author, currentYear } from '@/helpers'

import { Button, Card, CardBody, Col, Container, Row } from 'react-bootstrap'

import deleteIcon from '@/images/delete.png'
import { Head } from '@inertiajs/react'

const Page = () => {
  return (
    <div className="auth-box d-flex align-items-center">
      <Head title="Delete Account" />
      <Container fluid className="container-xxl">
        <Row className="align-items-center justify-content-center">
          <Col xl={10}>
            <Card className="rounded-4">
              <Row className="justify-content-between g-0">
                <Col lg={6}>
                  <CardBody>
                    <div className="auth-brand text-center mb-4">
                      <AppLogo />
                    </div>

                    <div className="mb-4">
                      <div className="avatar-xxl mx-auto mt-2">
                        <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle">
                          <img src={deleteIcon} alt="delete icon" height={64} />
                        </div>
                      </div>
                    </div>

                    <h4 className="fw-bold text-center mb-3">Account Deactivated</h4>
                    <p className="text-muted text-center mb-4">
                      Your account is currently inactive. Reactivate now to regain access to all features and opportunities.
                    </p>

                    <div className="d-grid">
                      <Button type="button" variant="primary" className="fw-semibold py-2">
                        Reactivate Now
                      </Button>
                    </div>

                    <p className="text-center text-muted mt-4 mb-0">
                      © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
                    </p>
                  </CardBody>
                </Col>

                <Col lg={6} className="d-none d-lg-block">
                  <div className="h-100 position-relative card-side-img rounded-end-4 overflow-hidden">
                    <div className="p-4 card-img-overlay rounded-4 rounded-start-0 auth-overlay d-flex align-items-end justify-content-center"></div>
                  </div>
                </Col>
              </Row>
            </Card>
          </Col>
        </Row>
      </Container>
    </div>
  )
}

export default Page
