// React/Full/TS/src/components/TouchSpinInput.tsx
import clsx from 'clsx'
import { type ChangeEvent, useEffect, useState } from 'react'
import { Button, FormControl, type FormControlProps } from 'react-bootstrap'
import type { ButtonVariant } from 'react-bootstrap/types'
import { TbMinus, TbPlus } from 'react-icons/tb'

type PropsType = {
  min?: number
  max?: number
  value?: number
  setValue?: (value: number) => void
  className?: string
  inputClassName?: string
  buttonClassName?: string
  variant?: ButtonVariant
  size?: FormControlProps['size']
} & Omit<FormControlProps, 'value' | 'onChange'>

const TouchSpinInput = ({
  min = 0,
  max = 100,
  value,
  setValue,
  className,
  inputClassName,
  buttonClassName,
  variant = 'light',
  size,
  ...props
}: PropsType) => {
  const [localValue, setLocalValue] = useState<number>(value ?? 0)

  const increment = () => {
    if (!props.readOnly) {
      setLocalValue((prev) => {
        if (prev >= max) return prev
        return prev + 1
      })
    }
  }

  const decrement = () => {
    if (!props.readOnly) {
      setLocalValue((prev) => {
        if (prev <= min) return prev
        return prev - 1
      })
    }
  }

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const val = e.target.value

    if (val === '') {
      setLocalValue(0)
      return
    }

    const newValue = parseInt(val)

    if (newValue < min) {
      setLocalValue(min)
      return
    }
    if (newValue > max) {
      setLocalValue(max)
      return
    }
    setLocalValue(newValue)
  }

  useEffect(() => {
    if (setValue) {
      setValue(localValue)
    }
  }, [localValue])

  return (
    <div className={clsx('input-group touchspin', className, size === 'sm' && 'input-group-sm', size === 'lg' && 'input-group-lg')}>
      <Button variant={variant} className={clsx('floating', buttonClassName)} disabled={props.disabled} onClick={decrement}>
        <TbMinus />
      </Button>
      <FormControl
        type="number"
        size={size}
        min={min}
        max={max}
        value={localValue}
        onChange={handleChange}
        className={clsx('border-0', inputClassName)}
        {...props}
      />
      <Button variant={variant} className={clsx('floating', buttonClassName)} disabled={props.disabled} onClick={increment}>
        <TbPlus />
      </Button>
    </div>
  )
}

export default TouchSpinInput

// src/components/TouchSpinInput.vue
<template>
  <div :class="inputGroupClasses">
    <BButton
      :variant="props.variant"
      :class="['floating', props.buttonClassName]"
      :disabled="props.disabled"
      @click="decrement"
    >
      <Icon icon="tabler-minus" />
    </BButton>

    <BFormInput
      type="number"
      :size="props.size"
      :min="props.min"
      :max="props.max"
      v-model="localValue"
      :disabled="props.disabled"
      :readonly="props.readonly"
      :class="['border-0', props.inputClassName]"
    />

    <BButton
      :variant="props.variant"
      :class="['floating', props.buttonClassName]"
      :disabled="props.disabled"
      @click="increment"
    >
      <Icon icon="tabler-plus" />
    </BButton>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed } from 'vue'
import { BButton, BFormInput, type BaseButtonVariant } from 'bootstrap-vue-next'
import { Icon } from '@iconify/vue'

type Props = {
  min?: number
  max?: number
  modelValue?: number
  className?: string
  inputClassName?: string
  buttonClassName?: string
  variant?: keyof BaseButtonVariant
  size?: 'sm' | 'lg'
  disabled?: boolean
  readonly?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  min: 0,
  max: 100,
  modelValue: 0,
  variant: 'light',
  size: undefined,
  disabled: false,
  readonly: false
})

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void
}>()

const localValue = ref<number>(props.modelValue ?? 0)

watch(
  () => props.modelValue,
  (val: number) => {
    if (val !== undefined && val !== localValue.value) {
      localValue.value = val
    }
  }
)

watch(localValue, (val: number) => {
  emit('update:modelValue', val)
})

const increment = () => {
  if (!props.readonly && localValue.value < props.max) {
    localValue.value++
  }
}

const decrement = () => {
  if (!props.readonly && localValue.value > props.min) {
    localValue.value--
  }
}

const inputGroupClasses = computed(() => [
  'input-group',
  'touchspin',
  props.className,
  props.size === 'sm' && 'input-group-sm',
  props.size === 'lg' && 'input-group-lg'
])
</script>
