// NextJs/NextJs/Full/TS/src/app/(admin)/forms/pickers/page.tsx
import ColorPicker from '@/app/(admin)/forms/pickers/components/ColorPicker'
import DatePicker from '@/app/(admin)/forms/pickers/components/DatePicker'
import DayPicker from '@/app/(admin)/forms/pickers/components/DayPicker'
import FlatPicker from '@/app/(admin)/forms/pickers/components/FlatPicker'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Row } from 'react-bootstrap'

const Page = () => {
  return (
    <>
      <Container fluid>
        <PageBreadcrumb title="Pickers" subtitle="Forms" />
      </Container>
      <Container>
        <Row className="justify-content-center">
          <Col lg={12}>
            <DatePicker />

            <DayPicker />

            <FlatPicker />

            <ColorPicker />
          </Col>
        </Row>
      </Container>
    </>
  )
}

export default Page

// Nuxt/Full/pages/forms/pickers/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Pickers" subtitle="Forms" />
    </BContainer>

    <BContainer>
        <BRow>
            <BCol lg="12">

                <Flatpickers />

                <ColorPickers />
            </BCol>
        </BRow>

    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import ColorPickers from './components/ColorPickers.vue';
import Flatpickers from './components/Flatpickers.vue';

usePageTitle('Pickers')
</script>

<style scoped></style>
