// Nuxt/Full/pages/graphs/echart/line/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Line EChart" subtitle="Charts" />
        <BRow>
            <BCol xl='6'>
                <UICard title="Line Chart">
                    <CustomEChart :extensions="[LineChart, CanvasRenderer, TooltipComponent, GridComponent]"
                        :getOptions="getLineChart" :style="{ height: '300px' }" />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Line Stacked Chart">
                    <CustomEChart :extensions="[LinesChart, CanvasRenderer]" :getOptions="getStackedLineChart" :style="{
                        height: '300px'
                    }" />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <UICard title="Line Marker">
                    <CustomEChart :extensions="[LinesChart, CanvasRenderer]" :getOptions="getLineMarkerChart" :style="{
                        height: '300px'
                    }" />
                </UICard>
            </BCol>
            <BCol xl='6'>
                <DynamicLineChart />
            </BCol>

            <BCol xl='6'>
                <UICard title="Step Line">
                    <CustomEChart :extensions="[LinesChart, CanvasRenderer]" :getOptions="getStepLine" :style="{
                        height: '300px'
                    }" />
                </UICard>
            </BCol>

            <BCol xl='6'>
                <UICard title="Line Y Category">
                    <CustomEChart :extensions="[LinesChart, CanvasRenderer]" :getOptions="getLineYCategory" :style="{
                        height: '300px'
                    }" />
                </UICard>
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import CustomEChart from '~/components/CustomEChart.vue';
import UICard from '~/components/UICard.vue';
import { getLineChart, getLineMarkerChart, getLineYCategory, getStackedLineChart, getStepLine } from './data';
import { LineChart, LinesChart } from 'echarts/charts';
import { CanvasRenderer } from 'echarts/renderers';
import { GridComponent, TooltipComponent } from 'echarts/components';
import DynamicLineChart from './components/DynamicLineChart.vue';

usePageTitle('EChart Line Chart')
</script>

<style scoped></style>

// React/Full/JS/src/views/graphs/echart/line/index.jsx
import ComponentCard from '@/components/cards/ComponentCard';
import CustomEChart from '@/components/CustomEChart';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { LinesChart } from 'echarts/charts';
import { CanvasRenderer } from 'echarts/renderers';
import { Col, Container, Row } from 'react-bootstrap';
import { getLineChart, getLineMarkerChart, getLineYCategory, getStackedLineChart, getStepLine } from './data';
import DynamicLineChart from './components/DynamicLineChart';
const Page = () => {
  return <Container fluid>
      <PageBreadcrumb title="Line Chart" subtitle="Charts" />
      <Row>
        <Col xl={6}>
          <ComponentCard title="Line Chart">
            <CustomEChart extensions={[LinesChart, CanvasRenderer]} getOptions={getLineChart} style={{
            height: '300px'
          }} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Line Stacked Chart">
            <CustomEChart extensions={[LinesChart, CanvasRenderer]} getOptions={getStackedLineChart} style={{
            height: '300px'
          }} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <ComponentCard title="Line Marker">
            <CustomEChart extensions={[LinesChart, CanvasRenderer]} getOptions={getLineMarkerChart} style={{
            height: '300px'
          }} />
          </ComponentCard>
        </Col>
        <Col xl={6}>
          <DynamicLineChart />
        </Col>

        <Col xl={6}>
          <ComponentCard title="Step Line">
            <CustomEChart extensions={[LinesChart, CanvasRenderer]} getOptions={getStepLine} style={{
            height: '300px'
          }} />
          </ComponentCard>
        </Col>

        <Col xl={6}>
          <ComponentCard title="Line Y Category">
            <CustomEChart extensions={[LinesChart, CanvasRenderer]} getOptions={getLineYCategory} style={{
            height: '300px'
          }} />
          </ComponentCard>
        </Col>
      </Row>
    </Container>;
};
export default Page;
