// Nuxt/Full/pages/(apps)/users/permissions/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Permissions" subTitle="Users" />
        <BRow class="justify-content-center">
            <BCol xxl="10">
                <BCard no-body>
                    <BCardHeader class="border-light justify-content-between">
                        <div class="d-flex gap-2">
                            <div class="app-search">
                                <input v-model="searchQuery" type="search" class="form-control"
                                    placeholder="Search permissions...">
                                <Icon name="lucide:search" size="18" class="app-search-icon text-muted" />
                            </div>
                        </div>

                        <div>
                            <BFormSelect v-model="perPage" :options="perPageOptions"
                                class="form-control my-1 my-md-0" />
                        </div>
                    </BCardHeader>

                    <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                        v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                        hover :fields="fields" :items="permissions" :per-page="perPage" :current-page="currentPage"
                        @filtered="onFiltered" responsive
                        class="table table-custom table-nowrap table-centered mb-0 w-100">
                        <template #head()="data">
                            <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                        </template>
                        <template #head(action)>
                            <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                        </template>
                        <template #cell(assigned)="{ item }">
                            <span v-for="(role, idx) in item.roles" :key="idx"
                                class="badge  badge-label fs-xxs fw-semibold me-1"
                                :class="[`bg-${role.variant}-subtle`, `text-${role.variant}`]">{{
                                    role.label }}</span>
                        </template>
                        <template #cell(createdDate)="{ item }">
                            {{ item.date }}, <span class="text-muted">{{ item.time }}</span>
                        </template>

                        <template #cell(action)="{ item }">
                            <div class="d-flex justify-content-center gap-1">
                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                    <Icon name="tabler:eye" class="fs-lg" />
                                </button>
                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                    <Icon name="tabler:trash" class="fs-lg" @click="handleDeleteItem(item)" />
                                </button>
                            </div>
                        </template>
                    </BTable>
                    <BCardFooter class="border-0">
                        <TablePagination v-model:currentPage="currentPage" :per-page="perPage" :total-items="totalRows"
                            label="permissions" />
                    </BCardFooter>
                </BCard>
            </BCol>
        </BRow>
    </BContainer>
</template>

<script setup lang="ts">
import { BCard, BCardFooter, BCardHeader, BCol, BContainer, BFormSelect, BRow, BTable, type TableFieldRaw } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import TablePagination from '~/components/TablePagination.vue';
import { permissionManagementData, type ManagementType } from './data';

const fields: Exclude<TableFieldRaw<ManagementType>, string>[] = [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'assigned', label: 'Assign To' },
    { key: 'createdDate', label: 'Created Date', sortable: true },
    { key: 'users', label: 'Users', sortable: true },
    { key: 'action', label: 'Action', sortable: false },
]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(permissionManagementData.length)
const permissions = ref<ManagementType[]>(permissionManagementData)

function onFiltered(filteredItems: ManagementType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

function adjustPage() {
    const totalPages = Math.ceil(permissions.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: ManagementType) {
    deleteItem(item)
    totalRows.value = permissions.value.length
    adjustPage()
}


const { selected, deleteItem } = useTableActions(permissions)

usePageTitle('User Permissions')


</script>

<style scoped></style>

// React/Full/JS/src/views/apps/users/permissions/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import DataTable from '@/components/table/DataTable';
import DeleteConfirmationModal from '@/components/table/DeleteConfirmationModal';
import TablePagination from '@/components/table/TablePagination';
import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getPaginationRowModel, getSortedRowModel, useReactTable } from '@tanstack/react-table';
import { useState } from 'react';
import { Button, Card, CardFooter, CardHeader, Col, Container, Row } from 'react-bootstrap';
import { LuSearch } from 'react-icons/lu';
import { TbEye, TbTrash } from 'react-icons/tb';
import { permissionManagementData } from '@/views/apps/users/permissions/data';
const Page = () => {
  const columnHelper = createColumnHelper();
  const columns = [columnHelper.accessor('name', {
    header: 'Name'
  }), columnHelper.accessor('roles', {
    header: 'Assign To',
    cell: ({
      row
    }) => <div className="d-flex gap-1 flex-wrap">
          {row.original.roles.map((role, idx) => <span key={idx} className={`badge bg-${role.variant}-subtle text-${role.variant} badge-label fs-xxs fw-semibold`}>
              {role.label}
            </span>)}
        </div>,
    enableSorting: false
  }), columnHelper.accessor('date', {
    header: 'Status',
    cell: ({
      row
    }) => <>
          {row.original.date}, <span className="text-muted">{row.original.time}</span>
        </>
  }), columnHelper.accessor('users', {
    header: 'Users'
  }), {
    header: 'Actions',
    cell: ({
      row
    }) => <div className="d-flex  gap-1">
          <Button variant="light" size="sm" className="btn-icon rounded-circle">
            <TbEye className="fs-lg" />
          </Button>
          <Button variant="light" size="sm" className="btn-icon rounded-circle" onClick={() => {
        toggleDeleteModal();
        setSelectedRowIds({
          [row.id]: true
        });
      }}>
            <TbTrash className="fs-lg" />
          </Button>
        </div>
  }];
  const [data, setData] = useState(() => [...permissionManagementData]);
  const [globalFilter, setGlobalFilter] = useState('');
  const [sorting, setSorting] = useState([]);
  const [pagination, setPagination] = useState({
    pageIndex: 0,
    pageSize: 8
  });
  const [selectedRowIds, setSelectedRowIds] = useState({});
  const table = useReactTable({
    data,
    columns,
    state: {
      sorting,
      globalFilter,
      pagination,
      rowSelection: selectedRowIds
    },
    onSortingChange: setSorting,
    onGlobalFilterChange: setGlobalFilter,
    onPaginationChange: setPagination,
    onRowSelectionChange: setSelectedRowIds,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    globalFilterFn: 'includesString',
    enableRowSelection: true
  });
  const pageIndex = table.getState().pagination.pageIndex;
  const pageSize = table.getState().pagination.pageSize;
  const totalItems = table.getFilteredRowModel().rows.length;
  const start = pageIndex * pageSize + 1;
  const end = Math.min(start + pageSize - 1, totalItems);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const toggleDeleteModal = () => {
    setShowDeleteModal(!showDeleteModal);
  };
  const handleDelete = () => {
    const selectedIds = new Set(Object.keys(selectedRowIds));
    setData(old => old.filter((_, idx) => !selectedIds.has(idx.toString())));
    setSelectedRowIds({});
    setPagination({
      ...pagination,
      pageIndex: 0
    });
    setShowDeleteModal(false);
  };
  return <Container fluid>
      <PageBreadcrumb title="Permissions" subtitle="Users" />

      <Row className="justify-content-center">
        <Col xxl={10}>
          <Card>
            <CardHeader className="border-light justify-content-between">
              <div className="d-flex gap-2">
                <div className="app-search">
                  <input data-table-search type="search" className="form-control" placeholder="Search permissions..." />
                  <LuSearch className="app-search-icon text-muted" />
                </div>
                {Object.keys(selectedRowIds).length > 0 && <Button variant="danger" onClick={toggleDeleteModal}>
                    Delete
                  </Button>}
              </div>
              <div>
                <select value={table.getState().pagination.pageSize} onChange={e => table.setPageSize(Number(e.target.value))} className="form-select form-control my-1 my-md-0">
                  {[5, 10, 15, 20].map(size => <option key={size} value={size}>
                      {size}
                    </option>)}
                </select>
              </div>
            </CardHeader>
            <DataTable table={table} emptyMessage="No records found" />
            {table.getRowModel().rows.length > 0 && <CardFooter className="border-0">
                <TablePagination totalItems={totalItems} start={start} end={end} itemsName="permissions" showInfo previousPage={table.previousPage} canPreviousPage={table.getCanPreviousPage()} pageCount={table.getPageCount()} pageIndex={table.getState().pagination.pageIndex} setPageIndex={table.setPageIndex} nextPage={table.nextPage} canNextPage={table.getCanNextPage()} />
              </CardFooter>}
            <DeleteConfirmationModal show={showDeleteModal} onHide={toggleDeleteModal} onConfirm={handleDelete} selectedCount={Object.keys(selectedRowIds).length} itemName="row" />
          </Card>
        </Col>
      </Row>
    </Container>;
};
export default Page;
