// Vue/Full/src/views/ui/list-group/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="List Group" subTitle="UI" />
        </BContainer>

        <div class="container-xl">
            <BRow>
                <BCol lg="12">
                    <UICard title="Examples" isCollapsable>
                        <p class="text-muted mb-2">
                            List groups are a flexible and powerful component for displaying a series of content. Modify
                            and extend them to support just about any content within.
                        </p>
                        <a class="btn btn-link p-0 fw-semibold"
                            href="https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/list-group.html"
                            target="_blank">
                            List Group on Bootstrap
                            <Icon icon="tabler:chevron-right" class="ms-1" />
                        </a>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Basic Example" isCollapsable>
                        <p class="text-muted">
                            The most basic list group is an unordered list with list items and the proper classes. Build
                            upon it with the options that follow, or with your own CSS as needed.
                        </p>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <Icon icon="tabler:cloud" class="me-1 align-top fs-xl" /> Dropbox Cloud Storage
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-slack" class="me-1 align-top fs-xl" /> Slack Team Collaboration
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-windows" class="me-1 align-top fs-xl" /> Microsoft Windows OS
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:device-desktop-analytics" class="me-1 align-top fs-xl" /> Zendesk
                                Customer Support
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-stripe" class="me-1 align-top fs-xl" /> Stripe Payment
                                Integration
                            </li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Active Items" isCollapsable>
                        <p class="text-muted">
                            Add <code>.active</code> to a <code>.list-group-item</code> to indicate the current active
                            selection.
                        </p>
                        <ul class="list-group">
                            <li class="list-group-item active">
                                <Icon icon="tabler:brand-github" class="me-1 align-top fs-xl" /> GitHub Repository
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-figma" class="me-1 align-top fs-xl" /> Figma Design Tool
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-notion" class="me-1 align-top fs-xl" /> Notion Workspace
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-trello" class="me-1 align-top fs-xl" /> Trello Task Manager
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:cloud" class="me-1 align-top fs-xl" /> DigitalOcean Cloud
                            </li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Disabled Items" isCollapsable>
                        <p>Add <code>.disabled</code> to a <code>.list-group-item</code> to make it <em>appear</em>
                            disabled.</p>
                        <ul class="list-group">
                            <li class="list-group-item disabled" aria-disabled="true">
                                <Icon icon="tabler:cloud" class="me-1 align-top fs-xl" /> Dropbox Cloud Storage
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-slack" class="me-1 align-top fs-xl" /> Slack Team Collaboration
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-windows" class="me-1 align-top fs-xl" /> Microsoft Windows OS
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:device-desktop-analytics" class="me-1 align-top fs-xl" /> Zendesk
                                Customer Support
                            </li>
                            <li class="list-group-item">
                                <Icon icon="tabler:brand-stripe" class="me-1 align-top fs-xl" /> Stripe Payment
                                Integration
                            </li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Links and Buttons" isCollapsable>
                        <p class="text-muted">
                            Use <code>&lt;a&gt;</code>s or <code>&lt;button&gt;</code>s to create <em>actionable</em>
                            list group items with hover, disabled, and active states by adding
                            <code>.list-group-item-action</code>.
                        </p>
                        <div class="list-group">
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action active">Stripe
                                Payment Integration</a>
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action">Dropbox Cloud
                                Service</a>
                            <button type="button" class="list-group-item list-group-item-action">Slack
                                Communication</button>
                            <button type="button" class="list-group-item list-group-item-action">Notion Productivity
                                App</button>
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action disabled"
                                tabindex="-1">Zendesk Support Tool</a>
                        </div>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Flush" isCollapsable>
                        <p class="text-muted">
                            Add <code>.list-group-flush</code> to remove some borders and rounded corners to render list
                            group items edge-to-edge in a parent container (e.g., cards).
                        </p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Slack Collaboration Tool</li>
                            <li class="list-group-item">Dropbox Cloud Storage</li>
                            <li class="list-group-item">Notion Workspace Organizer</li>
                            <li class="list-group-item">Zendesk Customer Support</li>
                            <li class="list-group-item">Stripe Payment Processor</li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Horizontal" isCollapsable>
                        <p class="text-muted">
                            Add <code>.list-group-horizontal</code> to change the layout of list group items from
                            vertical to horizontal across all breakpoints.
                        </p>
                        <ul class="list-group list-group-horizontal mb-3">
                            <li class="list-group-item">Slack</li>
                            <li class="list-group-item">Notion</li>
                            <li class="list-group-item">Dropbox</li>
                        </ul>
                        <ul class="list-group list-group-horizontal-sm mb-3">
                            <li class="list-group-item">Figma</li>
                            <li class="list-group-item">Stripe</li>
                            <li class="list-group-item">Zendesk</li>
                        </ul>
                        <ul class="list-group list-group-horizontal-md">
                            <li class="list-group-item">Trello</li>
                            <li class="list-group-item">Asana</li>
                            <li class="list-group-item">ClickUp</li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Contextual Classes" isCollapsable>
                        <p class="text-muted">Use contextual classes to style list items with a stateful background and
                            color.</p>
                        <ul class="list-group">
                            <li class="list-group-item">Dapibus ac facilisis in</li>
                            <li class="list-group-item list-group-item-primary">A simple primary list group item</li>
                            <li class="list-group-item list-group-item-secondary">A simple secondary list group item
                            </li>
                            <li class="list-group-item list-group-item-success">A simple success list group item</li>
                            <li class="list-group-item list-group-item-danger">A simple danger list group item</li>
                            <li class="list-group-item list-group-item-warning">A simple warning list group item</li>
                            <li class="list-group-item list-group-item-info">A simple info list group item</li>
                            <li class="list-group-item list-group-item-light">A simple light list group item</li>
                            <li class="list-group-item list-group-item-dark">A simple dark list group item</li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Contextual Classes with Link" isCollapsable>
                        <p class="text-muted">Use contextual classes to style list items with a stateful background and
                            color.</p>
                        <div class="list-group">
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action">Darius ac
                                facilities in</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-primary">A simple primary
                                list group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-secondary">A simple
                                secondary list group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-success">A simple success
                                list group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-danger">A simple danger
                                list group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-warning">A simple warning
                                list group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-info">A simple info list
                                group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-light">A simple light list
                                group item</a>
                            <a href="javascript:void(0);"
                                class="list-group-item list-group-item-action list-group-item-dark">A simple dark list
                                group item</a>
                        </div>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Custom Content" isCollapsable>
                        <p class="text-muted">Add nearly any HTML within, even for linked list groups, with the help of
                            flexbox utilities.</p>
                        <div class="list-group">
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action active">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-2">List group item heading</h5>
                                    <small>3 days ago</small>
                                </div>
                                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget
                                    risus varius blandit.</p>
                                <small>Donec id elit non mi porta.</small>
                            </a>
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-2">List group item heading</h5>
                                    <small class="text-muted">3 days ago</small>
                                </div>
                                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget
                                    risus varius blandit.</p>
                                <small class="text-muted">Donec id elit non mi porta.</small>
                            </a>
                            <a href="javascript:void(0);" class="list-group-item list-group-item-action">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-2">List group item heading</h5>
                                    <small class="text-muted">3 days ago</small>
                                </div>
                                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget
                                    risus varius blandit.</p>
                                <small class="text-muted">Donec id elit non mi porta.</small>
                            </a>
                        </div>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="With Badges" isCollapsable>
                        <p class="text-muted">Add badges to any list group item to show counts, activity, and more.</p>
                        <ul class="list-group">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Gmail Notifications <span class="badge bg-primary rounded-pill">14</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Unprocessed Orders <span class="badge bg-success rounded-pill">2</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Urgent Tickets <span class="badge bg-danger rounded-pill">99+</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Completed Transactions <span class="badge bg-success rounded-pill">20+</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Invoices Awaiting Approval <span class="badge bg-warning rounded-pill">12</span>
                            </li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Checkboxes and Radios" isCollapsable>
                        <p class="text-muted">Place Bootstrap’s checkboxes and radios within list group items.</p>
                        <ul class="list-group">
                            <li class="list-group-item">
                                <input class="form-check-input me-1" type="checkbox" id="newsletterCheckbox">
                                <label class="form-check-label" for="newsletterCheckbox">Subscribe to newsletter</label>
                            </li>
                            <li class="list-group-item">
                                <input class="form-check-input me-1" type="checkbox" id="termsCheckbox">
                                <label class="form-check-label" for="termsCheckbox">Accept terms and conditions</label>
                            </li>
                        </ul>
                        <ul class="list-group mt-2">
                            <li class="list-group-item">
                                <input class="form-check-input me-1" type="radio" name="notificationOptions"
                                    id="emailRadio" checked>
                                <label class="form-check-label" for="emailRadio">Notify by Email</label>
                            </li>
                            <li class="list-group-item">
                                <input class="form-check-input me-1" type="radio" name="notificationOptions"
                                    id="smsRadio">
                                <label class="form-check-label" for="smsRadio">Notify by SMS</label>
                            </li>
                        </ul>
                    </UICard>
                </BCol>

                <BCol xl="4">
                    <UICard title="Numbered" isCollapsable>
                        <p class="text-muted">
                            Numbers are generated by <code>counter-reset</code> on the <code>&lt;ol&gt;</code>, and
                            styled via <code>::before</code>.
                        </p>
                        <ol class="list-group list-group-numbered">
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">INSPINIA Admin</div>
                                    INSPINIA Admin
                                </div>
                                <span class="badge bg-primary rounded-pill">865</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">INSPINIA React Admin</div>
                                    INSPINIA React Admin
                                </div>
                                <span class="badge bg-primary rounded-pill">140</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-start">
                                <div class="ms-2 me-auto">
                                    <div class="fw-bold">Angular Version</div>
                                    Angular Version
                                </div>
                                <span class="badge bg-primary rounded-pill">85</span>
                            </li>
                        </ol>
                    </UICard>
                </BCol>
            </BRow>
        </div>
    </MainLayout>
</template>


<script setup lang="ts">
import { usePageMeta } from '@/composables/usePageMeta';
import { BCol, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import UICard from '@/components/UICard.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';

usePageMeta('List Group')
</script>

// React-Inertia/Full/resources/js/pages/ui/list-group/index.tsx
import ComponentCard from '@/components/cards/ComponentCard'
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Card, CardBody, CardHeader, CardTitle, Col, Container, ListGroup, ListGroupItem, Row } from 'react-bootstrap'
import FormCheckInput from 'react-bootstrap/esm/FormCheckInput'
import FormCheckLabel from 'react-bootstrap/esm/FormCheckLabel'
import {
  TbBrandFigma,
  TbBrandGithub,
  TbBrandNotion,
  TbBrandSlack,
  TbBrandStripe,
  TbBrandTrello,
  TbBrandWindows,
  TbChevronRight,
  TbCloud,
  TbDeviceDesktopAnalytics,
} from 'react-icons/tb'
import { Link } from '@inertiajs/react'
import MainLayout from '@/layouts/MainLayout'

const BasicExample = () => {
  return (
    <ComponentCard title="Basic Example">
      <p className="text-muted">
        The most basic list group is an unordered list with list items and the proper classes. Build upon it with the options that follow, or with
        your own CSS as needed.
      </p>
      <ListGroup as={'ul'}>
        <ListGroupItem>
          <TbCloud className="me-1 align-middle fs-xl" />
          Dropbox Cloud Storage
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandSlack className="me-1 align-middle fs-xl" /> Slack Team Collaboration
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandWindows className="me-1 align-middle fs-xl" /> Microsoft Windows OS
        </ListGroupItem>
        <ListGroupItem>
          <TbDeviceDesktopAnalytics className="me-1 align-middle fs-xl" /> Zendesk Customer Support
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandStripe className="me-1 align-middle fs-xl" /> Stripe Payment Integration
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const ActiveItems = () => {
  return (
    <ComponentCard title="Active Items">
      <p className="text-muted">
        Add <code>.active</code> to a<code>.list-group-item</code> to indicate the current active selection.
      </p>
      <ListGroup as={'ul'}>
        <ListGroupItem active>
          <TbBrandGithub className="me-1 align-middle fs-xl" /> GitHub Repository
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandFigma className="me-1 align-middle fs-xl" /> Figma Design Tool
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandNotion className="me-1 align-middle fs-xl" /> Notion Workspace
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandTrello className="me-1 align-middle fs-xl" /> Trello Task Manager
        </ListGroupItem>
        <ListGroupItem>
          <TbCloud className="me-1 align-middle fs-xl" />
          DigitalOcean Cloud
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const DisabledItems = () => {
  return (
    <ComponentCard title="Basic Example">
      <p>
        Add <code>.disabled</code> to a <code>.list-group-item</code> to make it
        <em>appear</em> disabled.
      </p>
      <ListGroup as={'ul'}>
        <ListGroupItem disabled>
          <TbCloud className="me-1 align-middle fs-xl" />
          Dropbox Cloud Storage
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandSlack className="me-1 align-middle fs-xl" /> Slack Team Collaboration
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandWindows className="me-1 align-middle fs-xl" /> Microsoft Windows OS
        </ListGroupItem>
        <ListGroupItem>
          <TbDeviceDesktopAnalytics className="me-1 align-middle fs-xl" /> Zendesk Customer Support
        </ListGroupItem>
        <ListGroupItem>
          <TbBrandStripe className="me-1 align-middle fs-xl" /> Stripe Payment Integration
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const LinksAndButtons = () => {
  return (
    <ComponentCard title="Links and Buttons">
      <p className="text-muted">
        Use <code>&lt;a&gt;</code>s or
        <code>&lt;button&gt;</code>s to create <em>actionable</em> list group items with hover, disabled, and active states by adding
        <code>.list-group-item-action</code>.
      </p>
      <ListGroup>
        <ListGroupItem active action>
          Stripe Payment Integration
        </ListGroupItem>
        <ListGroupItem action>Dropbox Cloud Service</ListGroupItem>
        <button type="button" className="list-group-item list-group-item-action">
          Slack Communication
        </button>
        <button type="button" className="list-group-item list-group-item-action">
          Notion Productivity App
        </button>
        <ListGroupItem action disabled>
          Zendesk Support Tool
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const Flush = () => {
  return (
    <ComponentCard title="Flush">
      <p className="text-muted">
        Add <code>.list-group-flush</code> to remove some borders and rounded corners to render list group items edge-to-edge in a parent container
        (e.g., cards).
      </p>
      <ListGroup variant="flush">
        <ListGroupItem>Slack Collaboration Tool</ListGroupItem>
        <ListGroupItem>Dropbox Cloud Storage</ListGroupItem>
        <ListGroupItem>Notion Workspace Organizer</ListGroupItem>
        <ListGroupItem>Zendesk Customer Support</ListGroupItem>
        <ListGroupItem>Stripe Payment Processor</ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const Horizontal = () => {
  return (
    <ComponentCard title="Horizontal">
      <p className="text-muted">
        Add <code>.list-group-horizontal</code> to change the layout of list group items from vertical to horizontal across all breakpoints.
        Alternatively, choose a responsive variant
        <code>.list-group-horizontal-sm | md | lg | xl </code> to make a list group horizontal starting at that breakpoint’s <code>min-width</code>.
      </p>
      <ListGroup horizontal className="mb-3">
        <ListGroupItem>Slack</ListGroupItem>
        <ListGroupItem>Notion</ListGroupItem>
        <ListGroupItem>Dropbox</ListGroupItem>
      </ListGroup>
      <ListGroup horizontal="sm" className="mb-3">
        <ListGroupItem>Figma</ListGroupItem>
        <ListGroupItem>Stripe</ListGroupItem>
        <ListGroupItem>Zendesk</ListGroupItem>
      </ListGroup>
      <ListGroup horizontal="md">
        <ListGroupItem>Trello</ListGroupItem>
        <ListGroupItem>Asana</ListGroupItem>
        <ListGroupItem>ClickUp</ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const ContextualClasses = () => {
  return (
    <ComponentCard title="Contextual classes">
      <p className="text-muted">Use contextual classes to style list items with a stateful background and color.</p>
      <ListGroup>
        <ListGroupItem>Dapibus ac facilisis in</ListGroupItem>
        <ListGroupItem variant="primary">A simple primary list group item</ListGroupItem>
        <ListGroupItem variant="secondary">A simple secondary list group item</ListGroupItem>
        <ListGroupItem variant="success">A simple success list group item</ListGroupItem>
        <ListGroupItem variant="danger">A simple danger list group item</ListGroupItem>
        <ListGroupItem variant="warning">A simple warning list group item</ListGroupItem>
        <ListGroupItem variant="info">A simple info list group item</ListGroupItem>
        <ListGroupItem variant="light">A simple light list group item</ListGroupItem>
        <ListGroupItem variant="dark">A simple dark list group item</ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const ContextualClassesWithLink = () => {
  return (
    <ComponentCard title="Contextual classes with Link">
      <p className="text-muted">Use contextual classes to style list items with a stateful background and color.</p>
      <ListGroup>
        <ListGroupItem action>Darius ac facilities in</ListGroupItem>
        <ListGroupItem action variant="primary">
          A simple primary list group item
        </ListGroupItem>
        <ListGroupItem action variant="secondary">
          A simple secondary list group item
        </ListGroupItem>
        <ListGroupItem action variant="success">
          A simple success list group item
        </ListGroupItem>
        <ListGroupItem action variant="danger">
          A simple danger list group item
        </ListGroupItem>
        <ListGroupItem action variant="warning">
          A simple warning list group item
        </ListGroupItem>
        <ListGroupItem action variant="info">
          A simple info list group item
        </ListGroupItem>
        <ListGroupItem action variant="light">
          A simple light list group item
        </ListGroupItem>
        <ListGroupItem action variant="dark">
          A simple dark list group item
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const CustomContent = () => {
  return (
    <ComponentCard title="Custom content">
      <p className="text-muted">Add nearly any HTML within, even for linked list groups like the one below, with the help of flexbox utilities.</p>
      <ListGroup>
        <ListGroupItem action active>
          <div className="d-flex w-100 justify-content-between">
            <h5 className="mb-1">List group item heading</h5>
            <small>3 days ago</small>
          </div>
          <p className="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          <small>Donec id elit non mi porta.</small>
        </ListGroupItem>
        <ListGroupItem action>
          <div className="d-flex w-100 justify-content-between">
            <h5 className="mb-1">List group item heading</h5>
            <small className="text-muted">3 days ago</small>
          </div>
          <p className="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          <small className="text-muted">Donec id elit non mi porta.</small>
        </ListGroupItem>
        <ListGroupItem action>
          <div className="d-flex w-100 justify-content-between">
            <h5 className="mb-1">List group item heading</h5>
            <small className="text-muted">3 days ago</small>
          </div>
          <p className="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
          <small className="text-muted">Donec id elit non mi porta.</small>
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const WithBadges = () => {
  return (
    <ComponentCard title="With badges">
      <p className="text-muted">Add badges to any list group item to show unread counts, activity, and more with the help of some utilities.</p>
      <ListGroup>
        <ListGroupItem className="d-flex justify-content-between align-items-center">
          Gmail Notifications
          <span className="badge bg-primary rounded-pill">14</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-center">
          Unprocessed Orders
          <span className="badge bg-success rounded-pill">2</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-center">
          Urgent Tickets
          <span className="badge bg-danger rounded-pill">99+</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-center">
          Completed Transactions
          <span className="badge bg-success rounded-pill">20+</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-center">
          Invoices Awaiting Approval
          <span className="badge bg-warning rounded-pill">12</span>
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const CheckboxesAndRadios = () => {
  return (
    <ComponentCard title="Checkboxes and radios">
      <p className="text-muted">
        Place Bootstrap’s checkboxes and radios within list group items and customize as needed. You can use them without
        <code>&lt;label&gt;</code>s, but please remember to include an
        <code>aria-label</code> attribute and value for accessibility.
      </p>
      <ListGroup>
        <ListGroupItem>
          <FormCheckInput className="me-1" type="checkbox" id="firstCheckbox" />
          &nbsp;
          <FormCheckLabel htmlFor="firstCheckbox">Subscribe to newsletter</FormCheckLabel>
        </ListGroupItem>
        <ListGroupItem>
          <FormCheckInput className="me-1" type="checkbox" id="secondCheckbox" />
          &nbsp;
          <FormCheckLabel htmlFor="secondCheckbox">Accept terms and conditions</FormCheckLabel>
        </ListGroupItem>
      </ListGroup>
      <ul className="list-group mt-2">
        <ListGroupItem>
          <FormCheckInput className="me-1" type="radio" name="listGroupRadio" id="firstRadio" defaultChecked />
          &nbsp;
          <FormCheckLabel htmlFor="firstRadio">Notify by Email</FormCheckLabel>
        </ListGroupItem>
        <ListGroupItem>
          <FormCheckInput className="me-1" type="radio" name="listGroupRadio" id="secondRadio" />
          &nbsp;
          <FormCheckLabel htmlFor="secondRadio">Notify by SMS</FormCheckLabel>
        </ListGroupItem>
      </ul>
    </ComponentCard>
  )
}

const Numbered = () => {
  return (
    <ComponentCard title="Numbered">
      <p className="text-muted">
        Numbers are generated by <code>counter-reset</code> on the <code>&lt;ol&gt;</code>, and then styled and placed with a<code>::before</code>
        psuedo-element on the <code>&lt;li&gt;</code> with
        <code>counter-increment</code> and <code>content</code>.
      </p>
      <ListGroup numbered as={'ol'}>
        <ListGroupItem className="d-flex justify-content-between align-items-start">
          <div className="ms-2 me-auto">
            <div className="fw-bold">INSPINIA Admin</div>
            INSPINIA Admin
          </div>
          <span className="badge bg-primary rounded-pill">865</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-start">
          <div className="ms-2 me-auto">
            <div className="fw-bold">INSPINIA React Admin</div>
            INSPINIA React Admin
          </div>
          <span className="badge bg-primary rounded-pill">140</span>
        </ListGroupItem>
        <ListGroupItem className="d-flex justify-content-between align-items-start">
          <div className="ms-2 me-auto">
            <div className="fw-bold">Angular Version</div>
            Angular Version
          </div>
          <span className="badge bg-primary rounded-pill">85</span>
        </ListGroupItem>
      </ListGroup>
    </ComponentCard>
  )
}

const Page = () => {
  return (
    <MainLayout>
      <Container fluid>
        <PageBreadcrumb title="List Group" subtitle="UI" />
        <Container fluid="xl">
          <Row>
            <Col lg={12}>
              <Card>
                <CardHeader>
                  <CardTitle as={'h4'}>Examples</CardTitle>
                </CardHeader>
                <CardBody>
                  <p className="text-muted mb-2">
                    List groups are a flexible and powerful component for displaying a series of content. Modify and extend them to support just about
                    any content within.
                  </p>
                  <Link className="btn btn-link p-0 fw-semibold" href="https://react-bootstrap.netlify.app/docs/components/list-group" target="_blank">
                    List Group on React Bootstrap
                    <TbChevronRight className="ms-1" />
                  </Link>
                </CardBody>
              </Card>
            </Col>
            <Col xl={4}>
              <BasicExample />
            </Col>
            <Col xl={4}>
              <ActiveItems />
            </Col>
            <Col xl={4}>
              <DisabledItems />
            </Col>
            <Col xl={4}>
              <LinksAndButtons />
            </Col>
            <Col xl={4}>
              <Flush />
            </Col>
            <Col xl={4}>
              <Horizontal />
            </Col>
            <Col xl={4}>
              <ContextualClasses />
            </Col>
            <Col xl={4}>
              <ContextualClassesWithLink />
            </Col>
            <Col xl={4}>
              <CustomContent />
            </Col>
            <Col xl={4}>
              <WithBadges />
            </Col>
            <Col xl={4}>
              <CheckboxesAndRadios />
            </Col>
            <Col xl={4}>
              <Numbered />
            </Col>
          </Row>
        </Container>
      </Container>
    </MainLayout>
  )
}

export default Page
