// SvelteKit/Seed/src/lib/layouts/components/sidenav/components/AppMenu.svelte
<script lang="ts">
	import MenuItemWithChildren from '$lib/layouts/components/sidenav/components/MenuItemWithChildren.svelte';
	import MenuItem from '$lib/layouts/components/sidenav/components/MenuItem.svelte';
	import { scrollToElement } from '$lib/helpers/layout';
	import { onMount } from 'svelte';
	import { menuItems } from '$lib/layouts/components/data';
	import { writable } from 'svelte/store';

	const openMenuKey = writable<string | null>(null);

	const setOpenMenuKey = (key: string | null) => {
		openMenuKey.set(key);
	};

	const scrollToActiveLink = () => {
		const activeItem: HTMLAnchorElement | null = document.querySelector('.side-nav-link.active');
		if (activeItem) {
			const simpleBarContent = document.querySelector('#sidenav .simplebar-content-wrapper');
			if (simpleBarContent) {
				const containerRect = simpleBarContent.getBoundingClientRect();
				const itemRect = activeItem.getBoundingClientRect();

				const offset = itemRect.top - containerRect.top - window.innerHeight * 0.4;

				scrollToElement(simpleBarContent, simpleBarContent.scrollTop + offset, 500);
			}
		}
	};

	onMount(() => {
		setTimeout(() => scrollToActiveLink(), 100);
	});
</script>

<ul class="side-nav">
	{#each menuItems || [] as item, idx (idx)}
		{#if item.isTitle}
			<li class="side-nav-title">{item.label}</li>
		{:else if item.children}
			<MenuItemWithChildren {item} openMenuKey={$openMenuKey} {setOpenMenuKey} />
		{:else}
			<MenuItem {item} />
		{/if}
	{/each}
</ul>

// src/layouts/components/sidenav/components/AppMenu.vue
<template>
  <ul class="side-nav">
    <template v-for="(item, idx) in menuItems">
      <li v-if="item.isTitle" :key="item.key" class="side-nav-title">{{ tTitle(item.label) }}</li>
      <template v-else>
        <MenuItemWithChildren
          v-if="item.children"
          :key="item.key"
          :item="item"
          :open-menu-key="openMenuKey"
          :set-open-menu-key="setOpenMenuKey"
        />
        <MenuItem v-else :key="idx" :item="item" />
      </template>
    </template>
  </ul>
</template>

<script setup lang="ts">
import MenuItemWithChildren from '@/layouts/components/sidenav/components/MenuItemWithChildren.vue'
import MenuItem from '@/layouts/components/sidenav/components/MenuItem.vue'
import { menuItems } from '@/layouts/components/data'
import { scrollToElement } from '@/helpers/layout'
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const TITLE_MAP: Record<string, string> = {
  'MENU': 'nav.section_menu',
  'APPS': 'nav.section_apps',
  'CUSTOM PAGES': 'nav.section_custom_pages',
  'LAYOUTS': 'nav.section_layouts',
  'COMPONENTS': 'nav.section_components',
  'MENU ITEMS': 'nav.section_menu_items',
}
function tTitle(label: string | undefined) {
  if (!label) return ''
  return TITLE_MAP[label] ? t(TITLE_MAP[label]) : label
}

const openMenuKey = ref<string | null>(null)

const setOpenMenuKey = (key: string | null) => {
  openMenuKey.value = key
}

const scrollToActiveLink = () => {
  const activeItem: HTMLAnchorElement | null = document.querySelector('.side-nav-link.active')
  if (activeItem) {
    const simpleBarContent = document.querySelector('#sidenav .simplebar-content-wrapper')
    if (simpleBarContent) {
      const containerRect = simpleBarContent.getBoundingClientRect()
      const itemRect = activeItem.getBoundingClientRect()

      const offset = itemRect.top - containerRect.top - window.innerHeight * 0.4

      scrollToElement(simpleBarContent, simpleBarContent.scrollTop + offset, 500)
    }
  }
}

onMounted(() => {
  setTimeout(() => scrollToActiveLink(), 100)
})
</script>
