// Angular/Full/src/app/views/apps/projects/kanban-board/kanban-board.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {NgIcon} from '@ng-icons/core';
import {LucideAngularModule, LucideBriefcase, LucideCalendarClock, LucideSearch} from 'lucide-angular';
import {TaskItemType} from '@/app/views/apps/projects/kanban-board/types';
import {
    CdkDrag,
    CdkDragDrop,
    CdkDropList,
    CdkDropListGroup,
    moveItemInArray,
    transferArrayItem,
} from '@angular/cdk/drag-drop'
import {TaskItemComponent} from '@/app/views/apps/projects/kanban-board/components/task-item.component';
import {SimplebarAngularModule} from 'simplebar-angular';
import {RouterLink} from '@angular/router';

@Component({
    selector: 'app-kanban-board',
    imports: [
        PageTitleComponent,
        NgIcon,
        LucideAngularModule,
        CdkDropListGroup, CdkDropList, CdkDrag, TaskItemComponent, SimplebarAngularModule, RouterLink
    ],
    templateUrl: './kanban-board.component.html',
    styles: ``
})
export class KanbanBoardComponent implements OnInit{

    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideBriefcase = LucideBriefcase;
    protected readonly LucideCalendarClock = LucideCalendarClock;

    todoTasks: TaskItemType[] = []
    inprogressTasks: TaskItemType[] = []
    inreviewTasks: TaskItemType[] = []
    completedTasks: TaskItemType[] = []

    ngOnInit(): void {
        this.todoTasks = this.kanbanItems.filter((t) => t.status === 'todo')
        this.inprogressTasks = this.kanbanItems.filter((t) => t.status === 'in-progress')
        this.inreviewTasks = this.kanbanItems.filter((t) => t.status === 'in-review')
        this.completedTasks = this.kanbanItems.filter((t) => t.status === 'done')
    }

    drop(event: CdkDragDrop<TaskItemType[], any, any>) {
        if (event.previousContainer === event.container) {
            moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
        } else {
            transferArrayItem(
                event.previousContainer.data,
                event.container.data,
                event.previousIndex,
                event.currentIndex,
            );
        }
    }

    kanbanItems: TaskItemType[] = [
        {
            id: 1,
            category: {
                name: 'Design',
                variant: 'success',
            },
            title: 'AI Analytics Dashboard',
            users: [
                'assets/images/users/user-2.jpg',
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-1.jpg'
            ],
            date: '25 May, 2025',
            status: 'todo',
            progress: 65
        },
        {
            id: 2,
            category: {
                name: 'Development',
                variant: 'warning',
            },
            title: 'Marketing Landing Page Redesign',
            users: [
                'assets/images/users/user-6.jpg',
                'assets/images/users/user-4.jpg',
                'assets/images/users/user-8.jpg'
            ],
            date: '10 Jun, 2025',
            image: 'assets/images/kanban/img-1.png',
            status: 'todo'
        },
        {
            id: 3,
            category: {
                name: 'UI/UX',
                variant: 'info',
            },
            title: 'E-Commerce Website Redesign',
            users: [
                'assets/images/users/user-4.jpg',
                'assets/images/users/user-6.jpg',
                'assets/images/users/user-7.jpg',
                'assets/images/users/user-8.jpg'
            ],
            date: '28 May, 2025',
            status: 'todo'
        },
        {
            id: 4,
            category: {
                name:'App Development',
                variant: 'warning',
            },
            title: 'Mobile App Redesign',
            users: [
                'assets/images/users/user-1.jpg',
                'assets/images/users/user-2.jpg',
                'assets/images/users/user-3.jpg'
            ],
            date: '30 May, 2025',
            status: 'todo',
            progress: 80
        },
        {
            id: 5,
            category: {
                name: 'Marketing',
                variant: 'purple',
            },
            title: 'CRM System Upgrade',
            users: ['assets/images/users/user-4.jpg'],
            date: '30 May, 2025',
            image: 'assets/images/kanban/img-2.png',
            status: 'todo',
            progress: 45
        },

        {
            id: 6,
            category: {
                name: 'Testing',
                variant: 'info',
            },
            title: 'E-commerce Website QA Testing',
            users: [
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-7.jpg',
                'assets/images/users/user-9.jpg'
            ],
            date: '18 Jun, 2025',
            status: 'in-progress'
        },
        {
            id: 7,
            category: {
                name:'UI/UX',
                variant: 'info',
            },
            title: 'Mobile App Redesign',
            users: [
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-2.jpg',
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-9.jpg'
            ],
            date: '10 Jun, 2025',
            status: 'in-progress'
        },
        {
            id: 8,
            category: {
                name:'UI/UX Design',
                variant: 'success',
            },
            title: 'Website User Experience Overhaul',
            users: [
                'assets/images/users/user-4.jpg',
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-6.jpg'
            ],
            date: '15 June, 2025',
            status: 'in-progress',
            progress: 55
        },
        {
            id: 9,
            category: {
                name: 'Marketing',
                variant: 'danger',
            },
            title: 'Customer Engagement Platform Development',
            users: [
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-6.jpg'
            ],
            date: '10 June, 2025',
            status: 'in-progress'
        },

        {
            id: 10,
            category: {
                name: 'Design',
                variant: 'success',
            },
            title: 'AI Analytics Dashboard',
            users: [
                'assets/images/users/user-2.jpg',
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-1.jpg'
            ],
            date: '25 May, 2025',
            image: 'assets/images/kanban/img-3.png',
            status: 'in-review',
            progress: 65
        },
        {
            id: 11,
            category: {
                name: 'Development',
                variant: 'warning',
            },
            title: 'Marketing Landing Page Redesign',
            users: [
                'assets/images/users/user-6.jpg',
                'assets/images/users/user-4.jpg',
                'assets/images/users/user-8.jpg'
            ],
            date: '10 Jun, 2025',
            status: 'in-review'
        },
        {
            id: 12,
            category: {
                name:'UI/UX',
                variant: 'info',
            },
            title: 'E-Commerce Website Redesign',
            users: [
                'assets/images/users/user-4.jpg',
                'assets/images/users/user-6.jpg',
                'assets/images/users/user-7.jpg',
                'assets/images/users/user-8.jpg'
            ],
            date: '28 May, 2025',
            status: 'in-review'
        },

        // Done
        {
            id: 13,
            category: {
                name: 'Testing',
                variant: 'info',
            },
            title: 'E-commerce Website QA Testing',
            users: [
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-7.jpg',
                'assets/images/users/user-9.jpg'
            ],
            date: '18 Jun, 2025',
            status: 'done'
        },
        {
            id: 14,
            category: {
                name:'UI/UX',
                variant: 'info',
            },
            title: 'Mobile App Redesign',
            users: [
                'assets/images/users/user-5.jpg',
                'assets/images/users/user-2.jpg',
                'assets/images/users/user-3.jpg',
                'assets/images/users/user-9.jpg'
            ],
            date: '10 Jun, 2025',
            image: 'assets/images/kanban/img-4.png',
            status: 'done'
        }
    ];

}

<div class="container-fluid">
    <app-page-title title="Kanban Board" subTitle="Projects"/>

    <div class="outlook-box kanban-app">
        <div class="card h-100 mb-0 flex-grow-1">
            <div class="card-header border-light align-items-center gap-2">
                <div class="app-search">
                    <input type="search" class="form-control" placeholder="Search tasks...">
                    <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                </div>

                <div class="d-flex flex-wrap align-items-center gap-2">
                    <div class="app-search">
                        <select class="form-select form-control">
                            <option selected>Department</option>
                            <option value="Design">Design</option>
                            <option value="Development">Development</option>
                            <option value="UI/UX">UI/UX</option>
                            <option value="Marketing">Marketing</option>
                            <option value="Finance">Finance</option>
                            <option value="QA">QA</option>
                        </select>
                        <lucide-angular [img]="LucideBriefcase" class="app-search-icon text-muted"/>
                    </div>

                    <div class="app-search">
                        <select class="form-select form-control">
                            <option selected>Due Date</option>
                            <option value="Today">Today</option>
                            <option value="This Week">This Week</option>
                            <option value="This Month">This Month</option>
                        </select>
                        <lucide-angular [img]="LucideCalendarClock" class="app-search-icon text-muted"></lucide-angular>
                    </div>
                </div>

                <button type="submit" class="btn btn-secondary ms-lg-auto">
                    <ng-icon name="tablerPlus" class="me-1"/>
                    Add New Card
                </button>
            </div>

            <div class="card-body p-0">
                <div class="kanban-content bg-light bg-opacity-40" cdkDropListGroup>

                    <div class="kanban-board">
                        <div class="kanban-item py-2 px-3 d-flex align-items-center">
                            <h5 class="m-0">To Do ({{ todoTasks.length }})</h5>
                            <a [routerLink]="[]" class="ms-auto btn btn-sm btn-icon rounded-circle btn-primary">
                                <ng-icon
                                    name="tablerPlus"/>
                            </a>
                        </div>
                        <div class="kanban-board-group px-3" (cdkDropListDropped)="drop($event)"
                             cdkDropList
                             [cdkDropListData]="todoTasks">
                            <ngx-simplebar style="height: 100%;">
                                <ul>
                                    @for (task of todoTasks; track task.id; ) {
                                        <li class="kanban-item">
                                            <app-task-item [item]="task" cdkDrag/>
                                        </li>
                                    }
                                </ul>
                            </ngx-simplebar>
                        </div>
                    </div>

                    <div class="kanban-board">
                        <div class="py-2 px-3 d-flex align-items-center">
                            <h5 class="m-0">In Progress ({{ inprogressTasks.length }})</h5>
                            <a [routerLink]="[]" class="ms-auto btn btn-sm btn-icon rounded-circle btn-primary">
                                <ng-icon
                                    name="tablerPlus"/>
                            </a>
                        </div>
                        <div class="kanban-board-group px-3" (cdkDropListDropped)="drop($event)"
                             cdkDropList
                             [cdkDropListData]="inprogressTasks">
                            <ngx-simplebar style="height: 100%;">
                                <ul>
                                    @for (task of inprogressTasks; track task.id) {
                                        <li class="kanban-item">
                                            <app-task-item [item]="task" cdkDrag/>
                                        </li>
                                    }
                                </ul>
                            </ngx-simplebar>
                        </div>
                    </div>


                    <div class="kanban-board">
                        <div class="kanban-item py-2 px-3 d-flex align-items-center">
                            <h5 class="m-0">In Review ({{ inreviewTasks.length }})</h5>
                            <a [routerLink]="[]" class="ms-auto btn btn-sm btn-icon rounded-circle btn-primary">
                                <ng-icon
                                    name="tablerPlus"/>
                            </a>
                        </div>
                        <div class="kanban-board-group px-3" (cdkDropListDropped)="drop($event)"
                             cdkDropList
                             [cdkDropListData]="inreviewTasks">
                            <ngx-simplebar style="height: 100%;">
                                <ul>
                                    @for (task of inreviewTasks; track task.id) {
                                        <li class="kanban-item">
                                            <app-task-item [item]="task" cdkDrag/>
                                        </li>
                                    }
                                </ul>
                            </ngx-simplebar>
                        </div>
                    </div>

                    <div class="kanban-board">
                        <div class="py-2 px-3 d-flex align-items-center">
                            <h5 class="m-0">Done ({{ completedTasks.length }})</h5>
                            <a [routerLink]="[]" class="ms-auto btn btn-sm btn-icon rounded-circle btn-primary">
                                <ng-icon
                                    name="tablerPlus"/>
                            </a>
                        </div>
                        <div class="kanban-board-group px-3" (cdkDropListDropped)="drop($event)"
                             cdkDropList
                             [cdkDropListData]="completedTasks">
                            <ngx-simplebar style="height: 100%;">
                                <ul>
                                    @for (task of completedTasks; track task.id) {
                                        <li class="kanban-item">
                                            <app-task-item [item]="task" cdkDrag/>
                                        </li>
                                    }
                                </ul>
                            </ngx-simplebar>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// Vue/Full/src/views/apps/projects/kanban-board/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Kanban Board" subTitle="Projects" />

            <div class="outlook-box kanban-app">
                <BCard no-body class="h-100 mb-0 flex-grow-1">
                    <BCardHeader class="border-light align-items-center gap-2">

                        <div class="app-search">
                            <input type="search" class="form-control" placeholder="Search tasks...">
                            <Icon  icon="lucide:search" class="app-search-icon text-muted" />
                        </div>

                        <div class="d-flex flex-wrap align-items-center gap-2">

                            <div class="app-search">
                                <select class="form-select form-control">
                                    <option selected>Department</option>
                                    <option value="Design">Design</option>
                                    <option value="Development">Development</option>
                                    <option value="UI/UX">UI/UX</option>
                                    <option value="Marketing">Marketing</option>
                                    <option value="Finance">Finance</option>
                                    <option value="QA">QA</option>
                                </select>
                                <Icon  icon="lucide:briefcase" class="app-search-icon text-muted" />
                            </div>

                            <div class="app-search">
                                <select class="form-select form-control">
                                    <option selected>Due Date</option>
                                    <option value="Today">Today</option>
                                    <option value="This Week">This Week</option>
                                    <option value="This Month">This Month</option>
                                </select>
                                <Icon  icon="lucide:calendar-clock" class="app-search-icon text-muted" />
                            </div>
                        </div>

                        <button type="submit" class="btn btn-secondary ms-lg-auto">
                            <Icon icon="tabler:plus" class="me-1" /> Add New
                            Card
                        </button>
                    </BCardHeader>

                    <BCardBody class="p-0">
                        <div class="kanban-content bg-light bg-opacity-40">

                            <div v-for="(status, idx) in statuses" :key="idx" class="kanban-board">
                                <div class="kanban-item py-2 px-3 d-flex align-items-center">
                                    <h5 class="m-0">{{ toTitleCase(status) }} ({{ tasksByStatus(status).length }})</h5>
                                    <RouterLink to="" class="ms-auto btn btn-sm btn-icon rounded-circle btn-primary">
                                        <Icon icon="tabler:plus" />
                                    </RouterLink>
                                </div>
                                <simplebar class="kanban-board-group px-3">
                                    <ul data-plugins="sortable">
                                        <li class="kanban-item" v-for="(task, idx) in tasksByStatus(status)" :key="idx">
                                            <VueDraggableNext group="project-task" id="project-tasks-list">
                                                <TaskCard :item="task" />
                                            </VueDraggableNext>
                                        </li>
                                    </ul>
                                </simplebar>
                            </div>
                        </div>
                    </BCardBody>
                </BCard>
            </div>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardHeader, BContainer } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { KanbanTaskData, type KanbanTaskType } from './data';
import TaskCard from './components/TaskCard.vue';
import simplebar from 'simplebar-vue';
import { VueDraggableNext } from 'vue-draggable-next'
import { toTitleCase } from '@/helpers/casing';
import { usePageMeta } from '@/composables/usePageMeta';
import { Icon } from '@iconify/vue';
import MainLayout from '@/layouts/MainLayout.vue';

const statuses: KanbanTaskType['status'][] = ['todo', 'in-progress', 'in-review', 'done']

const tasksByStatus = (status: string) => {
    return KanbanTaskData.filter((task: KanbanTaskType) => task.status === status)
}

usePageMeta('Kanban Board')

</script>

<style lang="scss" scoped></style>
