// Seed/src/layouts/MainLayout.vue
<template>
  <VerticalLayout v-if="layout.orientation === 'vertical'">
    <slot />
  </VerticalLayout>

  <HorizontalLayout v-if="layout.orientation === 'horizontal'">
    <slot />
  </HorizontalLayout>
</template>

<script setup lang="ts">
import VerticalLayout from '@/layouts/VerticalLayout.vue'
import HorizontalLayout from '@/layouts/HorizontalLayout.vue'
import { useLayout } from '@/stores/layout.ts'

const { layout } = useLayout()
</script>

// NextJs/NextJs/Seed/JS/src/layouts/MainLayout.jsx
'use client';

import Loader from '@/components/Loader';
import { useLayoutContext } from '@/context/useLayoutContext';
import HorizontalLayout from '@/layouts/HorizontalLayout';
import VerticalLayout from '@/layouts/VerticalLayout';
import { Fragment, useEffect, useState } from 'react';
const MainLayout = ({
  children
}) => {
  const {
    orientation
  } = useLayoutContext();
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) return <Loader height="100vh" />;
  return <Fragment>
      {orientation === 'vertical' && <VerticalLayout>{children}</VerticalLayout>}
      {orientation === 'horizontal' && <HorizontalLayout>{children}</HorizontalLayout>}
    </Fragment>;
};
export default MainLayout;
