// NextJs/NextJs/Full/JS/src/app/(admin)/(apps)/(projects)/projects/components/ProjectCard2.jsx
import { toPascalCase } from '@/helpers/casing';
import clsx from 'clsx';
import Image from 'next/image';
import Link from 'next/link';
import { Card, CardBody, CardHeader, Col, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, ProgressBar, Row } from 'react-bootstrap';
import { TbBan, TbCalendarTime, TbDotsVertical, TbEdit, TbListCheck, TbMessage2, TbPaperclip, TbShare, TbTrash } from 'react-icons/tb';
const ProjectCard2 = ({
  project
}) => {
  const {
    comments,
    date,
    icon: Icon,
    progress,
    members,
    status,
    task,
    title,
    updatedTime,
    variant,
    files
  } = project;
  return <Card>
      <CardHeader className="bg-light-subtle border-light p-3">
        <div className="avatar-xl me-3">
          <span className="avatar-title text-bg-light rounded-circle">
            <Icon className={`fs-24 text-${variant}`} />
          </span>
        </div>
        <div>
          <h5 className="mb-1 d-flex align-items-center">
            <Link href="/projects/" className="link-reset">
              {title}
            </Link>
          </h5>
          <p className="text-muted mb-2 fs-xxs">Updated {updatedTime}</p>
          <span className={clsx('badge fs-xxs badge-label', status === 'delayed' ? 'badge-soft-danger' : status === 'pending-review' ? 'badge-soft-warning' : 'badge-soft-success')}>
            {toPascalCase(status)}
          </span>
        </div>
        <div className="ms-auto">
          <Dropdown>
            <DropdownToggle className="btn btn-icon btn-ghost-light text-muted drop-arrow-none">
              <TbDotsVertical className="fs-xl" />
            </DropdownToggle>
            <DropdownMenu className="dropdown-menu-end">
              <li>
                <DropdownItem href="#">
                  <TbShare className="me-2" />
                  Share
                </DropdownItem>
              </li>
              <li>
                <DropdownItem href="#">
                  <TbEdit className="me-2" />
                  Edit
                </DropdownItem>
              </li>
              <li>
                <DropdownItem href="#">
                  <TbBan className="me-2" />
                  Block
                </DropdownItem>
              </li>
              <li>
                <DropdownItem className="text-danger" href="#">
                  <TbTrash className="me-2" />
                  Delete
                </DropdownItem>
              </li>
            </DropdownMenu>
          </Dropdown>
        </div>
      </CardHeader>
      <CardBody>
        <Row>
          <Col sm={6}>
            <div className="d-flex align-items-center gap-2 mb-3">
              <TbListCheck className="text-muted fs-lg" />
              <h5 className="fs-base mb-0 fw-medium">
                {task.completed}/{task.total}&nbsp;
                {task.new && <span className="badge bg-secondary">+{task.new} New</span>}
              </h5>
            </div>
          </Col>
          <Col sm={6}>
            <div className="d-flex align-items-center gap-2 mb-3">
              <TbPaperclip className="text-muted fs-lg" />
              <h5 className="fs-base mb-0 fw-medium">{files} Files</h5>
            </div>
          </Col>
        </Row>

        <Row>
          <Col sm={6}>
            <div className="d-flex align-items-center gap-2 mb-3">
              <TbMessage2 className="text-muted fs-lg" />
              <h5 className="fs-base mb-0 fw-medium">{comments} Comments</h5>
            </div>
          </Col>
          <Col sm={6}>
            <div className="d-flex align-items-center gap-2 mb-3">
              <TbCalendarTime className="text-muted fs-lg" />
              <h5 className="fs-base mb-0 fw-medium">{date}</h5>
            </div>
          </Col>
        </Row>

        <p className="my-2 text-muted fw-semibold fs-xxs">Team Members:</p>
        <div className="avatar-group avatar-group-xs mb-3">
          {members.map((member, idx) => <div className="avatar" key={idx}>
              <Image src={member} alt="" className="rounded-circle avatar-xs" />
            </div>)}
        </div>

        <div className="mt-3">
          <div className="d-flex align-items-center justify-content-between mb-2">
            <p className="mb-0 text-muted fw-semibold fs-xxs">Progress</p>
            <p className="fw-semibold mb-0">{progress}%</p>
          </div>
          <ProgressBar variant={variant} now={progress} style={{
          height: '5px'
        }} />
        </div>
      </CardBody>
    </Card>;
};
export default ProjectCard2;

// Vue-Inertia/Full/resources/js/pages/apps/projects/projects/components/ProjectCard2.vue
<template>
 <BCard no-body>
    <BCardHeader class="bg-light-subtle border-light p-3 d-flex align-items-center">
      <div class="avatar-xl me-3">
        <span class="avatar-title text-bg-light rounded-circle">
          <Icon :icon="project.icon" :class="`fs-24 text-${project.variant}`" />
        </span>
      </div>

      <div>
        <h5 class="mb-1 d-flex align-items-center">
          <Link href="/projects" class="link-reset">
            {{ project.title }}
          </Link>
        </h5>
        <p class="text-muted mb-2 fs-xxs">Updated {{ project.updatedTime }}</p>
        <span
          :class="clsx(
            'badge fs-xxs badge-label',
            project.status === 'delayed'
              ? 'badge-soft-danger'
              : project.status === 'pending-review'
              ? 'badge-soft-warning'
              : 'badge-soft-success'
          )"
        >
          {{ toPascalCase(project.status) }}
        </span>
      </div>

      <div class="ms-auto">
        <BDropdown placement="bottom-end" toggle-class="btn btn-icon btn-ghost-light text-muted drop-arrow-none">
          <template #button-content>
            <Icon icon="tabler:dots-vertical" class="fs-xl" />
          </template>
          <BDropdownItem>
            <Icon icon="tabler:share" class="me-2" />
            Share
          </BDropdownItem>
          <BDropdownItem>
            <Icon icon="tabler:edit" class="me-2" />
            Edit
          </BDropdownItem>
          <BDropdownItem>
            <Icon icon="tabler:ban" class="me-2" />
            Block
          </BDropdownItem>
          <BDropdownItem class="text-danger">
            <Icon icon="tabler:trash" class="me-2" />
            Delete
          </BDropdownItem>
        </BDropdown>
      </div>
    </BCardHeader>

    <BCardBody>
      <BRow>
        <BCol sm="6">
          <div class="d-flex align-items-center gap-2 mb-3">
            <Icon icon="tabler:list-check" class="text-muted fs-lg" />
            <h5 class="fs-base mb-0 fw-medium">
              {{ project.task.completed }}/{{ project.task.total }}
              <span v-if="project.task.new" class="badge bg-secondary">+{{ project.task.new }} New</span>
            </h5>
          </div>
        </BCol>
        <BCol sm="6">
          <div class="d-flex align-items-center gap-2 mb-3">
            <Icon icon="tabler:paperclip" class="text-muted fs-lg" />
            <h5 class="fs-base mb-0 fw-medium">{{ project.files }} Files</h5>
          </div>
        </BCol>
      </BRow>

      <BRow>
        <BCol sm="6">
          <div class="d-flex align-items-center gap-2 mb-3">
            <Icon icon="tabler:message-2" class="text-muted fs-lg" />
            <h5 class="fs-base mb-0 fw-medium">{{ project.comments }} Comments</h5>
          </div>
        </BCol>
        <BCol sm="6">
          <div class="d-flex align-items-center gap-2 mb-3">
            <Icon icon="tabler:calendar-time" class="text-muted fs-lg" />
            <h5 class="fs-base mb-0 fw-medium">{{ project.date }}</h5>
          </div>
        </BCol>
      </BRow>

      <p class="my-2 text-muted fw-semibold fs-xxs">Team Members:</p>
      <div class="avatar-group avatar-group-xs mb-3">
        <div v-for="(member, idx) in project.members" :key="idx" class="avatar">
          <img :src="member" alt="" class="rounded-circle avatar-xs" />
        </div>
      </div>

      <div class="mt-3">
        <div class="d-flex align-items-center justify-content-between mb-2">
          <p class="mb-0 text-muted fw-semibold fs-xxs">Progress</p>
          <p class="fw-semibold mb-0">{{ project.progress }}%</p>
        </div>
        <BProgress :value="project.progress" :variant="project.variant" height="5px" />
      </div>
    </BCardBody>
  </BCard>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BCardHeader, BRow, BCol, BDropdown, BDropdownItem, BProgress } from 'bootstrap-vue-next';
import type { ProjectType } from '../data';
import clsx from 'clsx';
import { Icon } from '@iconify/vue';
import { toPascalCase } from '@/helpers/casing';
import { Link } from '@inertiajs/vue3';

defineProps<{ project: ProjectType }>()
</script>

<style scoped>

</style>
