// NextJs/NextJs/Seed/JS/src/app/(auth)/auth-1/delete-account/page.jsx
import deleteIcon from '@/assets/images/delete.png';
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';
import Image from 'next/image';
import { Button, Card, Col, Container, Row } from 'react-bootstrap';
const Page = () => {
  return <div className="auth-box overflow-hidden align-items-center d-flex">
      <Container>
        <Row className="justify-content-center">
          <Col xxl={4} md={6} sm={8}>
            <div className="auth-brand text-center mb-4">
              <AppLogo />
            </div>

            <Card className="p-4 rounded-4">
              <div className="mb-4">
                <div className="avatar-xxl mx-auto mt-2">
                  <div className="avatar-title bg-light-subtle border border-light border-dashed rounded-circle d-flex align-items-center justify-content-center">
                    <Image src={deleteIcon} alt="delete icon" height={64} />
                  </div>
                </div>
              </div>

              <h4 className="fw-bold text-center mb-3">Account Deactivated</h4>
              <p className="text-muted text-center mb-4">
                Your account is currently inactive. Reactivate now to regain access to all features and opportunities.
              </p>

              <div className="d-grid">
                <Button type="button" variant="primary" className="fw-semibold py-2">
                  Reactivate Now
                </Button>
              </div>
            </Card>

            <p className="text-center text-muted mt-4 mb-0">
              © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
            </p>
          </Col>
        </Row>
      </Container>
    </div>;
};
export default Page;

// SvelteKit/Seed/src/routes/(auth)/auth-1/delete-account/+page.svelte
<script lang="ts">
	import { author, currentYear } from '$lib/helpers';
	import { Button, Card, Col, Container, Row } from '@sveltestrap/sveltestrap';
	import PageMeta from '$lib/components/PageMeta.svelte';
	import AuthLogo from '$lib/components/AuthLogo.svelte';
	import deleteImage from '$lib/assets/images/delete.png';
</script>

<PageMeta title="Delete Account" />

<div class="auth-box overflow-hidden d-flex align-items-center">
	<Container>
		<Row class="justify-content-center">
			<Col sm="8" md="6" xxl="4">
				<div class="auth-brand text-center mb-4">
					<AuthLogo />
				</div>

				<Card class="p-4 rounded-4">
					<div class="mb-4">
						<div class="avatar-xxl mx-auto mt-2">
							<div
								class="avatar-title bg-light-subtle border border-light border-dashed rounded-circle"
							>
								<img src={deleteImage} alt="deactivated" height="64" />
							</div>
						</div>
					</div>

					<h4 class="fw-bold text-center mb-3">Account Deactivated</h4>
					<p class="text-muted text-center mb-4">
						Your account is currently inactive. Reactivate now to regain access to all features and
						opportunities.
					</p>

					<div class="d-grid">
						<Button color="primary" class="fw-semibold py-2">Reactivate Now</Button>
					</div>
				</Card>

				<p class="text-center text-muted mt-4 mb-0">
					© 2014 - {currentYear} INSPINIA — by <span class="fw-semibold">{author}</span>
				</p>
			</Col>
		</Row>
	</Container>
</div>
