// Angular/Full/src/app/views/ecommerce/customers/customers.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {RouterLink} from '@angular/router';
import {LucideAngularModule, LucideDownload, LucidePlus, LucideSearch} from 'lucide-angular';
import {AsyncPipe} from '@angular/common';
import {NgIcon} from '@ng-icons/core';
import {Observable} from 'rxjs';
import {TableService} from '@core/services/table.service';
import {FormsModule} from '@angular/forms';
import {NgbDropdownModule, NgbPaginationModule} from '@ng-bootstrap/ng-bootstrap';
import {currency} from '@/app/constants';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';

type CustomerType = {
    id: number;
    name: string;
    email: string;
    avatar: string;
    phone: string;
    countryFlag: string;
    country: string;
    date: string;
    time: string;
    orders: number;
    totalSpends: number;
    selected?: boolean
}

@Component({
    selector: 'app-customers',
    imports: [
        PageTitleComponent,
        RouterLink,
        LucideAngularModule,
        NgIcon,
        FormsModule,
        NgbDropdownModule,
        NgbPaginationModule,
        NgbdSortableHeader,
        AsyncPipe,
    ],
    providers: [TableService],
    templateUrl: './customers.component.html',
    styles: ``
})
export class CustomersComponent implements OnInit {
    customers$: Observable<CustomerType[]>
    total$: Observable<number>;

    constructor(public tableService: TableService<CustomerType>) {
        this.customers$ = this.tableService.items$
        this.total$ = this.tableService.total$
    }

    ngOnInit(): void {
        this.tableService.setItems(this.customers, 8)
    }

    selectAll = false;

    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    deleteSelected() {
        this.tableService.deleteSelectedItems();
        this.selectAll = false;
    }

    get hasSelection(): boolean {
        return this.tableService.hasSelectedItems();
    }

    customers: CustomerType[] = [
        {
            id: 1,
            name: 'Carlos Méndez',
            email: 'carlos@techlaunch.mx',
            avatar: 'assets/images/users/user-7.jpg',
            phone: '+1 (415) 992-3412',
            countryFlag: 'assets/images/flags/us.svg',
            country: 'United States',
            date: '2 Feb, 2024',
            time: '08:34 AM',
            orders: 58,
            totalSpends: 198.25
        },
        {
            id: 2,
            name: 'Sophie Laurent',
            email: 'sophie.laurent@eurotech.fr',
            avatar: 'assets/images/users/user-2.jpg',
            phone: '+33 6 12 34 56 78',
            countryFlag: 'assets/images/flags/fr.svg',
            country: 'France',
            date: '15 Mar, 2024',
            time: '10:22 AM',
            orders: 42,
            totalSpends: 245.80
        },
        {
            id: 3,
            name: 'Akira Tanaka',
            email: 'akira.tanaka@techjapan.co.jp',
            avatar: 'assets/images/users/user-3.jpg',
            phone: '+81 90-1234-5678',
            countryFlag: 'assets/images/flags/jp.svg',
            country: 'Japan',
            date: '28 Jan, 2024',
            time: '03:15 PM',
            orders: 75,
            totalSpends: 320.50
        },
        {
            id: 4,
            name: 'Emma Watson',
            email: 'emma.watson@britinnovate.uk',
            avatar: 'assets/images/users/user-4.jpg',
            phone: '+44 7700 900123',
            countryFlag: 'assets/images/flags/gb.svg',
            country: 'United Kingdom',
            date: '10 Apr, 2024',
            time: '09:47 AM',
            orders: 29,
            totalSpends: 175.30
        },
        {
            id: 5,
            name: 'Lucas Schmidt',
            email: 'lucas.schmidt@techdeutsch.de',
            avatar: 'assets/images/users/user-5.jpg',
            phone: '+49 151 23456789',
            countryFlag: 'assets/images/flags/de.svg',
            country: 'Germany',
            date: '20 Feb, 2024',
            time: '02:10 PM',
            orders: 63,
            totalSpends: 280.75
        },
        {
            id: 6,
            name: 'Isabella Rossi',
            email: 'isabella.rossi@italiatech.it',
            avatar: 'assets/images/users/user-6.jpg',
            phone: '+39 333 4567890',
            countryFlag: 'assets/images/flags/it.svg',
            country: 'Italy',
            date: '5 Mar, 2024',
            time: '11:25 AM',
            orders: 51,
            totalSpends: 210.40
        },
        {
            id: 7,
            name: 'Mateo Vargas',
            email: 'mateo.vargas@latamtech.ar',
            avatar: 'assets/images/users/user-8.jpg',
            phone: '+54 9 11 2345 6789',
            countryFlag: 'assets/images/flags/ar.svg',
            country: 'Argentina',
            date: '18 Apr, 2024',
            time: '04:50 PM',
            orders: 37,
            totalSpends: 190.20
        },
        {
            id: 8,
            name: 'Priya Sharma',
            email: 'priya.sharma@indotech.in',
            avatar: 'assets/images/users/user-9.jpg',
            phone: '+91 98765 43210',
            countryFlag: 'assets/images/flags/in.svg',
            country: 'India',
            date: '10 Jan, 2024',
            time: '06:30 AM',
            orders: 82,
            totalSpends: 350.90
        },
        {
            id: 9,
            name: 'Liam O’Connor',
            email: 'liam.oconnor@ausinnovate.au',
            avatar: 'assets/images/users/user-10.jpg',
            phone: '+61 400 123 456',
            countryFlag: 'assets/images/flags/au.svg',
            country: 'Australia',
            date: '25 Mar, 2024',
            time: '01:15 PM',
            orders: 45,
            totalSpends: 230.65
        },
        {
            id: 10,
            name: 'Olga Petrova',
            email: 'olga.petrova@rus-tech.ru',
            avatar: 'assets/images/users/user-1.jpg',
            phone: '+7 912 345 67 89',
            countryFlag: 'assets/images/flags/ru.svg',
            country: 'Russia',
            date: '8 Feb, 2024',
            time: '07:40 AM',
            orders: 68,
            totalSpends: 295.15
        }
    ];

    protected readonly LucidePlus = LucidePlus;
    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideDownload = LucideDownload;
    protected readonly currency = currency;
}

<div class="container-fluid">

    <app-page-title title="Customers" subTitle="Ecommerce"/>

    <div class="row justify-content-center">
        <div class="col-xxl-10">
            <div class="card">
                <div class="card-header border-light d-flex align-items-center justify-content-between flex-wrap gap-2">

                    <div class="d-flex gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" type="search" class="form-control"
                                   placeholder="Search customer...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>
                        @if (hasSelection) {
                            <button class="btn btn-danger" (click)="deleteSelected()">Delete</button>
                        }
                    </div>


                    <div class="d-flex align-items-center gap-2">
                        <div>
                            <select [(ngModel)]="tableService.pageSize" class="form-select form-control my-1 my-md-0">
                                <option [ngValue]="5">5</option>
                                <option [ngValue]="8">8</option>
                                <option [ngValue]="10">10</option>
                                <option [ngValue]="15">15</option>
                                <option [ngValue]="20">20</option>
                            </select>
                        </div>

                        <div ngbDropdown>
                            <button class="btn btn-default dropdown-toggle drop-arrow-none" type="button"
                                    ngbDropdownToggle>
                                <lucide-angular [img]="LucideDownload" class="me-1"/>
                                Export
                                <ng-icon
                                    name="tablerChevronDown" class="ms-1"/>
                            </button>
                            <ul class="dropdown-menu-end" ngbDropdownMenu>
                                <li><a ngbDropdownItem>Export as PDF</a></li>
                                <li><a ngbDropdownItem>Export as CSV</a></li>
                                <li><a ngbDropdownItem>Export as Excel</a></li>
                            </ul>
                        </div>

                        <a [routerLink]="[]" class="btn btn-primary">
                            <lucide-angular [img]="LucidePlus" class="fs-sm me-1"/>
                            Add Customer
                        </a>
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th class="ps-3" style="width: 1%;">
                                <input [(ngModel)]="selectAll" (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" id="select-all-products">
                            </th>
                            <th sortable="name" (sort)="tableService.setSort($event.column, $event.direction)">Clients
                                Name
                            </th>
                            <th sortable="email" (sort)="tableService.setSort($event.column, $event.direction)">Email
                            </th>
                            <th sortable="phone" (sort)="tableService.setSort($event.column, $event.direction)">Phone
                            </th>
                            <th sortable="country" (sort)="tableService.setSort($event.column, $event.direction)">
                                Country
                            </th>
                            <th sortable="date" (sort)="tableService.setSort($event.column, $event.direction)">Joined
                            </th>
                            <th sortable="orders" (sort)="tableService.setSort($event.column, $event.direction)">
                                Orders
                            </th>
                            <th sortable="totalSpends" (sort)="tableService.setSort($event.column, $event.direction)">
                                Total Spends
                            </th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for (customer of customers$ | async; track $index) {
                                    <tr>
                                        <td class="ps-3">
                                            <input class="form-check-input form-check-input-light fs-14" type="checkbox"
                                                   [(ngModel)]="customer.selected" (change)="toggleSingleSelection()"/>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <div class="avatar avatar-sm">
                                                    <img [src]="customer.avatar" [alt]="customer.name"
                                                         class="img-fluid rounded-circle"/>
                                                </div>
                                                <div>
                                                    <h5 class="mb-0">
                                                        <a routerLink="/pages/profile"
                                                           class="link-reset">{{ customer.name }}</a>
                                                    </h5>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{{ customer.email }}</td>
                                        <td>{{ customer.phone }}</td>
                                        <td>
                                            <img [src]="customer.countryFlag" alt="" class="rounded-circle me-1"
                                                 height="16"/>
                                            {{ customer.country }}
                                        </td>
                                        <td>{{ customer.date }} <small class="text-muted">{{ customer.time }}</small>
                                        </td>
                                        <td>{{ customer.orders }}</td>
                                        <td>{{ currency }}{{customer.totalSpends && customer.totalSpends.toFixed(2) }}</td>
                                        <td>
                                            <div class="d-flex align-items-center justify-content-center gap-1">
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon name="tablerEye" class="fs-lg"/>
                                                </button>
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon name="tablerEdit" class="fs-lg"/>
                                                </button>
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle"
                                                        (click)="tableService.deleteItem(customer)">
                                                    <ng-icon name="tablerTrash" class="fs-lg"/>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="11" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                    <div class="d-flex justify-content-between pagination-boxed align-items-center">
                        {{ tableService.showingRange }} customers
                        <ngb-pagination
                            [collectionSize]="(total$ | async)!"
                            [(page)]="tableService.page"
                            [pageSize]="tableService.pageSize"
                        >
                            <ng-template ngbPaginationPrevious>
                                <ng-icon name="tablerChevronLeft"/>
                            </ng-template>
                            <ng-template ngbPaginationNext>
                                <ng-icon name="tablerChevronRight"/>
                            </ng-template>
                        </ngb-pagination>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>

// Vue/Full/src/views/apps/ecommerce/customers/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Customers" subTitle="Ecommerce" />

            <BRow class="justify-content-center">
                <BCol xxl="10">
                    <BCard no-body>
                        <BCardHeader
                            class="border-light d-flex align-items-center justify-content-between flex-wrap gap-2">

                            <div class="d-flex gap-2">
                                <div class="app-search">
                                    <input type="search" class="form-control" v-model="searchQuery"
                                        placeholder="Search customer...">
                                    <Icon  icon="lucide:search" class="app-search-icon text-muted" />
                                </div>
                                <BButton v-if="selected.length" variant="danger" @click="handleDeleteSelected">
                                    Delete
                                </BButton>
                            </div>


                            <div class="d-flex align-items-center gap-5">

                                <div>
                                    <BFormSelect v-model="perPage" :options="perPageOptions"
                                        class="form-control my-1 my-md-0" />
                                </div>

                                <div>

                                    <BDropdown toggle-class="btn btn-default drop-arrow-none"
                                        class="btn-icon btn-ghost-light text-muted">
                                        <template #button-content>
                                            <Icon icon="lucide:download" class="me-1" /> Export
                                            <Icon icon="tabler:chevron-down" class="align-middle ms-1" />

                                        </template>
                                        <li>
                                            <BDropdownItem>Export as PDF</BDropdownItem>
                                        </li>
                                        <li>
                                            <BDropdownItem>Export as CSV</BDropdownItem>
                                        </li>
                                        <li>
                                            <BDropdownItem>Export as Excel</BDropdownItem>
                                        </li>
                                    </BDropdown>
                                </div>



                                <RouterLink to="" class="btn btn-primary">
                                    <Icon icon="lucide:plus" class="fs-sm me-1" /> Add Customer
                                </RouterLink>
                            </div>
                        </BCardHeader>

                        <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                            v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                            hover :fields="fields" :items="allCustomers" :per-page="perPage" :current-page="currentPage"
                            @filtered="onFiltered" responsive
                            class="table table-custom table-nowrap table-centered mb-0 w-100">
                            <template #head()="data">
                                <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                            </template>
                            <template #head(id)>
                                <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                                    id="select-all-products" value="option" :checked="allSelected"
                                    :indeterminate="isIndeterminate" @change="toggleSelectAll" />
                            </template>
                            <template #head(action)>
                                <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                            </template>
                            <template #cell(id)="data">
                                <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                    type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                    @change="onToggleRow(data.item, $event)" />
                            </template>
                            <template #cell(name)="{ item }">
                                <div class="d-flex align-items-center gap-2">
                                    <div class="avatar avatar-sm">
                                        <img :src="item.avatar" alt="avatar-7" class="img-fluid rounded-circle" />
                                    </div>
                                    <div>
                                        <h5 class="mb-0">
                                            <RouterLink to="/pages/profilez" class="link-reset">{{ item.name }}
                                            </RouterLink>
                                        </h5>
                                    </div>
                                </div>
                            </template>
                            <template #cell(country)="{ item }">
                                <img :src="item.countryFlag" alt="" class="rounded-circle me-1" height="16" />
                                {{ item.country }}
                            </template>
                            <template #cell(joinedDate)="{ item }">
                                {{ item.joined.date }} <small class="text-muted">{{ item.joined.time }}</small>
                            </template>
                            <template #cell(totalSpent)="{ item }">
                                {{ currency }}{{ item.totalSpends }}
                            </template>
                            <template #cell(action)="{ item }">
                                <div class="d-flex justify-content-center gap-1">
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:eye" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:edit" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:trash" class="fs-lg" @click="handleDeleteItem(item)" />
                                    </button>
                                </div>
                            </template>

                        </BTable>
                        <BCardFooter class="border-0">
                            <TablePagination v-model:currentPage="currentPage" :per-page="perPage"
                                :total-items="totalRows" label="customers" />
                        </BCardFooter>
                    </BCard>
                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardFooter, BCardHeader, BCol, BContainer, BFormSelect, BRow, type TableFieldRaw } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import { customers, type CustomerType } from './data';
import { currency } from '@/helpers';
import { ref } from 'vue';
import { usePageMeta } from '@/composables/usePageMeta';
import { useTableActions } from '@/composables/useTableActions';
import { Icon } from '@iconify/vue';
import MainLayout from '@/layouts/MainLayout.vue';

const fields: Exclude<TableFieldRaw<CustomerType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Client Name', sortable: true },
    { key: 'email', label: 'Email', sortable: true },
    { key: 'phone', label: 'Phone', sortable: true },
    { key: 'country', label: 'Country', sortable: true },
    { key: 'joinedDate', label: 'Joined Date', sortable: true },
    { key: 'orders', label: 'Orders', sortable: true },
    { key: 'totalSpent', label: 'Total Spends', sortable: true },
    { key: 'action', label: 'Action', sortable: false },
]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(customers.length)
const allCustomers = ref<CustomerType[]>(customers)

function onFiltered(filteredItems: CustomerType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}


function adjustPage() {
    const totalPages = Math.ceil(allCustomers.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: CustomerType) {
    deleteItem(item)
    totalRows.value = allCustomers.value.length
    adjustPage()
}

function handleDeleteSelected() {
    deleteSelected()
    totalRows.value = allCustomers.value.length
    adjustPage()
}

const { selected, toggleSelectAll, onToggleRow, deleteSelected, deleteItem, allSelected, isIndeterminate } = useTableActions(allCustomers)

usePageMeta('Customers')


</script>

<style scoped></style>
