// Angular/Full/src/app/views/ecommerce/reports/sales/sales.component.ts
import {Component, OnInit} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {LucideAngularModule, LucideCalendar, LucideSearch} from 'lucide-angular';
import {NgIcon} from '@ng-icons/core';
import {ApexOptions, NgApexchartsModule} from 'ng-apexcharts';
import {getColor} from '@/app/utils/color-utils';
import {Observable} from 'rxjs';
import {TableService} from '@core/services/table.service';
import {currency} from '@/app/constants';
import {NgbPaginationModule} from '@ng-bootstrap/ng-bootstrap';
import {FormsModule} from '@angular/forms';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';
import {FlatpickrDirective, provideFlatpickrDefaults} from 'angularx-flatpickr';
import {ApexchartComponent} from '@app/components/apexchart.component';
import {AsyncPipe} from '@angular/common';

type RevenueRecordType = {
    id: number;
    orders: number;
    refunds: number;
    date: string;
    averageRevenue: number;
    tax: number;
    revenue: number;
    balance: number;
    selected?: boolean
}

@Component({
    selector: 'app-sales',
    imports: [
        PageTitleComponent,
        LucideAngularModule,
        NgIcon,
        NgApexchartsModule,
        NgbPaginationModule,
        FormsModule,
        NgbdSortableHeader,
        FlatpickrDirective,
        ApexchartComponent,
        AsyncPipe
    ],
    templateUrl: './sales.component.html',
    providers: [provideFlatpickrDefaults(),TableService],
    styles: ``
})
export class SalesComponent implements OnInit {
    dateRange: Date[] = this.getCurrentMonthRange();
    protected readonly LucideSearch = LucideSearch;
    protected readonly LucideCalendar = LucideCalendar;

    revenueData$: Observable<RevenueRecordType[]>
    total$: Observable<number>;

    constructor(public tableService: TableService<RevenueRecordType>) {
        this.revenueData$ = this.tableService.items$
        this.total$ = this.tableService.total$
    }

    ngOnInit(): void {
        this.tableService.setItems(this.revenueData, 8)
    }

    selectAll = false;

    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    revenueData: RevenueRecordType[] = [
        {
            id: 1,
            date: '10 July, 2025',
            orders: 68,
            refunds: 4,
            averageRevenue: 18.60,
            tax: 25.78,
            revenue: 612.70,
            balance: 6625.46
        },
        {
            id: 2,
            date: '09 July, 2025',
            orders: 85,
            refunds: 1,
            averageRevenue: 22.10,
            tax: 31.85,
            revenue: 786.35,
            balance: 6012.76
        },
        {
            id: 3,
            date: '08 July, 2025',
            orders: 61,
            refunds: 3,
            averageRevenue: 17.40,
            tax: 23.67,
            revenue: 531.10,
            balance: 5226.41
        },
        {
            id: 4,
            date: '07 July, 2025',
            orders: 79,
            refunds: 2,
            averageRevenue: 20.65,
            tax: 29.45,
            revenue: 726.80,
            balance: 4695.31
        },
        {
            id: 5,
            date: '06 July, 2025',
            orders: 53,
            refunds: 6,
            averageRevenue: 15.10,
            tax: 20.89,
            revenue: 400.55,
            balance: 3968.51
        },
        {
            id: 6,
            date: '05 July, 2025',
            orders: 91,
            refunds: 4,
            averageRevenue: 22.50,
            tax: 32.90,
            revenue: 851.30,
            balance: 3567.96
        },
        {
            id: 7,
            date: '04 July, 2025',
            orders: 47,
            refunds: 5,
            averageRevenue: 16.25,
            tax: 22.05,
            revenue: 382.47,
            balance: 2716.66
        },
        {
            id: 8,
            date: '03 July, 2025',
            orders: 82,
            refunds: 1,
            averageRevenue: 21.03,
            tax: 31.11,
            revenue: 792.65,
            balance: 2334.19
        },
        {
            id: 9,
            date: '02 July, 2025',
            orders: 65,
            refunds: 3,
            averageRevenue: 17.92,
            tax: 24.15,
            revenue: 583.42,
            balance: 1541.54
        },
        {
            id: 10,
            date: '01 July, 2025',
            orders: 73,
            refunds: 2,
            averageRevenue: 19.85,
            tax: 27.34,
            revenue: 660.12,
            balance: 958.12
        }
    ]

    salesChartOptions: () => ApexOptions = () => ({
        chart: {
            height: 400,
            type: 'line',
            stacked: false,
            toolbar: {show: false}
        },
        stroke: {
            width: [0, 0, 2, 2, 2],
            curve: 'smooth',
        },
        plotOptions: {
            bar: {
                columnWidth: '40%'
            }
        },
        colors: [getColor('primary'), getColor('danger'), getColor('secondary'), "#bbcae14d"],
        series: [
            {
                name: 'Orders',
                type: 'bar',
                data: [320, 402, 391, 334, 390, 330]
            },
            {
                name: 'Refunds',
                type: 'bar',
                data: [20, 30, 28, 22, 35, 25]
            },
            {
                name: 'Avg. Revenue/Order',
                type: 'line',
                data: [15.5, 16.2, 15.8, 16.0, 15.9, 16.3]
            },
            {
                name: 'Revenue',
                type: 'area',
                data: [4960, 6512, 6182, 5344, 6201, 5379]
            },
            {
                name: 'Tax',
                type: 'bar',
                data: [496, 651, 618, 534, 620, 537]
            }
        ],
        xaxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
        },
        yaxis: [
            {
                title: {
                    text: 'Orders / Refunds / Avg Revenue',
                    style: {
                        fontSize: '11px',
                        fontWeight: 600,
                    }
                }
            },
            {
                opposite: true,
                title: {
                    text: 'Revenue / Tax',
                    style: {
                        fontSize: '11px',
                        fontWeight: 600,
                    }
                }
            }
        ],
        legend: {
            show: false
        }
    })
    protected readonly currency = currency;

    getCurrentMonthRange(): Date[] {
        const start = new Date();
        start.setDate(1);
        start.setHours(0, 0, 0, 0);

        const end = new Date();
        end.setMonth(end.getMonth() + 1);
        end.setDate(0);
        end.setHours(23, 59, 59, 999);

        return [start, end];
    }
}

<div class="container-fluid">
    <app-page-title title="Sales Reports" subTitle="Ecommerce"/>

    <div class="row justify-content-center">
        <div class="col-xxl-10">
            <div data-table data-table-rows-per-page="8" class="card">
                <div class="card-header border-light justify-content-between">
                    <h5 class="card-title mb-0">Products - 2025</h5>
                    <div class="d-flex align-items-center gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" type="search" class="form-control"
                                   placeholder="Search reports...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>

                        <div class="app-search">
                            <input type="text" style="min-width: 250px;" class="form-control" [(ngModel)]="dateRange"
                                   mwlFlatpickr [options]="{dateFormat:'d M, Y',mode:'range'}">
                            <lucide-angular [img]="LucideCalendar" class="app-search-icon text-muted"/>
                        </div>

                        <button type="submit" class="btn btn-secondary">
                            <ng-icon name="tablerDownload" class="me-2"/>
                            Export Report
                        </button>
                    </div>
                </div>

                <div class="card-body">
                    <app-apexchart [getOptions]="salesChartOptions"/>
                </div>

                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th class="ps-3" style="width: 1%;">
                                <input [(ngModel)]="selectAll" (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" value="option">
                            </th>
                            <th sortable="date" (sort)="tableService.setSort($event.column, $event.direction)">Date</th>
                            <th sortable="orders" (sort)="tableService.setSort($event.column, $event.direction)">
                                Orders
                            </th>
                            <th sortable="refunds" (sort)="tableService.setSort($event.column, $event.direction)">
                                Refunds
                            </th>
                            <th sortable="averageRevenue"
                                (sort)="tableService.setSort($event.column, $event.direction)">Avr. Revenue per Order
                            </th>
                            <th sortable="tax" (sort)="tableService.setSort($event.column, $event.direction)">Tax</th>
                            <th sortable="revenue" (sort)="tableService.setSort($event.column, $event.direction)">
                                Revenue
                            </th>
                            <th sortable="balance" (sort)="tableService.setSort($event.column, $event.direction)">
                                Balance
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for (item of revenueData$ | async; track $index) {
                                    <tr>
                                        <td class="ps-3">
                                            <input [(ngModel)]="item.selected" (change)="toggleSingleSelection()"
                                                   type="checkbox"
                                                   class="form-check-input form-check-input-light fs-14 mt-0"
                                            />
                                        </td>
                                        <td>{{ item.date }}</td>
                                        <td>{{ item.orders }}</td>
                                        <td>{{ item.refunds }}</td>
                                        <td>{{ currency }}{{ item.averageRevenue && item.averageRevenue.toFixed(2) }}</td>
                                        <td>{{ currency }}{{ item.tax && item.tax.toFixed(2) }}</td>
                                        <td>{{ currency }}{{ item.revenue && item.revenue.toFixed(2) }}</td>
                                        <td>{{ currency }}{{ item.balance && item.balance.toFixed(2) }}</td>
                                    </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="11" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                    <div
                         class="d-flex justify-content-between pagination-boxed align-items-center">
                        {{ tableService.showingRange }} sales
                        <ngb-pagination
                            [collectionSize]="(total$ | async)!"
                            [(page)]="tableService.page"
                            [pageSize]="tableService.pageSize"
                        >
                            <ng-template ngbPaginationPrevious>
                                <ng-icon name="tablerChevronLeft"/>
                            </ng-template>
                            <ng-template ngbPaginationNext>
                                <ng-icon name="tablerChevronRight"/>
                            </ng-template>
                        </ngb-pagination>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

// Nuxt/Full/pages/(apps)/(ecommerce)/reports/sales/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Sales Reports" subTitle="Ecommerce" />

        <BRow class="justify-content-center">
            <BCol xxl="10">
                <BCard no-body>
                    <BCardHeader class="border-light justify-content-between">
                        <h5 class="card-title mb-0">Products - 2025</h5>
                        <div class="d-flex align-items-center gap-2">
                            <div class="app-search">
                                <input v-model="searchQuery" type="search" class="form-control"
                                    placeholder="Search reports...">
                                <Icon size="18" name="lucide:search" class="app-search-icon text-muted" />
                            </div>

                            <div class="app-search">
                                <FlatPickr v-model="date" :config="config" type="text" style="min-width: 250px;"
                                    class="form-control" />
                                <Icon size="18" name="lucide:calendar" class="app-search-icon text-muted" />
                            </div>

                            <button type="submit" class="btn btn-secondary">
                                <Icon name="tabler:download" class="me-2" />
                                Export Report
                            </button>
                        </div>
                    </BCardHeader>

                    <BCardBody>
                        <CustomApexChart :get-options="getSalesChartOptions" :series="getSalesChartOptions().series" />
                    </BCardBody>

                    <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                        v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                        hover :fields="fields" :items="sales" :per-page="perPage" :current-page="currentPage"
                        @filtered="onFiltered" responsive
                        class="table table-custom table-nowrap table-centered mb-0 w-100">
                        <template #head()="data">
                            <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                        </template>
                        <template #head(id)>
                            <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                                id="select-all-products" value="option" :checked="allSelected"
                                :indeterminate="isIndeterminate" @change="toggleSelectAll" />
                        </template>
                        <template #head(action)>
                            <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                        </template>
                        <template #cell(id)="data">
                            <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                @change="onToggleRow(data.item, $event)" />
                        </template>

                    </BTable>
                    <BCardFooter class="border-0">
                        <TablePagination v-model:currentPage="currentPage" :per-page="perPage" :total-items="totalRows"
                            label="categories" />
                    </BCardFooter>
                </BCard>
            </BCol>
        </BRow>

    </BContainer>
</template>

<script setup lang="ts">
import { BCard, BCardBody, BCardFooter, BCardHeader, BCol, BContainer, BRow, BTable, type TableFieldRaw } from 'bootstrap-vue-next';
import CustomApexChart from '~/components/CustomApexChart.vue';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import { getSalesChartOptions, salesData, type SalesDataType } from './data';
import TablePagination from '~/components/TablePagination.vue';
import { getCurrentMonthRange } from '~/helpers/generators';

const date = ref<string | Date | null>()

const config = ref({
    dateFormat: 'd M, Y',
    mode: 'range',
    defaultDate: getCurrentMonthRange(),
})

const fields: Exclude<TableFieldRaw<SalesDataType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'date', label: 'Date', sortable: true },
    { key: 'orders', label: 'Orders', sortable: true },
    { key: 'refunds', label: 'Refunds', sortable: true },
    { key: 'averageRevenuePerOrder', label: 'Avr. Revenue per Order', sortable: true },
    { key: 'tax', label: 'Tax', sortable: true },
    { key: 'revenue', label: 'Revenue', sortable: true },
    { key: 'balance', label: 'Balance', sortable: true },
]

const searchQuery = ref('')

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(salesData.length)
const sales = ref<SalesDataType[]>(salesData)

function onFiltered(filteredItems: SalesDataType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

const { selected, toggleSelectAll, onToggleRow, allSelected, isIndeterminate } = useTableActions(sales)

usePageTitle('Sales Reports')

</script>

<style scoped></style>
