// Vue-Inertia/Full/resources/js/pages/tables/static/components/CustomTable.vue
<template>
    <BCard no-body>
        <BCardHeader class="justify-content-between d-flex align-items-center">
            <BCardTitle>Custom Table</BCardTitle>
            <span class="badge badge-label badge-soft-success fs-xxs">Exclusive</span>
        </BCardHeader>

        <BCardBody class="p-0">
            <BTableSimple responsive class="table-custom align-middle mb-0">
                <thead class="bg-light align-middle bg-opacity-25 thead-sm">
                    <tr class="text-uppercase fs-xxs">
                        <th v-for="(header, idx) in productsTable.header" :key="idx"
                            :style="header === 'Actions' ? { width: '1%' } : { width: 'auto' }">
                            {{ header }}
                        </th>
                    </tr>
                </thead>

                <tbody>
                    <tr v-for="(product, idx) in productsTable.data" :key="idx">
                        <td>{{ product.name }}</td>
                        <td>{{ product.category }}</td>
                        <td>{{ currency }}{{ product.price.toFixed(2) }}</td>
                        <td>{{ product.stock }}</td>
                        <td>{{ product.rating }} ★</td>
                        <td>
                            <span :class="[
                                'badge',
                                'badge-label',
                                `badge-soft-${product.status === 'Active' ? 'success' : 'warning'}`
                            ]">
                                {{ product.status }}
                            </span>
                        </td>

                        <td class="text-end">
                            <BDropdown variant="link" toggle-class="drop-arrow-none fs-xxl link-reset p-0 text-muted"
                                end>
                                <template #button-content>
                                    <Icon icon="tabler:dots-vertical" />
                                </template>
                                <BDropdownItem>
                                    <Icon icon="tabler:eye" class="me-1" /> View
                                </BDropdownItem>
                                <BDropdownItem>
                                    <Icon icon="tabler:edit" class="me-1" /> Edit
                                </BDropdownItem>
                                <BDropdownItem href="#" class="text-danger">
                                    <Icon icon="tabler:trash" class="me-1" /> Delete
                                </BDropdownItem>
                            </BDropdown>
                        </td>
                    </tr>
                </tbody>
            </BTableSimple>
        </BCardBody>
    </BCard>
</template>

<script setup lang="ts">
import { currency } from '@/helpers';
import { productsTable } from '../data';
import { BTableSimple } from 'bootstrap-vue-next';
import { Icon } from '@iconify/vue';

</script>

// NextJs/NextJs/Full/JS/src/app/(admin)/tables/static/components/CustomTable.jsx
import { productsTable } from '@/app/(admin)/tables/static/data';
import { currency } from '@/helpers';
import { Card, CardBody, CardHeader, CardTitle, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, Table } from 'react-bootstrap';
import { TbDotsVertical, TbEdit, TbEye, TbTrash } from 'react-icons/tb';
const CustomTable = () => {
  return <Card>
      <CardHeader className="justify-content-between">
        <CardTitle> Custom Table </CardTitle>
        <span className="badge badge-label badge-soft-success fs-xxs">Exclusive</span>
      </CardHeader>

      <CardBody className="p-0">
        <Table responsive className="table-custom align-middle mb-0">
          <thead className="bg-light align-middle bg-opacity-25 thead-sm">
            <tr className="text-uppercase fs-xxs">
              {productsTable.header.map((header, idx) => <th key={idx} style={header === 'Actions' ? {
              width: '1%'
            } : {
              width: 'auto'
            }}>
                  {header}
                </th>)}
            </tr>
          </thead>
          <tbody>
            {productsTable.data.map((product, idx) => <tr key={idx}>
                <td>{product.name}</td>
                <td>{product.category}</td>
                <td>
                  {currency}
                  {product.price.toFixed(2)}
                </td>
                <td>{product.stock}</td>
                <td>{product.rating} ★</td>
                <td>
                  <span className={`badge badge-label badge-soft-${product.status === 'Active' ? 'success' : 'warning'}`}>{product.status}</span>
                </td>
                <td className="text-end">
                  <Dropdown align="end" className="text-muted">
                    <DropdownToggle variant="link" className="drop-arrow-none fs-xxl link-reset p-0">
                      <TbDotsVertical />
                    </DropdownToggle>
                    <DropdownMenu>
                      <DropdownItem href="#">
                        <TbEye className="me-1" /> View
                      </DropdownItem>
                      <DropdownItem href="#">
                        <TbEdit className="me-1" /> Edit
                      </DropdownItem>
                      <DropdownItem href="#" className="text-danger">
                        <TbTrash className="me-1" /> Delete
                      </DropdownItem>
                    </DropdownMenu>
                  </Dropdown>
                </td>
              </tr>)}
          </tbody>
        </Table>
      </CardBody>
    </Card>;
};
export default CustomTable;
