// Seed/src/layouts/MainLayout.vue
<template>
  <VerticalLayout v-if="layout.orientation === 'vertical'">
    <slot />
  </VerticalLayout>

  <HorizontalLayout v-if="layout.orientation === 'horizontal'">
    <slot />
  </HorizontalLayout>
</template>

<script setup lang="ts">
import VerticalLayout from '@/layouts/VerticalLayout.vue'
import HorizontalLayout from '@/layouts/HorizontalLayout.vue'
import { useLayout } from '@/stores/layout.ts'

const { layout } = useLayout()
</script>

// SvelteKit/Seed/src/lib/layouts/MainLayout.svelte
<script lang="ts">
	import VerticalLayout from '$lib/layouts/VerticalLayout.svelte';
	import HorizontalLayout from '$lib/layouts/HorizontalLayout.svelte';
	import { layout } from '$lib/stores/layout';
</script>

{#key $layout.orientation}
	{#if $layout.orientation === 'vertical'}
		<VerticalLayout><slot /></VerticalLayout>
	{:else if $layout.orientation === 'horizontal'}
		<HorizontalLayout><slot /></HorizontalLayout>
	{/if}
{/key}
