// src/views/other-apps/clients/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Clients" subTitle="Apps" />

            <BRow class="justify-content-center">
                <BCol xxl="10">
                    <BCard no-body>
                        <BCardHeader class="border-light justify-content-between">
                            <div class="d-flex gap-2">
                                <div class="app-search">
                                    <input v-model="searchQuery" type="text" class="form-control"
                                        placeholder="Search clients...">
                                    <Icon icon="lucide:search"  class="app-search-icon text-muted" />
                                </div>

                                <BButton v-if="selected.length" variant="danger" @click="handleDeleteSelected">
                                    Delete
                                </BButton>

                                <button type="submit" class="btn btn-purple rounded-circle btn-icon">
                                    <Icon icon="lucide:plus" class="fs-lg" />
                                </button>
                            </div>

                            <div class="d-flex align-items-center gap-2">
                                <span class="me-2 fw-semibold">Filter By:</span>


                                <div class="app-search">
                                    <select data-table-filter="country" class="form-select form-control my-1 my-md-0">
                                        <option value="All">Country</option>
                                        <option value="US">USA</option>
                                        <option value="UK">UK</option>
                                        <option value="AU">Australia</option>
                                        <option value="DE">Germany</option>
                                        <option value="IN">India</option>
                                    </select>
                                    <Icon icon="lucide:globe" :size="18" class="app-search-icon text-muted" />
                                </div>


                                <div class="app-search">
                                    <select data-table-filter="type" class="form-select form-control my-1 my-md-0">
                                        <option value="All">Project Type</option>
                                        <option value="Project">Project</option>
                                        <option value="Contract">Contract</option>
                                        <option value="Retainer">Retainer</option>
                                        <option value="Dashboard">Dashboard</option>
                                    </select>
                                    <Icon icon="lucide:layout"  class="app-search-icon text-muted" />
                                </div>


                                <div>
                                    <BFormSelect v-model="perPage" :options="perPageOptions"
                                        class="form-control my-1 my-md-0" />
                                </div>
                            </div>
                        </BCardHeader>
                        <BTable show-empty :filter="searchQuery" empty-text="Nothing found."
                            v-model:selected-rows="selected" thead-class="bg-light align-middle bg-opacity-25 thead-sm"
                            hover :fields="fields" :items="clientsData" :per-page="perPage" :current-page="currentPage"
                            @filtered="onFiltered" responsive
                            class="table table-custom table-nowrap table-centered mb-0 w-100">
                            <template #head()="data">
                                <span class="text-uppercase fs-xxs">{{ data.label }}</span>
                            </template>
                            <template #head(id)>
                                <input class="form-check-input form-check-input-light fs-14 mt-0" type="checkbox"
                                    id="select-all-products" value="option" :checked="allSelected"
                                    :indeterminate="isIndeterminate" @change="toggleSelectAll" />
                            </template>
                            <template #head(action)>
                                <span class="text-uppercase d-flex justify-content-center fs-xxs">Actions</span>
                            </template>
                            <template #cell(id)="data">
                                <input class="form-check-input form-check-input-light fs-14 product-item-check mt-0"
                                    type="checkbox" :value="data.item" :checked="selected.includes(data.item)"
                                    @change="onToggleRow(data.item, $event)" />
                            </template>
                            <template #cell(name)="{ item }">
                                <div class="d-flex justify-content-start align-items-center gap-2">
                                    <div class="avatar avatar-sm">
                                        <img :src="item.image" alt="avatar-7" class="img-fluid rounded-circle" />
                                    </div>
                                    <div>
                                        <h5 class="text-nowrap mb-0 lh-base fs-base">
                                            <RouterLink to="/pages/profile" class="link-reset">{{ item.name }}
                                            </RouterLink>
                                        </h5>
                                        <p class="text-muted fs-xs mb-0">{{ item.email }}</p>
                                    </div>
                                </div>
                            </template>
                            <template #cell(country)="{ item }">
                                <span class="badge p-1 text-bg-light fs-sm">
                                    <img :src="item.flag" alt="" class="rounded-circle me-1" height="12" />
                                    {{ item.countryCode }}
                                </span>
                            </template>
                            <template #cell(status)="{ item }">
                                <span class="badge badge-label"
                                    :class="item.status === 'active' ? 'bg-success-subtle text-success' : item.status === 'pending' ? 'bg-warning-subtle text-warning' : 'bg-danger-subtle text-danger'">{{
                                        toPascalCase(item.status) }}</span>
                            </template>

                            <template #cell(action)="{ item }">
                                <div class="d-flex justify-content-center gap-1">
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:eye" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:edit" class="fs-lg" />
                                    </button>
                                    <button class="btn btn-light btn-icon btn-sm rounded-circle">
                                        <Icon icon="tabler:trash" class="fs-lg" @click="handleDeleteItem(item)" />
                                    </button>
                                </div>
                            </template>

                        </BTable>
                        <BCardFooter class="border-0">
                            <TablePagination v-model:currentPage="currentPage" :per-page="perPage"
                                :total-items="totalRows" label="categories" />
                        </BCardFooter>
                    </BCard>
                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCard, BCardFooter, BCardHeader, BCol, BContainer, BFormSelect, BRow, BTable, type TableFieldRaw } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import TablePagination from '@/components/TablePagination.vue';
import { clients, type ClientType } from './data';
import { Icon } from '@iconify/vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { ref } from 'vue';
import { toPascalCase } from '@/helpers/casing';
import { usePageMeta } from '@/composables/usePageMeta';
import { useTableActions } from '@/composables/useTableActions';


const fields: Exclude<TableFieldRaw<ClientType>, string>[] = [
    { key: 'id', label: 'Id' },
    { key: 'name', label: 'Clients Name', sortable: true },
    { key: 'phone', label: 'Phone', sortable: true },
    { key: 'country', label: 'Country', sortable: true },
    { key: 'enrollDate', label: 'Enrolled', sortable: true },
    { key: 'type', label: 'Type', sortable: true },
    { key: 'role', label: 'Job title', sortable: true },
    { key: 'status', label: 'Status', sortable: true },
    { key: 'action', label: 'Actions', sortable: false },
]

const searchQuery = ref('')

const perPageOptions = [5, 8, 10, 20, 50]

const currentPage = ref(1)
const perPage = ref(8)
const totalRows = ref(clients.length)
const clientsData = ref<ClientType[]>(clients)

function onFiltered(filteredItems: ClientType[]) {
    totalRows.value = filteredItems.length
    currentPage.value = 1
}

function adjustPage() {
    const totalPages = Math.ceil(clientsData.value.length / perPage.value)
    if (currentPage.value > totalPages) {
        currentPage.value = totalPages || 1
    }
}

function handleDeleteItem(item: ClientType) {
    deleteItem(item)
    totalRows.value = clientsData.value.length
    adjustPage()
}

function handleDeleteSelected() {
    deleteSelected()
    totalRows.value = clientsData.value.length
    adjustPage()
}

const { selected, toggleSelectAll, onToggleRow, deleteSelected, deleteItem, allSelected, isIndeterminate } = useTableActions(clientsData)

usePageMeta('Clients')

</script>

<style scoped></style>

// Angular/Full/src/app/views/other-apps/clients/clients.component.ts
import {Component, inject, OnInit, QueryList, ViewChildren} from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {NgbdSortableHeader} from '@core/directive/sortable.directive';
import {TableService} from '@core/services/table.service';
import {AsyncPipe, DecimalPipe} from '@angular/common';
import {Observable} from 'rxjs';
import {FormsModule} from '@angular/forms';
import {NgIcon} from '@ng-icons/core';
import {RouterLink} from '@angular/router';
import {NgbPaginationModule} from '@ng-bootstrap/ng-bootstrap';
import {clients} from '@/app/views/other-apps/clients/data';
import {LucideAngularModule, LucideGlobe, LucideLayout, LucideSearch} from 'lucide-angular';
import {toTitleCase} from '@/app/utils/string-utils';


type ClientType = {
    name: string;
    email: string;
    avatar: string;
    phone: string;
    countryName: string;
    flag: string;
    enrollDate: string;
    type: string;
    title: string;
    status: "active" | "inactive" | "pending",
    selected?: boolean;
}


@Component({
    selector: 'app-clients',
    imports: [
        PageTitleComponent,
        FormsModule,
        NgIcon,
        RouterLink,
        NgbPaginationModule,
        NgbdSortableHeader,
        LucideAngularModule,
        AsyncPipe
    ],
    providers: [TableService],
    templateUrl: './clients.component.html',
    styles: ``
})
export class ClientsComponent implements OnInit {
    filterProjectType='All'
    filterByCountry='All'
    selectAll = false;

    LucideGlobe=LucideGlobe
    LucideLayout=LucideLayout
    LucideSearch=LucideSearch


    sortCountries = clients.slice(0, 5)
    records$: Observable<ClientType[]>
    total$: Observable<number>;

    @ViewChildren(NgbdSortableHeader) headers!: QueryList<NgbdSortableHeader<ClientType>>;
    public tableService = inject(TableService<ClientType>)

    constructor(public pipe: DecimalPipe) {
        this.records$ = this.tableService.items$
        this.total$ = this.tableService.total$

    }

    ngOnInit(): void {
        this.tableService.setItems(clients, 8)
    }

    toggleAllSelection() {
        this.tableService.setAllSelection(this.selectAll);
    }

    toggleSingleSelection() {
        this.tableService.items$.subscribe(items => {
            this.selectAll = items.every((item: any) => item.selected);
        }).unsubscribe();
    }

    deleteSelected() {
        this.tableService.deleteSelectedItems();
        this.selectAll = false;
    }

    get hasSelection(): boolean {
        return this.tableService.hasSelectedItems();
    }


    protected readonly toTitleCase = toTitleCase;
}

<div class="container-fluid">
    <app-page-title title="Clients" subTitle="Apps"/>

    <div class="row justify-content-center">
        <div class="col-xxl-10">
            <div class="card">
                <div class="card-header border-light justify-content-between">
                    <div class="d-flex gap-2">
                        <div class="app-search">
                            <input [(ngModel)]="tableService.searchTerm" type="text" class="form-control"
                                   placeholder="Search clients...">
                            <lucide-angular [img]="LucideSearch" class="app-search-icon text-muted"/>
                        </div>
                        @if (hasSelection) {
                            <button class="btn btn-danger" (click)="deleteSelected()">Delete</button>
                        }

                        <button type="submit" class="btn btn-purple rounded-circle btn-icon">
                            <ng-icon
                                name="tablerPlus" class="fs-lg"/>
                        </button>
                    </div>

                    <div class="d-flex align-items-center gap-2">
                        <span class="me-2 fw-semibold">Filter By:</span>
                        <div class="app-search">
                            <select [(ngModel)]="filterByCountry"
                                    (ngModelChange)="tableService.setFilter('countryName', filterByCountry)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">Country</option>
                                <option value="US">USA</option>
                                <option value="UK">UK</option>
                                <option value="AU">Australia</option>
                                tab
                                <option value="DE">Germany</option>
                                <option value="IN">India</option>
                            </select>
                            <lucide-angular [img]="LucideGlobe" class="app-search-icon text-muted"/>
                        </div>


                        <div class="app-search">
                            <select [(ngModel)]="filterProjectType"
                                    (ngModelChange)="tableService.setFilter('type', filterProjectType)"
                                    class="form-select form-control my-1 my-md-0">
                                <option value="All">Project Type</option>
                                <option value="Project">Project</option>
                                <option value="Contract">Contract</option>
                                <option value="Retainer">Retainer</option>
                                <option value="Dashboard">Dashboard</option>
                            </select>
                            <lucide-angular [img]="LucideLayout" class="app-search-icon text-muted"/>
                        </div>


                        <div>
                            <select [(ngModel)]="tableService.pageSize" data-table-set-rows-per-page
                                    class="form-select form-control my-1 my-md-0">
                                <option [ngValue]="5">5</option>
                                <option [ngValue]="8">8</option>
                                <option [ngValue]="10">10</option>
                                <option [ngValue]="15">15</option>
                            </select>
                        </div>
                    </div>

                </div>
                <div class="table-responsive">
                    <table class="table table-custom table-centered table-select table-hover w-100 mb-0">
                        <thead class="bg-light bg-opacity-25 thead-sm">
                        <tr class="text-uppercase fs-xxs">
                            <th scope="col" style="width: 1%;">
                                <input [(ngModel)]="selectAll" (change)="toggleAllSelection()"
                                       class="form-check-input form-check-input-light fs-14 mt-0"
                                       type="checkbox" id="checkAll" value="option">
                            </th>
                            <th sortable="name"
                                (sort)="tableService.setSort($event.column, $event.direction)">Clients Name
                            </th>
                            <th sortable="phone"
                                (sort)="tableService.setSort($event.column, $event.direction)">Phone
                            </th>
                            <th sortable="countryName"
                                (sort)="tableService.setSort($event.column, $event.direction)">Country
                            </th>
                            <th sortable="enrollDate"
                                (sort)="tableService.setSort($event.column, $event.direction)">Enrolled
                            </th>
                            <th sortable="type"
                                (sort)="tableService.setSort($event.column, $event.direction)">Type
                            </th>
                            <th sortable="title"
                                (sort)="tableService.setSort($event.column, $event.direction)">Job Title
                            </th>
                            <th sortable="status"
                                (sort)="tableService.setSort($event.column, $event.direction)">Status
                            </th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            @if ((total$ | async)! > 0) {
                                @for (client of records$ | async; track $index) {
                                    <tr>
                                        <td><input type="checkbox"    class="form-check-input form-check-input-light fs-14 mt-0"
                                                   [(ngModel)]="client.selected"
                                                   (change)="toggleSingleSelection()"/></td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <div class="avatar avatar-sm">
                                                    <img [src]="client.avatar" [alt]="client.name"
                                                         class="img-fluid rounded-circle"/>
                                                </div>
                                                <div>
                                                    <h5 class="mb-0 fs-base">
                                                        <a routerLink="/pages/profile"
                                                           class="link-reset">{{ client.name }}</a>
                                                    </h5>
                                                    <p class="text-muted fs-xs mb-0">{{ client.email }}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>{{ client.phone }}</td>
                                        <td>
                                            <span class="badge p-1 text-bg-light fs-sm">
                                              <img [src]="client.flag" class="rounded-circle me-1" height="12"/>
                                                {{ client.countryName }}
                                            </span>
                                        </td>
                                        <td>{{ client.enrollDate }}</td>
                                        <td>{{ client.type }}</td>
                                        <td>{{ client.title }}</td>
                                        <td>
                            <span
                                class="badge badge-label"
                                [class]="client.status === 'pending' ?
                                'bg-warning-subtle text-warning': client.status === 'inactive' ?
                                'bg-danger-subtle text-danger':
                                'bg-success-subtle text-success'
                              "
                            >
                              {{ toTitleCase(client.status) }}
                            </span>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center justify-content-center gap-1">
                                                <a [routerLink]="[]" class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon name="tablerEye" class="fs-lg"/>
                                                </a>
                                                <a [routerLink]="[]" class="btn btn-light btn-icon btn-sm rounded-circle">
                                                    <ng-icon name="tablerEdit" class="fs-lg"/>
                                                </a>
                                                <button class="btn btn-light btn-icon btn-sm rounded-circle"
                                                        (click)="tableService.deleteItem(client)">
                                                    <ng-icon name="tablerTrash" class="fs-lg"/>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            } @else {
                                <tr class="no-results">
                                    <td colspan="11" class="text-center text-muted py-3">Nothing found.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer border-0">
                    @if ((total$ | async)! > 0) {
                        <div
                            class="pagination pagination-boxed mb-0 justify-content-between align-items-center">
                            {{ tableService.showingRange }} clients
                            <ngb-pagination
                                [collectionSize]="(total$ | async)!"
                                [(page)]="tableService.page"
                                [pageSize]="tableService.pageSize"
                            >
                                <ng-template ngbPaginationPrevious>
                                    <ng-icon name="tablerChevronLeft"/>
                                </ng-template>
                                <ng-template ngbPaginationNext>
                                    <ng-icon name="tablerChevronRight"/>
                                </ng-template>
                            </ngb-pagination>

                        </div>
                    }
                </div>
            </div>
        </div>
    </div>

</div>
