// src/layouts/components/topbar/index.vue
<template>
  <header class="app-topbar">
    <div class="container-fluid topbar-menu">
      <div class="d-flex align-items-center gap-2">
        <div class="logo-topbar">
          <RouterLink to="/" class="logo-light">
            <span class="logo-lg">
              <img :src="logo" alt="logo" />
            </span>
            <span class="logo-sm">
              <img :src="logoSm" alt="small logo" />
            </span>
          </RouterLink>

          <RouterLink to="/" class="logo-dark">
            <span class="logo-lg">
              <img :src="logoDark" alt="dark logo" />
            </span>
            <span class="logo-sm">
              <img :src="logoSm" alt="small logo" />
            </span>
          </RouterLink>
        </div>

        <!-- Sidebar Menu Toggle Button -->
        <button class="sidenav-toggle-button btn btn-primary btn-icon" @click="toggleSideNav">
          <Icon icon="tabler:menu-4" class="fs-22" />
        </button>

        <!-- Search -->
        <div class="app-search d-none d-xl-flex">
          <BFormInput
            type="search"
            class="topbar-search"
            name="search"
            :placeholder="t('topbar.search')"
          />
          <Icon icon="lucide:search"  class="app-search-icon text-muted" />
        </div>

        <MegaMenu />
      </div>

      <div class="d-flex align-items-center gap-2">
        <LanguageDropdown />

        <MessageDropdown />

        <NotificationDropdown />

        <CustomizerToggler />

        <ThemeToggler />

        <UserProfile />
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import MegaMenu from '@/layouts/components/topbar/components/MegaMenu.vue'
import LanguageDropdown from '@/layouts/components/topbar/components/LanguageDropdown.vue'
import MessageDropdown from '@/layouts/components/topbar/components/MessageDropdown.vue'
import NotificationDropdown from '@/layouts/components/topbar/components/NotificationDropdown.vue'
import CustomizerToggler from '@/layouts/components/topbar/components/CustomizerToggler.vue'
import ThemeToggler from '@/layouts/components/topbar/components/ThemeToggler.vue'
import UserProfile from '@/layouts/components/topbar/components/UserProfile.vue'
import { useLayout } from '@/stores/layout.ts'
import { Icon } from '@iconify/vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

import logo from '@/assets/images/logo.png'
import logoSm from '@/assets/images/logo-sm.png'
import logoDark from '@/assets/images/logo-black.png'

const { layout, setSideNavSize, toggleMobileMenu } = useLayout()

const toggleSideNav = () => {
  const html = document.documentElement
  const currentSize = html.getAttribute('data-sidenav-size')

  if (currentSize === 'offcanvas') {
    toggleMobileMenu()
  } else if (layout.sidenav.size === 'compact') {
    setSideNavSize(currentSize === 'compact' ? 'condensed' : 'compact', false)
  } else {
    setSideNavSize(currentSize === 'condensed' ? 'default' : 'condensed')
  }
}
</script>

// SvelteKit/Seed/src/lib/layouts/components/topbar/index.svelte
<script lang="ts">
	import MegaMenu from '$lib/layouts/components/topbar/components/MegaMenu.svelte';
	import LanguageDropdown from '$lib/layouts/components/topbar/components/LanguageDropdown.svelte';
	import MessageDropdown from '$lib/layouts/components/topbar/components/MessageDropdown.svelte';
	import NotificationDropdown from '$lib/layouts/components/topbar/components/NotificationDropdown.svelte';
	import CustomizerToggler from '$lib/layouts/components/topbar/components/CustomizerToggler.svelte';
	import ThemeToggler from '$lib/layouts/components/topbar/components/ThemeToggler.svelte';
	import UserProfile from '$lib/layouts/components/topbar/components/UserProfile.svelte';

	import Icon from '@iconify/svelte';
	import { layout, setSideNavSize } from '$lib/stores/layout';
	import { Container, Input } from '@sveltestrap/sveltestrap';
	import { showBackdrop, toggleAttribute } from '$lib/helpers/layout';

	import logo from '$lib/assets/images/logo.png';
	import logoSm from '$lib/assets/images/logo-sm.png';
	import logoDark from '$lib/assets/images/logo-black.png';

	const toggleSideNav = () => {
		const html = document.documentElement;
		const currentSize = html.getAttribute('data-sidenav-size');

		if (currentSize === 'offcanvas') {
			toggleAttribute('class', 'sidebar-enable');
			showBackdrop();
		} else if ($layout.sidenav.size === 'compact') {
			setSideNavSize(currentSize === 'compact' ? 'condensed' : 'compact', false);
		} else {
			setSideNavSize(currentSize === 'condensed' ? 'default' : 'condensed');
		}
	};
</script>

<header class="app-topbar">
	<Container fluid class="topbar-menu">
		<div class="d-flex align-items-center gap-2">
			<div class="logo-topbar">
				<a href="/" class="logo-light">
					<span class="logo-lg">
						<img src={logo} alt="logo" />
					</span>
					<span class="logo-sm">
						<img src={logoSm} alt="small logo" />
					</span>
				</a>

				<a href="/" class="logo-dark">
					<span class="logo-lg">
						<img src={logoDark} alt="dark logo" />
					</span>
					<span class="logo-sm">
						<img src={logoSm} alt="small logo" />
					</span>
				</a>
			</div>

			<!-- Sidebar Menu Toggle Button -->
			<button class="sidenav-toggle-button btn btn-primary btn-icon" on:click={toggleSideNav}>
				<Icon icon="tabler:menu-4" class="fs-22" />
			</button>

			<!-- Search -->
			<div class="app-search d-none d-xl-flex">
				<Input
					type="search"
					class="topbar-search"
					name="search"
					placeholder="Search for something..."
				/>
				<Icon icon="lucide:search" height="18" width="18" class="app-search-icon text-muted" />
			</div>

			<MegaMenu />
		</div>

		<div class="d-flex align-items-center gap-2">
			<LanguageDropdown />

			<MessageDropdown />

			<NotificationDropdown />

			<CustomizerToggler />

			<ThemeToggler />

			<UserProfile />
		</div>
	</Container>
</header>
