// SvelteKit/Seed/src/routes/(admin)/dashboard/components/RecentOrders.svelte
<script lang="ts">
	import UICard from '$lib/components/UICard.svelte';
	import Icon from '@iconify/svelte';
	import {
		Dropdown,
		DropdownItem,
		DropdownMenu,
		DropdownToggle,
		Table
	} from '@sveltestrap/sveltestrap';
	import Pagination from '$lib/components/Pagination.svelte';
	import { derived, writable } from 'svelte/store';
	import { orders as ordersData } from '../data';
	import { currency } from '$lib/helpers';
	import { toTitleCase } from '$lib/helpers/casing';
	import type { OrderType } from '../types';

	const orders = writable<OrderType[]>(ordersData);
	const currentPage = writable(1);
	const perPage = writable(5);

	const totalItems = derived(orders, ($orders) => $orders.length);

	const paginatedOrders = derived(
		[orders, currentPage, perPage],
		([$orders, $currentPage, $perPage]) => {
			const start = ($currentPage - 1) * $perPage;
			return $orders.slice(start, start + $perPage);
		}
	);
</script>

<UICard title="Recent Orders" hasCardFooter bodyClass="p-0" footerClass="border-0">
	<svelte:fragment slot="card-header-actions">
		<div class="d-flex gap-2">
			<a href={null} class="btn btn-sm btn-soft-secondary">
				<Icon icon="tabler:plus" class="me-1" />
				Add Order
			</a>
			<a href={null} class="btn btn-sm btn-primary">
				<Icon icon="tabler:file-export" class="me-1" />
				Export CSV
			</a>
		</div>
	</svelte:fragment>

	<Table responsive class="table-centered table-custom table-nowrap mb-0">
		<tbody>
			{#each $paginatedOrders as item (item.id)}
				<tr>
					<td>
						<div class="d-flex align-items-center">
							<img src={item.user.image} alt="avatar" class="avatar-sm rounded-circle me-2" />
							<div>
								<h5 class="fs-base my-1"><a href={item.url} class="text-body">{item.id}</a></h5>
								<span class="text-muted fs-xs">{item.user.name}</span>
							</div>
						</div>
					</td>
					<td>
						<span class="text-muted fs-xs">Product</span>
						<h5 class="fs-base mt-1 fw-normal">{item.product}</h5>
					</td>
					<td>
						<span class="text-muted fs-xs">Date</span>
						<h5 class="fs-base mt-1 fw-normal">{item.date}</h5>
					</td>
					<td>
						<span class="text-muted fs-xs">Amount</span>
						<h5 class="fs-base mt-1 fw-normal">{currency}{item.amount}</h5>
					</td>
					<td>
						<span class="text-muted fs-xs">Status</span>
						<h5 class="fs-base mt-1 fw-normal">
							<Icon icon="tabler:circle-filled" class="fs-xs text-{item.variant}" />
							{toTitleCase(item.status)}
						</h5>
					</td>
					<td style="width: 30px;">
						<Dropdown>
							<DropdownToggle color="link" class="p-0 text-muted">
								<Icon icon="tabler:dots-vertical" class="fs-lg" />
							</DropdownToggle>
							<DropdownMenu end>
								<DropdownItem href="#">View Details</DropdownItem>
								<DropdownItem href="#">Cancel Order</DropdownItem>
							</DropdownMenu>
						</Dropdown>
					</td>
				</tr>
			{/each}
		</tbody>
	</Table>

	<svelte:fragment slot="card-footer">
		<Pagination {currentPage} {perPage} {totalItems} paginationInfoLabel="orders" />
	</svelte:fragment>
</UICard>

// Vue-Inertia/Seed/resources/js/pages/dashboard/components/RecentOrders.vue
<template>
  <UICard title="Recent Orders" body-class="p-0" footer-class="border-0">
    <template #card-header-actions>
      <div class="d-flex gap-2">
        <Link href="#" class="btn btn-sm btn-soft-secondary">
          <Icon icon="tabler:plus" class="me-1" />
          Add Order
        </Link>
        <Link href="#" class="btn btn-sm btn-primary">
          <Icon icon="tabler:file-export" class="me-1" />
          Export CSV
        </Link>
      </div>
    </template>

    <BTable
      small
      hover
      :fields="fields"
      :items="orders"
      :per-page="perPage"
      :current-page="currentPage"
      responsive
      thead-class="d-none"
      class="table table-centered table-custom table-nowrap mb-0"
    >
      <template #cell(iduserurl)="data">
        <div class="d-flex align-items-center">
          <img :src="data.item.user.image" alt="" class="avatar-sm rounded-circle me-2" />
          <div>
            <h5 class="fs-base my-1">
              <Link :href="data.item.url" class="text-body">#{{ data.item.id }}</Link>
            </h5>
            <span class="text-muted fs-xs">{{ data.item.user.name }}</span>
          </div>
        </div>
      </template>

      <template #cell(product)="data">
        <span class="text-muted fs-xs">Product</span>
        <h5 class="fs-base mt-1 fw-normal">{{ data.item.product }}</h5>
      </template>

      <template #cell(date)="data">
        <span class="text-muted fs-xs">Date</span>
        <h5 class="fs-base mt-1 fw-normal">{{ data.item.date }}</h5>
      </template>

      <template #cell(amount)="data">
        <span class="text-muted fs-xs">Amount</span>
        <h5 class="fs-base mt-1 fw-normal">{{ currency }}{{ data.item.amount }}</h5>
      </template>

      <template #cell(statusvariant)="data">
        <span class="text-muted fs-xs">Status</span>
        <h5 class="fs-base mt-1 fw-normal">
          <Icon icon="tabler:circle-filled" :class="`fs-xs text-${data.item.variant}`" />
          {{ toTitleCase(data.item.status) }}
        </h5>
      </template>

      <template #cell(actions)>
        <BDropdown
          :variant="null"
          placement="bottom-end"
          no-caret
          toggle-class="text-muted card-drop border-0 p-0"
        >
          <template #button-content>
            <Icon icon="tabler:dots-vertical" class="fs-lg" />
          </template>

          <BDropdownItem>View Details</BDropdownItem>
          <BDropdownItem>Cancel Order</BDropdownItem>
        </BDropdown>
      </template>
    </BTable>

    <template #card-footer>
      <div class="align-items-center justify-content-between row text-center text-sm-start">
        <BCol class="col-sm">
          <span class="text-muted"
            >Showing <span class="fw-semibold">{{ start }}</span> to
            <span class="fw-semibold">{{ end }}</span> of
            <span class="fw-semibold">{{ totalItems }}</span> orders</span
          >
        </BCol>
        <BCol class="col-sm-auto mt-3 mt-sm-0">
          <BPagination
            v-model="currentPage"
            :total-rows="orders.length"
            :per-page="perPage"
            align="end"
            first-number
            last-number
            class="m-0 pagination-boxed"
          >
            <template #prev-text>
              <Icon icon="tabler:chevron-left" />
            </template>
            <template #next-text>
              <Icon icon="tabler:chevron-right" />
            </template>
          </BPagination>
        </BCol>
      </div>
    </template>
  </UICard>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { currency } from '@/helpers'
import { toTitleCase } from '@/helpers/casing'
import type { OrderType } from '@/pages/dashboard/components/types'
import { orders as orderData } from '@/pages/dashboard/components/data'
import UICard from '@/components/UICard.vue'
import { computed, ref } from 'vue'
import { Link } from '@inertiajs/vue3'

const fields = [
  { key: 'iduserurl', label: 'Id' },
  { key: 'product', label: 'Product' },
  { key: 'date', label: 'Date' },
  { key: 'amount', label: 'Amount' },
  { key: 'statusvariant', label: 'Status' },
  { key: 'actions', label: 'Actions' },
]

const currentPage = ref(1)
const perPage = ref(5)

const orders = ref<OrderType[]>(orderData)

const totalItems = computed(() => orders.value.length)

const start = computed(() =>
  totalItems.value === 0 ? 0 : (currentPage.value - 1) * perPage.value + 1,
)

const end = computed(() => Math.min(currentPage.value * perPage.value, totalItems.value))
</script>
