// SvelteKit/Seed/src/lib/components/CustomEChart.svelte
<script lang="ts">
	import { Chart } from 'svelte-echarts';
	import type { EChartsOption } from 'echarts';
	import { getDefaultFontFamily } from '$lib/helpers/chart';
	import { onMount } from 'svelte';
	import { get } from 'svelte/store';

	import { init, use } from 'echarts/core';

	import { layout } from '$lib/stores/layout';

	export let getOptions: () => EChartsOption;
	export let extensions: any[] = [];
	export let style: string = 'width: 100%; height: 100%';

	let chartOptions: EChartsOption = {};
	let extensionsRegistered = false;

	let layoutKey = '';

	if (!extensionsRegistered) {
		use(extensions);
		extensionsRegistered = true;
	}

	onMount(() => {
		updateOptions();

		const unsubscribe = layout.subscribe(() => {
			layoutKey = `${get(layout).theme}-${get(layout).skin}`;
			updateOptions();
		});

		return () => unsubscribe();
	});

	function updateOptions() {
		const baseOptions = getOptions();
		chartOptions = {
			...baseOptions,
			textStyle: {
				...(baseOptions.textStyle || {}),
				fontFamily: getDefaultFontFamily()
			}
		};
	}
</script>

<div {style}>
	<Chart options={chartOptions} {init} style="width: 100%; height: 100%;" />
</div>

// Nuxt/Seed/components/CustomEChart.vue
<template>
  <client-only>
    <VChart
        :key="layoutKey"
        :option="options"
        v-bind="props"
        autoresize
    />
  </client-only>
</template>

<script setup lang="ts">
import {use} from 'echarts/core';
import type {EChartsOption} from 'echarts'
import {getDefaultFontFamily} from "~/helpers/chart";

type PropsType = {
  getOptions: () => EChartsOption
  extensions: any[]
}

const props = defineProps<PropsType>()

let extensionsRegistered = false

onBeforeMount(() => {
  if (!extensionsRegistered) {
    use(props.extensions)
    extensionsRegistered = true
  }
})

const {layout} = useLayout();

const layoutKey = computed(() =>
    `${layout.theme}-${layout.skin}`
)

const options = ref<EChartsOption>()

onMounted(() => {
  watch(layoutKey, () => {
    if (typeof window === 'undefined') return
    window.requestAnimationFrame(() => {
        const baseOptions = props.getOptions()

        options.value = {
          ...baseOptions,
          textStyle: {
            ...(baseOptions.textStyle || {}),
            fontFamily: getDefaultFontFamily()
          }
        } as EChartsOption

    })
  }, {immediate: true})
})
</script>
