// Nuxt/Full/pages/tables/static/components/HoverableRowsTable.vue
<template>
  <BCard no-body>
    <BCardHeader class="justify-content-between d-flex align-items-center">
      <BCardTitle>Hoverable Rows</BCardTitle>
      <NuxtLink
        to="https://react-bootstrap.netlify.app/docs/components/table#example"
        target="_blank"
        class="icon-link icon-link-hover link-secondary link-underline-secondarlink-secondary link-underline-opacity-25 fw-semibold"
      >
        View Docs <Icon name="tabler:arrow-right" class="bi align-middle fs-lg" />
      </NuxtLink>
    </BCardHeader>

    <BCardBody>
      <BTableSimple responsive hover class="align-middle mb-0">
        <thead class="align-middle thead-sm">
          <tr class="text-uppercase fs-xxs">
            <th
              v-for="(header, idx) in productsTable.header"
              :key="idx"
              :style="header === 'Actions' ? { width: '1%' } : { width: 'auto' }"
            >
              {{ header }}
            </th>
          </tr>
        </thead>

        <tbody>
          <tr v-for="(product, idx) in productsTable.data" :key="idx">
            <td>{{ product.name }}</td>
            <td>{{ product.category }}</td>
            <td>{{ currency }}{{ product.price.toFixed(2) }}</td>
            <td>{{ product.stock }}</td>
            <td>{{ product.rating }} ★</td>
            <td>
              <span
                :class="[
                  'badge',
                  'badge-label',
                  `badge-soft-${product.status === 'Active' ? 'success' : 'warning'}`
                ]"
              >
                {{ product.status }}
              </span>
            </td>

            <td class="text-end">
              <BDropdown
                variant="link"
                toggle-class="drop-arrow-none fs-xxl link-reset p-0 text-muted"
                end
              >
                <template #button-content>
                  <Icon name="tabler:dots-vertical" />
                </template>
                <BDropdownItem>
                  <Icon name="tabler:eye" class="me-1" /> View
                </BDropdownItem>
                <BDropdownItem>
                  <Icon name="tabler:edit" class="me-1" /> Edit
                </BDropdownItem>
                <BDropdownItem to="#" class="text-danger">
                  <Icon name="tabler:trash" class="me-1" /> Delete
                </BDropdownItem>
              </BDropdown>
            </td>
          </tr>
        </tbody>
      </BTableSimple>
    </BCardBody>
  </BCard>
</template>

<script setup lang="ts">
import { currency } from '~/helpers';
import { productsTable } from '../data';
import { BTableSimple } from 'bootstrap-vue-next';


</script>

// NextJs/NextJs/Full/TS/src/app/(admin)/tables/static/components/HoverableRowsTable.tsx
import { productsTable } from '@/app/(admin)/tables/static/data'
import { currency } from '@/helpers'
import Link from 'next/link'
import { Card, CardBody, CardHeader, CardTitle, Dropdown, DropdownItem, DropdownMenu, DropdownToggle, Table } from 'react-bootstrap'
import { TbArrowRight, TbDotsVertical, TbEdit, TbEye, TbTrash } from 'react-icons/tb'

const HoverableRowsTable = () => {
  return (
    <Card>
      <CardHeader className="justify-content-between">
        <CardTitle> Hoverable Rows </CardTitle>
        <Link
          href="https://react-bootstrap.netlify.app/docs/components/table#example"
          target="_blank"
          className="icon-link icon-link-hover link-secondary link-underline-secondarlink-secondary link-underline-opacity-25 fw-semibold">
          View Docs <TbArrowRight className="bi align-middle fs-lg" />
        </Link>
      </CardHeader>

      <CardBody>
        <Table responsive hover className="align-middle mb-0">
          <thead className="align-middle thead-sm">
            <tr className="text-uppercase fs-xxs">
              {productsTable.header.map((header, idx) => (
                <th key={idx} style={header === 'Actions' ? { width: '1%' } : { width: 'auto' }}>
                  {header}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {productsTable.data.map((product, idx) => (
              <tr key={idx}>
                <td>{product.name}</td>
                <td>{product.category}</td>
                <td>
                  {currency}
                  {product.price.toFixed(2)}
                </td>
                <td>{product.stock}</td>
                <td>{product.rating} ★</td>
                <td>
                  <span className={`badge badge-label badge-soft-${product.status === 'Active' ? 'success' : 'warning'}`}>{product.status}</span>
                </td>
                <td className="text-end">
                  <Dropdown align="end" className="text-muted">
                    <DropdownToggle variant="link" className="drop-arrow-none fs-xxl link-reset p-0">
                      <TbDotsVertical />
                    </DropdownToggle>
                    <DropdownMenu>
                      <DropdownItem href="#">
                        <TbEye className="me-1" /> View
                      </DropdownItem>
                      <DropdownItem href="#">
                        <TbEdit className="me-1" /> Edit
                      </DropdownItem>
                      <DropdownItem href="#" className="text-danger">
                        <TbTrash className="me-1" /> Delete
                      </DropdownItem>
                    </DropdownMenu>
                  </Dropdown>
                </td>
              </tr>
            ))}
          </tbody>
        </Table>
      </CardBody>
    </Card>
  )
}

export default HoverableRowsTable
