// SvelteKit/Seed/src/routes/(auth)/auth-1/reset-password/+page.svelte
<script lang="ts">
	import { author, currentYear } from '$lib/helpers';
	import { Button, Card, Col, Container, Form, Input, Row } from '@sveltestrap/sveltestrap';
	import AuthLogo from '$lib/components/AuthLogo.svelte';
	import PageMeta from '$lib/components/PageMeta.svelte';
</script>

<PageMeta title="Reset Password" />

<div class="auth-box overflow-hidden d-flex align-items-center">
	<Container>
		<Row class="justify-content-center">
			<Col sm="8" md="6" xxl="4">
				<div class="auth-brand text-center mb-4">
					<AuthLogo />
					<h4 class="fw-bold mt-3">Forgot Password ? | IN+</h4>
					<p class="text-muted w-lg-75 mx-auto">
						Enter your email address and we'll send you a link to reset your password.
					</p>
				</div>

				<Card class="p-4 rounded-4">
					<Form>
						<div class="mb-3">
							<label for="userEmail" class="form-label">
								Email address <span class="text-danger">*</span>
							</label>
							<div class="input-group">
								<Input type="email" id="userEmail" placeholder="you@example.com" required />
							</div>
						</div>

						<div class="mb-3">
							<Input type="checkbox" label="Agree the Terms & Policy" name="agree" />
						</div>

						<div class="d-grid">
							<Button color="primary" type="submit" class="fw-semibold py-2">Send Request</Button>
						</div>
					</Form>

					<p class="text-muted text-center mt-4 mb-0">
						Return to
						<a href="/auth-1/sign-in" class="text-decoration-underline link-offset-3 fw-semibold">
							Sign in
						</a>
					</p>
				</Card>

				<p class="text-center text-muted mt-4 mb-0">
					© 2014 - {currentYear} INSPINIA — by <span class="fw-semibold">{author}</span>
				</p>
			</Col>
		</Row>
	</Container>
</div>

// NextJs/NextJs/Seed/JS/src/app/(auth)/auth-1/reset-password/page.jsx
import AppLogo from '@/components/AppLogo';
import { author, currentYear } from '@/helpers';
import Link from 'next/link';
import { Button, Card, Col, Container, Form, FormControl, FormLabel, Row } from 'react-bootstrap';
const Page = () => {
  return <div className="auth-box overflow-hidden align-items-center d-flex">
      <Container>
        <Row className="justify-content-center">
          <Col xxl={4} md={6} sm={8}>
            <div className="auth-brand text-center mb-4">
              <AppLogo />
              <h4 className="fw-bold mt-3">Forgot Password ? | IN+</h4>
              <p className="text-muted w-lg-75 mx-auto">Enter your email address and we&apos;ll send you a link to reset your password.</p>
            </div>

            <Card className="p-4 rounded-4">
              <Form>
                <div className="mb-3 form-group">
                  <FormLabel>
                    Email address <span className="text-danger">*</span>
                  </FormLabel>
                  <FormControl type="email" placeholder="you@example.com" required />
                </div>

                <div className="mb-3">
                  <div className="form-check">
                    <input className="form-check-input form-check-input-light fs-14" type="checkbox" id="termAndPolicy" />
                    <label className="form-check-label" htmlFor="termAndPolicy">
                      Agree the Terms & Policy
                    </label>
                  </div>
                </div>

                <div className="d-grid">
                  <Button type="submit" className="btn btn-primary fw-semibold py-2">
                    Send Request
                  </Button>
                </div>
              </Form>

              <p className="text-muted text-center mt-4 mb-0">
                Return to{' '}
                <Link href="/auth-1/sign-in" className="text-decoration-underline link-offset-3 fw-semibold">
                  Sign in
                </Link>
              </p>
            </Card>

            <p className="text-center text-muted mt-4 mb-0">
              © 2014 - {currentYear} INSPINIA — by <span className="fw-semibold">{author}</span>
            </p>
          </Col>
        </Row>
      </Container>
    </div>;
};
export default Page;
