// Vue/Full/src/views/apps/users/contacts/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="Contacts" subTitle="Apps" />

            <BRow class="mb-3">
                <BCol lg="12">
                    <form class="bg-light-subtle rounded border p-3">

                        <BRow class="gap-3">
                            <BCol lg="4">
                                <div class="app-search">
                                    <input type="text" class="form-control" placeholder="Search contact name...">
                                    <Icon  icon="tabler:search" class="app-search-icon text-muted" />
                                </div>
                            </BCol>
                            <BCol>
                                <div class="d-flex flex-wrap align-items-center gap-2">
                                    <span class="me-2 fw-semibold">Filter By:</span>

                                    <div class="app-search">
                                        <select class="form-select form-control my-1 my-md-0">
                                            <option selected>Designation</option>
                                            <option value="Manager">Manager</option>
                                            <option value="Developer">Developer</option>
                                            <option value="Designer">Designer</option>
                                            <option value="Sales">Sales</option>
                                            <option value="Support">Support</option>
                                        </select>
                                        <Icon  icon="lucide:user-check" class="app-search-icon text-muted" />
                                    </div>

                                    <div class="app-search">
                                        <select class="form-select form-control my-1 my-md-0">
                                            <option selected>Location</option>
                                            <option value="USA">USA</option>
                                            <option value="UK">UK</option>
                                            <option value="Germany">Germany</option>
                                            <option value="India">India</option>
                                            <option value="Canada">Canada</option>
                                        </select>
                                        <Icon  icon="lucide:map-pin" class="app-search-icon text-muted" />
                                    </div>

                                    <div class="app-search">
                                        <select class="form-select form-control my-1 my-md-0">
                                            <option selected>Department</option>
                                            <option value="UI/UX">UI/UX</option>
                                            <option value="Engineering">Engineering</option>
                                            <option value="HR">HR</option>
                                            <option value="Marketing">Marketing</option>
                                            <option value="Finance">Finance</option>
                                        </select>
                                        <Icon  icon="lucide:layers" class="app-search-icon text-muted" />
                                    </div>

                                    <button type="submit" class="btn btn-secondary">Apply</button>

                                    <div role="group" aria-label="Layout toggle button group"
                                        class="ms-auto flex-shrink-0">
                                        <input type="radio" class="btn-check" name="btnradio" id="btnradio1" checked>
                                        <label class="btn btn-soft-primary btn-icon me-1" for="btnradio1">
                                            <Icon icon="lucide:layout-grid" class="fs-lg" />
                                        </label>

                                        <input type="radio" class="btn-check" name="btnradio" id="btnradio2">
                                        <label class="btn btn-soft-primary btn-icon" for="btnradio2">
                                            <Icon icon="lucide:list" class="fs-lg" />
                                        </label>
                                    </div>

                                </div>
                            </BCol>
                        </BRow>
                    </form>
                </BCol>
            </BRow>

            <BRow>
                <BCol md="6" xxl="3" v-for="(contact, idx) in contacts" :key="idx">
                    <ContactCard :contact="contact" />
                </BCol>
            </BRow>

            <ul class="pagination pagination-rounded pagination-boxed justify-content-center">
                <BPagination first-number last-number hide-ellipsis :total-rows="50" :per-page="10"
                    class="pagination-boxed" />
            </ul>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BPagination, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '@/components/PageBreadcrumb.vue';
import ContactCard from './components/ContactCard.vue';
import { contacts } from './data';
import { usePageMeta } from '@/composables/usePageMeta';
import MainLayout from '@/layouts/MainLayout.vue';
import { Icon } from '@iconify/vue';

usePageMeta('Contacts')
</script>

<style scoped></style>

// React-Inertia/Full/resources/js/pages/apps/users/contacts/index.tsx
import PageBreadcrumb from '@/components/PageBreadcrumb'
import { Col, Container, Pagination, Row } from 'react-bootstrap'
import { LuLayers, LuLayoutGrid, LuList, LuMapPin, LuSearch, LuUserCheck } from 'react-icons/lu'
import ContactCard from '@/pages/apps/users/contacts/components/ContactCard'
import { TbChevronLeft, TbChevronRight } from 'react-icons/tb'
import { contacts } from '@/pages/apps/users/contacts/data'
import MainLayout from '@/layouts/MainLayout'

const Page = () => {
    return (
        <MainLayout>
            <Container fluid>
                <PageBreadcrumb title="Contacts" subtitle="Apps" />
                <Row className="mb-3">
                    <Col lg={12}>
                        <form className="bg-light-subtle rounded border p-3">
                            <Row className="gap-3">
                                <Col lg={4}>
                                    <div className="app-search">
                                        <input type="text" className="form-control" placeholder="Search contact name..." />
                                        <LuSearch className="app-search-icon text-muted" />
                                    </div>
                                </Col>
                                <Col>
                                    <div className="d-flex flex-wrap align-items-center gap-2">
                                        <span className="me-2 fw-semibold">Filter By:</span>

                                        <div className="app-search">
                                            <select className="form-select form-control my-1 my-md-0">
                                                <option>Designation</option>
                                                <option value="Manager">Manager</option>
                                                <option value="Developer">Developer</option>
                                                <option value="Designer">Designer</option>
                                                <option value="Sales">Sales</option>
                                                <option value="Support">Support</option>
                                            </select>
                                            <LuUserCheck className="app-search-icon text-muted" />
                                        </div>

                                        <div className="app-search">
                                            <select className="form-select form-control my-1 my-md-0">
                                                <option>Location</option>
                                                <option value="USA">USA</option>
                                                <option value="UK">UK</option>
                                                <option value="Germany">Germany</option>
                                                <option value="India">India</option>
                                                <option value="Canada">Canada</option>
                                            </select>
                                            <LuMapPin className="app-search-icon text-muted" />
                                        </div>

                                        <div className="app-search">
                                            <select className="form-select form-control my-1 my-md-0">
                                                <option>Department</option>
                                                <option value="UI/UX">UI/UX</option>
                                                <option value="Engineering">Engineering</option>
                                                <option value="HR">HR</option>
                                                <option value="Marketing">Marketing</option>
                                                <option value="Finance">Finance</option>
                                            </select>
                                            <LuLayers className="app-search-icon text-muted" />
                                        </div>
                                        <button type="submit" className="btn btn-secondary">
                                            Apply
                                        </button>
                                        <div role="group" aria-label="Layout toggle button group" className="ms-auto flex-shrink-0">
                                            <input type="radio" className="btn-check " name="btnradio" id="btnradio1" defaultChecked />
                                            <label className="btn btn-soft-primary btn-icon me-1" htmlFor="btnradio1">
                                                <LuLayoutGrid className="fs-lg" />
                                            </label>
                                            <input type="radio" className="btn-check" name="btnradio" id="btnradio2" />
                                            <label className="btn btn-soft-primary btn-icon" htmlFor="btnradio2">
                                                <LuList className="fs-lg" />
                                            </label>
                                        </div>
                                    </div>
                                </Col>
                            </Row>
                        </form>
                    </Col>
                </Row>
                <Row>
                    {contacts.map((contact, idx) => (
                        <Col xxl={3} md={6} key={idx}>
                            <ContactCard contact={contact} />
                        </Col>
                    ))}
                </Row>

                <Pagination className="pagination-rounded pagination-boxed justify-content-center">
                    <Pagination.Prev disabled>
                        <TbChevronLeft />
                    </Pagination.Prev>
                    <Pagination.Item active>{1}</Pagination.Item>
                    <Pagination.Item>{2}</Pagination.Item>
                    <Pagination.Item>{3}</Pagination.Item>
                    <Pagination.Item>{4}</Pagination.Item>
                    <Pagination.Item>{5}</Pagination.Item>
                    <Pagination.Ellipsis />
                    <Pagination.Item>{20}</Pagination.Item>
                    <Pagination.Next>
                        <TbChevronRight />
                    </Pagination.Next>
                </Pagination>
            </Container>
        </MainLayout>
    )
}

export default Page
