// NextJs/NextJs/Full/JS/src/app/(admin)/ui/links/page.jsx
import ComponentCard from '@/components/cards/ComponentCard';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import Link from 'next/link';
import { Card, CardBody, CardHeader, CardTitle, Col, Container, Row } from 'react-bootstrap';
import { TbChevronRight } from 'react-icons/tb';
const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'purple', 'pink', 'orange', 'light', 'link'];
const ColoredLinks = () => {
  return <ComponentCard title="Colored links">
      <p className="text-muted">
        You can use the <code>.link-*</code> classes to colorize links. Unlike the
        <Link href="/ui/utilities">
          <code>.text-*</code> classes
        </Link>
        , these classes have a <code>:hover</code> and <code>:focus</code> state. Some of the link styles use a relatively light foreground color, and
        should only be used on a dark background in order to have sufficient contrast.
      </p>
      {colorVariants.slice(0, 6).map((item, idx) => <p key={idx}>
          <Link href="" className={`link-${item}`}>
            {item.charAt(0).toUpperCase() + item.slice(1)} link
          </Link>
        </p>)}
      <p>
        <Link href="" className="link-light">
          Light link
        </Link>
      </p>
      <p>
        <Link href="" className="link-dark">
          Dark link
        </Link>
      </p>
      <p className="mb-0">
        <Link href="" className="link-body-emphasis">
          Emphasis link
        </Link>
      </p>
    </ComponentCard>;
};
const LinkUtilities = () => {
  return <ComponentCard title="Link utilities">
      <p className="text-muted">
        <Link href="/ui/utilities">Colored link helpers</Link> have been updated to pair with our link utilities. Use the new utilities to modify the
        link opacity, underline opacity, and underline offset.
      </p>
      {colorVariants.slice(0, 6).map((item, idx) => <p key={idx}>
          <Link href="" className={`link-${item} text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover`}>
            {item.charAt(0).toUpperCase() + item.slice(1)} link
          </Link>
        </p>)}
      <p>
        <Link href="" className="link-light text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
          Light link
        </Link>
      </p>
      <p>
        <Link href="" className="link-dark text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
          Dark link
        </Link>
      </p>
      <p>
        <Link href="" className="link-body-emphasis text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover">
          Emphasis link
        </Link>
      </p>
    </ComponentCard>;
};
const LinkOpacity = () => {
  return <ComponentCard title="Link opacity">
      <p className="text-muted">
        Change the alpha opacity of the link <code>rgba()</code> color value with utilities. Please be aware that changes to a color’s opacity can
        lead to links with <em>insufficient</em> contrast.
      </p>
      <p>
        <Link className="link-opacity-10" href="">
          Link opacity 10
        </Link>
      </p>
      <p>
        <Link className="link-opacity-25" href="">
          Link opacity 25
        </Link>
      </p>
      <p>
        <Link className="link-opacity-50" href="">
          Link opacity 50
        </Link>
      </p>
      <p>
        <Link className="link-opacity-75" href="">
          Link opacity 75
        </Link>
      </p>
      <p className="mb-0">
        <Link className="link-opacity-100" href="">
          Link opacity 100
        </Link>
      </p>
    </ComponentCard>;
};
const LinkHoverOpacity = () => {
  return <ComponentCard title="Link hover opacity">
      <p className="text-muted">You can even change the opacity level on hover.</p>
      <p>
        <Link className="link-opacity-10-hover" href="">
          Link hover opacity 10
        </Link>
      </p>
      <p>
        <Link className="link-opacity-25-hover" href="">
          Link hover opacity 25
        </Link>
      </p>
      <p>
        <Link className="link-opacity-50-hover" href="">
          Link hover opacity 50
        </Link>
      </p>
      <p>
        <Link className="link-opacity-75-hover" href="">
          Link hover opacity 75
        </Link>
      </p>
      <p className="mb-0">
        <Link className="link-opacity-100-hover" href="">
          Link hover opacity 100
        </Link>
      </p>
    </ComponentCard>;
};
const UnderlineColor = () => {
  return <ComponentCard title="Underline color">
      <p className="text-muted">Change the underline’s color independent of the link text color.</p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-primary">
          Primary underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-secondary">
          Secondary underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-success">
          Success underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-danger">
          Danger underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-warning">
          Warning underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-info">
          Info underline
        </Link>
      </p>
      <p>
        <Link href="" className="text-decoration-underline link-underline-light">
          Light underline
        </Link>
      </p>
      <p className="mb-0">
        <Link href="" className="text-decoration-underline link-underline-dark">
          Dark underline
        </Link>
      </p>
    </ComponentCard>;
};
const UnderlineOpacity = () => {
  return <ComponentCard title="Underline opacity">
      <p className="text-muted">
        Change the underline’s opacity. Requires adding
        <code>.link-underline</code> to first set an <code>rgba()</code> color we use to then modify the alpha opacity.
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-0" href="#">
          Underline opacity 0
        </Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-10" href="#">
          Underline opacity 10
        </Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-25" href="#">
          Underline opacity 25
        </Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-50" href="#">
          Underline opacity 50
        </Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-75" href="#">
          Underline opacity 75
        </Link>
      </p>
      <p className="mb-0">
        <Link className="text-decoration-underline link-offset-2 link-underline link-underline-opacity-100" href="#">
          Underline opacity 100
        </Link>
      </p>
    </ComponentCard>;
};
const UnderlineOffset = () => {
  return <ComponentCard title="Underline offset">
      <p className="text-muted">
        Change the underline’s opacity. Requires adding
        <code>.link-underline</code> to first set an <code>rgba()</code> color we use to then modify the alpha opacity.
      </p>
      <p>
        <Link href="">Default link</Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-1" href="">
          Offset 1 link
        </Link>
      </p>
      <p>
        <Link className="text-decoration-underline link-offset-2" href="">
          Offset 2 link
        </Link>
      </p>
      <p className="mb-0">
        <Link className="text-decoration-underline link-offset-3" href="">
          Offset 3 link
        </Link>
      </p>
    </ComponentCard>;
};
const HoverVariants = () => {
  return <ComponentCard title="Hover variants">
      <p className="text-muted">
        Just like the <code>.link-opacity-*-hover</code> utilities,
        <code>.link-offset</code> and <code>.link-underline-opacity</code> utilities include
        <code>:hover</code> variants by default. Mix and match to create unique link styles.
      </p>
      <Link className="link-offset-2 link-offset-3-hover text-decoration-underline link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="">
        Underline opacity 0
      </Link>
    </ComponentCard>;
};
const page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="Links" subtitle="UI" />
        <Container fluid="xl">
          <Row>
            <Col xl={12}>
              <Card>
                <CardHeader>
                  <CardTitle as={'h4'}>Examples</CardTitle>
                </CardHeader>
                <CardBody>
                  <p className="text-muted mb-2">Documentation and examples for Colored links with hover states.</p>
                  <Link className="btn btn-link p-0 fw-semibold" href="https://getbootstrap.com/docs/5.3/helpers/colored-links/" target="_blank">
                    Links on Bootstrap
                    <TbChevronRight className="ms-1" />
                  </Link>
                </CardBody>
              </Card>
            </Col>
            <Col xl={6}>
              <ColoredLinks />
            </Col>
            <Col xl={6}>
              <LinkUtilities />
            </Col>
            <Col xl={6}>
              <LinkOpacity />
            </Col>
            <Col xl={6}>
              <LinkHoverOpacity />
            </Col>
            <Col xl={6}>
              <UnderlineColor />
            </Col>
            <Col xl={6}>
              <UnderlineOpacity />
            </Col>
            <Col xl={6}>
              <UnderlineOffset />
            </Col>
            <Col xl={6}>
              <HoverVariants />
            </Col>
          </Row>
        </Container>
      </Container>
    </>;
};
export default page;

// Angular/Full/src/app/views/ui/links/links.component.ts
import { Component } from '@angular/core';
import {PageTitleComponent} from '@app/components/page-title.component';
import {UiCardComponent} from '@app/components/ui-card.component';
import {NgIcon} from '@ng-icons/core';

@Component({
  selector: 'app-links',
    imports: [
        PageTitleComponent,
        UiCardComponent,
        NgIcon
    ],
  templateUrl: './links.component.html',
  styles: ``
})
export class LinksComponent {

}

<div class="container-fluid">
    <app-page-title title="Links" subTitle="UI" />
</div>

<div class="container-xl">
    <div class="row">
        <div class="col-xl-12">
            <app-ui-card title="Examples">
                <div card-body>
                    <p class="text-muted mb-2">
                        Documentation and examples for Colored links with hover states.
                    </p>

                    <a class="btn btn-link p-0 fw-semibold"
                       href="https://getbootstrap.com/docs/5.3/helpers/colored-links/" target="_blank">
                        Links on Bootstrap
                        <ng-icon name="tablerChevronRight" class="ms-1"/>
                    </a>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Colored Links">
                <div card-body>
                    <p class="text-muted">You can use the <code>.link-*</code> classes to colorize links. Unlike the <a
                        href="ui-utilities.html"><code>.text-*</code> classes</a>, these classes have a
                        <code>:hover</code> and <code>:focus</code> state. Some of the link styles use a relatively
                        light foreground color, and should only be used on a dark background in order to have sufficient
                        contrast.
                    </p>


                    <p><a href="javascript:void(0);" class="link-primary">Primary link</a></p>
                    <p><a href="javascript:void(0);" class="link-secondary">Secondary link</a></p>
                    <p><a href="javascript:void(0);" class="link-success">Success link</a></p>
                    <p><a href="javascript:void(0);" class="link-danger">Danger link</a></p>
                    <p><a href="javascript:void(0);" class="link-warning">Warning link</a></p>
                    <p><a href="javascript:void(0);" class="link-info">Info link</a></p>
                    <p><a href="javascript:void(0);" class="link-light">Light link</a></p>
                    <p><a href="javascript:void(0);" class="link-dark">Dark link</a></p>
                    <p class="mb-0"><a href="javascript:void(0);" class="link-body-emphasis">Emphasis link</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Link Utilities">
                <div card-body>
                    <p class="text-muted"><a href="ui-utilities.html">Colored link helpers</a> have been updated to pair
                        with our link utilities. Use the new utilities to modify the link opacity, underline opacity,
                        and underline offset.</p>

                    <p><a href="javascript:void(0);"
                          class="link-primary text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Primary
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-secondary text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Secondary
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-success text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Success
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-danger text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Danger
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-warning text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Warning
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-info text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Info
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-light text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Light
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-dark text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Dark
                        link</a></p>
                    <p><a href="javascript:void(0);"
                          class="link-body-emphasis text-decoration-underline link-offset-2 link-underline-opacity-25 link-underline-opacity-75-hover">Emphasis
                        link</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Link Opacity">
                <div card-body>
                    <p class="text-muted">Change the alpha opacity of the link <code>rgba()</code> color value with
                        utilities. Please be aware that changes to a color’s opacity can lead to links with
                        <em>insufficient</em> contrast.
                    </p>

                    <p><a class="link-opacity-10" href="javascript:void(0);">Link opacity 10</a></p>
                    <p><a class="link-opacity-25" href="javascript:void(0);">Link opacity 25</a></p>
                    <p><a class="link-opacity-50" href="javascript:void(0);">Link opacity 50</a></p>
                    <p><a class="link-opacity-75" href="javascript:void(0);">Link opacity 75</a></p>
                    <p class="mb-0"><a class="link-opacity-100" href="javascript:void(0);">Link opacity 100</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Link Hover Opacity">
                <div card-body>
                    <p class="text-muted">You can even change the opacity level on hover.</p>

                    <p><a class="link-opacity-10-hover" href="javascript:void(0);">Link hover opacity 10</a></p>
                    <p><a class="link-opacity-25-hover" href="javascript:void(0);">Link hover opacity 25</a></p>
                    <p><a class="link-opacity-50-hover" href="javascript:void(0);">Link hover opacity 50</a></p>
                    <p><a class="link-opacity-75-hover" href="javascript:void(0);">Link hover opacity 75</a></p>
                    <p class="mb-0"><a class="link-opacity-100-hover" href="javascript:void(0);">Link hover opacity 100</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Underline Color">
                <div card-body>
                    <p class="text-muted">Change the underline’s color independent of the link text color.</p>

                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-primary">Primary underline</a></p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-secondary">Secondary underline</a>
                    </p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-success">Success underline</a></p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-danger">Danger underline</a></p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-warning">Warning underline</a></p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-info">Info underline</a></p>
                    <p><a href="javascript:void(0);" class="text-decoration-underline link-underline-light">Light underline</a></p>
                    <p class="mb-0"><a href="javascript:void(0);" class="text-decoration-underline link-underline-dark">Dark underline</a>
                    </p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Underline Opacity">
                <div card-body>
                    <p class="text-muted">Change the underline’s opacity. Requires adding <code>.link-underline</code>
                        to first set an <code>rgba()</code> color we use to then modify the alpha opacity.</p>

                    <p><a class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-0"
                          href="javascript:void(0);">Underline opacity 0</a></p>
                    <p><a class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-10"
                          href="javascript:void(0);">Underline opacity 10</a></p>
                    <p><a class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-25"
                          href="javascript:void(0);">Underline opacity 25</a></p>
                    <p><a class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-50"
                          href="javascript:void(0);">Underline opacity 50</a></p>
                    <p><a class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-75"
                          href="javascript:void(0);">Underline opacity 75</a></p>
                    <p class="mb-0"><a
                        class="text-decoration-underline link-offset-2 link-underline link-underline-opacity-100"
                        href="javascript:void(0);">Underline opacity 100</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Underline Offset">
                <div card-body>
                    <p class="text-muted">Change the underline’s opacity. Requires adding <code>.link-underline</code>
                        to first set an <code>rgba()</code> color we use to then modify the alpha opacity.</p>

                    <p><a href="javascript:void(0);">Default link</a></p>
                    <p><a class="text-decoration-underline link-offset-1" href="javascript:void(0);">Offset 1 link</a></p>
                    <p><a class="text-decoration-underline link-offset-2" href="javascript:void(0);">Offset 2 link</a></p>
                    <p class="mb-0"><a class="text-decoration-underline link-offset-3" href="javascript:void(0);">Offset 3 link</a></p>
                </div>
            </app-ui-card>
        </div>

        <div class="col-xl-6">
            <app-ui-card title="Hover Variants">
                <div card-body>
                    <p class="text-muted">Just like the <code>.link-opacity-*-hover</code> utilities,
                        <code>.link-offset</code> and <code>.link-underline-opacity</code> utilities include
                        <code>:hover</code> variants by default. Mix and match to create unique link styles.
                    </p>

                    <a class="link-offset-2 link-offset-3-hover text-decoration-underline link-underline link-underline-opacity-0 link-underline-opacity-75-hover"
                       href="javascript:void(0);">
                        Underline opacity 0
                    </a>
                </div>
            </app-ui-card>
        </div>
    </div>

</div>
