// Nuxt/Full/pages/forms/basic/index.vue
<template>
    <BContainer fluid>
        <PageBreadcrumb title="Basic Elements" subtitle="Forms" />

        <BContainer>
            <BRow>
                <BCol xl='12'>
                    <InputTextFieldType />

                    <InputType />

                    <InputGroups />

                    <FloatingLabels />

                    <InputSizes />

                    <ChecksRadiosSwitches />
                </BCol>
            </BRow>
        </BContainer>
    </BContainer>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import PageBreadcrumb from '~/components/PageBreadcrumb.vue';
import InputTextFieldType from './components/InputTextFieldType.vue';
import InputType from './components/InputType.vue';
import InputGroups from './components/InputGroups.vue';
import FloatingLabels from './components/FloatingLabels.vue';
import InputSizes from './components/InputSizes.vue';
import ChecksRadiosSwitches from './components/ChecksRadiosSwitches.vue';

usePageTitle('Basic Elements')
</script>

<style scoped>

</style>

// React/Full/JS/src/views/forms/basic/index.jsx
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { Col, Container, Row } from 'react-bootstrap';
import InputTextFieldType from '@/views/forms/basic/components/InputTextFieldType';
import InputType from '@/views/forms/basic/components/InputType';
import InputGroups from '@/views/forms/basic/components/InputGroups';
import FloatingLabels from '@/views/forms/basic/components/FloatingLabels';
import InputSizes from '@/views/forms/basic/components/InputSizes';
import ChecksRadiosSwitches from '@/views/forms/basic/components/ChecksRadiosSwitches';
const Page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="Basic Elements" subtitle="Forms" />

        <Container>
          <Row>
            <Col xl={12}>
              <InputTextFieldType />

              <InputType />

              <InputGroups />

              <FloatingLabels />

              <InputSizes />

              <ChecksRadiosSwitches />
            </Col>
          </Row>
        </Container>
      </Container>
    </>;
};
export default Page;
