// Full/src/views/forms/file-uploads/index.vue
<template>
    <MainLayout>
        <BContainer fluid>
            <PageBreadcrumb title="File Uploader" subTitle="Forms" />
        </BContainer>
        <BContainer>
            <BRow class="mt-3">
                <BCol xs="12">
                    <Dropzone />

                    <FilePond />
                </BCol>
            </BRow>

        </BContainer>
    </MainLayout>
</template>

<script setup lang="ts">
import { BCol, BContainer, BRow } from 'bootstrap-vue-next';
import Dropzone from './components/Dropzone.vue';
import FilePond from './components/FilePond.vue';
import { usePageMeta } from '@/composables/usePageMeta';
import MainLayout from '@/layouts/MainLayout.vue';

usePageMeta('File Uploader')
</script>

<style scoped></style>

// NextJs/NextJs/Full/JS/src/app/(admin)/forms/file-uploads/page.jsx
import Dropzone from '@/app/(admin)/forms/file-uploads/components/Dropzone';
import FilePond from '@/app/(admin)/forms/file-uploads/components/FilePond';
import PageBreadcrumb from '@/components/PageBreadcrumb';
import { Col, Container, Row } from 'react-bootstrap';
const Page = () => {
  return <>
      <Container fluid>
        <PageBreadcrumb title="File Uploads" subtitle="Forms" />
      </Container>

      <Container>
        <Row>
          <Col cols={12}>
            <Dropzone />
            <FilePond />
          </Col>
        </Row>
      </Container>
    </>;
};
export default Page;
