// NextJs/NextJs/Seed/JS/src/components/OTPInput.jsx
'use client';

import { useRef } from 'react';
import { FormControl, FormLabel } from 'react-bootstrap';
const OTPInput = ({
  code,
  setCode,
  inputClassName,
  label,
  labelClassName
}) => {
  const inputsRef = useRef([]);
  const handleChange = (e, idx) => {
    const value = e.target.value;
    if (!/^\d?$/.test(value)) return;
    const newCode = [...code];
    newCode[idx] = value;
    setCode(newCode);
    if (value && idx < inputsRef.current.length - 1) {
      inputsRef.current[idx + 1]?.focus();
    }
  };
  const handleKeyDown = (e, idx) => {
    if (e.key === 'Backspace' && !code[idx] && idx > 0) {
      inputsRef.current[idx - 1]?.focus();
    }
  };
  return <>
      <FormLabel className={labelClassName}>
        {label} <span className="text-danger">*</span>
      </FormLabel>
      <div className="d-flex gap-2 two-factor">
        {code.map((number, idx) => <FormControl key={idx} type="text" inputMode="numeric" pattern="[0-9]*" maxLength={1} className={`text-center ${inputClassName}`} value={number} onChange={e => handleChange(e, idx)} onKeyDown={e => handleKeyDown(e, idx)} ref={el => {
        inputsRef.current[idx] = el;
      }} autoComplete="one-time-code" />)}
      </div>
    </>;
};
export default OTPInput;

// SvelteKit/Seed/src/lib/components/OtpInput.svelte
<script lang="ts">
	import { Input } from '@sveltestrap/sveltestrap';

	export let value: string = '';
	export let length: number = 6;

	let otp: string[] = Array(length).fill('');

	$: if (value && value.length === length && value !== otp.join('')) {
		otp = value.split('');
	}

	const handleInput = (index: number, e: Event) => {
		const input = e.target as HTMLInputElement;

		const char = input.value.replace(/[^0-9]/g, '').charAt(0) || '';
		otp[index] = char;
		input.value = char;

		value = otp.join('');

		if (char && input.nextElementSibling) {
			(input.nextElementSibling as HTMLInputElement).focus();
		}
	};

	const handleKeyDown = (index: number, e: KeyboardEvent) => {
		const input = e.target as HTMLInputElement;
		if (e.key === 'Backspace' && !input.value && input.previousElementSibling) {
			(input.previousElementSibling as HTMLInputElement).focus();
		}
	};
</script>

<div class="d-flex gap-2 mb-3 two-factor">
	{#each otp as val, i (i)}
		<Input
			type="number"
			bind:value={otp[i]}
			on:input={(e) => handleInput(i, e)}
			on:keydown={(e) => handleKeyDown(i, e)}
			class="text-center"
			required
			inputmode="numeric"
			maxlength={1}
		/>
	{/each}
</div>
