// Vue-Inertia/Seed/resources/js/components/UICard.vue
<template>
  <BCard v-if="isVisible" no-body v-bind="$attrs">
    <BCardHeader
      class="justify-content-between align-items-center"
      :class="[headerClass, { 'border-0': isCollapsed }]"
    >
      <h5 class="card-title mb-0" :class="titleClass">{{ title }}</h5>

      <div v-if="isCollapsable || isReloadable || isCloseable" class="card-action">
        <button v-if="isCollapsable" class="card-action-item border-0" @click="collpase">
          <Icon :icon="isCollapsed ? 'tabler:chevron-down' : 'tabler:chevron-up'" size="16" />
        </button>
        <button v-if="isReloadable" class="card-action-item border-0" @click="reload">
          <Icon icon="tabler:refresh" size="16" />
        </button>
        <button v-if="isCloseable" class="card-action-item border-0" @click="close">
          <Icon icon="tabler:x" size="16" />
        </button>
      </div>
      <slot v-else name="card-header-actions" />
    </BCardHeader>

    <BCollapse :show="!isCollapsed">
      <BCardBody :class="bodyClass">
        <slot />
      </BCardBody>

      <BCardFooter v-if="$slots['card-footer']" :class="footerClass">
        <slot name="card-footer" />
      </BCardFooter>
    </BCollapse>

    <div v-if="isReloading" class="card-overlay d-flex">
      <div class="spinner-border text-primary" />
    </div>
  </BCard>
</template>

<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { ref } from 'vue'

type PropsType = {
  title: string
  titleClass?: string
  headerClass?: string
  bodyClass?: string
  footerClass?: string
  isCollapsable?: boolean
  isReloadable?: boolean
  isCloseable?: boolean
}

defineProps<PropsType>()

const isCollapsed = ref<boolean>(false)
const isReloading = ref<boolean>(false)
const isVisible = ref<boolean>(true)

const collpase = () => {
  isCollapsed.value = !isCollapsed.value
}

const reload = () => {
  isReloading.value = true
  setTimeout(() => (isReloading.value = false), 1500) // fake reload
}

const close = () => {
  isVisible.value = false
}
</script>

// SvelteKit/Seed/src/lib/components/UICard.svelte
<script lang="ts">
	import Icon from '@iconify/svelte';
	import { Card, CardBody, CardFooter, CardHeader, Collapse } from '@sveltestrap/sveltestrap';

	export let title: string;
	export let titleClass: string = '';
	export let headerClass: string = '';
	export let bodyClass: string = '';
	export let footerClass: string = '';
	export let isCollapsable: boolean = false;
	export let isReloadable: boolean = false;
	export let isCloseable: boolean = false;
	export let hasCardFooter = false;

	let isCollapsed = false;
	let isReloading = false;
	let isVisible = true;

	const collapse = () => {
		isCollapsed = !isCollapsed;
	};

	const reload = () => {
		isReloading = true;
		setTimeout(() => {
			isReloading = false;
		}, 1500);
	};

	const close = () => {
		isVisible = false;
	};
</script>

{#if isVisible}
	<Card>
		<CardHeader
			class="justify-content-between align-items-center {headerClass} {isCollapsed
				? 'border-0'
				: ''}"
		>
			<h5 class="card-title mb-0 {titleClass}">{title}</h5>

			{#if isCollapsable || isReloadable || isCloseable}
				<div class="card-action">
					{#if isCollapsable}
						<button class="card-action-item border-0" on:click={collapse}>
							<Icon
								icon={isCollapsed ? 'tabler:chevron-down' : 'tabler:chevron-up'}
								height="16"
								width="16"
							/>
						</button>
					{/if}
					{#if isReloadable}
						<button class="card-action-item border-0" on:click={reload}>
							<Icon icon="tabler:refresh" height="16" width="16" />
						</button>
					{/if}
					{#if isCloseable}
						<button class="card-action-item border-0" on:click={close}>
							<Icon icon="tabler:x" height="16" width="16" />
						</button>
					{/if}
				</div>
			{:else}
				<slot name="card-header-actions" />
			{/if}
		</CardHeader>

		<Collapse isOpen={!isCollapsed}>
			<CardBody class={bodyClass}>
				<slot />
			</CardBody>

			{#if hasCardFooter}
				<CardFooter class={footerClass}>
					<slot name="card-footer" />
				</CardFooter>
			{/if}
		</Collapse>

		{#if isReloading}
			<div class="card-overlay d-flex">
				<div class="spinner-border text-primary"></div>
			</div>
		{/if}
	</Card>
{/if}
